fomantic/Fomantic-UI

- src/definitions/modules/search.js
- src/definitions/modules/search.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/search.variables
Now it is possible to make search results scroll-able. 
1. Handles keyboard events
2. Regains scroll position after closing of results due to blur/click event
Search: Without category
Search: Withcategory
> [Enhancement]: [Search] Scrollable search result

- tasks/config/tasks.js
In case of errors in less compilation in tasks.js a proper check for an existing filename property is not given and breaks when it's undefined
#1463
> fix(build): double check for existing object property in tasks

- src/definitions/modules/dropdown.js
When `values` are given on initialization of a dropdown, all entries which have a `selected` attribute set will trigger the `onChange` event
The already existing `fireOnChange` setting does not cover this situation to prevent the callback.
In comparison: When a dropdown is just converted from a select and those option values do also have the `selected` property set, then the onchange does not happen, so the behavior  does not match, but should.
The second dropdown (which uses the `values` setting) will trigger the onChange event two times on initialization because of the two preseleced values.
https://jsfiddle.net/7g2ywtfc/
Both dropdowns won't trigger the onChange event on initialization
https://jsfiddle.net/7g2ywtfc/1/
#1470
> [Dropdown]: Initial preselected values trigger onchange event

- tasks/config/user.js
- tasks/install.js
In some situations (for example in yarn workspaces), mostly within custom build chains, the users semantic.json cannot be found because the requireDotFile starts from within the fomantic folder.
Instead , the second parameter should be given as `process.cwd()` to support starting the search in a different folder
Thanks to @JMS-1 for the solution, which i just adopted by this PR
#1466
> [Build] Support gulp calls to find semantic.json from outside fomantic folder

- src/definitions/elements/button.less
- src/themes/default/elements/button.variables
Since we centralized the vertical-align setting for icons by #1372 , now icons within buttons also get the wrong vertical align. This PR sets a valid value for them
Remove the last css setting for the button > icon to see the issue (look closely though)
https://jsfiddle.net/vcptskxy/
https://github.com/fomantic/Fomantic-UI/pull/1372#issuecomment-633039695
> [Button] Correct vertical align for icons within buttons

- src/definitions/modules/dropdown.less
When the dropdown is used as simple dropdown without JavaScript, it doesn't support more than two nested level of sub-menus. It always exposes only two levels of sub -menus.
And despite the sub-menu declares the value '**left**' for the class name, it always appears rightward. It should respect the value '**left**' from the class name and should be appeared leftward.
When the dropdown menu is invoked with JavaScript, the last dropdown in the right menu doesn't behave properly and the sub-menus inside the dropdown overlaps each others. They should appear in the correct location like other dropdown menus.
Bug version: https://jsfiddle.net/w3nejghr/
Fix version: https://jsfiddle.net/k31zf0h2/
#1369
> fix(dropdown): the nested dropdown menus do not behave correctly

- src/definitions/modules/tab.js
The implemented auto activation of tabs when no active tab is found #977 #1025 lead into some situations where a manual set of the active tab does not work anymore and always the last tab was selected. 
This especially happens when tabs are initialized separately. Such situations need the old until FUI 2.7.7 which did not check for existing active tabs at all
This PR adds a new option `autoTabActivation` (default true to avoid being a breaking change within the 2.8.x branch)
When set to false the behavior is the same as until 2.7.7
When set to a string and no active tab exists, it will use that string as the path name for the tab to be activated.
The third tab is supposed to be active
The last initiated tab is selected
https://jsfiddle.net/z632cfq5
The previous selected tab stays selected …
> [Tab] Make auto activation of tabs optional

- src/definitions/modules/dropdown.js
This PR ensures that a dropdown has only one sizer element no matter how many times it is initialized.
It looks like `!module.has.sizer()` of [this line](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/dropdown.js#L360) already ensures it, but actually does not. `$sizer.length > 0` inside `has.sizer()` always returns `false` because `sizer.selector` is `> input.sizer` even though the sizer element is created as `span` element (I think `> span.sizer` is needed instead of `> input.sizer`).
I'm not 100% sure whether this is a bug, so feel free to close this PR if anything is wrong.
Both test cases initialize the dropdown twice.
Try to see how many sizer elements are created via your developer tool.
* Two sizer elements are created
https://jsfiddle.net/c5oz8fhk/
* …
> [dropdown] Fix a sizer element being created every time dropdown is initialized

- tasks/config/project/release.js
By #1467 we added the current directory location. The release task was still missing that extra parameter. According to @JMS-1 this lead into a missing version number in semantic.json when the release is build locally from a different path
#1498
> fix(build): missing extra parameter for current directory in release task leads into missing build number

- src/definitions/modules/dimmer.less
Firefox messes around with (large) modals in certain situations. For example when trying to drag inside an input inside a modal, it scrolls to the top of the modal. Even worse on Mac where the whole modals overlays other div containers...
Reason for this is the `perspective` setting for the page dimmer. It seems this was introduced some years back to also fix some firefox issues, so i don't dare to remove this setting completely to avoid possible other, currently unknown, issues in probably other browsers as well.
- Try to drag in the below input inside of the modal
- The modal scrolls to the top (on macos it also overlaps the upper CSS container of jsfiddle (tried using browerstack)
https://jsfiddle.net/hzk7vwa4/7/
- Nothing happens even in Firefox now
https://jsfiddle.net/hy2fzkca/ …
> fix(dimmer): page dimmer in firefox results in misaligned modals

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
This PR fixes the first level of simple dropdown inside the right menu was cropped and out of the screen when the parent menu item has short text, and the dropdown doesn't specify the class name `left`.
To avoid this, all dropdown inside the right menu will be forced to appear leftward by default. The dropdown can also appear leftward or rightward by having `left` or `right` class name for it's nested dropdown menus.
This PR also fix the dropdown inside the buttons which are positioned incorrectly.
https://jsfiddle.net/18jogrs9/
https://jsfiddle.net/usfh3tpw/1/
https://jsfiddle.net/ymo0f9st/
#1502
#1514
> fix(dropdown): fix some bugs introduce by the previous commit (#1473)

- src/definitions/elements/icon.less
- src/definitions/elements/text.less
- src/themes/default/elements/icon.variables
- src/themes/default/elements/text.variables
This PR corrects/partly reverts the vertical alignment of unsized icons of #1372 which unfortunately breaks the vertical alignment in most cases when icons are just used beside inline texts which is probably the most used case.
I obviously hadn't really tested the old PR 🙄
While testing this now, i also recognized the `text` element needs the same line-height setting to avoid overlapping which is also fixed now.
https://jsfiddle.net/usfh3tpw/2/
https://jsfiddle.net/usfh3tpw/3/
https://github.com/go-gitea/gitea/pull/11767
#1371
> [Icon,Text] Fix vertical alignment

- src/definitions/elements/label.less
- src/themes/default/elements/label.variables
- `basic labels` have a border which increases the height in comparison to usual labels.
When inline together the line height gets increased
- Because of that, a `basic image label` was not properly supported
- All attached labels were not really attached to the boundary of a segment (as every other `attached` component is doing)  . That was especially visible when a `basic attached label` was used
Watch the height and width difference on basic labels as well as the misaligned image labels and unattached borders in attached labels
https://jsfiddle.net/lubber/wt0heq5k/60/
https://jsfiddle.net/lubber/wt0heq5k/99/
Watch the height and width difference on basic labels as well as the misaligned image labels and unattached borders in attached labels
#1430
> [Label] Basic Labels had different height and adjusted (attached) image labels 

- src/definitions/modules/slider.js
The `interpretLabel` setting is not defined as a settings property by default. It's also supposed to be `false` by default instead of `undefined` 
#1526
> [Slider] interpretLabel is undefined instead of false by default

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
When a dropdown was created out of prepared divs, the `column` menus were not working.
That's because the previous approach was using `display:inline-block` which breaks when the sourcecode contains linebreaks. (Which a well formatted HTML source always has)
It was working when a `select` tag was converted, but only because the generated HTML did not contain any whitespace
This PR now switches to flexbox for column menus which does not care about linebreaks :) As the transition does `block` by default we had to teach dropdown to use flex when column menus are used
https://jsfiddle.net/lubber/suqcb52r/9/
#1300
> [Dropdown] Columnar dropdowns were not working on raw div dropdowns

- src/definitions/collections/menu.less
When icon groups were used in submenus, they were wrongly positioned and the the icon group itself was totally messed up
https://jsfiddle.net/lubber/8bn2rqwt/21/
#936
> [Menu] Fix icon group position and alignment in submenus

- src/themes/default/elements/icon.overrides
This PR fixes an unconverted numeric classname for the `stopwatch.20` icon
@exoego prepared a fix for the icon creation script already here https://github.com/fomantic/create-fomantic-icons/pull/104
#1544
> [Icon] Numeric classname `stopwatch.20` since font aweseome 5.13

- src/definitions/modules/dropdown.js
If a placeholder text contained HTML (for example an icon) if was not remembered when reused (for example when the dropdown is cleared.
Select something, then clear it via Button.
The original placeholder misses the icon
https://jsfiddle.net/lubber/L8hof4jp/2/
The icon is preserved
https://jsfiddle.net/lubber/L8hof4jp/4/
|Broken|Fixed|
|-|-|
|![htmlplaceholder_broken](https://user-images.githubusercontent.com/18379884/86036443-2c2b5f00-ba3e-11ea-862c-6cd8de3fe225.gif)|![htmlplaceholder_fixed](https://user-images.githubusercontent.com/18379884/86036453-32214000-ba3e-11ea-8204-ec3f3c321fd0.gif)|
#1403
> [Dropdown] HTML in placeholders was not preserved

- src/definitions/modules/popup.less
`left/right centered` tooltips got misaligned border after a second.
Thanks to @ko2in, [he figured out ](https://github.com/fomantic/Fomantic-UI/issues/442#issuecomment-649751669)it's obviously a bug in firefox on posix systems (linux/mac) when a scaling factor in transform is used (obviously in combination with translateY because all other tooltip positions work and also use the scale transform)
It does not happen at all on Windows
Hover over the below labels 'left center' and 'right center' using firefox on linux or mac. 
The tooltip slightly moves to the bottom and the tooltips lower border gets 'ghosted' after 1-2 seconds
https://jsfiddle.net/bg7j2Lzo
The text still moves slightly, but the border is not ghosting anymore
https://jsfiddle.net/c3qorphu/
|Broken|Fixed|
|-|-| …
> [Popup] left/right center tooltips were misaligned on Firefox (posix)

- src/definitions/modules/calendar.js
Whenever a calendar popup is shown the calendar gets redrawn several times even if nothing was changed!
Open the console, i adjusted the 2.8.6 calendar as well as the fixed one to show a console.log whenever the calendar gets redrawn.
Click into the date field, but do not select anything. Instead click outside of the field, so the calendar closes again
The calendar gets redrawn all the time. Even 2 times when no date was selected!
https://jsfiddle.net/lubber/gzsxr8t1/2/
The calendar only gets redrawn when something changed (date value, mode view (day/time))
https://jsfiddle.net/lubber/gzsxr8t1/3/
https://github.com/mdehoog/Semantic-UI-Calendar/issues/130
> [Calendar] Avoid unnecessary redraw which slows down the module

- dist/components/slider.js
I changed the return result, beacause of this https://floating-point-gui.de/
variables values where rounded when they arrive thanks to rounded difference, but the result of difference and module.get.min whas not rounded
Issue jsfiddle: https://jsfiddle.net/dfj7urbz/
#1545
> [Slider] operation sometimes returns not rounded value

- src/definitions/collections/form.less
A `field` inside `fields` groups had a wrong bottom margin to the next field (or its labels) on mobile view . See screenshots  for easy explanation
While initially adopting the fix by @VanquishedWombat i later recognized (thanks to @ko2in 😉 ) that the whole mobile view adjustment could be implemented much easier which, as a result, fixed the main issue automatically. It also fixes a rare situation when `one wide field` is used 
That said, this PR removes the `!important` from the fields width allowing for simpler override in media query because of higher specificity
For easier review i also prepared a jsfiddle with all form field combinations.  (see below)
Use this and scale the screen to see the difference in mobile view which now works as expected
https://jsfiddle.net/lubber/xt56f3v2/2/ …
> [Form] Fields in field groups on mobile view had wrong bottom margin

- src/themes/default/globals/site.variables
Two variables for (inverted)disabledText are declared two times in the same file. I removed the first instance, because it was already always overridden by the same declaration  200 LOC later here
https://github.com/fomantic/Fomantic-UI/blob/0269a8213ac2ff438965c6a82503e7561d2024ae/src/themes/default/globals/site.variables#L990-L991
I know it's technically not necessary because the last declaration wins in LESS (that's the concept of the override-files), but to avoid confusion and satisfy reporting users i created this PR ;)
https://github.com/Semantic-Org/Semantic-UI/issues/6990
> fix(site): duplicatedVariables

- src/definitions/modules/dimmer.js
When a dimmer already had a rgb background color, the `opacity` setting for the dimmer was not working because it created an invalid background color value .
Reason was because for a pure rgb value the third splitted string array element still had a closing parenthesis, which in turn created an invalid value like
```
rgba(111,111,111),0.1)
```
https://jsfiddle.net/lubber/mt1cn3qp/13/
https://jsfiddle.net/lubber/mt1cn3qp/15/
Given a
```
$('.ui.segment').dimmer({
opacity: 0.3
})
```
> [Dimmer] opacity setting created invalid value on rgb background

- src/definitions/modules/dimmer.less
- src/definitions/modules/sidebar.less
- src/definitions/views/card.less
While i initially thought about implementing a new dimmer variant based on a different background, i tried to simply change the dimmer variables instead, so my idea would work by just creating a new theme.
However, as the dimmer currently only supports `background-color` this prevents to use an image or a radial gradient as dimmer background for the existing variables.
That said, this PR changes the `background-color` property to just `background` which is compatible with the default color value and allows for themes to use other other type of background than just the color.
Again: This PR does not change the default theme behavior, it just provides the possibility to use other background-types than just the color
I adjusted this to my local docs page to test this and and as the …
> [Dimmer] Support more background types than only color

- src/definitions/modules/calendar.js
https://github.com/fomantic/Fomantic-UI/blob/0269a8213ac2ff438965c6a82503e7561d2024ae/src/definitions/modules/calendar.js#L1355-L1358
The above code expects parsing on partial input, e.g. `1`, to be failed on `new Date("1")`.
However, there are incosintency between browsers on how `new Date` consturctor or `Date.parse` works.
input    | Chrome | Firefox
---|----------|--------
new Date("1") | success | invalid 
new Date("10") | success | invalid  
new Date("100") | success | invalid  
new Date("1000") | success | success 
On Chrome,  `new Date("1")` or such can create instance of Date.
So, `getDate` is a number, then hour is not chosen correctly.
This PR adds a check input is number-only `^[0-9]+$ or not.
If input is number-only, it should go to time-only or date-only logic. …
> [Calendar] Chrome chooses wrong hour on time-only calendar

- src/definitions/elements/list.less
When an `icon button` was used inside lists, those got vertical misaligned, because the icon selector was not aware of this and always assumed an i-tag  which this PR now makes clear.
http://jsfiddle.net/lubber/tgLzjwmk/
http://jsfiddle.net/lubber/tgLzjwmk/2/
Watch the middle icon button which is vertically misaligned
https://github.com/Semantic-Org/Semantic-UI/issues/3423
> [List] icon buttons were misaligned

- src/definitions/modules/calendar.js
The calendar columns are not evenly divided, which this PR fixes by adding the [column count](https://fomantic-ui.com/collections/table.html#column-count) classnames to the calendars table.
This is especially visible when using an inline calendar: Monday and Wednesday are much wider than the other columns.
https://jsfiddle.net/lubber/5u1Lft84/1/
https://jsfiddle.net/lubber/5u1Lft84/2/
> [Calendar] Evenly divide column widths

- src/definitions/elements/button.less
A `compact icon button` padding was overridden by the usual padding because of too low specifitiy
https://jsfiddle.net/lubber/ad2m4gqv/1/
https://jsfiddle.net/lubber/ad2m4gqv/2/
Watch the middle Pause button
> [Button] compact icon button had wrong padding

- src/definitions/elements/text.less
- src/themes/default/globals/colors.less
- src/themes/default/globals/variation.variables
For consistency with other elements like form/button/label, etc. this PR adds the states `info`, `success`, `warning`, `error` to the `text` element.
> [Text] support state colors

- src/definitions/modules/popup.less
To avoid accidental inheritance of styling from parent element, `text-shado: none` is explicitly set for `[data-tooltip]` popup.
https://jsfiddle.net/kpbo7qjg/
#1577
> [Popup] Remove text-shadow explicitly on tooltip to avoid inheritance from parent

- src/definitions/elements/segment.less
The horizontal segments should have the rounded corner, but the rounded corners seem to be coverd by the background of the segment inside of it.
The first and last segment inside the horizontal segments now adjust the border-radius to appear the rounded corner from the horizontal segments.
**Before:** https://jsfiddle.net/fax0kqd4/
**After:** https://jsfiddle.net/1ho0egx3/
**Before:**
**After:**
> [Segment]: Horizontal segments' rounded corner

- src/themes/default/collections/table.variables
The default vertical alignment of table footer were explicitly set as middle, which ignores the `top aligned` and `bottom aligned`
variant from table row and unable to align top and bottom within table footer.
By setting default value as inherit will enable to specify vertical alignment from table row without needing to specify top or bottom aligned on each cell.
**Before:**
The class name `top aligned` and `bottom aligned` cannot be applied from table footer row (https://jsfiddle.net/ow6b1hLv/)
**After:**
The class name `top aligned` and `bottom aligned` can be applied from table footer row (https://jsfiddle.net/c6ujLqyn/)
#1581
> [Table] Change default vertical alignment of table footer

- src/definitions/collections/menu.less
- src/definitions/collections/message.less
- src/definitions/collections/table.less
- src/definitions/elements/header.less
- src/definitions/elements/input.less
- src/definitions/elements/step.less
- src/definitions/modules/calendar.less
- src/definitions/modules/dropdown.less
- src/definitions/modules/embed.less
- src/definitions/modules/modal.less
- src/definitions/modules/toast.less
- src/definitions/views/feed.less
- src/definitions/views/statistic.less
In certain situations only `.icon` selectors were used to address icons incomponents. However this interferes with a  possible `icon button`  resulting in wrong sizes or wrong aligned margins and colors for those buttons.
This PR adds the i tag to those selectors to make sure only a "real" icon is selected as it was supposed  to be.
https://jsfiddle.net/lubber/djy148eb/33/
https://jsfiddle.net/lubber/djy148eb/32/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/87834159-07cae180-c88a-11ea-8bfc-147e915eefab.png)<br>![image](https://user-images.githubusercontent.com/18379884/87834049-b02c7600-c889-11ea-8451-a64b6a15b216.png)|![image](https://user-images.githubusercontent.com/18379884/87833893-42804a00-c889-11ea-8d77-0f2e23a8c28a.png)|
> [Icon/Button] Make sure real icon selectors are addressed

- src/definitions/modules/calendar.js
The default tooltip position of cell tooltips is `left center`. This leads into situations where the tooltip is cut to the left.
On first instantiation of a calendar popup the position of tooltips is not correctly fetched because the popup module hasn't adjusted its pointer position classes yet. Because of this ,the direction of possible cell tooltips is wrongly calculated. 
If the same calendar is opened a second time, this does not occur anymore, because the popup module has now adjusted its position.
This PR now adjusts any existing cell tooltip positions inside the calendar whenever the popup get's shown (the popup module always (re-)calculates its position then). So this not only fixes it on first instantiation but also in case the calendar position changes while scrolling , so the …
> [Calendar] Adjust cell tooltip positions according to popup position to avoid it being hidden

- src/definitions/modules/toast.less
The toast error progress bar is not visibile because the build process omitted to compile for error variation of toast progress
and ended up showing the same color as error background of toast which makes the progress bar not visible.
**Broken:** https://jsfiddle.net/dutrieux/vunftrhx/
**Fixed:** https://jsfiddle.net/wfvqzabn/
#1600
> [Toast] Fix the toast error progress bar visibility

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/calendar.variables
This PR adds full `inverted` support to the calendar component.
It also adds new metadata support for disabled/eventDates to supply new attributes `inverted` and `variation`. This way each cell tooltip can be adjusted on its own and makes it possible to have inverted or `basic` cell tooltips on non inverted calendars and vice versa
https://jsfiddle.net/lubber/xo2b9tfz/19/
- `inverted calendar`
> The darker left pointer or the calendar surrounding popup isn't part of this PR, because it's a general issue also for normal calendar and covered in #1084 
- ... keep non inverted cell tooltip
```javascript
disabledDates: [{
date: new Date(2020, 11, 19),
message: 'xmas gift shopping',
inverted: false
}],
```
- ... normal calendar, but inverted tooltip
```javascript
disabledDates: [{
date: new …
```
> [Calendar]: Inverted Variant

- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
- src/definitions/modules/dropdown.js
The native `change` event should be triggered whenever a date is selected from the picker and the input field blurs.
Currently it is only triggered when the dates input field has been changed manually and the field blurs.
I adopted the same method for this as in `checkbox` or `dropdown`
https://jsfiddle.net/lubber/asdjkwpo/11/
https://jsfiddle.net/lubber/asdjkwpo/11/
|Broken|Fixed|
|-|-|
|![calendarnativechange_wrong](https://user-images.githubusercontent.com/18379884/88369948-65cb5d80-cd91-11ea-87ce-2c7974aa2d29.gif)|![calendarnativechange_right](https://user-images.githubusercontent.com/18379884/88369961-6b28a800-cd91-11ea-99a1-2336a1d986b8.gif)|
#1251
> [Calendar] trigger native change event on date selection

- src/definitions/collections/form.less
- src/themes/default/collections/form.variables
When error prompts appear on checkboxes inside of `grouped inline fields`, there was no distance between error prompts in comparison to single inline fields.
Suggested by @VanquishedWombat , this PR slightly adjusts the bottom margin , so the distance looks better (not exactly equal to single inline fields, because the grouping should still be recognizable)
Look at the prompt distance of the 2 groups of radios and checkboxes which are grouped inline. The top three checkboxes are single inline for comparison
https://jsfiddle.net/lubber/8wbf1z0v/10/
https://jsfiddle.net/lubber/8wbf1z0v/9/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/88800515-969ffe00-d1a8-11ea-8891-e50a43d209e6.png)|![image](https://user-images.githubusercontent.com/18379884/88800584-b041 …
> [Form] Adjust checkbox margins in grouped inline fields for nice distance of error prompts

- src/definitions/behaviors/form.js
Whenever a form was cleared or reset by their respective behaviors `clear` or `reset`, any existing error messages were not removed
Additionally , when form fields are revalidated after they have been invalidated the error message was still visible in the error messages. However this was not the case when the form had inline errors.
https://jsfiddle.net/lubber/70c8tapg/10/
https://jsfiddle.net/lubber/70c8tapg/12/
|Broken|Fixed|
|-|-|
|![formvlearerror_wrong](https://user-images.githubusercontent.com/18379884/88725726-cf9a8d00-d12c-11ea-8edd-4dcc29fc1e57.gif)|![formvlearerror_right](https://user-images.githubusercontent.com/18379884/88725736-d6290480-d12c-11ea-8912-fe1297651d6c.gif)|
#1610 
https://github.com/Semantic-Org/Semantic-UI/issues/4363 …
> [Form]: Remove existing error messages on clear and reset and adjust error messages on revalidation when not inline

- src/definitions/modules/sidebar.less
When a `bottom sidebar` was used inside non body pushable context, it was always added to the context divs height, making the vertical scrollbar appear. As the body will still provide a possible scrollbar it's save to remove the inner pushable vertical scrollbar.
Reason for the behavior is the 100% `translate3d()` setting to hide the sidebar which adds its content to the parent div. For `left`/`right` the `overflow-x:hidden` is already set and for `top` it's a negative position of `-100%`, so the change of overflow-y is not affected in the other cases.
https://jsfiddle.net/lubber/vd2ecqgL/9/
✔️ Ok, same as above
https://jsfiddle.net/lubber/vd2ecqgL/69/
✔️  when the inner segment should be scrollable itself
https://jsfiddle.net/lubber/vd2ecqgL/77/
✔️  when inside grid columns …
> [Sidebar] Avoid scrollbar on non body pushable (visible on bottom sidebars)

- src/definitions/behaviors/form.js
the `is valid` behavior deletes possible existing error states on a field, although it shouldn't.
That's because the field validator always removes the error state by default (before probably adding it again) and did not respect a `showErrors` setting. showErrors however is only meant to show **new** errors. If it is false it should not touch any existing error state class.
I now also added the `showErrors` parameter as an option to the `is valid` behavior in case someone definately wants to show errors on **not already validated** fields.
As the parameter is optional the change is fully backwards compatible.
- Click on "submit" to invalidate the form
- Click on the second button to call `is valid`
- The invalid field loses its error state
https://jsfiddle.net/02gfdbx9/
- The invalid …
> [Form] isValid should not delete error state

- src/definitions/behaviors/form.js
The `fieldDirty` check failed whenever a dropdown, converted from a `select` tag, was part of the form **and** was defined as `multiple`
The comparison of currentValue and initialValue failed for those dropdowns, because the `.val()` method returned arrays instead of strings for select-multiple fields. Dropdowns made out of `div` were working, because those use an input field, which holds a string.
Raw `==` comparisons of two arrays are never true, so that fiel was always considered dirty.
Just click into the textarea to trigger the forms dirty check ...
... the dirty check for the form will immediatly fail (considered dirty), even though no value has been changed, and triggers the onDirty event
https://jsfiddle.net/vtbyr8o1
... the dirty check successfully considers the form to be …
> [Form] dirty state check failed for multiple variant of native select tag

- src/definitions/behaviors/form.js
When the `preventLeaving` feature is used, the dirtycheck was ignored on a submit even when the validation failed (which aborts the submit).
Whenever a validation failes it should therefore also reset a possible existing submitting flag to keep the preventLeavin feature working
- Enter some letter (not a number) into the input field, so the form gets dirty, but is still invalid
- Click on the "Google Link" next to the submit button
- The Browser will tell you that there are changes in the form 👍 Click Cancel
- Now click on the submit button, it will invalidate the fields
-Click on the "Google Link" again...
- The Browser immediatly redirects to the Google site and does not warn you about the form changes
https://jsfiddle.net/lubber/tfceLxas
- The Browser will also tell you that there are …
> [Form] Reset submitting flag when validation fails to keep dirtycheck with preventLeaving setting

- package.json
The `main` property in package.json misses  the file extension. [jsdelivr needs the file extension](https://www.jsdelivr.com/features#publishing-packages), otherwise it does not recognize the default file. It's also [advised by npm](https://docs.npmjs.com/creating-a-package-json-file) to include the file extension.
https://github.com/Semantic-Org/Semantic-UI/issues/6999
> [Chore] fix cdn default js file

- src/definitions/modules/slider.less
- src/themes/default/modules/slider.variables
This PR encourages the slider label to appear in one line without breaking the word into new line especially when the last label contains more than one word and break into multiple line which make the label overlaps the slider track in some situations.
This PR also supports to change the slider label position using `bottom aligned` flag in CSS class name which makes the label to be appeared below the slider track.
**Before:** https://jsfiddle.net/qr1hxs3L/
**After:** https://jsfiddle.net/qr1hxs3L/1/
| Label Before | Label After  |
|---|---|
| ![Broken-Slider-Label](https://user-images.githubusercontent.com/930315/89179786-744a1e00-d5b6-11ea-81d2-e7ca72f93c0a.png) | ![Fix-Slider-Label](https://user-images.githubusercontent.com/930315/89179810-80ce7680-d5b6-11ea-90a8-7c179c4329d4.png) | …
> feat(slider): prevent line break in slider label and support bottom aligned label

- src/definitions/elements/input.less
- src/definitions/modules/calendar.js
- src/definitions/modules/dropdown.js
When a dropdown with search selection, or a calendar field, is disabled, the input fields were still accessible by using the tab key
- i adopted the same observer logic code to calendar as it was already existing in dropdown
- i also fixed the variable declaration for `selectionComplete` (implemented by #1602 (was defined globally instead of module instance))
- Click left next to the top disabled calendar field
- Press tab 
... it enters the disabled calendar field 😞 
... pressing tab again will enter the disabled dropdown field 😢 
https://jsfiddle.net/lubber/2qdjhrvc/5/
.. the first button is focused as expected
https://jsfiddle.net/lubber/2qdjhrvc/10/
#1605
> [Dropdown, Calendar] Pressing tab entered disabled dropdown/calendar fields

- src/definitions/modules/progress.js
A total value of 0 was unsupported and wrongly fetched (0 !== undefined !)
Although this might be a rarely used situation, it should behave correctly. Means an explicitely given total value of 0 is always fullfilled and should behave as 100%
This PR also fixes wrong handling of the `limitValues` setting and a wrong check in precentage calculation  for the total value which might be undefined and resulted in NaN numbers otherwise.
http://jsfiddle.net/lubber/9ov4yjkw/
http://jsfiddle.net/lubber/9ov4yjkw/4/
https://github.com/Semantic-Org/Semantic-UI/issues/3056
> [Progress ]Total value of 0 was unsupported and fix limitValues 

- src/themes/default/elements/icon.overrides
The two-word aliases for `chart line` and `line graph` are renamed into one-word aliases `chartline` and `linegraph` respectively to avoid conflicting with the class name `line` which is used by other FUI components.
**Broken:** https://jsfiddle.net/tqmab8vu/1/
**Fixed:** https://jsfiddle.net/85mw6can/
#1619
> fix(icon): Change two-word aliases into one-word aliases to avoid conflictions

- tasks/config/project/config.js
It seems that the current logic (below) to create file blob like `{foo,bar,buz}.less` assumes that `config.globs.individuals` is always like `{a,b,c}`, but it does not when `individuals` has only one single element.
https://github.com/fomantic/Fomantic-UI/blob/74458216193cbf22653784a98f58ce57b0fc0244/tasks/build/css.js#L131-L134
After This PR, `config.globs.components` and `config.globs.individuals` are `{a,b,c}` if those arrays has 1 or more elements, so `build/css.js` and `build/javascript.js` works regardless of the number of elements in `individuals`/`components`
I have no idea how to test build tasks.... 
Suggestion is highly appreciated 🙏 
#1638
> [Build] Fix issue when "individuals" or "components" has only single element 

- tasks/config/project/config.js
Implement https://github.com/fomantic/Fomantic-UI/pull/1639#discussion_r468923211
So users no need to remove the items in `individuals` from `components`, or even can omit `components` at all.
Corresponding docs update: https://github.com/fomantic/Fomantic-UI-Docs/pull/224
no-issue
> [Build] Remove individuals from components so users can specify only individuals

- src/definitions/modules/dropdown.js
When calling `templates.menu()`, the object passed always has a single fixed key `values`.
However, the implementation of `templates.menu()` reads the object with the configurable key `fields.values`.
So if a key other then `values` is configured, this will fail.
```
$("#selectBox").dropdown({
fields: {
values: 'valuesX'
}
});
```
See [JSFiddle](https://jsfiddle.net/wardlootens/04war7mx/3/)
> [Dropdown] Use configured 'fields.values' key instead of fixed 'values'

- src/definitions/modules/calendar.js
After implementing #1462, a pure given date in `yyyy-mm-dd` format did not work in safari  anymore , because safari does not handle the internal converted date of `yyyy-mm-dd 00:00:00`
This PR now changes the dashes to slashes, so the internal result is  `yyyy/mm/dd 00:00:00`, which is supported in every browser
- Use Safari
The given date `2020-08-12` results in `August, 12, 2000`
https://jsfiddle.net/lubber/s82zoc5w/
The given date `2020-08-12` correctly results in `August, 12, 2020` as in every other browser already
https://jsfiddle.net/lubber/s82zoc5w/2/
https://github.com/fomantic/Fomantic-UI/issues/1462#issuecomment-672559777
> [Calendar] Support safari to accept yyyy-mm-dd format using dashes

- src/definitions/modules/search.js
Results in search responses which got an URL to be followed when clicked on it, are followed twice: First by the click event handler of a result and second by the native `a` link behavior
- Enter something in the search field so it returns some entries
- Click on one of the results
- Watch console (network tab)
Link is followed twice 👎 
https://jsfiddle.net/lubber/nf8321pc/1/
Link is followed once 👍 
https://jsfiddle.net/lubber/nf8321pc/2/
#1652
> [Search] Avoid unnecessary double link navigation

- src/themes/default/globals/site.variables
`blackHover` and `greyHover` are declared twice. The first one was obviously a copy/past regression when we centralized the color definitions.
However they don't have any effect because they are redeclared /overridden a second time some LOC later.
Also SUI does not have them declared twice (end with brown), so this PR makes the logic equal to SUI again.
https://github.com/Semantic-Org/Semantic-UI/blob/deb275d2d5fe9a522a0b7bd8b6b6a1c939552718/src/themes/default/globals/site.variables#L752-L754
SUI also just uses the declared versions later on
https://github.com/Semantic-Org/Semantic-UI/blob/deb275d2d5fe9a522a0b7bd8b6b6a1c939552718/src/themes/default/globals/site.variables#L783-L786
#1654
> [Site] greyhover and blackhover are declared twice

- src/definitions/behaviors/form.js
The field selector in forms also fetches dropdowns search fields which are not supposed to be form inputs.
Each fetched fields  is bound to events. especially the blur event.
This leads into the situation that jquery 3.4 runs into a "maximum callstack exceeded" bug, because the blur recursively triggers another blur for the same field again when the dropdown was initialized before the form was initialized. Its not happening when the dropdown is initialized after the form was initialized because the `search dropdown` possible hasn't created  the internally used search field. The event system handling seems to changed slightly between jquery 3.3.1 and 3.4, because it was not happening the error is not happening with older jqery versions. However the field selector was ever since fetching …
> [Form] Dont bind events to dropdown search inputs to prevent jquery 3.4 callstack error

- src/definitions/modules/dropdown.less
This PR fixes
- multiple search button dropdown had wrong padding
- Placeholders in multiple search dropdowns were wrapping
- Search in dropdown buttons had ghosting text
https://jsfiddle.net/lubber/47r2v1cf/59
https://jsfiddle.net/lubber/47r2v1cf/60
#1623
> [Dropdown] Multiple search button dropdown misaligned, placeholder wraps and search text ghosting

- src/definitions/modules/dropdown.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/dropdown.variables
IOS devices do not show a scrollbar when the content is not scrolled. This is a design decision by apple and cannot be adjusted via CSS (for example by  `-webkit-scrollbar`)
A similiar behavior is built into firefox mobile (also on Android)
That said if one opens a dropdown it is not clear, if the shown entries are the only available options or if the user has to scroll down to see more, which is confusing and probably leads to wrong selections (because the user did not know of more choices, because of avoided scrolling)
This PR provides the optional `scrollhint` class to be used for the `menu` to show a short animation hint on the right edge (where the usual scrollbar appears) when the dropdown opens to indicate swiping to see more entries
Use an iOS Device or Firefox mobile (also on …
> [Dropdown] optional show a scrollhint on ios devices (or firefox mobile) to indicate more entries

- src/definitions/elements/input.less
`action` or `labeled` input fields don't have state border style for the buttons or labels when inside grouped fields
https://jsfiddle.net/lubber/nudwt41r/4/
https://jsfiddle.net/lubber/nudwt41r/3/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/88765814-612eec80-d177-11ea-9cab-b19d44445806.png)|![image](https://user-images.githubusercontent.com/18379884/88765881-7c016100-d177-11ea-8c71-8e566c35ca37.png)|
#1238
> [Input,Form] Action or labeled inputs in grouped fields were not styled properly with state classes

- src/definitions/modules/dropdown.less
The `very short`  size variation did not work. It was always overridden by the `short` variation because both share same specificity, thus the declaration order matters.
I used a new "test" and "short test" naming to show the difference 
Wrong order: first `very test`, then  `test`
https://jsfiddle.net/lubber/nq4c5eg1/13
Correct order: first `test`, then  `very test`
https://jsfiddle.net/lubber/nq4c5eg1/12
> [Dropdown] "very short" menu height always overriden by normal "short" height because of  wrong specificity order 

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
Allows dropdown menu item's text and description to stack vertically
https://jsfiddle.net/hj824Ld3/
#1059
> feature(dropdown): Allows vertical dropdown menu item content

- src/definitions/modules/checkbox.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/checkbox.variables
It was not supported to have any kind of checkbox positioned to the right of the label.
This PR now introduces `right aligned` checkbox variants
https://jsfiddle.net/lubber/c9b61qzs/56/
> [Checkbox] Support right aligned position of checkbox variants

- src/definitions/modules/dropdown.less
Sometimes, we will need to create a stack of dropdown and the label together as described in this [issue](https://github.com/fomantic/Fomantic-UI/issues/1667).
This PR intends to support the dropdown to be formatted with the label at left or right position same as input element stacks with the [label](https://fomantic-ui.com/elements/input.html#labeled) and the [action](https://fomantic-ui.com/elements/input.html#action) button.
This implementation is not standalone and 100% semantic because, the class name `dropdown` is already used by dropdown module.
At the moment, it only works when the theme has enabled the labeled input variation `@variationInputLabeled` and the dropdown module needs to be the child of `labeled input` element. If we could find any suitable alias for this module, …
> feat(dropdown): Dropdown formatted with label like input labeled

- src/definitions/modules/dropdown.js
In situations where a dropdown was inside a right menu (which got a flex setting) the transition module was taking that flex displaytype setting for the dropdown menu. This unfortunately results into a horizontal menu list.
To be able to adjust this, i added the `displayType`, used for the transition, setting to the dropdown module as well. If set, this setting could be used just as in transition to correct the display if needed.
Additionally this setting also had to be provided to the hiding transition, otherwise the wrong flex setting would  be reapplied before hiding the dropdown again.
Click the top right menu button
The menu is displayed horizontally
https://jsfiddle.net/lubber/wtvfd7pn/25/
The menu is displayed vertical
https://jsfiddle.net/lubber/wtvfd7pn/24/
> [Dropdown] Allow displayType transition setting to be overriden by dropdown

- src/theme.less
- src/themes/default/globals/site.variables
This PR updates the import for the Lato font via google font api to [v2](https://developers.google.com/fonts/docs/css2)
https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin&display=swap
https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&subset=latin&display=swap
https://github.com/Semantic-Org/Semantic-UI/issues/6973
> [Chore] Update google fonts api to v2

- src/definitions/modules/dropdown.js
This PR simply add the ability to prevent the `onChange` event trigerring when the `set selected` behavior is used. Until now, the only way to not trigger the `onChange` was to use the `set value` behavior, which is not IMHO the right stuff to call when you want to programmatically select a value.
> [Dropdown] Add `preventChangeTrigger` parameter to the `set selected` behavior

- src/definitions/modules/slider.js
When step is 0, this division returns `Infinity`, so later on function `gapRatio` while loop is infinite.
Now is checking if step is 0 to change for 1 else return step.
* Add an slider
* Resize window
* Window is freezed
https://jsfiddle.net/mthrcf5n/3/
--> Simply move JSFiddle's grid divider or resize your browser window
It should have a normal behavior now
https://jsfiddle.net/TheJltres/p4zte923/3/
#1684
> [Slider] - With step 0, divides by 0

- src/definitions/modules/dropdown.js
Hi!
This fix is very simple,  when `allowAdditions` is handled by click event, `forceSelection` triggers event click again, but with `allowAdditions` removed can't find the item.
As far as I know I can't know if the event calling this method is the original click or `forceSelection` trigger, so what I did is: if there's no element and `allowAdditions` and `forceSelection` is set to true return `null`.
- Add a non existing value to the dropdown
A JS error occurs `Cannot read property 'trim' of undefined`
http://jsfiddle.net/kamalkemo/bwhsrvdf/
No error anymore
http://jsfiddle.net/lubber/sqpc9d1y/
#1679
> fix(dropdown) - forceSelection trigger event with null addition

- src/definitions/modules/slider.js
Here was set a minimum step of 0, i think for the same reason of #1684, if you remove this step it handles `atoLabel` for all kind of steps.
**This fix needs #1686**
PD. Sorry @ko2in I could not do it with fewer line changes 🤣 
https://jsfiddle.net/TheJltres/z43vub60/1/
#1685
> [Slider] No minimum step for label generator

- src/definitions/modules/slider.js
Store previous value to skip onChange trigger if no change is found in value.
I've assumed here that `onChange` is to behave differently than `onMove`, let me know if this assumption is incorrect and there are changes needed.
Added a new variable `previousValue` and compare it with new value before triggering `onChange` and `onMove`. 
If new changes are found then trigger both or else trigger only `onMove`.
Fiddle: https://jsfiddle.net/MrL1605/5vp4u38g/16/
- Testcase 1:
Sliding the slider and going back to same position should trigger `onMove` on every position and should not trigger `onChange`.
- Testcase 2:
Simply clicking on standard slider tab should not trigger `onChange`, but `onMove` should be triggered. (standard and range)
- Testcase 3:
If a standard slider is already at `x` …
> [slider]: onChange is triggered without moving slider

- src/definitions/behaviors/form.js
Adds the possibility to use `$('.ui.form').form('set optional', fieldName, bool);` to set or unset a field as optional for validation.
https://jsfiddle.net/giandrop/gbwunp7j/14/
#1500
> [Form Validation] Set optional field behavior

- src/definitions/views/card.less
Since chrome 85, images inside horizontal cards are stretched when their parent node has `display: table` set (for example inside a `compact segment` or inside a `toast-box`)
This is triggered because horizontal card images have a fixed 100% height set. By leaving the height to `auto` as for all other card variants, the images shown correctly again.
Even if this _could_ be an error in the latest chrome (it's also in chrome 86 beta and 87 dev) i don't think we should set the height to 100% anyway (just because non equal size images would definately be stretched.
https://jsfiddle.net/lubber/orvshx8z/14/
https://jsfiddle.net/lubber/orvshx8z/16/
> [Card] Images in horizontal cards are stretched on latest chrome when inside css table layout

- src/definitions/modules/progress.js
The `limitValues` setting limits the values between 0 and 100. Instead it should limit the calculated precentages instead and calculate the actual values afterwards.
Click on the + icon. It should increase the progress
It reduces the value and even by clicking many times on the + button the value is stuck
https://jsfiddle.net/lubber/q01tfzeb/6/
All fine
https://jsfiddle.net/lubber/q01tfzeb/12/
#1689
> [Progress] limitValues setting limits values to 100 instead of percentages

- src/definitions/modules/progress.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/progress.variables
This PR allows to display the progress bar aligned to the right growing to the left by using `ui right aligned progress`
https://jsfiddle.net/lubber/zrx39u1b/15/
https://github.com/Semantic-Org/Semantic-UI/issues/7017
> [Progress] Support right aligned progress bar

- src/definitions/collections/form.less
- src/themes/default/globals/colors.less
When the form with error state contain the labels, these labels will be styled as red color, but only they're used as HTML label element.
Now, any element with `label` class will have the same style as label element, and produces more consistent design flow.
**Before:** https://jsfiddle.net/ko2in/sdca1hjt/2/
**After:** https://jsfiddle.net/ko2in/sdca1hjt/4/
Before | After
----------|---------
> [Label,Form] Apply the error color not only to the label tag but also with label class

- src/definitions/modules/calendar.js
This PR allows for single digits as month/day when trying to parse them to correctly handle the `monthFirst` setting
In addtion it also supports single digits as of `2020-5-1` now
- Have a calendar with `monthFirst: false`
- Try to enter `1-5-2020`
- You expect `1 May, 2020` as the result
You get `5 January, 2020`
https://jsfiddle.net/ko2in/gn801bzj/
You get `1 May, 2020` as expected 
https://jsfiddle.net/lubber/67d2hsrw/
https://github.com/fomantic/Fomantic-UI/issues/829#issuecomment-708378939
> [Calendar]: Support single digit months and days at parsing time

- src/definitions/elements/header.less
The specificity has changed for icons by #1593 . This had an impact when using an `aligned icon header` to not correctly be aligned anymore because of the wrong display setting.
This PR adjusts the specificity again
https://jsfiddle.net/lubber/j294u6mx/7/
#1708
> [Header] Icon content was not aligned

- src/definitions/elements/button.less
- src/themes/default/globals/variation.variables
This PR support `stackable buttons` group variation to automatic stack a button group on mobile devices
https://jsfiddle.net/lubber/xzL827ch/
#1230
> [Button] Support stackable buttons

- src/definitions/behaviors/form.js
This PR adds a new option `errorFocus` (default `false` to stay backward compatible).
When set to `true`, the first found error field will be focussed ready to immediatly change the values.
When set to a string, it will be used as a dom selector to be able to focus anything else (most probably the error message box)
Until now the user always had to click into the related field before
https://jsfiddle.net/lubber/r91wax23/1/
https://jsfiddle.net/lubber/r91wax23/2/
|Before|After|
|-|-|
|![errorfocusbad](https://user-images.githubusercontent.com/18379884/96262144-aec23500-0fc1-11eb-8a35-31b08ec95342.gif)|![errorfocusgood](https://user-images.githubusercontent.com/18379884/96262156-b41f7f80-0fc1-11eb-9e54-25fe5922b280.gif)|
#1659
> [Form] Option errorfocus to auto focus the first error field on form validation

- src/definitions/modules/dropdown.js
When a dropdown has given a callback for the show behavior, it was ignored when the data was retrieved by the remote api call .
Watch console. 
Nothing 👎 
https://jsfiddle.net/fep02ctm/6/
Console output from show callback works 👍 
https://jsfiddle.net/lubber/1fks5rwt/
#1712
> [Dropdown] show callback was ignored on remote api call

- src/definitions/modules/slider.less
#1631 introduced the ability to put labels below a slider instead of above it, but using `bottom aligned` together with the size variations (small/large/big) results in messed up spacing.
Before: https://jsfiddle.net/ghL7p089/
After: https://jsfiddle.net/ghL7p089/1/
https://github.com/fomantic/Fomantic-UI/pull/1631#issuecomment-715079996
> [Slider] Fix bottom aligned labels for size variations

- src/definitions/modules/dropdown.js
When a `search` dropdown was used, loading remote content via `apiSettings`, the menu did not show up on mobile devices.
This was due to the lost search focus which happened when the menu nodes were recreated after the api returned the dropdown items. Mobile devices triggered a blur of the search field, while desktop browsers did not. Blurring the search field however led to not showing the dropdown menu anymore. 
This PR also fixes that the API was called twice the first time one clicked on the search field (while it was only triggered once when clicking on the dropdown icon)
- Dropdown menu not shown on mobile devices
https://fomantic-ui.com/jsfiddle/#!lubber/t6az41op/1/
- Watch console: The responseAsync callback is fired twice.
https://jsfiddle.net/edanL3gf/
- Dropdown appears on …
> [Dropdown] Menu did not show up on mobile when search and api was used (api was also called twice)

- src/definitions/collections/grid.less
A `stackable grid` inside a popup did not have enough specificity to adjust the width on mobile views
- Click on the red bar to show the popup 
- Adjust screen to mobile size
- Watch the blue background
- Remove the CSS to see issue
https://jsfiddle.net/lubber/fv1hg0jm/5/
> [Grid] stackable grid had wrong width inside popup

- src/definitions/elements/icon.less
When making use of a `floating label` inside an icon group, the label text is shown italic (because icon groups use the `i` tag
https://jsfiddle.net/lubber/786vh0Lt/3/
> [Icon] Labels in icon groups where shown italic

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
When selection of adjacent days is enabled by `selectAdjacentDays:true`. those days should respect possible existing eventdates classes as well as active selected days
- The first of November should be shown as eventdate in the adjacent days area of october
- A selection of the third of November inside the adjacent days area of October should be shown
https://jsfiddle.net/lubber/c4s9dLm0/20/
https://jsfiddle.net/lubber/c4s9dLm0/21/
#1734
> [Calendar] Show active and eventdates on enabled adjacent days

- src/themes/default/globals/site.variables
This PR tries to solve the issue that `gulp-concat-css` doesn't find the google path because of the semicolons
This issue does only occur when building inside a node_modules folder. using `npx gulp build` inside a forked git repo folder is /was still working while having semicolons inside the google path
#1738
> fix(chore): use url encoded semicolons so gulp-concat doesnt break

- src/definitions/elements/icon.less
Adds one more `.icon` to the icon color definition to make it work in nested lists.
https://jsfiddle.net/medc42zu/2/
#1748
> [Icon] Make colored icon selector more specific

- src/definitions/modules/slider.js
This PR adds a new option to the `set value` or `set rangeValue` behavior to optionally avoid the `onChange` callback
The change is backward compatible, because when the new parameter is omitted, it behaves like before (triggering the callback)
`.slider('set value',10,false)`
The onChange callback is triggered immediatly
`.slider('set value',10)`
https://jsfiddle.net/lubber/pwfd81rL/2/
The onChange callback is not triggered
`.slider('set value',10,false)`
https://jsfiddle.net/lubber/pwfd81rL/3/
#1750
> [Slider] support control over change trigger when setting a value or range

- src/definitions/elements/icon.less
- src/themes/default/elements/icon.variables
I added functionality to make an icon group bordered.
```html
<p>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="corner pen icon"></i>
</i>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="user icon"></i>
</i>
<i class="huge bordered icons">
<i class="big red dont icon"></i>
<i class="black user icon"></i>
</i>
</p>
<p>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="corner pen top left icon"></i>
</i>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="corner pen top right icon"></i>
</i>
<br>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="corner pen bottom left icon"></i>
</i>
<i class="huge bordered icons">
<i class="book icon"></i>
<i class="corner pen bottom right icon"></i>
</i>
</p>
``` …
> [Icons] allow corner icons and icon groups to be bordered

- scripts/nightly-version.js
The current nightly build script is expecting only one available numeric semver milestone to be available, because it only filters milestones which have a "x" inside their version.
While i was preparing issues to 2.9.0 by creating new milestones, the nightly build is fetching the wrong milestone and does not build (correctly) anymore
This PR now sorts all existing milestones ((still leaving out those including an x) to make sure the next upcoming version will be catched
Watch the console
It will identify 2.9.0 as next nightly build version
https://jsfiddle.net/lubber/hru65zet/7/
It will identify 2.8.8 as next nightly build version
https://jsfiddle.net/lubber/hru65zet/5/
> fix(chore): Fetch correct milestones for nightly beta build

- src/definitions/collections/table.less
The first header cell of definition table disables the pointer event which causes the problem when the cell contains the content that are needed the pointer event such as dropdown, input field or the content from title attribute is unable to be seen.
This PR changes the behavior of pointer event to become available if there is content inside the cell.
Put the mouse cursor over the header `Foo title` and `subtitle` in the first cell.
**Before (Tooltip disappear):** https://jsfiddle.net/ko2in/furswynh/2/
**Now (Tooltip appears):** https://jsfiddle.net/ko2in/furswynh/3/
#1756
> [Table] Allow pointer events for the first header cell in definition table

- src/definitions/views/card.less
The content element of the card has top border and the card also has box shadow which makes the card border thicker when 
the card representing the content horizontally.
This PR removes the top border from the card content if it's inside the horizontal card.
**Before:** https://jsfiddle.net/ko2in/9fyxu08L/
**After:** https://jsfiddle.net/ko2in/82ykuofc/
**Before:**
**After:**
None
> [Card] Fix the top border thickness of horizontal card

- src/definitions/views/card.less
- src/themes/default/views/card.variables
When header link was inside an inverted cards group (not inside a single card!), it was not styled properly.
This PR now adds the same logic as for single card making link header visible again
https://jsfiddle.net/lubber/t8asvzdk/12/
https://jsfiddle.net/lubber/t8asvzdk/13/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/98971950-1c567800-2512-11eb-8e8e-8b7dc5eb2971.png)|![image](https://user-images.githubusercontent.com/18379884/98971807-ef09ca00-2511-11eb-9904-61ba0f312aba.png)|
> [Card]: Inverted header links were not styled properly

- src/definitions/elements/loader.less
- src/definitions/views/card.less
- src/themes/default/globals/variation.variables
- src/themes/default/views/card.variables
This PR adds the `disabled` and `loading` variant to the `card` view. It's basically a selector copy from `segment`
https://jsfiddle.net/lubber/w34yba98/22/
https://github.com/fomantic/Fomantic-UI/issues/928#issuecomment-520630529
> [Card] Disabled and loading variants just like segment

- src/definitions/elements/segment.less
In `disabled` or `loading` segments, selection of text via mouse or even clicking on links was still possible
I also removed the unnecessary text-shadow setting
Try to select the header inside the two segments with your mouse or click in the link, it should not work
Remove the custom CSS part to see the issue
https://jsfiddle.net/lubber/dz30etxj/26/
> [Segment] Prevent user selection on disabled and loading segments

- src/definitions/modules/dropdown.less
icon groups were not respected to add the same margins inside dropdown menus as for single icons
https://jsfiddle.net/lubber/3qw8ck2o/
https://jsfiddle.net/lubber/3qw8ck2o/2/
> The visible margin difference to the first entry is because of the wider used single icon but the margin itself is the same
#1765
> feat(dropdown): support icon groups margin

- src/definitions/modules/dropdown.js
When a multiple dropdown (non select) was used and selected data has characters like `&` or `'` set, there were stored entity encoded (returning into false positives when comparing later to their original values). Even worse this was only done for all previous selected values, the current to be added value was kept raw already. dropdowns using select tags do not store the selected data in an input field, so the issue does not happen there.
Original data should be kept, as it is already the case for dropdown made out of select tags. Also SUI does not do this.
Additionally this PR fixes a situation when a value has double quotes which led to a js error when trying to remove that label .
Double quotes in select menus are now also kept encoded instead of being removed to have the same …
> [Dropdown] multiselect values encoding, label cannot be removed, quotes missing in select dropdown

- src/definitions/modules/toast.js
- src/definitions/modules/toast.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/toast.variables
This PR adds 
- the `horizontal` variant
- dynamic setting of title, message, icon or image to a toast template create out of an existing DOM node
- makes the close duration time configurable just as it is possible for show/hide duration
to the `toast` module.
The testcase uses DOM Node templates without content as  a base to create the toast and changes its content by the usual settings and makes use of the new `horizontal` variant.
https://jsfiddle.net/lubber/Lsrg071y/45/
#1370
> [Toast] horizontal variant and dynamic DOM node content support

- src/definitions/modules/modal.js
This PR adds the same dynamic functionality like toast to create a modal just out of properties or reuse a DOM node modal as a template with its content being dynamically set via js properties.
Everything is optional and backward compatible 🙂 
Most of the code is copied /adopted from the toast component so the usage is equal.
This goes along with @prudho fui-alert plugin approach (#1716) which could be more simplified then
By providing new properties to the modal module and targeting to body you create temporary modals without the need to create markup on your own. The modal is temporary and will be removed from the DOM once closed.
```javascript
$('body').modal({
title: 'Important Notice',
class: 'mini',
closeIcon: true,
content: 'You will be logged out in 5 Minutes',
actions: [{
text: …
```
> feat(modal): dynamic modal content

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
There currently is no declarative way to display content of a modal center aligned.
- Workaround for header is `icon header` or `ui centered header` or `ui center aligned header`
- Workaround for `actions` is to create an own theme modifying the `@actionAlign` variable
- For the content  itself there is no workaround than creating a css class manually (would also work for actions
This PR copies over the existing variant from `header` (which supports `centered` as well as `center aligned` already) and applies it to any direct sibling of the modal itself, so  `header` or `content` or even `actions` can be displayed centered out of the box in the fomantic way
https://jsfiddle.net/lubber/qb8pe0rj/4/
> [Modal] Centered variant for any content

- src/definitions/modules/calendar.js
The date sanitizer returns `undefined` when the date argument is not a valid date object or date string which doesn't allow to reset the date value especially for min and max date by passing `null` value via `set minDate` and `set MaxDate`.
This PR makes the `sanitiseDate` method to return `null` if the value of date argument is not valid date object or date string.
**Unable to reset min date and max date:** https://jsfiddle.net/cr7myt25/2/
**Enable to reset min date and max date:** https://jsfiddle.net/ko2in/8ym30fju/8/
#1776
> fix(calendar): return null instead of undefined in sanitizer

- src/definitions/modules/dropdown.js
When clearing the selected items from multiple dropdown via `clear` method, the `onChange` callback triggers although the `preventChange` is set as true.
It's because, when the dropdown is multiple selection, the `clear` calls the specific internal method to remove multiple selected items without forwarding the `preventChange` setting which results triggering the `onChange` callback.
This PR makes the `clear` method to call the internal method by passing the `preventChange` setting which supports to prevent triggering the `onChange` callback.
**Bug:** https://jsfiddle.net/ko2in/vadg8nr2/1/
**Fix:** https://jsfiddle.net/ko2in/vadg8nr2/2/
**Bug:**
**Fix:**
#1781
> fix(dropdown): Clearing multiple selection dropdown supports to prevent onChange callback

- src/definitions/modules/dropdown.js
When the menu contain the child menu, the calculation of menu height is incorrect while evaluating to open upward or downard.
It's because the child menu is hidden when the current menu is in the transition of being open and it doesn't occupy any space in the current menu and the height of the current menu is incorrectly calculated without the height of child menu which let the menu opens upward or downward incorrectly.
This PR checks if the current menu has the child menu and adds the child menu height to the current menu height to give correct assumption whether the menu fits in the screen upward or downward.
Open the fiddle and adjust the page where the dropdown is not fit to open downward. Click the button to open dropdown. The dropdown should open upward.
- Bug: …
> fix(dropdown): calculate correct height of current menu if it contains child menu

- src/definitions/elements/button.less
A `labeled icon button` got a wrong margin especially when used for multiple dropdown buttons as the specificity changed in  #1571 
However `labeled icon buttons` are never supposed to be displayed without text so the selector for single icon buttons should not select labeled buttons.
- Adjust the selector via console accordingly
https://jsfiddle.net/jLn0wkv9/1/
#1783
> [Button] labeled icon buttons have wrong margin

- src/definitions/collections/table.less
This PR fixes a missing comma, which otherwise led into a wrong selector generation
Thanks to @ivantcholakov for finding this typo! 🙂 👍 
https://github.com/fomantic/Fomantic-UI/commit/c0483997eaf3e378abcaef1cf6b25bdfd1d33ffb#r44990281
> fix(table): missing comma lead into wrong selector

- src/definitions/modules/dropdown.less
In cases where you want to use an inverted dropdown menu, without having the dropdown being inverted itself, this wasnt possible.
Especially when one uses menus with dropdown buttons inside, this was not supported.
This PR now allows to have an `inverted menu` inside a non-inverted dropdown.
- The left button is a non-inverted dropdown but uses an `inverted menu`
- The right button is an `inverted dropdown` as usual
- Only Right menu is inverted
https://jsfiddle.net/lubber/v2mc7gre/
- Both menus are inverted
https://jsfiddle.net/lubber/v2mc7gre/2/
> feat(dropdown): support inverted menu in non-inverted dropdown

- src/definitions/collections/grid.less
Compact and very compact grids had the same margin as the normal grid when they should have had smaller margins. In addition, the layout was working differently for a normal grid vs compact/very compact grids and these changes makes all the grids work consistently.
Compact and very compact grids extend outside of parent element
https://jsfiddle.net/wovbrhp1/4/
https://github.com/fomantic/Fomantic-UI/issues/1260
> fix(grid): incorrect margins in compact and very compact grid

- src/definitions/collections/form.less
- src/definitions/elements/input.less
[Firefox does not set the default placeholder to 100% opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#Opaque_text)
This results into a visual difference when an input field is shown next to a dropdown, whereas the placeholder opacity is 100%, while firefox defaults it around 54%
Open in Firefox to see the difference: The normal input fields placeholders have a lower opacity than the dropdown placeholder
https://jsfiddle.net/lubber/eh8v6y35/2/
https://jsfiddle.net/lubber/eh8v6y35/4/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/102506740-b6ff2500-4083-11eb-99f3-1606545c0d3d.png)|![image](https://user-images.githubusercontent.com/18379884/102506669-a77fdc00-4083-11eb-8fd0-886c1b66402f.png)| …
> [Input / Form] Firefox has different placeholder opacity by default

- src/definitions/elements/header.less
Icon groups were not supported in headers
https://jsfiddle.net/lubber/4kwhux5t/12/
https://jsfiddle.net/lubber/4kwhux5t/21/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/102535891-22a7b900-40a9-11eb-83bd-7df579574dd0.png)|![image](https://user-images.githubusercontent.com/18379884/102538989-5a186480-40ad-11eb-86e8-d4a2352d2689.png)
https://github.com/Semantic-Org/Semantic-UI/issues/2553
> [Header] Support icon groups

- src/definitions/collections/message.less
Usage of icon groups were not supported for `icon message`.
http://jsfiddle.net/lubber/0ht8y135/15/
http://jsfiddle.net/lubber/0ht8y135/13/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/102527770-e6229000-409d-11eb-9534-e70ca53bcd97.png)|![image](https://user-images.githubusercontent.com/18379884/102527722-d440ed00-409d-11eb-8e86-d1481a281d67.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/2553
> [Message] Support icon groups

- src/definitions/behaviors/form.js
It was not possible to allow for an optional range check for the decimal or number validator. This was only supported for integer values.
This PR now 
- supports decimal and number validators to supply a range by making the check for a range value a separate `range` validator so it can be reused.
- adds 2 new validators `maxValue` and `minValue` accordingly
- displays the range values in the default error prompt as well if no prompt is given 
```javascript
rules: [
{
type   : 'decimal'
}
]
```
```javascript
rules: [
{
type   : 'decimal[0.5..1.9]'
}
]
rules: [
{
type   : 'minValue[50]'
}
]
rules: [
{
type   : 'maxValue[10]'
}
]
```
https://jsfiddle.net/lubber/g3nte1m6/14/
https://github.com/Semantic-Org/Semantic-UI/issues/5496
> [Form]: Support range values for decimal and number validation, add max/minValue and display range in default prompt

- src/definitions/collections/form.less
When a dropdown item has got a description, every added state class like `error` also styles such extra items by accident
Original fix by @awgv 
http://jsfiddle.net/lubber/w8ugyc6d/2/
https://github.com/Semantic-Org/Semantic-UI/issues/5207
https://github.com/Semantic-Org/Semantic-UI-React/issues/1462
> [Dropdown / Form] Item text with descriptions gets wrong state class

- src/definitions/modules/popup.less
A `bottom center` tooltip had it's arrow misaligned and not correctly centered
https://jsfiddle.net/lubber/9mbupL4t/16/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/102603076-a0f47180-4122-11eb-8c4f-7ca98b33db66.png)|![image](https://user-images.githubusercontent.com/18379884/102603019-91752880-4122-11eb-8005-ad2e58951a24.png)
https://github.com/Semantic-Org/Semantic-UI/issues/7021
> [Tooltip] Bottom center tooltip was misaligned

- src/definitions/collections/message.less
- src/themes/default/globals/variation.variables
This PR adds a `centered` or `center aligned` as well as a `right aligned` variant to the `message` component just like many other components already support.
https://jsfiddle.net/lubber/03qx4gr5/39/
https://github.com/Semantic-Org/Semantic-UI/issues/5049
> [Message] centered and right aligned variant

- src/definitions/modules/checkbox.less
- src/definitions/modules/dropdown.less
- src/themes/default/globals/variation.variables
The `read-only checkbox` still changed their cursor on hover confusing the user one could still change it.
While doing it i added support for `read-only` to the dropdown component as well
- Removed cursor changes for `read-only checkbox`
- Added "read-only" variant to `dropdown` similar to the existing variant for `checkbox`
https://jsfiddle.net/lubber/s25L87ud/5/
|Before|After|
|-|-|
|![readonlywrong](https://user-images.githubusercontent.com/18379884/102715872-70563880-42d8-11eb-896e-9a0d646c5b40.gif)|![readonlyfix](https://user-images.githubusercontent.com/18379884/102715879-751aec80-42d8-11eb-9790-cda81aa6f15b.gif)|
https://github.com/Semantic-Org/Semantic-UI/issues/5482
> [Checkbox, Dropdown] Support and fix read only variant

- src/definitions/behaviors/form.js
The validation triggered by change and blur are similar. However, the code was unneccesary different.
Additionally the blur validation did not respect a possible given `revalidate:false` resulting in revalidating error fields all the time when the field blurs (even if one only wants revalidation on submit)
It also fixes not showing/updating the error messages on blur as change does
- Click on "submit" to invalidate the fields
- Enter something in the first input field. It does not immediatly revalidate while typing, because `revalidate:false` prevents that (which is correct)
- Now blur the field by pressing tab or click somewhere outside the field
The field gets revalidated
http://jsfiddle.net/lubber/g8n9c6kb/4/
The field does not get validated as expected …
> [Form] Simplify Blur validation and respect revalidate:false

- src/definitions/behaviors/form.js
When a form gets initialized it is refreshing the field selectors.
This is fine as long as there is only one call to the same form. Whenever a later bahavior call like `get values` takes place on the same form and the form fields have changed, the previous stored instance is not getting refresh (because only the "new" module is)
The[ original issue in the SUI repo](https://github.com/Semantic-Org/Semantic-UI/issues/5703) had a very good detailed explanation and jsfiddle example (thanks @cueedee) and the solution which i adopted in a similar way.
- A form gets initialized 
- another field input is added to the DOM
- the existing form is called again with the behavior "get values"
- It is expected that also the new field is affected
- Focus on the textarea at `4` to see the difference
- It …
> [Form] Refresh on instance rather than module to fetch dom changes

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
Inline (or no selection) dropdowns did not support `clearable` (while SUI does and even the FUI docs mention it)
Remove CSS to see the issues
https://jsfiddle.net/lubber/hemuypkc/8/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/102779186-174bda80-4394-11eb-8092-abc0254f1a23.png)|![image](https://user-images.githubusercontent.com/18379884/102820709-fd32ec00-43d5-11eb-9de1-b0561001598a.png)|
#924 
https://github.com/Semantic-Org/Semantic-UI/issues/5800 (loading / min-width fix)
> [Dropdown] Clearable inline support

- src/definitions/modules/nag.js
- src/definitions/modules/nag.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/nag.variables
This PR finishes the `nag` module. It was hidden from the docs, because there were still bugs inside and not completely done (but already used in several projects). I refactored some code and added usual features so this module can be officially supported again (I'll do another PR for the docs then) 
- Removed the dependency of the jquery cookie plugin. Cookie storage method is now natively supported inside the module. Now every storage method also got the same api for easier abstraction
- Added expiration functionality for localstorage method as well 
- Added color support
- Added sizing support
- fixed grouping (wrong border radius)
- fixed animation (wrong direction)
- slightly fixed text colors for better contrast
- fully backward compatible to existing code …
> [Nag] Refactored: no jquery cookie plugin dependency, colors, sizes, fixes

- src/definitions/elements/icon.less
Icon transformations like `rotated` or `flipped` were not supported when used inside icon groups
https://jsfiddle.net/lubber/pf0yq7ta/4/
https://jsfiddle.net/lubber/pf0yq7ta/5/
#1740
> [Icon] Support transformations in icon groups

- src/definitions/modules/toast.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/toast.variables
Another year, another Toast enhancement 😄 
- new position variants `top attached` and `bottom attached` which will show the toast over the whole width of the screen. Just like notificatons on mobile devices
- support for `centered` content and actions as we now have in other components as well
- fixed a visual bug when more than 2 vertical attached action buttons were used
- made compact variant unselectable at compile time
> Hint for reviewers: 
> The usage of `attached` position variants in combination with `centered` toast class does only support `attached` actions (because of the flexbox usage to align a possible icon/image next to the content.)
https://jsfiddle.net/lubber/gdst7h6j/
> [Toast] Top/Bottom attached position variant and centered support

- src/definitions/behaviors/form.js
It was not possible to mix shorthand and full object rules together (only the first one validatedc and then crashes at JS console).
Example:
```javascript
fields: {
gender: {
identifier: 'gender',
rules: [
{
type   : 'empty',
prompt : 'Please select a gender'
}
]
},
bender: 'empty',
render: 'empty'
}
```
Click on "Submit", every field should invalidate
- Watch console: JS error, no form error message, only first field invalidates
https://jsfiddle.net/lubber/gthw5ejc/1/
- All fine 😁 
https://jsfiddle.net/lubber/gthw5ejc/2/
https://github.com/Semantic-Org/Semantic-UI/issues/2688
https://github.com/Semantic-Org/Semantic-UI/issues/3027
https://github.com/Semantic-Org/Semantic-UI/issues/6026
> [Form] Support mix of shorthand and full object field rules

- package-lock.json
- package.json
- tasks/config/tasks.js
This PR upgrades gulp-clean-css (respectively clean-css) to the latest version.
Now the removement of special header comments in the concatenated minified css file `semantic.min.css` is properly done and works
Before, the minified concatenated css file still contained every special `/*! ... */` header from each single .css file which increased the minified css file significantly.
> #### Note for reviewers in case you wonder, why i removed nearly all previous options for the minify plugin
> Just because those previous values are default now in clean-css 4.2 (gulp-clean-css 4.3 depends in clean-css 4.2 ... don't get confused)🙂 
`npm install && npx gulp build`
The created `dist/semantic.min.css` does only contain one single comment header, but not every header from each concatenated single …
> fix(build): upgrade css minify and remove specialcomments in concat build

- package-lock.json
- package.json
- tasks/config/project/release.js
- tasks/config/tasks.js
This PR adjust some build settings. It...
- prepares for the next 2.8.8 release by updating the version number in `package.json`. For 2.8.7 this was done after the NPM upload, so the 2.8.7 release had the 2.8.6 header.
- fixes inclusion of the version number in the comment headers of each file (was omitted since a few versions)
- fixes to adjust the year in the comment header to the year of release (was a hardcoded 2014 before)
```
/*!
* # Fomantic-UI - Accordion
* http://github.com/fomantic/Fomantic-UI/
*
*
* Released under the MIT license
* http://opensource.org/licenses/MIT
*
*/
```
```
/*
* # Fomantic UI - 2.8.6
* https://github.com/fomantic/Fomantic-UI
* http://fomantic-ui.com/
*
* Copyright 2014 Contributors
* Released under the MIT license
* http://opensource.org/licenses/MIT
*
*/ …
```
> fix(build): use current year and implement version in header

- src/definitions/behaviors/form.js
This PR adds support to use the form wide `shouldTrim` setting individually per field rule 
Enter "    dog" (leading spaces) into the field. Although the global `shouldTrim` setting is set to false, the field still validates, because `shouldTrim:true` is set to the fieldrule itself
https://jsfiddle.net/lubber/6349nfh0/1/
#1278
> [Form] Support shouldtrim option per fieldrule

- src/definitions/elements/icon.less
- src/themes/default/elements/icon.variables
- Moved corner icon offsets into a variable, so one can easily adjust them
- Added render condition to possibly reduce CSS
> feat(icon): use corner offset variables

- src/definitions/collections/form.less
- src/definitions/collections/grid.less
- src/definitions/modules/slider.less
- src/themes/default/collections/grid.variables
- src/themes/default/collections/table.variables
- src/themes/default/elements/header.variables
- src/themes/default/elements/list.variables
- src/themes/default/globals/site.variables
- src/themes/default/modules/checkbox.variables
- src/themes/default/modules/dropdown.variables
- src/themes/default/modules/modal.variables
- src/themes/default/views/card.variables
LESS 4 enforces parenthesis to divider math operations. This was missing at a few places so Fomantic did not build with LESS 4
A codesnippet from FUI
The div should have a red background with a visible top margin.
- using LESS 3.13.1. All fine
https://jsfiddle.net/lubber/8mqpo3ne/2/
- using LESS 4.0.0. Breaks. No color, no padding
https://jsfiddle.net/lubber/8mqpo3ne/8/
- using LESS 4.0.0 and added parenthesis. Works again
https://jsfiddle.net/lubber/8mqpo3ne/10/
#1818
> [Chore] Added parenthesis to math divisions to support LESS 4

- src/definitions/modules/modal.js
When a modal opens and the screen ist large, so there exists a scrollbar, selected fixed elements on the screen are adjusted so they dont move while the screen is shown/closed.
- The `fixed nag` element was missing to be supported
- existing values for `padding` were not taken into account. For all previous selectors (toast-container, menu, sidebar) this was not a problem, because they haven't had a padding by default. But the new `nag` selector actually has a padding of 1em.
- In case a non fixed selector was used, the `padding` was the wrong approach (for example the `close` icon inside the `nag`)
- When the modal hides, the previously set values for padding were overridden by 0. Whenever there was a default padding before, this would not work anymore. I now completely removed the …
> [Modal] bodyfixed selector did not work with existing padding values

- src/definitions/modules/dropdown.js
When a dropdown was initialized by providing its values via settings parameter, it was not possible to define a submenu structure, which will also simplify such tasks when working with remote data.
This was only possible by using existing DOM structure before.
This PR now allows for a value type `menu`, `left menu`, `right menu`.
```javascript
values: [
{
name: 'Age',
value: 'age',
type: 'menu',
values: [
{
name: 'Baby',
value: 'baby'
},
{
name: 'Kid',
value: 'kid'
},
{
name: 'Teen',
value: 'teen'
}
]
}
]
});
```
https://jsfiddle.net/lubber/qu6nf81p/5/
A discord request 😉
> feat(dropdown): support submenu values

- src/definitions/modules/progress.less
`centered progress` was missing a slight adjustment to really display the text centered
https://jsfiddle.net/lubber/w5bkzr3h/2/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/103408003-0b64d300-4b61-11eb-8c85-2d745e0c2541.png)![image](https://user-images.githubusercontent.com/18379884/103408013-13247780-4b61-11eb-8637-afa616c92c93.png)|![image](https://user-images.githubusercontent.com/18379884/103407976-eff9c800-4b60-11eb-9a66-498ab82bc00f.png)![image](https://user-images.githubusercontent.com/18379884/103407990-fb4cf380-4b60-11eb-8087-19b82f1dbf1f.png)|
> fix(progress): adjust center position

- src/definitions/behaviors/form.js
This PR fixes a regression from #1811 whereas the fields are not refreshed anymore when a form gets initialized a second/multiple times
Watch the last section of the testcase
https://jsfiddle.net/lubber/s9p4moyx/10/
https://jsfiddle.net/lubber/s9p4moyx/11/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/103755390-0cd54600-500e-11eb-9c8a-16a720dc27e0.png)|![image](https://user-images.githubusercontent.com/18379884/103755417-19f23500-500e-11eb-8501-c5eadaf3c478.png)|
https://github.com/fomantic/Fomantic-UI/pull/1811#issuecomment-755162533
> fix(form): refresh module on re-initializaion

- src/definitions/collections/form.less
- src/definitions/collections/message.less
- src/themes/default/globals/colors.less
- src/themes/default/globals/site.variables
The state colors in `inverted form` and `inverted message` were too dark for field label and message text
I adjusted them so they now match a error field input label to make it readable and consistent
https://jsfiddle.net/lubber/hczb1rg2/52/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/103707098-5726da80-4fae-11eb-8987-061ee0aa4fac.png)|![image](https://user-images.githubusercontent.com/18379884/103707054-41191a00-4fae-11eb-93ed-5591ed169ef0.png)|
> fix(form): inverted state forms colors

- src/definitions/modules/toast.less
- src/themes/default/modules/toast.variables
an `attached` positioned toast container still showed an 1px background on the right of the toast
https://jsfiddle.net/lubber/9vkoqp8m/21/
Look closely to the very right of the toast. You can see a 1px background green color
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/104102335-00671c80-529e-11eb-927e-edf7cf0ce5f8.png)|![image](https://user-images.githubusercontent.com/18379884/104102179-efb6a680-529d-11eb-93f1-e88aa020d0bd.png)|
> fix(toast): attached toast margin and border

- src/definitions/modules/nag.js
The `nag` module was still missing the usual callbacks `onshow`, `onvisible`, `onhide`, `onhidden` we have in other modules like modal , calendar or toast.
Even worse, existing code was not even used anywhere or non existing options (`speed` (exists, not used) -> `duration` (used, non existing)
All of this has now been corrected 😊 
Turn on developer console and watch the output while showin/hiding/dismissing the nag
https://jsfiddle.net/lubber/k7xodeqz/2/
> fix(nag): missing callbacks and fixed unused code

- src/definitions/elements/loader.less
- src/definitions/elements/segment.less
This PR adds support to use `loading`, `disabled` or `inverted` to the group variants instead of each single segment inside a group
https://jsfiddle.net/lubber/dz30etxj/60/
https://github.com/fomantic/Fomantic-UI/discussions/1842
> feat(segment): disabled, inverted and loading groups

- src/definitions/elements/icon.less
- src/themes/default/elements/icon.variables
- src/themes/default/globals/variation.variables
This PR adds a `colored` variant to `circular` or `bordered` icon(s).
Currently the border of a circular or bordered icon is always grey. Even if the icon itself has got a color.
By adding a `colored` class to such icons the border will inherit its color from the icon itself.
https://jsfiddle.net/lubber/8xqfopah/3/
> feat(icon): colored variant for bordered or circular

- src/definitions/modules/dropdown.js
This PR adds a new `onSearch` callback to allow access to the search term being entered so that external processes can be informed about the term being typed in. Such processes may include an API that requires authentication with a token, especially if the website in question already has an existing API
https://jsfiddle.net/oafqnm3v/
Relates to #1846
> feat(dropdown) adds onSearch callback for when searching in the dropdown

- src/definitions/modules/dropdown.js
Adds additional options to `remoteData` to allow a description to be created and also allows to specify if using/wanting a vertical description
https://jsfiddle.net/lubber/ywpLuk4c/3/
Relates to #1845
> feat(dropdown): addition of (vertical) descriptions to menu item template

- src/definitions/elements/icon.less
I accidently placed the `.colored` selector outside of the icon scope with #1856 which made the specificity useless. 🙄 
This PR is fixing this
> fix(icon): colored selector was wrongly placed

- src/definitions/behaviors/form.js
Whenever the escape key was pressed inside an input of a form and the validation trigger was set to `blur` and using jquery >= 3.4.0 the "maximum callstack exceeded" error occurs.
This is because jquery removed/changed the internal `blur()` handling.
By using the native `.blur()` instead this error is fixed
- Click into the first inut field, so it gets focus
- Press the ESC Kay
"Maximum callstack Exceeded"
https://jsfiddle.net/lubber/ou7ft2bs/2/
No error as expected
https://jsfiddle.net/lubber/ou7ft2bs/3/
|Broken|Fixed|
|-|-|
|![formcallstack_bad](https://user-images.githubusercontent.com/18379884/107114821-1f3edb80-6869-11eb-81ee-abd17ad4d281.gif)|![formcallstack_good](https://user-images.githubusercontent.com/18379884/107114826-249c2600-6869-11eb-9ce4-150a7f4fbba0.gif)| …
> feat(form): escaped caused maximum callstack exceeded

- src/definitions/collections/menu.less
`column dropdown` was not working when used inside menus
The right "Leaderboard" Menu entry is supposed to be a `two column` dropdown
- It's ignored and still displayed as one column
- https://jsfiddle.net/lubber/or6nd413/10/
- Two columns as expected
https://jsfiddle.net/lubber/or6nd413/9/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/107130630-be96b980-68cf-11eb-9043-b4ca905ede95.png)|![image](https://user-images.githubusercontent.com/18379884/107130637-cf472f80-68cf-11eb-8c0a-0fabae9edce6.png)|
> feat(dropdown): columns were ignored inside menus

- src/definitions/modules/dropdown.js
The `name` fields property was doubled by #1852 . This PR removes the redundant entry
> fix(dropdown): double declaration of name

- src/definitions/modules/dimmer.js
This PR offers the same possibility to provide individual transform methods for show and hide animations as we have for `toast`
So in addition to `transition:'fade'` (which still works so stays backward compatible), you can now use the same as in toast:
```javascript
transition: {
showMethod: 'fade',
hideMethod: 'zoom'
}
```
> feat(dimmer): support individual show/hide transition

- src/definitions/modules/search.js
As the docs tell, when the `onSelect` callback returns `false` there should be no selection and menu hiding happen.
But infact only the menu is not hidden, the value is still selected.
This is because of #83 where it was made possible to change the value inside the onSelect callback.
To still support this i moved the value setting back to the point after the callback but now the value is only overridden if the previous value is still unchanged (to recognize a possible manual change in the callback.
- Enter something in the searchfield to bring up the menulist
- Select something from the list
Although the onSelect callback returns false, the value is still overridden, while the menu remains
http://jsfiddle.net/lubber/9z4j5wqo/9/
Value is not overridden, menu remains, just as the docs say …
> fix(search): dont set value when onselect returns false

- src/definitions/modules/dropdown.js
- src/definitions/modules/search.js
Chrome based Browsers ignore `autocomplete='off'` 
Read their reasons here https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164
Unfortunately this leads into having the search input field in a dropdown getting those autocompletes as well.
As the above mentioned comment mentions, this PR set a semantic name as autocomplete value instead of "off" when the browser is chromium based.
Here, the dropdown has a label named "Adress". This triggers Chrome to show the autocomplete even if "autocomplete="off" is set (which works in other browsers like firefox as expected)
You may have to create an address in the chrome settings (in case you havent already save any) to see the autofill
https://jsfiddle.net/lubber/3gw9rk8o/6/
No autofill
https://jsfiddle.net/lubber/3gw9rk8o/8/
#1880 …
> fix(dropdown): autocomplete in chrome does not support "off"

- src/definitions/modules/modal.js
- src/definitions/modules/modal.less
This PR adds the possibility of using JS config templates for the modal module.
That means you can declare a reusable dynamic template function which returns predefined config settings (modified depending of your input to the template function) as the modal is already prepared to create dynamic content out of pure js since #1774 
For this reason modal now also has an optional `autoshow` option, which enables you to immediatly show the modal on instantiation time, so no more need for `$(.ui.modal).modal({closable:false}).modal('show')` but `$(.ui.modal).modal({closable:false, autoShow:true})`
Modal now also can use the transition methods for show/hide individually (backwards compatible) (just like in toast and for dimmer in #1867) 
A js template is called as a modal behavior
```javascript …
```
> [Modal] JS Config Templates, alert, confirm, prompt

- src/definitions/modules/search.js
When a search has no result and one presses the "arrow down" key on the keyboard, a javascript error
> Cannot read property 'top' of undefined
occurs
This PR also fixes dead, unused and unnecessary code of the affected function "ensureVisible"
https://jsfiddle.net/vphxjf61
https://jsfiddle.net/vphxjf61/1/
#1964
> fix(search): fetch "Cannot read property 'top' of undefined

- src/definitions/elements/segment.less
When a `placeholder segment` is used for tabs, it messes up the display.
Switch between the tabs, the placeholder tab should only be visible when tab 2 gets activated
Messed up, the placeholder is shown all the time and also totally misaligned
https://jsfiddle.net/eo7sut0g/
All fine
https://jsfiddle.net/lubber/bf1t4nzq/12/
#1920
> fix(segment): support placeholder segments for tab usage

- src/definitions/elements/header.less
An `icon header` has got a left padding which is only supposed to be needed when it's a normal header having an icon next to the header text
https://jsfiddle.net/lubber/c0vapqbz/2/
#1908
> fix(header): icon headers should not have a left content padding

- src/definitions/behaviors/form.js
When using input masking libraries like [Cleave.js](https://github.com/nosir/cleave.js/) in conjunction with Fomantic form validation rules for payments, legitimate card numbers from Fomantic's test cards would not validate if it contained spaces.
JSFiddle showing the problem: https://jsfiddle.net/h8pe31qb/
JSFiddle showing the solution with the modified line in this PR (excuse the roughness, I simply pasted in the result of my `gulp build` with the change included: https://jsfiddle.net/og5a6x2w/
Failure on valid credit card number:
After fix: No validation error
> feat(validation): allow credit card numbers with spaces

- src/definitions/modules/calendar.js
When the `disabledDaysOfWeek` setting is used for the `calendar` module, this messed up the month or year selection
Open the calendar and click on the year to select a different month or a different year
Some months/years are also disabled
https://jsfiddle.net/lubber/twhdeuqb/
All months and years are selectable
https://jsfiddle.net/lubber/twhdeuqb/2/
|Broken|Fixed|
|-|-|
|![disableddays_broken](https://user-images.githubusercontent.com/18379884/112612731-8ca9ca00-8e1f-11eb-8d28-370128957404.gif)|![disableddays_fixed](https://user-images.githubusercontent.com/18379884/112612748-90d5e780-8e1f-11eb-9686-f8b648f27d22.gif)|
#1927
> fix(calendar): disabled week days should not affect month and year view

- src/definitions/behaviors/form.js
When a form contains a file upload field it is also bound to several form events which are not supposed to happen on those and do not work because flie upload fields are limited in access.
That said, when using jQuery > 3.4.0, it triggers a `Maximum callstack exceeded instead`
- Click on the "Upload image" Button and select something you like 
"maximum callstack exceeded"
https://jsfiddle.net/vzctb5pu/2/
Nothing 🙂 
https://jsfiddle.net/lubber/7f269p84/8/
|Broken|Fixed|
|-|-|
|![formfilebroken](https://user-images.githubusercontent.com/18379884/115141916-263f5280-a03f-11eb-9a03-cb6936c7847e.gif)|![formfilefixed](https://user-images.githubusercontent.com/18379884/115141919-2a6b7000-a03f-11eb-8384-ad8db6bd0dd3.gif)|
> fix(form): file upload fields trigger error using jquery > 3.4.0

- src/definitions/behaviors/form.js
The dirty functionality uses jquerys `triggerHandler` method to bind namespaces extra events. Unfortunately this also calls native bound events twice.
The extra events however are not necessary, it is enough to call the namespaces dirty/clean checker on the original events which prevents the multiple calls
- Open the modal
- Start typing something in the input field
- The `keyup` event is triggered twice
https://jsfiddle.net/lubber/p51nx39y
- The `keyup` event is triggered only once
https://jsfiddle.net/lubber/p51nx39y/1/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/116621741-f39d3000-a943-11eb-946a-77d331fdd9f4.png)|![image](https://user-images.githubusercontent.com/18379884/116621702-e3855080-a943-11eb-9401-c80051a14511.png)
#1942
> fix(form): separate dirty events trigger multiple native event calls

- src/definitions/modules/dropdown.js
- src/definitions/modules/popup.js
This PR adds optional support for individual setting of transition method and duration to the dropdown and popup module.
We already have the same optional setting in toast, modal and dimmer, so this PR concludes a unique syntax.
Because the settings are optional, this change is 100% backwards compatible. 
```javascript
// duration is used as before from settings.duration
transition: {
showMethod: 'zoom',
hideMethod: 'fly'
}
// complete individual settings
transition: {
showMethod: 'zoom',
showDuration: 1000,
hideMethod: 'fly',
hideDuration: 500
}
```
https://jsfiddle.net/lubber/4o6b8Lqp/37/
https://github.com/Semantic-Org/Semantic-UI/issues/2911
> feat(dropdown,popup): support individual show and hide transition and duration

- src/definitions/elements/segment.less
This PR adds support for `equal width` horizontal segments. We already have equal width in form and grid.
https://jsfiddle.net/lubber/dpr5fuq3/12/
|Before|After
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/119235478-0cf45f00-bb33-11eb-8051-7c84c57493ec.png)|![image](https://user-images.githubusercontent.com/18379884/119235469-fea64300-bb32-11eb-865b-3cbe7abc5cd2.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/5878
> feat(segment): support equal width

- src/definitions/modules/rating.less
A `disabled rating` component only changes the cursor but still allows for pointer events (for example when used inside a `card`.
https://jsfiddle.net/lubber/opLg53bq/1/
https://jsfiddle.net/lubber/opLg53bq/2/
#1972
> fix(rating): disabled rating should not allow pointer events

- src/definitions/modules/dimmer.js
This PR adds the same syntax for the optional `hideDuration/showDuration` value of the `transition` setting to the `dimmer` module as we already have in toast, modal, popup and dropdown.
As dimmer was the only module which was already/also supporting an object for the duration value, i kept the logic in for backward compatibility
https://jsfiddle.net/lubber/x2dzht4b/6/
> feat(dimmer): support individual show/hide duration

- src/definitions/elements/icon.less
The `loading` variant was missing for icon groups
https://jsfiddle.net/lubber/9q6g0d83/6/
> feat(icon): support loading variant for icon groups

- package.json
- src/definitions/modules/dimmer.js
We fixed support for LESS 4 by #1819 , but the package.json retricts installation to 3.x if less 4.x is already installed by throwing "this version is not supported". Seems more and more people have LESS 4 installed now which breaks installation in some setup environments 
I changed the dependency so every version >= 3.7 is supported now
#1893
> feat(dependency): support a possible installed v4 of less

- src/definitions/modules/slider.less
LESS 4 forces parenthesis for math division. There was one line missing to take care of that. Everything else was covered by #1819  already
> fix(slider): less 4 support needs parenthesis

- src/definitions/modules/modal.js
While preparing the docs for #1774 , i recognized that modal
- does not create action buttons at all when the actions container is not available in the DOM
- does always stack action buttons on DOM modals when reused
https://jsfiddle.net/lubber/5f6rm830/2/
https://jsfiddle.net/lubber/5f6rm830/3/
https://jsfiddle.net/lubber/5f6rm830/6/
https://jsfiddle.net/lubber/5f6rm830/5/
> fix(modal): dont stack same actions buttons

- scripts/nightly-version.js
The current nightly build is broken, because the next nightly version would be `2.9.0-beta-0`, which was already uploaded (by accident) to npm in 2019, so it already exists, which breaks the build.
This PR now checks for possible existing npm versions and increases the beta number accordingly.
> i found out that `2.9.0-beta.0` is not available in the `versions` property from the npm api, but it is in the `time` property of https://registry.npmjs.org/fomantic-ui
This PR also allows for possible downgrades.
Means, if we have a `2.9.0-beta.1234` but , by some reason, we would have to create a 2.8.9 at a later stage, the script would not allow that (the next github milestone was always supposed to be greater than the latest nightly)
> fix(nightly): check for already uploaded versions and support downgrades

- src/definitions/modules/calendar.js
This PR adds triggering of the `onSelect` event when user press the Enter key after entering a date in the input field. It also allow user to rollback if the date field is not correct for him by returning `false` (can be usefull for #1517 and #1518).
Before:
After:
>  feat(calendar): trigger onSelect() event on enter key down

- src/definitions/modules/dimmer.js
From my work on ES6 modules, I have implemented the `onVisible` and `onHidden` callbacks for the `Dimmer` module.
`onVisible` is triggereg when dimmer is fully shown, and `onHidden` when dimmer fully hidden.
> feat(dimmer): add onVisible and onHidden callbacks

- src/definitions/modules/calendar.js
Selecting a future month on a `startCalendar` didn't allow to use arrows on the `endCalendar`, since it was not refreshed before showing it.
See #1851
Broken:
Fixed:
#1851
> fix(calendar): arrow keys on endCalendar when startCal has future month

- CONTRIBUTING.md
- dist/components/dropdown.js
- dist/components/menu.css
- dist/components/progress.js
- dist/components/transition.js
- dist/components/visibility.js
- dist/semantic.css
- dist/semantic.js
- examples/assets/library/iframe-content.js
- examples/assets/library/iframe.js
- src/definitions/behaviors/api.js
- src/definitions/behaviors/visibility.js
- src/definitions/collections/menu.less
- src/definitions/modules/dropdown.js
- src/definitions/modules/progress.js
- src/definitions/modules/sticky.js
- src/definitions/modules/transition.js
- tasks/admin/components/init.js
- tasks/admin/distributions/init.js
Found via `codespell -q 3 -S *.min.js,CHANGELOG.md -L adn,ba,te,ue,varius`
> fix(docs): various typos

- src/definitions/modules/calendar.js
This PR allow some hours to be disabled trough a new parameter called `disabledHours`. It's adapted from @lubber-de's code to disable days.
Hours can be disabled using these patterns:
```js
disabledHours: [
0, // Midnight will always be disabled
{
// Every Saturday and Sunday will be entirely disabled (not this is just an example, not the way to do it...)
days: [0, 6],
hours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
message: 'We dont work on Saturday and Sunday',
inverted: true,
variation: 'basic'
},
{
// Friday afternoon will be disabled
date: new Date('2021-07-02'),
hours: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
message: 'Sorry this afternoon we are closed !',
inverted: true
},
{
// All hours between 1 and 7 will be disabled every …
```
> feat(calendar): disabledhours

- src/definitions/modules/toast.less
- src/themes/default/globals/variation.variables
This PR adds a new `centered` variant to the toast position to be able to display them in the middle of the screen
```javascript
$('body').toast({
message: 'I am so centered',
position: 'centered'
})
```
https://jsfiddle.net/lubber/x3w1gsht/13/
> feat(toast): new centered variant to display in the middle of the screen

- src/definitions/modules/popup.less
The Fix from #1801 was basically correct, however the specificity for transform-origin in later selectors override it, so the result was even worse
https://fomantic-ui.com/modules/popup.html#position
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/126305468-ef0bdfbf-fc86-4848-99ed-d39a8415e82a.png)|![image](https://user-images.githubusercontent.com/18379884/126305225-5e628f5c-3560-48bf-9a63-a961894db228.png)|
> fix(tooltip): fix arrow position for bottom center

- src/definitions/modules/rating.less
- src/themes/default/globals/variation.variables
The autoprefixer was not creating the vendor specific attributes for the rating module anymore, making partial ratings not visually work in chrome/webkit based browsers.
Try in Chrome
https://jsfiddle.net/lubber/2tayv1h0/12/
https://jsfiddle.net/lubber/2tayv1h0/10/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/126663620-1a11b27a-7d58-4dd7-9193-d1700404b123.png)|![image](https://user-images.githubusercontent.com/18379884/126663687-eff5c1ce-ecaa-4317-aa39-ec18ab589820.png)|
> fix(rating): partial rating needs webkit prefix

- examples/assets/library/iframe-content.js
- src/definitions/behaviors/api.js
- test/helpers/sinon.js
Found via `codespell -q 3 -S ./dist.*.min.js,CHANGELOG.md -L adn,ba,te,ue,varius
> fix(api): source typos

- src/definitions/behaviors/form.js
Whenever the enter key is pressed inside a form field, it triggers a form submit. However, this is also a browser default behavior, thus the event was called twice. Especially for IE11 this was causing the normal submit to not function anymore. 
I also made sure that native input fields of type "reset", "button" or "submit" are not fetched for input validation anymore (just in case someone would try). A native "reset" button would otherwise also submit the form (when enter is pressed on focussed button)
- Click into the name field and press enter
obsubmit is called twice
https://jsfiddle.net/lubber/r4egcLwp/4/
obsubmit is called once
https://jsfiddle.net/lubber/r4egcLwp/2/
https://github.com/Semantic-Org/Semantic-UI/issues/5824
> fix(form): avoid double submit on enterkey

- src/definitions/modules/dropdown.js
As proposed in https://github.com/fomantic/Fomantic-UI/discussions/1745#discussioncomment-120688 this PR changes the default value for `fullTextSearch` to `exact` as it already is for the search component.
As this is a breaking change it is supposed to be part of 2.9
> feat(dropdown): new default exact for fulltextsearch

- src/definitions/modules/dropdown.js
Whenever more than 1 dropdown is using remoteData, the sessionstorage is sharing the keys because of a missing namespace.
Now, if different dropdowns use the same ids, but different values then the second dropdown will return the wrong names from the first dropdown.
This PR adds the dropdowns id/namespace to the sessionstorage keys, so those are now unique to their respective dropdowns.
Dropdown 1 has the following elements (key, value)
1, monday
2, tuesday
3, wednesday
Dropdown 2 has the following elements (key, value)
1, january
2, february
3, march
The second dropdown will get the Weeknames out of the sessionstorage instead of the monthnames, because the keys are the same.
https://github.com/Semantic-Org/Semantic-UI/issues/5211
> fix(dropdown): add namespace to sessionstorage

- src/definitions/collections/form.less
- src/definitions/elements/input.less
This PR add visual support for the usage of native color, week or month inputs
- color inputs had wrong padding
- week and month inputs were not supported inside a form
https://jsfiddle.net/lubber/947q8xve/32/
All fine
https://jsfiddle.net/lubber/947q8xve/36/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/129473435-d52ab3a1-b72d-46e6-9268-c34099dd6f16.png)|![image](https://user-images.githubusercontent.com/18379884/129473421-86de3de2-b2b2-4650-9498-bb34a3999ee8.png)|
#881
#1099
https://github.com/Semantic-Org/Semantic-UI/pull/5890
> feat(form): support month, week and color input

- README.md
After github has acquired dependabot, the badge is not working anymore
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/129543329-43405c8c-863d-4c85-ba83-f6ccf8039373.png)|![image](https://user-images.githubusercontent.com/18379884/129543976-bdc808dc-0bd4-4941-93e3-3ac5da1d7539.png)|
> Update dependabot badge

- src/definitions/modules/checkbox.less
CSS Only checkboxes without Javascript which have linked labels (`<label for="id">`) to be (un) checked by clicking on its label did not have any pointer indicators and text was selected on dragging.
Hover on the Labels (HTML+CSS Only) 
- No pointer indicator
- Dragging selects text
https://jsfiddle.net/lubber/xhrjdu0p/8/
- Pointer is shown on hover
- Text doesn't get selected
https://jsfiddle.net/lubber/xhrjdu0p/10/
|Bad|Good|
|-|-|
|![csscheckboxlabel](https://user-images.githubusercontent.com/18379884/129558873-b412cca0-6772-43ff-99f4-b83214a3f98f.gif)|![csscheckboxlabel_fixed](https://user-images.githubusercontent.com/18379884/129558908-305269eb-cd03-4f98-8247-7c27e426f579.gif)|
> fix(checkbox): show pointer on css only linked labels

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
A dropdown menu in a non-selection dropdown did not have a rounded bottom border radius (this is only needed for the selection variant)
Tagged as breaking change, because i changed the variable name (it was used only once and is now dedicated to the selection variant)
Watch the bottom corners of the dropdown menu:
No bottom border radius
https://jsfiddle.net/lubber/wa2fo1pq/20/
border radius
https://jsfiddle.net/lubber/wa2fo1pq/22/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/129742930-cb0ffaed-0c1d-47ea-8a19-a26cf11c5107.png)|![image](https://user-images.githubusercontent.com/18379884/129742985-f671246a-6d38-4c83-b5a6-97f2d7ee6030.png)|
The `dropdown button` was also not correctly styled (not even the downward version)
|Before|After|
|-|-| …
> fix(dropdown): non selection and button upward variant border radius

- src/definitions/behaviors/form.js
Using `set values` for a checkbox field inside a form will only accept "true" or "1" to recognize the field as checked.
However, the standard value for a checked checkbox (when retrieved by "get values") is "on". 
This PR now accepts a possible "on" value for given checkbox fields to also check the checkbox to have the same bahavior.
In addition, any string value will now be set as value for the checkbox as well. (This is valid specification as of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#value), but any other string than "on" will not check the checkbox.
Watch the second checkbox at the bottom. It will be given "on" as value.
Not checked
https://jsfiddle.net/lubber/yhzqf9be/11/
Checked
https://jsfiddle.net/lubber/yhzqf9be/12/ …
> feat(checkbox): detect on as checked and add checkbox string values

- src/definitions/collections/grid.less
A `stretched row` inside `doubling grid` was not stretched on tablet size.
Yes, i left the `!important` in because there are many grid selector combinations where it probably breaks other situations which would need much more investigation. As the !important was there before, i decided to leave it in for now.
https://jsfiddle.net/lubber/e97w2g5k/7/
Remove CSS and resize viewport to see issue (as shown below)
https://github.com/Semantic-Org/Semantic-UI/issues/5989
> feat(grid): stretched rows not broken on tablet size

- src/definitions/elements/segment.less
This PR corrects #19 
@hammy2899 already smelled it somehow [by his comment](https://github.com/fomantic/Fomantic-UI/pull/19#issuecomment-396199507) 😄 
[The related issue](https://github.com/Semantic-Org/Semantic-UI/issues/5408) was related to `tab attached segments`, but the fix was applied to all attached segments.
This now had impact in some other (non tab) situations.
Most recognizable when an attached segment is used inside a stretched grid row. (See screenshots below)
I also fixed the same situation for `top attached tab segments` (it was the same issue, but not mentioned/used)
https://jsfiddle.net/lubber/m1vne69p/25
https://jsfiddle.net/lubber/m1vne69p/26
Watch three areas
- the bottom margin of the attached segments in the upper area
- the bottom tabs when switching between the …
> feat(segment):larger margin only for tab attached segment

- src/definitions/collections/menu.less
- src/definitions/elements/segment.less
An `attached text menu` still had borders
http://jsfiddle.net/lubber/o1dzf6rs/10/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/130334796-1ea70e26-c4d5-4f39-9215-82c9fba83232.png)|![image](https://user-images.githubusercontent.com/18379884/130334811-147d530b-345f-437d-aa8f-155522887b97.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/5205
> fix(menu): attached text menu had borders

- src/definitions/collections/menu.less
- src/themes/default/globals/variation.variables
A `centered` variant. I also added the alias `center aligned` as we have both of this wordings already in other elements.
Especially useful for `pagination` menu
https://jsfiddle.net/lubber/r4egcLwp/16/
https://github.com/Semantic-Org/Semantic-UI/issues/2921
> feat(menu): centered variant

- src/definitions/collections/table.less
Links in (very) compact selectable tables got a wrong padding, and reverted the compact padding.
https://jsfiddle.net/lubber/ensmy25b/7/
The table is `compact`, but contains a link which was adding padding again.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/131183801-5dee803b-3992-422c-95fd-b91c6113da1c.png)|![image](https://user-images.githubusercontent.com/18379884/131183774-db5d3e79-157c-4425-a11e-51babedbf1d1.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/5293
> fix(table): links in compact selectable table cell get wrong padding

- src/definitions/collections/form.less
If one declares a selection dropdown as `compact`, this was overridden when such dropdown was used inside a form.
https://jsfiddle.net/lubber/weLpsajc/7/
Remove CSS to see the difference
Watch the left dropdown field. This is an explicite `compact` dropdown.
https://github.com/Semantic-Org/Semantic-UI/issues/5011
> fix(form): keep a compact dropdown compact

- src/definitions/collections/form.less
- src/definitions/elements/input.less
New native input types like "week", "date", "email", "url" etc. have a browser inbuild validation.
When those get invalid the pseudo selector `:invalid` is set. In general all input field types, which have the `required` attribute set and are empty, are considered invalid. 
This PR adds the error class styling to such input elements by default. If nothing has been entered in such fields, those are not considered invalid (as long as they do not also have the `required` attribute set).
I decided to only show the invalid error colors when there is either something entered invalid or no placeholder is given. This way one can decide to not show the error colors on empty fields (initial forms) by defining a placeholder (even a " " works , if somebody does not want a textual placeholder set). …
> feat(input): support invalid pseudoclass

- src/definitions/globals/site.less
- src/definitions/modules/dimmer.less
- src/definitions/modules/dropdown.less
- src/themes/default/globals/site.variables
Custom scrollbars are already implemented since a long time for non body elements.
However, only webit based browsers were targeted.
This PR now adds the same look and feel to firefox and IE as well (as far, as those browsers support it)
https://jsfiddle.net/lubber/h0n7bur6/3/
Remove CSS to see the behavior before.
|webkit before|firefox before|IE before|webkit AFTER|firefox AFTER|IE AFTER|
|-|-|-|-|-|-|
|![image](https://user-images.githubusercontent.com/18379884/132592891-b6eefc3d-9f0c-4363-b127-f18fd2738099.png)|![image](https://user-images.githubusercontent.com/18379884/132593214-98788bef-fb93-4a50-8d3f-4c89653d2cc0.png)|![image](https://user-images.githubusercontent.com/18379884/132593330-04ccb227-eb33-40f5-896e-e06135c27c3a.png)|![image](https://user-images.githubusercontent.com/1837 …
> feat(chore): same custom scrollbars in chrome, FF and IE

- src/definitions/modules/modal.js
When using modals via JS properties only having any approve/deny buttons declared as actions, those did not respect the `onApprove` or `onDeny` callbacks returning a possible false to prevent hiding the modal.
Try to click on either buttons. Both should _not_ hide the modal as the onApprove and onDeny callbacks return false.
https://jsfiddle.net/lubber/np2bdLew/14/
https://jsfiddle.net/lubber/np2bdLew/15/
#2105
> fix(modal): respect approve deny callback on js modals

- src/definitions/modules/dimmer.less
- src/themes/default/modules/dimmer.variables
The `blurring` dimmer is inperformant because every single node inside the dimmable context is blurred separately which takes lots of time. 
It also causes positioning glitches when applied (Try the blurring example at https://fomantic-ui.com/modules/modal.html#dimmer-variations and see the sidebar suddenly vanishes!) 
Additionally when used in modals it is not nicely animated when the modal hides.
This PR switches from the old filter approach on each single node to the modern backdrop-filer approach on the dimmer itself only which is much more performant and nicely animates now.
For each browser not supporting this technique, the old behavior will still apply as before.
Remove CSS to see the difference
https://jsfiddle.net/lubber/egzbcoL2/35/
|Before|After|
|-|-| …
> feat(dimmer): use modern blurring to improve performance

- src/definitions/elements/icon.less
I have a dropdown with two items
The first item has a simple icon
`<i class="blue file excel outline icon"></i>`
The second one has two grouped icons
```html
<i class="icons">
<i class="red file excel outline icon"></i>
<i class="red bottom right corner key icon"></i>
</i>
```
Because the `.icon` has a width and the `.icons` does not visually they look off. The grouped icons has a smaller width then the simple icon
This PR adds a min-width to the `.icons` to make sure that the .icons group will be at least the same size of the `.icon`
I didn't want to use `width` because in some cases maybe the grouped icons need more space.
For the same reason i added a min-width i added also a min-height.
the height is not the cause of my problem, but i think it's best to add it as well. …
> fix(icon): adjust icons width to match single icon 

- src/definitions/modules/toast.js
Just as in #2108 , if an action button has a approve/deny class, a possible returned false in the `onApprove` and/or `onDeny` callback did not prevent to hide the toast.
The bug and therefore the fix is exactly the same for toast as it was for modal before.
Try to click on the action buttons on the opened toast.
They close the toast
https://jsfiddle.net/lubber/np2bdLew/16/
They do not close the toast
https://jsfiddle.net/lubber/np2bdLew/18/
> fix(toast): respect approve deny callbacks in actions

- src/definitions/modules/checkbox.js
This PR adds support to use the left/right keys on a `slider checkbox` or `toggle checkbox`  once focussed and initialted via JS.
- Focus a checkbox
- Press right to move the knot to the right
- Press left to move the knot to the left
https://jsfiddle.net/lubber/ne18mzk2/7/
#2102
> feat(checkbox): use left/right to switch off/on toggle+slider variant

- src/definitions/collections/form.less
- src/definitions/collections/grid.less
- src/definitions/collections/menu.less
- src/definitions/collections/message.less
- src/definitions/collections/table.less
- src/definitions/elements/button.less
- src/definitions/elements/header.less
- src/definitions/elements/icon.less
- src/definitions/elements/input.less
- src/definitions/elements/label.less
- src/definitions/elements/loader.less
- src/definitions/elements/segment.less
- src/definitions/elements/text.less
- src/definitions/modules/checkbox.less
- src/definitions/modules/dropdown.less
- src/definitions/modules/nag.less
- src/definitions/modules/progress.less
- src/definitions/modules/rating.less
- src/definitions/modules/slider.less
- src/definitions/modules/toast.less
- src/definitions/views/card.less
- src/definitions/views/statistic.less
- src/themes/default/globals/variation.variables
This PR allows to define a color list for each component individually out of the central `colors.less` file.
For example, now it is possible to have only red, blue and orange buttons, but only yellow labels and no colors for message at all. See example below.
All of this can be defined in the central `variation.variables` file as before (or in custom theme file)
Before this change you were only able to reduce the whole color list by modifying the colors.less file and change the available colors for all components at once.
> ### Tip for reviewers: 
> For an easier overview add `?w=1` to the review URL which will ignore all the whitespace changes. github also has an  option for this via the gear icon
```less
// Only red, blue and orange buttons
@variationMessageColors: red, blue, orange;
// …
```
> feat(chore): color list for each component separately

- src/definitions/modules/sidebar.less
The `pusher` element disables overflowing by default since https://github.com/Semantic-Org/Semantic-UI/issues/1655
In my tests that is only necessary in the mentioned particular testcase (a grid was used and the content is smaller than the sidebar)
However, there are still situations where that setting prevents other techniques inside the pusher like `native sticky` (where a parent node cannot have overflowing to be hidden to function properly)
This PR now allows to prevent the overflow:hidden setting if the pusher gets an additional `overflowing` class added.
This way previous codebases stay completely backward compatible by default.
- Scroll down, the Table header gets sticky
- Open the sidebar via provided button
- Close the Sidebar by clicking inside the dimmer
- Scroll the page again …
> fix(sidebar): make overflow hidden optional to support sticky

- src/definitions/modules/toast.js
- src/definitions/modules/toast.less
- src/themes/default/modules/toast.variables
Once again: Another year, another toast enhancement 🙂 
This PR
- adds accessibility support using aria labels to toasts just like we did for modals in #2036 
- adds a `ui image toast` variant to show images without any padding
- fixes missing html support in titles
- fixes wrong placement of vertical actions when the message was too short
- supports the `onClick` handler in any case now even if `closeOnClick` is set to false 
- onClick can now also return false to prevent closing the toast
- the close icon gets a dedicated event now independent of the onClick event
https://jsfiddle.net/lubber/xym8qg9j/37/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/135695861-ab15784f-41ea-43b0-9c0f-89f785fca86d.png)|![image](https://user-images.githubusercontent.com/18 …
> feat(toast): image variant, a11y support, title html, click support

- src/definitions/collections/form.less
- src/definitions/elements/input.less
- src/themes/default/elements/input.variables
- src/themes/default/globals/variation.variables
This PR styles the file input field so it has the same look as normal input fields by adding a `file` variant to the `input` element.
It also supports using action inputs for file inputs, if one needs additional features like icons.
If not using an action input i also added color variants to support colors for the native file input trigger button.
It also adds an `invisible file input`, in case one does not need the filepath being shown and only needs a button.
See examples in the jsfiddle
https://jsfiddle.net/lubber/xv0zLadf/3/
https://jsfiddle.net/lubber/xv0zLadf/12/
#105 
https://github.com/Semantic-Org/Semantic-UI/issues/403
> feat(input): file input variant

- src/definitions/collections/table.less
- src/definitions/elements/container.less
- src/definitions/elements/segment.less
- src/themes/default/collections/table.variables
- src/themes/default/elements/container.variables
- src/themes/default/elements/segment.variables
- src/themes/default/globals/variation.variables
This PR adds a `stuck` variant which supports to have the head, foot, first column and last column of a table being stuck while scrolling (using position `sticky`)
You can freely stick any combination like `head first stuck`, `foot first last stuck`, `head foot first stuck`, `first last stuck`, etc.
This feature needs to have the table being wrapped by a overflowing container having a fixed height (and/or optional width).
That said, i also added a new `scrolling container` and `scrolling segment` variant, which can be used for that purpose.
Because the other classnames already exists and provide different functionality
Because the other classnames (beside "footer") already exists and provide different functionality
Unfortunately the other approach cannot properly support having the first …
>  feat(table): all scroll stuck head foot first last variant

- src/definitions/collections/table.less
A sortable table header always got a left border, even when the table is not celled
https://jsfiddle.net/efncg5d0/
#2149
> fix(table): sortable border only when celled

- src/definitions/modules/tab.js
If I initialize the active tab with the name of second tab in the property `autoTabActivation` and set the property `historyType` to `state`, the active tab is not set to the right tab (the second).
If I set the property `historyType` to `hash`, that's work !
https://jsfiddle.net/dutrieux/p3oru58t/ 
https://jsfiddle.net/dutrieux/b4r8n7hg/
#2154
> fix(tab): initializing active tab with historytype 'state'

- src/definitions/modules/dropdown.js
onChange event is fire when the menu of dropdown is open when allowReselection=true and with remote content
This problem is only when dropdown use remote content and is not multiple.
1. select a item on the **first** dropdown
2. click on the **first** dropdown to display the menu, on show on console
https://jsfiddle.net/dutrieux/p5k83jL6/
https://jsfiddle.net/dutrieux/hfLby8d9/
2.8.8
#2161
> fix(dropdown): onChange is fired on menu openeing when reselection=true

- src/definitions/modules/tab.js
This PR adds a new callback "onBeforeChange"  before changing a tab, so you can cancel the tab change if needed.
The second tab cannot be clicked/changed anymore
https://jsfiddle.net/lubber/f5knryej/7/
#796
> feat(tab): callback to support tab change cancel

- src/definitions/elements/segment.less
A `basic attached segment` should not have borders.
https://jsfiddle.net/lubber/ywo3fbnz/6/
#330
> fix(segment): ignore attached border when basic

- src/definitions/modules/dropdown.js
When pasting a string inside a `search selection dropdown` existing comma values (the default delimiter) is ignored. Even worse, when pressing enter afterwards the whole pasted string, containing delimiter values is used as a value itself.
This MR now supports the paste event and splits the pasted string into separate values and adds them when either `allowAdditions:true` or if the value exists in the dropdown menu.
Therefore the delimiter key is now also supported on multiple dropdowns which do not allow additions for consistency
https://jsfiddle.net/lubber/jc3xtshd 
#2166 
https://github.com/Semantic-Org/Semantic-UI/issues/5897
https://github.com/Semantic-Org/Semantic-UI/issues/3521
> fix(dropdown): split delimiter values on paste

- src/definitions/modules/progress.js
Whenever a progress was (re)set to 0 any previously existing class states were not removed. This led into the success callback  not being called again when it was already triggered once
1. click on reset button
2. click on 100% button 
3. check the console, the onSuccess event is triggered
4. click on reset button
5. click on 100% button
6. check the console, the onSuccess event is **not** triggered
https://jsfiddle.net/dutrieux/v85om3t1/
6. check the console, the onSuccess event is triggered again
https://jsfiddle.net/lubber/aqb5zjuo/
#2177
> feat(progress): onsuccess was not triggered on reset

- src/definitions/behaviors/api.js
The apis `formData` collections always extended an already existing data value. If this however already contained properties of the same names as the formfields those were extended as well.
This led into situations where you want to reuse the same api several times. Especially for multiple name form fields like dropdown those always kept the previous values when submitted multiple times
- Open console
- Select three languages (English + French + Dutch)
- submit
- console show all three selected languages
- remove one (for example French)
- submit again.
console again shows all three languages 
https://jsfiddle.net/lubber/05msby9h
console only shows the two languages
https://jsfiddle.net/lubber/05msby9h/5/
#2174
> fix(api): reset existing formdata for proper renewing

- src/definitions/elements/input.less
- src/definitions/modules/dropdown.less
- src/themes/default/elements/input.variables
This PR fixes support for `icon input` and `corner labeled input` when used with a `dropdown`
https://jsfiddle.net/lubber/szgydxh9/6/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/146658217-b584bf5c-9c86-4617-9c68-1f8c0afa93c5.png)|![image](https://user-images.githubusercontent.com/18379884/146658226-44e0f714-a8ac-4df6-b4ab-9df0aa91c0b2.png)|
#2171 
#2172
> fix(input): support icon and corner labeled dropdown variant

- src/themes/default/modules/checkbox.variables
The toggle Checkbox LESS code accidently uses the slider variables for transition duration (obviously copy paste issue). 
For consistency, and this obvioulsy was the origin intention, a dedicated, already existing but never used, variable should be used.
For backward compatibility i changed the value to the same as for the slider variant, so the resulting css remains the same.
Thanks to @ghedsouza for [the original PR ](https://github.com/Semantic-Org/Semantic-UI-LESS/pull/23)
> fix(checkbox): wrong variable usage

- src/definitions/elements/segment.less
Horizontal segments should use their respective group variables (those however still contain the same values as for the single segment variabels used before)
https://github.com/Semantic-Org/Semantic-UI-LESS/issues/49
> fix(segment): horizontal should use group variables

- src/themes/bookish/elements/header.overrides
- src/themes/chubby/elements/button.overrides
- src/themes/chubby/elements/header.overrides
- src/themes/instagram/views/card.overrides
- src/themes/material/collections/menu.overrides
- src/themes/material/elements/button.overrides
- src/themes/material/elements/header.overrides
- src/themes/material/modules/dropdown.overrides
- src/themes/material/modules/modal.overrides
- src/themes/rtl/globals/site.overrides
When using webpack 4+ and LESS 3/4 the font imports have to be interpreted as raw CSS, otherwise the build breaks.
This is already fixed for the default theme since 3 years, but any of the included optional themes will fail.
I also updated the google font api usage to v2
> fix(themes): less3/4 needs font import interpreted as raw css

- src/definitions/behaviors/api.js
Revert and proper fix of #2175 
I forgot to check for an empty dropdown value. Jquery unfortunately does not return the field at all on `serializeArray` when multiple named fields (which should return an array) are empty.
- Select something then submit
- The selected values will be logged
- Remove all selected entries and submit
The previous selected values are logged again
https://jsfiddle.net/lubber/05msby9h/5/
No value is logged as the field is empty
https://jsfiddle.net/lubber/05msby9h/6/
#2174
> fix(api): empty dropdown data was overriden by previous data

- src/definitions/modules/toast.less
A possible theme overrides file was not used for the toast component.
#2190
> fix(toast): possible theme overrides were missing

- src/definitions/modules/modal.js
The default modals config templates (alert/confirm/prompt) button handler does not work anymore since #2108 because the default selectors require the `onapprove` and `ondeny` selectors.
This PR now supports both: appvove/deny selectors as well as custom selectors (e.g. by globally overriding them via `$.fn.modal.settings.className.ok = 'purple';`
Try all three buttons. Whatever you click to close the modal, a toast message should be shown
No toasts, because the handler is ignored
https://jsfiddle.net/lubber/jpcdh06r/10/
All fine as expected
https://jsfiddle.net/lubber/jpcdh06r/11/
> fix(modal): default templates handler was not working

- src/definitions/modules/modal.js
- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
when you have two modals on top of each other, if the height of both of them are the same and close buttons are out of the modal, the close buttons are on each other which has a bad user experience.
In addition the close icon from the first modal was still clickable and would close the first modal.
In some cases the close icon could be shown over a different inner Dimmer making the close icon invisible, so i added a slight text shadow to keep it visible. This text shadow is not recognizable on usual modal usage .
At last i made the dimmer class of the inner dimmer optional, so one could customize that as well.
- Have a wide vieport (> tablet), so the close icon of a modal will apear outside the modal to the upper right
- Open modal via button 
- open another modal via the second button …
> fix(modal): outside close button handling

- src/definitions/modules/accordion.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/accordion.overrides
- src/themes/default/modules/accordion.variables
This MR enhances the accordion module:
- Pure CSS variant now possible using the[ details/summary tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) (yes, IE/old Edge do not support that, that's ok for 2.9.0 and 2022 and you can still use the JS version which works there) 😉 . 
- `inverted` styled variant
- `tree` variant (for proper indentation which a tree view needs) (also works as CSS only!)
- new `right dropdown icon` variant, to be able to place the dropdown icon to the right (just as in accordion menu already). Usefull for example when used inside `message`
- fixed the right dropdown icon (also in accordion menu)
- fixed possible usage of `title` or `content` elements inside an accordion which are supposed to be parts of different elements
- `basic styled` …
> feat(accordion): pure css, inverted, basic, right, tree, nested fixes

- src/definitions/modules/toast.js
Some content inside toasts should remain clickable without closing the toast. (even if `closeOnClick` is true)
While this was already hardcoded for `a` tags if fails for possible other tags like `accordion` or `details` (Especially when used together with the new #2197 😉 )
The previously hardcoded selector is not a customizable classname setting.
Btw: `input` is not needed to be set here, because any kind of input inside a toast will already set the whole toast to not closing when clicked (because it is expected to be clicked into the input fields).
The new setting here is supposed for elements which _can_ be clicked, but are not expected to.
https://jsfiddle.net/lubber/fd8Lx9u2/24/
> This also shows how to nicely use the new `ui basic inverted styled accordion` inside the toast
> feat(toast): allow clickable items without closing

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
I would like to automate the npm publishing of new releases, so this PR adds another github workflow which publishes to npm ONLY when a new github release is published.
@hammy2899 
I would like to setup this release workflow for the Fomantic-UI-CSS and Fomantic-UI-LESS repos as well, so could you please upload a/the NPM secret to the fomantic-organization as well (and/or to the respective single repositories)
Otherwise i always have to bother you to create the releases manually yourself 😉 
I intentionally did not implement a version-adjustment inside package.json within the workflow script to avoid publishing wrong releases in case one of us does something wrong while adding tags . So unless we manually change the version number inside package json a possible npm publish will fail …
> feat(chore): automatic npm releases, ci fix and add node 16

- src/definitions/elements/header.less
An `.image.icon` (used by a `<img>`) inside a `.ui.icon.header` was not working anymore (misaligned), which was used on the homepage a lot.
https://jsfiddle.net/lubber/o0gtx196/22/
https://fomantic-ui.com
#2208
> fix(header): image icon support again

- package-lock.json
- package.json
- tasks/config/project/install.js
This PR adds a Grouping Header to the component selection at install time.
It's more a hack by using disabled entries, but works out good enough 😄 
I, for now, decided against renaming the form.js to formvalidation.js because i fear a too big breaking change and most probably people who want form elements also want the validation anyway.
I could have just changed the checkbox selection name to "formvalidation" but effectively the script would have continued with "form" anyway which probably creates more confusion.
- run `npx gulp install`
- select "Yes, extend my settings"
- select "express" or "custom"
- see the checkbox components list are now grouped by unselectable "headers"
#2180
> feat(build): group components in checkbox selection

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/calendar.variables
Several small fixes:
- Multimonth calendar offset was only possible by providing it via data attributes `data-month-offset`. This is now also possible by using the `monthOffset` value as well.
- This PR also fixes date parsing in case whitespace is part of the date.
- By disabling the observer in the popupoptions by default the calendar works properly when used inside modals
- multimonth calendars now appear in the same way inside popup as a single calendar
https://jsfiddle.net/lubber/mo97gk6y/12/
https://jsfiddle.net/lubber/mo97gk6y/13/
#2200 
https://github.com/mdehoog/Semantic-UI-Calendar/issues/99
> feat(calendar): multimonth, parser & modal usage fix

- src/definitions/elements/button.less
- src/themes/default/elements/button.variables
- src/themes/default/globals/variation.variables
This PR adds new button group variants `wrapping` and `spaced`
There also exists another optional `wrapped` helper class which should be set when it's known if a button group is actually wrapped (this will adjust some border-radius values). It is not possible to detect a wrapping child automatically via pure CSS, that's why the developer should handle this using that helper class whenever needed.
The PR also fixes some adjustments when used together with `basic` and/or `inverted` and improved conditional compilation at some places
https://jsfiddle.net/lubber/akb4wh2n/
#2157 
https://github.com/Semantic-Org/Semantic-UI/issues/7069
> [Button]] wrapping and spaced variant for button Groups

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
The `simple dropdown` css only variant was broken when trying to use it with a `upward` menu
- menu was cut on smaller screens
- dropdown itself was overlayed by menu
- simple selection variant had wrong borders
https://jsfiddle.net/lubber/cz09kaue/1/
https://jsfiddle.net/lubber/cz09kaue/3/
https://github.com/Semantic-Org/Semantic-UI/issues/6288
> fix(dropdown): fix simple upward variant

- README.md
Starting from v2.9.0 i would like to reduce IE11/old Edge and old mobile platform support.
Fomantic will still work in those browsers in general, but in case there are dedicated bugs, we will not spent time into trying to fix them for those ancient browsers/platforms anymore. 
As i used markdown footnotes for detailed explanation such footnotes are found at the end of the readme as follows:
* Last 2 Versions Firefox, Chrome, Safari Mac, Edge
* Last 4 Versions of Android, Chrome for Android, iOS Safari[^1]
* IE 11[^2]
* Microsoft Edge 12-44[^2]
[^1]: Fomantic-UI should basically still work in iOS Safari 7+, Android 4.4+, but, starting from v2.9.0, we won't support them anymore if anything works different than in recent versions.
[^2]: Fomantic-UI should basically still work in IE11 / old …
> feat(docs): limit/clarify IE, old edge, old mobile support

- src/definitions/behaviors/api.js
It seems a more common case people are sending JSON array instead of JSON objects for their api response.
We already supported that since 2.7.0 #294 by the `rawResponse` setting, but people have to actively enable it.
This PR changes the default value so json arrays are not converted to objects anymore by default.
I am still against always forcing json arrays no to be converted, because it is a valid conversion by `$.extend` and probably still needed for some projects.
#2220
> feat(api): dont convert array response to object by default

- examples/assets/library/iframe-content.js
- examples/assets/library/iframe.js
- src/definitions/behaviors/api.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/modal.js
- src/definitions/modules/popup.js
- src/definitions/modules/sidebar.js
- src/definitions/modules/toast.js
- test/helpers/sinon.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with the [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) method which works similarily but isn't deprecated.
.substr() probably isn't going away any time soon but as the change is trivial it probably doesn't hurt to switch.
> fix(chore): replace deprecated .substr() with .slice()

- src/definitions/modules/dropdown.js
On a multiple dropdown, having `allowAdditions:true`, the press of the delimiter key (comma by default) was checked via the keycode. However the keycode does not take possible pressed shift/alt keys into account.
This results in triggering a multi dropdown entry even when pressing the key together with shift/alt, so it was not possible to declare for example the semicolon as a delimiter.
As we already have the delimiter string for concatenation/splitting of existing values, this PR now also uses that setting for the keypress.
https://jsfiddle.net/lubber/27whu5tf/9/
https://jsfiddle.net/lubber/27whu5tf/11/
#2245 
https://github.com/Semantic-Org/Semantic-UI/issues/3016
https://github.com/Semantic-Org/Semantic-UI/issues/3318
> fix(dropdown): use central delimiter char instead of key

- src/definitions/modules/calendar.less
The grid adjustment for multimonth calendars needed a higher specificity , so the calendarss fit the to popup edges.
https://jsfiddle.net/lubber/mo97gk6y/19/
> fix(calendar): adjust margin specificity for multimonth

- src/definitions/collections/form.less
- src/definitions/elements/input.less
- src/themes/default/collections/form.variables
Date or other new input types used in chrome based browsers are showing an additional icon to trigger the value seletcion.
Unfortunately the icons had an additional padding making the inputs appear larger than normal inputs which interferes with the overall ui when such inputs were shown next to each other.
I also adjusted the appearance of the icon to match the `icon input` appearance and added the pointer to the icon as such native icon has a bahaviour to show a dialog.
The Email-Input to the very right has a smaller height than the others
Same height everywhere
https://jsfiddle.net/lubber/1umaonxg/1/
> fix(input): date inputs were larger due to icon size

- src/definitions/elements/segment.less
Inverted attached segments got wrong border color (from non inverted variant). A slight specificity increase solves this.
http://jsfiddle.net/lubber/bxtmyv9z/46/
> fix(segment): adjust inverted attached border color specificity

- src/definitions/modules/dropdown.js
The search width sizer was cut in legacy Edge.
Use Legacy Edge <= 18 
https://jsfiddle.net/lubber/18mdtc4y/10/
https://jsfiddle.net/lubber/18mdtc4y/11/
Look at the "f" inside the dropdown search at the bottom right of the screenshot
#312
> fix(dropdown): legacyEdge cuts search input

- src/themes/material/globals/site.variables
Material theme changed the `@fontpath` in site variables. If one now wants to use the icons from the default theme this is not working anymore and all icons are broken
checkout/clone fui
1. Edit `src/theme.config` and change `@site` to `material` (keep `@icon` to `default`!)
2. Run `npx gulp build`
3. Put `dist` folder somewhere to test icons (i used the local docs to test the icon site)
#2261
> fix(theme): material theme changed fontpath in site variables

- src/definitions/behaviors/form.js
Whenever a form field is dynamically added to the form and added/removed via `add field` or `remove field` to add/remove related rules, the event listeners to such new fields wre not renewed resulting in not correctly validating the  new field at runtime.
- Click "add val2 field" to add a field dynamically to the already existing form
- Use submit button to make the form invalid.
- Type anything into each field to see the different
- The first field (which was already there) gets validated (error class is removed) whenever you type anything into the field
- The second field stays invalid (error class) while typing and only gets valid on blur
https://jsfiddle.net/lubber/0wyz2g7e/15/
- Both fields get validated while typing
https://jsfiddle.net/lubber/0wyz2g7e/18/
#2035
> fix(form): rebind events on dynamic fields

- package.json
This PR removes the interactive auto install which was called automatically after `npm install`.
Whenever Fomantic UI is installed via `npm install fomantic-ui` the `dist` folder is already available, so there is no need to compile it at install time.
The main reason to remove it is that especially yarn and recent versions of npm do not work with inquirer interactive scripts as post install and throw an error.
Manually calling `npx/yarn gulp install` or `npx/yarn gulp build` right after `npm install` however, works fine
a `--ignore-scripts` shouldn't be needed anymore then
#811 
#1859 
#1911
> fix(install): dont start interactive script on npm install

- .github/workflows/nightly.yml
- scripts/nightly-version.js
I've made changes to the nightly script to include the latest commit sha in the build metadata of the version so we can compare them. This allows us to only push the latest nightly to npm if there is now commits to push. I have also made changes to the workflow so it only continues and does the publish if the version was updated.
> build(scripts): reduce nightly publishing

- src/definitions/modules/calendar.js
This PR corrects the whitespace removement bug from #2200, because the previous fix was not respecting a possible space character between date and time, which was still needed and not working anymore.
I was initially trying to fix it in a single regex but it got too complicated so i went for the easier, reliable and readable solution instead using 2 regexes.
The provided date is wrong
https://jsfiddle.net/pL8he1ta/
Date is correct
https://jsfiddle.net/lubber/23y5mc0h/
#2274 
#2200
> fix(calendar): keep whitespace between date and time

- scripts/nightly-version.js
The nightly script is not able to provide the version name + commit hash as version number to npm, as npm always removes the hash from the version number. Thus the nightly is still always created because it can not compare the commit hashes.
This is now fixed, because the script takes the hash information out of the versions details from the npm registry.
npm still does not show the hash in the tags list, but at least the nightly can compare the commit hashes so it only creates a new version now when anything really has changed as @hammy2899 intended 
[#2273 ](https://github.com/fomantic/Fomantic-UI/pull/2273#issuecomment-1076019628)
> fix(nightly): get commit hash from npm

- src/definitions/modules/dropdown.less
It's just a 1 character change so I'll keep it short:
There's an ugly and probably unwanted shadow and radius on the inner floating dropdown `.menu` which this fix removes.
https://jsfiddle.net/0cpwnfkz/
> fix(dropdown): floating shadow and radius on direct child menu only

- .github/workflows/nightly.yml
- scripts/nightly-version.js
Fix the nightly script due to yarn publish not adding gitHead to the
registry. Also moved back to npm publish so we can keep functionality of
not publishing when there is no changes.
> build(scripts): fix nightly script

- .github/workflows/nightly.yml
Add `--tag nightly` to the publish command like it used to be...
> build(actions): add --tag to publish command

- src/definitions/modules/accordion.js
- src/definitions/modules/accordion.less
- src/themes/default/modules/accordion.overrides
Whenever an accordion title has got a dropdown inside, the activation of that dropdown also triggered toggling the accordion.
Also the dropdown icon inside the dropdown was animated just ike the accordion dropdown icon.
This PR fixes the css selectors and adds a new selector setting `ignore` to be able to defined a css selector which should not trigger the accordions toggle when inside a title node.
Click inside the dropdown
- The dropdown also toggles the accordion
- The dropdown icon of the dropdown element is rotated by 90 degress...
https://jsfiddle.net/lubber/sejrkaod/1/
- The dropdown handling stays for itself and does not interfere with the accordion toggle
- The dropdown icon (inside dropdown element) stays untouched and looks normal
https://jsfiddle.net/lubber/sejrkaod/13/
> fix(accordion): prevent ui dropdown icons in titles to animate

- src/definitions/modules/popup.less
- src/themes/default/modules/popup.variables
A CSS only tooltip only contains text as it uses the `::after` pseudo element to display the text via the content attribute.
However content cannot contain HTML, thus an additional selector after a ::after pseudo element can never happen and is infact invalid.
This situation not only never happens but also makes some parsers like Parcel complaining about invalid CSS.
Thus, i simply removed the whole selector.
#2315
> fix(popup): tooltips cannot contain headers

- src/definitions/elements/button.less
Whenever a `loading button` contains any kind of label it was still shown
- Select anything from the dropdown (it will get the loading state then)
- Remove CSS to see issue
https://jsfiddle.net/lubber/mrza0234/9/
#2288
> fix(button): loading buttons still shows labels

- src/definitions/modules/dropdown.js
The `preventChangeTrigger` option for some behaviors was not optimal and not even working.
Using a behavior needed to also provide some only internally used parameters like `$selectedText` which is confusing also in the docs.
Such functions are now also supporting to be called as behaviors having the second argument used as the `precentChangeTrigger` argument (which usually is only the third or fourth option)
Click on the Button to add 2 values without selecting something from the dropdown
The values are selected but the onChange trigger is still fired and you still need to call it with that null (to skip) parameter by
`.dropdown('set selected',['de','us'],null,true)`
https://jsfiddle.net/lubber/3w8jr560/9/
The values are selected and the onChange trigger is not fired and the behavior can …
> fix(dropdown): properly support preventchangetrigger

- src/definitions/modules/calendar.js
This PR adds support to use token strings as a date formatter.  It's still possible to provide functions as before.
The base idea is adopted from https://blog.stevenlevithan.com/archives/javascript-date-format
Now you can use something like
```javascript
formatter: {
date: '"Intergalactic Date:" D.M.YYYY' 
}
```
Usable Tokens (i compared popular big date libs like momentjs, date-fns, luxon and dayjs to make sure to basically match the same syntax)
|Description|Token|Resultset|
|-|-|-|
|Day of Week|d|0-6|
|Day of Week (2 char text)|dd|Su - Sa|
|Day of Week (3 char text)|ddd|Sun - Sat|
|Day of Week (Full text)|dddd|Sunday - Saturday|
|Day of Month |D|1 to 31|
|Day of Month (Leading zero)|DD|01-31|
|Day suffix|S|st,nd,rd,th|
|Month |M|1 to 12|
|Month (Leading zero)|MM|01-12|
|Month (3 char …
> feat(calendar): support token dateformats

- src/definitions/modules/slider.js
As proposed in #1988, I did a rework of the touch event handling of the slider component. The new touch event code
- does not prevent mouse input (fixes #1988)
- tracks Touch identifier to avoid confusion by other fingers on the touch screen
- handles touchcancel events in a sensible way
- does no dynamic binding and unbinding to all touch events on the page. In combination with the second point, this enables multitouch sliding of multiple sliders on the same page (I know, nobody asked for this, but it works. ;) ) – Unfortunately, multitouch sliding of the first and second thumb of the same slider is not easy to implement due global state within each slider module.
- only binds to touchstart events on the `.thumb` element to avoid accidential sliding while scrolling the page on a mobile …
> fix(slider): support mouse & touch all the time

- package.json
Upgrade node dependency to 12, which is the least supported version by now (yes, runs out of service by end of April, but i believe v12 is still widely spread and other dependencies are ugrading as well
> feat(build): require node 12 as minimum

- src/themes/default/elements/emoji.variables
- src/themes/default/elements/flag.variables
Emojis and flags were larger than the inheriting line-height, resulting in larger dropdowns when they contain such emojis/flags
This PR makes them in line with surrounding text.
I tag this as breaking change, because existing projects using emojis will get slightly smaller emojis unless they provide a size class.
Remove CSS to see issue (left dropdown is higher then right)
https://jsfiddle.net/lubber/ub7sgh96/12/
|Before|After
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/164993262-fc60dfff-ba84-4260-a2e6-51b935cadeec.png)|![image](https://user-images.githubusercontent.com/18379884/164993237-f7cd4514-c5f4-4a92-b14e-0608124744d5.png)|
#2333
> fix(emoji,flag): default lineheight should meet text

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/definitions/modules/dropdown.js
Whenever a dropdown was initialized via a select tag and also had initial values via the `values` setting, any preselected item was ignored.
The first select does not show any value, although 2 items are preselected
http://jsfiddle.net/cf4a7yoL/5/
All fine
http://jsfiddle.net/lubber/yv4f0ces/
#2342
> fix(dropdown): support preselected on value update for select tag

- src/definitions/behaviors/api.js
Fixes inefficient RegExp which could cause Regular expression Denial of Service attack
The problematic part `(?:\[(?:\d*|[a-z0-9_-]+)\])*` will matches
* (empty)
* `[]`
*  `[0123]`
*  `[abcd]`
*  `[0a_1b_c2]`
* `[][]`
*  `[0123][]`
*  `[abcd][0a_1b_c2]`
All these pattern is covered with the fixed regexp, I think.
. | Before | After
---|---|---
[ReDoS check](https://makenowjust-labs.github.io/recheck/playground/) | <img width="813" alt="image" src="https://user-images.githubusercontent.com/127635/166092555-00489c22-8cfc-4bc4-8795-21bf35944701.png"> | <img width="734" alt="image" src="https://user-images.githubusercontent.com/127635/166092549-034fd171-8d5d-46ac-b640-2a8b12ad9632.png">
[Railroad diagram (Only the problematic part)](https://regexper.com/) | [<img width="276" alt="image" …
> fix(api): fix inefficient RegExp that may cause ReDoS

- src/definitions/modules/dropdown.less
The specificity level for width setting for form input and dropdown menu input was identical. 
Thus, when dropdown.css was loaded before form.css and a search dropdown was used inside a form, the input was overflowing the dropdown menu.
by increasing the specificity this situation is fixed.
The second dropdown has an overflowing input field
https://jsfiddle.net/lubber/mcw01fob/4/
Second dropdown looks good 
https://jsfiddle.net/lubber/mcw01fob/5/
#2368
> fix(dropdown): input width specifitiy was same as form input

- src/definitions/collections/form.less
- src/definitions/collections/menu.less
- src/definitions/collections/table.less
- src/definitions/elements/input.less
- src/definitions/elements/segment.less
- src/definitions/globals/site.less
- src/definitions/modules/dimmer.less
- src/definitions/modules/dropdown.less
- src/definitions/modules/sticky.less
- src/definitions/views/card.less
This PR makes all IE specific LESS code optional. By default the new variable `@supportIE` (introduced by #2359 ) is true, so the code compiles as before
Early Edge Legacy versions still use the IE11 engine / -ms prefix syntax, so setting `supportIE: false;` will also disable support for those browsers.
> feat(chore): optional compile for ie specific code

- src/definitions/modules/dropdown.js
- src/definitions/modules/search.js
Whenever a dropdown had `apiSettings` set which also contained any callback for `onSuccess` or `onFailure` or `onError`, the menu was not shown anymore.
The search component had the same issue, so i also fixed it there.
- Open developer tools to watch console
- Click into the dropdown
- menu is not shown
- console output shows the onsuccess message
https://jsfiddle.net/34z06c2e/
- menu is shown as expected
- console output also shows the onsuccess message 
https://jsfiddle.net/lubber/3kj1b0wL/1/
#2401
> fix(dropdown): support callbacks given inside apisettings

- src/definitions/modules/modal.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/modal.variables
- Added a `basic` variant for header and actions of a modal which removes the separate background and border separator
- Added `left` variant for actions which displays the action buttons to the left (we already have this for toast) 
i also added some more options for variation switches to possibly reduce more css output if people dont need the actions or left/centered variants
https://jsfiddle.net/lubber/7w9uabd3/7/
#2395
> feat(modal): basic header and basic left actions

- src/definitions/modules/dropdown.js
When using a search dropdown from a mobile, it doesn't correctly open when you click on it.
The flow is stuck at a point :
```
// dropdown.js - line 1150
// When we click on the search dropdown, a touchscreen event is triggered, and
// it is attached to the search.focus function when the selector is a .input.search
search: {
focus: function(event) {
activated = true;
if(module.is.multiple()) {
module.remove.activeLabel();
}
if(!focused && !module.is.active() && (settings.showOnFocus || (event.type !== 'focus' && event.type !== 'focusin'))) {
focused = true;
module.search();
}
}
...
```
If the condition is met, `focused` becomes true, and we call `module.search()`.
After a few methods calls, we end up in the `filter` method : 
```
// dropdown.js - line 767
... …
```
> [Dropdown] Fix focus flow when a search dropdown is used from a mobile

- src/definitions/collections/form.less
form labels in inverted forms were not shown white but still black
#2421
> fix(form): inverted form labels were black

- src/definitions/modules/dropdown.js
in case of using the &lt;label&gt; element before a search dropdown to improove accessibility
- id of module is used to add an unique id to this very label 
- a reference to this label is made via the attribut "labelledby"
- see https://www.w3.org/WAI/tutorials/forms/labels/
https://jsfiddle.net/inselhopper/ot5zqvb2/38/
> feat(dropdown): improve accessibility in relation to search dropdown

- src/definitions/modules/popup.js
popup and calendar did not work anymore since the codeql fixes unnecessarily added a check for the popup settings being a string.
However on instantiating a popup a possible given string setting turns into an object, so whenever the popup is tried to be shown a script error and no popup occurs. Found this while trying calendar module...
#2375
> fix(popup): broken and unnecessary check for string

- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/modal.js
- src/definitions/modules/search.js
Allow using escape to dismiss calendars, dropdown, checkbox or search popups.
Previously, the escape key events (keydown, keyup) bubbled through the whole component tree.
This closed the modal when the escape key was used to dismiss a popup.
Fixing the issue requires all components to use the same event (keydown or keyup).
Standardize on keydown. This way propagation can be stopped prior to the modal closing.
This approach allows different components to "eat" the keystroke, while leaving the event
bubble up when required.
https://www.mutuallyhuman.com/blog/keydown-is-the-only-keyboard-event-we-need/
https://jsfiddle.net/lubber/hvbq6ke0/1/
- #2428
> fix(modal): avoid propagation of escape to modal

- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
calendar and checkbox had different default value for debug settings than every other module which this PR now makes unique (same for docs, which i prepare a separate PR)
> fix(chore): identical debug defaults for all modules

- src/definitions/modules/search.js
Hitting the escape key is supposed to blur the search field, but this never happens. It only hides a possible given result set.
This PR now implements it the way it is meant to be and blurs the field when there is NO resultset being displayed (otherwise it still hides it as before)
I also fixed the `set.type` function properly. A possible given "type" parameter made no sense, was not used and it only worked with the default category. So now somebody really can create custom templates and a given classname is added to the search component , not only category. 
- Click into the search field
- Hit Escape
or
- Click into the search field
- type "f" so something is displayed in the resultset
- Hit escape (it should hide the resultset)
- Hit escape again
Nothing happens …
> fix(search): blur on escape and proper type usage

- src/definitions/modules/accordion.js
- src/definitions/modules/dimmer.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/modal.js
- src/definitions/modules/popup.js
- src/definitions/modules/search.js
- src/definitions/modules/toast.js
Some modules use the transition module internall to do animations. But some missed to provide all debug settings from the parent module.
Especially the `silent` setting was not forwarded.
So whenever someone tried this
```javascript
$(el).dropdown({
silent: true
});
```
This was ignored by the transition module (in case it logs errors), because the default setting of silent is false in all modules.
> fix(chore): forward debug settings to transition on internal use

- src/definitions/modules/popup.js
I added  more detailed check for rtl. Currently only the module is checked. However, if body or the surrounding context would be defined as rtl then the module itself is also displayed as rtl, so this PR enhances the check (i already did the same inside the [sidebar PR](#2436 ) and [modal PR](#2433 ))
> fix(popup): detailed rtl check

- src/definitions/modules/sidebar.js
- src/definitions/modules/sidebar.less
The `scrollLock` and `returnScroll` setting was not working which this PR fixes
It also adopts the same scrollbar vanish code from modal to avoid moving page content when the scrollbar vanishes
>  When this is merged, remember to also adjust the new flyout component, as this uses the same selectors for .pushable and needs to be equal
- open sidebar
- dimmed pusher area is still scrollable as scrollbar remains visible
https://jsfiddle.net/lubber/dpu8gy65/1/
- open sidebar
- scroll pusher content
- close sidebar
- scroll position does not change
https://jsfiddle.net/lubber/dpu8gy65/18/
- dimmed pusher area is not scrollable anymore and scrollbar is hidden just as in modal
https://jsfiddle.net/lubber/dpu8gy65/23/
- scrollbar returns to the position where it was when the sidebar was opened …
> fix(sidebar): scrolllock and returnscroll

- src/definitions/modules/search.js
The default easing of the search module was missing, thus resulting in a jquery/js console error when `transition` is set to false or the transition module is not loaded (only then the easing setting is used at all)
console throws lots of errors when typing into the search field
https://jsfiddle.net/lubber/ge715toh/8/
https://jsfiddle.net/lubber/ge715toh/7/
> fix(search): missing default easing results in js error

- src/definitions/modules/modal.js
- src/definitions/modules/toast.js
This PR adds jquery short notation support (`$.`) to toast and modal which are made dynamically out of js properties and thus are not bound to an existing dom node.
Previously you always had to select body (which still works) when no existing domnode template exists. Infact the body selector was completely ignored.
```javascript
$('body').toast({
message: 'hello'
});
$('body').modal({
autoShow: true,
title: 'hello'
});
```
```javascript
$.toast({
message: 'hello'
});
$.modal({
autoShow: true,
title: 'hello'
});
```
https://jsfiddle.net/lubber/7s9ouapq/2/
> feat(toast,modal): support short notation $.

- src/definitions/modules/dimmer.less
- src/definitions/modules/modal.js
- src/definitions/modules/modal.less
A possible use of modal inside a different context container than body was not properly implemented. 
- Fetch/Hide/Restore of scrollbar did not work
- Positioning of the modal inside a scrolling container also broke
- Accidently usage of window or document as context setting broke the code
What i also fixed
- many preset/cached variables were not reused, which slightly costs performance
- used the slightly quicker array Access instead of jquerys .get() method
- Removed unnecessary !important settings (those were infact needed in case the context container has scrolled when the modal is opened (when testing this, you should have to change `.ui.dimmer {top:0!important}` to `.ui.dimmer {top:0}` in the jsfiddle via console) 
Click the button to open a modal. It is supposed to be displayed and …
> fix(modal): support context properly

- src/definitions/modules/toast.less
Toast transitions were not smooth  on start and end of animation because the browser switches from 3d to 2d transform which makes the toast noticably change by some pixels.
by applying a `will-change` hint this is not happening anymore
Watch the toast edges and font. A bit hard to recognize by the gifs. Try the testcase and check yourself ;)
https://jsfiddle.net/lubber/tu9rqm5p/5/
> fix(toast): enable smooth transition

- src/definitions/modules/flyout.js
This PR is an adaptation from @lubber-de's #2442.
It adds jquery short notation support (`$.`) to flyout which is made dynamically out of js properties and thus are not bound to an existing dom node.
Previously you always had to select body (which still works) when no existing domnode template exists. Infact the body selector was completely ignored.
```javascript
$('body').flyout({
title: 'Important Notice',
content: 'You will be logged out in 5 Minutes',
actions: [{
text: 'Alright, got it',
class: 'green',
icon: 'save'
}]
});
```
```javascript
$.flyout({
title: 'Important Notice',
content: 'You will be logged out in 5 Minutes',
actions: [{
text: 'Alright, got it',
class: 'green',
icon: 'save'
}]
});
```
> feat(flyout): support short notation $.

- src/definitions/modules/flyout.js
- src/definitions/modules/flyout.less
- src/definitions/modules/modal.less
- src/definitions/modules/sidebar.js
- src/definitions/modules/sidebar.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/flyout.variables
- src/themes/default/modules/modal.variables
- src/themes/default/modules/sidebar.variables
- moved many values into LESS variables
- a11y: aria labels, tab focus trap, close icon focussable and activateable via space key
- `autofocus` setting,`restoreFocus` setting
- fetch esc key to close flyout by new via `keyBoardShortcuts` setting
- basic actions, basic header
- left actions
- center aligned header, content, actions
- `blurring` setting
- smooth fadeout of dimmer (was hard removing the dimmer without any transition on close)
- temp flyouts have to be put before pusher in dom to avoid auto pusher wrap when not necessary
- smooth fadeout of dimmer (was hard removing the dimmer without any transition on close)
- `blurring` setting
- basic action on inverted dimmer
#2457
> fix(sidebar,flyout,modal): missing identical features and fixes

- src/definitions/modules/dropdown.js
introduced in https://github.com/fomantic/Fomantic-UI/pull/2409
this change was failing our strict tests as we require ID to not start with a number
no BC break as no stable release shipped yet
ping @Inselhopper, you are the original author, can the ID be anything or is some special format required?
> fix(dropdown): generated id should not start with a number

- src/definitions/modules/dropdown.js
Whenever a dropdown has a search input inside the menu itself (for example a button dropdown), blurring this search field did not close the dropdown. 
Some docs examples (mainly the one on the homepage) has to be slightly adjusted for a proper fix as those did not have the `search` class or a `search input` wrapper being added. Will do that in a separate docs PR 
- open the dropdown by clicking on the button
- click into the searchfield (should be focussed already, so most probably not needed)
- press tab
The next item in the dom gets highlighted, but the dropdown stays open
https://jsfiddle.net/lubber/xom7fy4z/2/
The dropdown gets closed
https://jsfiddle.net/lubber/xom7fy4z/6/
#2101
> fix(dropdown): hide menu on menu search blur

- src/definitions/behaviors/form.js
This improves #2484 to show an error instead of a debug info, because it is basically expected to always return an existing field
https://github.com/fomantic/Fomantic-UI/pull/2484#discussion_r990791831
> feat(form): error instead of debug if field not found

- tasks/build/css.js
- tasks/build/javascript.js
- tasks/config/defaults.js
- tasks/config/tasks.js
This PR allows to adjust the comment headers via config settings in `semantic.json`
- top comment banner in semantic(.min).(css/js) either by providing a complete custom text in `banner` or adjust some of the variables in the default banner template (year,url,repository,version,title) (of course you could combine them if the custom banner also has lodash templates variables inside via `<%= version %>` 
- strip all top headers from each component inside the concatenated semantic.css/js (this is already the case in the minified version) via `stripHeaders: true` . I intentionally did not set this to true by default as other peoples projects might rely on that.
I also fixed error fetching in case a themes name is not existing
```json
"banner": "/* A custom central FUI Banner !!!\n Awesome …
```
> feat(chore): strip/adjust comment headers via config

- package.json
- yarn.lock
The dependency to octokit was not bound to a major version making `yarn add fomantic-ui` break on node 12
#2511
> fix(chore): support node12 on add

- src/themes/default/elements/icon.variables
the icon fonts need font-display to eliminate lighthouse warning in devtools
Fontaweseome did this themselves by https://github.com/FortAwesome/wordpress-fontawesome/pull/110
> fix(icon): fix lighthouse warning

- tasks/config/user.js
Improve error message for when `semantic.json` cannot be found.
I was having an issue with my setup where `semantic.json` couldn't be found. Looking at require-dot-file, it seems `false` is returned when `semantic.json` isn't found. An error is printed only when the `MODULE_NOT_FOUND` error is thrown which wasn't happening in my case.
> feat(build): improve error message for when semantic.json is not found

- src/definitions/collections/form.less
- src/definitions/elements/input.less
- src/themes/default/globals/variation.variables
This PR makes automatic browser invalidation via `:invalid` pseudo class optional via new variables
```
@variationInputInvalid
@variationFormInvalid
```
#2533
> feat(input): make invalid pseudo class optional

- src/definitions/modules/nag.less
- src/themes/default/modules/nag.variables
overlay nag were always shown, although a nag should be hidden by default.
While we are at it i slightly adjusted the default background for better readability
https://github.com/fomantic/Fomantic-UI-Docs/issues/400
> fix(nag): overlay nags were always shown

- tasks/build/css.js
- tasks/build/javascript.js
- tasks/config/project/config.js
When trying to only compile one single component, for example doing this in `semantic.json`
```json
"components": ["popup"],
```
the build does not compile anything. That's because the used https://github.com/micromatch/braces lib expects at least 2 entries so `{popup,segment}` would work, but `{popup}` does not. That leads to gulp not finding any file match, thus not compiling anything.
> fix(build): one single component does not build

- src/definitions/collections/table.less
- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
- src/themes/default/modules/calendar.variables
A calendar popup inside an overflowing container does not allow the popup to be shown completely, because it's still inside the overflowing container of the related calendar input field
You can now use a `context` setting which will move the calendar popup outside of the overflowing container (if the given context isnt an overflowing container itself...)
https://jsfiddle.net/lubber/6evhd45q/
https://jsfiddle.net/lubber/6evhd45q/6/
#2542
> feat(calendar): support context setting

- src/definitions/modules/nag.js
The cookie storage engine does only support string values. This PR adjusts a given `value` and converts it to string in case a boolean/object/array/null/etc. is given, so it's independent to any storage engine
> fix(nag): make sure value is string for all storage engines

- src/definitions/elements/label.less
- src/themes/default/globals/variation.variables
- new `centered` variant (useful for `fluid` or `attached` labels) to center text inside label
- disable pointer events on disabled labels and support groups
> fix(label): disabled and centered label(s)

- src/definitions/modules/popup.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/popup.variables
This PR allows multiline tooltips via new `multiline` variation to be set in `data-variation`.
However the `data-tooltip` text has to be cleverly prepared to make this work completely.
- non breaking spaces have to use a non visible character like U+A0 (see https://qwerty.dev/whitespace/)
- newlines to break lines / trigger a tooltip newline
https://jsfiddle.net/lubber/Lk2sp8nq/15/
> feat(popup): multiline tooltip variation

- src/definitions/modules/dropdown.less
This partly reverts #2219 and only adds the overflow setting in case of a `simple selection` dropdown where a possible scrollbar is only needed. Since 2.9.0 a simple menu item dropdown unfortunately also applied a scrollbar, which is wrong.
This PR also fixes upward menu positioning in case a `floating simple upward dropdown` is used
https://jsfiddle.net/lubber/cz09kaue/12/
#2500
> fix(dropdown): keep overflow visible for non simple selection

- src/definitions/behaviors/api.js
One case was not fetched in the new 2.9.0 api form serializer: When a named key has an array push in between the named key like "foo[][bar]"
https://jsfiddle.net/lubber/pqxr5041/36/
#2520
> fix(api): support [] inside form names

- package.json
- src/definitions/elements/input.less
- yarn.lock
in some situations the padding inside labeled icon inputs is not correct
This change uses `@supports selector` which in turn needs a fix in autoprefixer. That's why i updated the autoprefixer dependency as well to avoid a build error.
The testcase is the same as from #2183 to make sure those examples stay intact
What matters is the first labeled dropdown having left/right icons leaving a gap between the dropdown icon and the input
https://jsfiddle.net/lubber/37xuoygt/5/
#2547
> fix(input): adjust padding in labeled dropdown icon inputs

- src/definitions/modules/dropdown.js
Reuse existing tabindex from select tag when transforming into dropdown. Even worse, an existing tabindex for a select would have inpact on tabbing even though the original select is hidden when transformed into a dropdown.
@inspector71 This will fix your issue
https://jsfiddle.net/lubber/qkyou3c1/2/
https://jsfiddle.net/lubber/qkyou3c1/3/
https://github.com/Semantic-Org/Semantic-UI/issues/7100
> fix(dropdown): reuse select tabindex

- src/definitions/collections/table.less
- src/definitions/elements/container.less
- src/definitions/elements/segment.less
- src/definitions/modules/dropdown.less
- src/definitions/modules/flyout.less
- src/definitions/modules/modal.less
- src/definitions/modules/search.less
- src/definitions/modules/sidebar.less
- src/themes/default/elements/container.variables
- src/themes/default/elements/segment.variables
- src/themes/default/globals/site.variables
- src/themes/default/globals/variation.variables
On mobile devices when scrolling inside a dropdown menu, scrolling table, segment, container, etc. reaching the top of the scrolling area, the browsers will reload the page "pull to refresh".
This PR prevents such behavior on selected components, where an accidental refresh shouldnt be wanted.
- Run on a mobile device
- touch scroll inside the table 
https://fomantic-ui.com/jsfiddle/#!lubber/fas7wbey/20/
https://fomantic-ui.com/jsfiddle/#!lubber/fas7wbey/19/
#2573
> feat(chore): prevent overscrolling

- src/definitions/behaviors/api.js
- src/definitions/behaviors/form.js
- src/definitions/behaviors/state.js
- src/definitions/behaviors/visibility.js
- src/definitions/globals/site.js
- src/definitions/modules/accordion.js
- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
- src/definitions/modules/dimmer.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/embed.js
- src/definitions/modules/flyout.js
- src/definitions/modules/modal.js
- src/definitions/modules/nag.js
- src/definitions/modules/popup.js
- src/definitions/modules/progress.js
- src/definitions/modules/rating.js
- src/definitions/modules/search.js
- src/definitions/modules/shape.js
- src/definitions/modules/sidebar.js
- src/definitions/modules/slider.js
- src/definitions/modules/sticky.js
- src/definitions/modules/tab.js
- src/definitions/modules/toast.js
- src/definitions/modules/transition.js
`globalThis` is quite new feature, but all supported browsers except IE11 should support it - https://caniuse.com/?search=globalThis
I do not consider this a problem, as IE11 is kept supported when `window` is defined which normally is, only there is no longer a fallback when undefined/shadowed.
For documentation purposes and easier revert/git bisect I propose this change as a separate PR.
> feat(chore): use modern globalThis

- .eslintrc.js
- .stylelintrc.js
Assert GH-2362 and reject any CRLF present by CI.
> feat(lint): enforce LF line break in all JS and LESS files

- .eslintrc.js
- src/definitions/behaviors/api.js
- src/definitions/behaviors/form.js
- src/definitions/behaviors/state.js
- src/definitions/behaviors/visibility.js
- src/definitions/globals/site.js
- src/definitions/modules/accordion.js
- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
- src/definitions/modules/dimmer.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/embed.js
- src/definitions/modules/flyout.js
- src/definitions/modules/modal.js
- src/definitions/modules/nag.js
- src/definitions/modules/popup.js
- src/definitions/modules/progress.js
- src/definitions/modules/rating.js
- src/definitions/modules/search.js
- src/definitions/modules/shape.js
- src/definitions/modules/sidebar.js
- src/definitions/modules/slider.js
- src/definitions/modules/sticky.js
- src/definitions/modules/tab.js
- src/definitions/modules/toast.js
- src/definitions/modules/transition.js
Modernize code using eslint advisory introduced in GH-2596. This PR focuses on fixing `unicorn/prefer-date-now` rule.
Needs https://github.com/fomantic/Fomantic-UI/pull/2602 merged first.
> feat(lint): use Date.now() instead of new Date().getTime()

- src/definitions/elements/icon.less
- src/themes/default/elements/icon.variables
This PR allows for custom selector strategies for icons.
Especially for Fontawesome Pro there are icons which share the exact same words but in a different order ("foo-bar" and "bar-foo" are 2 different icons). This wouldn't work using the default fui logic 
```less
i.icon.foo.bar::before {}
```
Now, it's possible to adjust 3 new variables which would allow different icon class selectors
```less
@iconClassSeparator: " "; // a space separator automatically forces order
// or
@iconForcedOrder: true;
```
results in
```less
i.icon[class*="foo bar"]::before {}
```
```less
@iconClassSeparator: "-";
```
results in
```less
i.icon.foo-bar::before {}
```
```less
@iconClassSeparator: "_";
@iconForcedOrder: true;
@iconForcedAttribute: data-icon
```
results in
```less …
```
> feat(icon): support custom naming and selector

- .stylelintrc.js
- src/definitions/collections/table.less
- src/definitions/elements/image.less
- src/definitions/elements/loader.less
- src/definitions/elements/segment.less
- src/definitions/modules/dimmer.less
- src/definitions/modules/dropdown.less
- src/definitions/modules/flyout.less
- src/definitions/modules/modal.less
- src/definitions/modules/popup.less
- src/definitions/modules/search.less
- src/definitions/modules/sidebar.less
- src/definitions/modules/sticky.less
- src/definitions/views/card.less
- src/themes/pulsar/elements/loader.overrides
Some CSS properties like `transform` - https://caniuse.com/transforms3d - has wide enough support without vendor prefix.
> feat(lint): remove unneeded vendor prefixes

- README.md
- package.json
- tasks/config/tasks.js
- yarn.lock
The default browserlist settings were still supporting old legacy browsers which we reduced in 2.9.0.
This PR adjust the browserlist setting so much less prefixes (if any) are added to the css files.
This PR also allows to configure a whole autoprefixer prefix-config instead of only the overrideBrowserslist attribute.
> feat(build): adjust autoprefixer config to match 2.9.0 browser support

- .github/workflows/ci.yml
- src/definitions/elements/flag.less
in case prettier finds an error, the git  diff is hard to recognize the actual difference so one knows what to fix.
I added the `--color` switch so the changes are easier recognizable in the actions log
> fix(ci): color git diff output

- .github/auto_assign.yml
As exoego left the team, he should not get autoassigned to reviews anymore
> fix(chore): dont assign exoego for autoreview anymore

- .github/workflows/ci.yml
This PR adjusts the default config versions for eslint airbnb and unicorn to the current major versions which are approved to work with our custom rules setting, as our own rules extend their defaults.
By the current logic, always the latest versions are taken, which would mean our CI could break if new major versions of the default rules introduce some changes not reflected in our code.
> fix(chore): fix eslint default config major versions

- src/definitions/modules/dropdown.js
blurring from a search dropdown having `forceSelection:true` let into reopening, thus focusing, the dropdown again. This was due to calling the `item.click` function internally without a given event. In such cases the menu should never be opened again
- On the page, click the dropdown and click on a list item to select it
- Click on another field on the page
https://jsfiddle.net/qjd7ur6L/
https://jsfiddle.net/lubber/thzxcjp4/4/
#2537
> fix(dropdown): dont reopen menu on forceselection and search blur

- src/definitions/modules/flyout.js
- src/definitions/modules/flyout.less
- src/themes/default/modules/flyout.variables
Whenever a flyout contains actions but no header, the content height is miscalculated and the action container is misaligned.
The resize calculation is also fixed now, as it was always expecting all 3 nodes (header,content,actions).
Now it also works, if some or even none of them is available inside the flyout
Remove CSS and remove the flyout.js from the resources on the left to see issue
https://jsfiddle.net/lubber/1oq4rtbj/8/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/211758739-4322a6d1-f818-4a2a-bedf-622f74a24d53.png)|![image](https://user-images.githubusercontent.com/18379884/211758613-8898dac8-eb2e-4bff-821f-c14279d4b624.png)|
> fix(flyout): content height wrong without header

- src/definitions/collections/menu.less
icons inside "right menu" of a "labeled menu" were not properly displayed since #111
As a labeled menu can contain dropdowns with themselves can also contain a right menu, we have to be careful of nested selectors here. That's why i did not simply revert the original patch (and we would need to remove and test losts of !important settings which most probably breaks a lot of other use cases)
https://jsfiddle.net/lubber/6hf9zxuw/4/
#2653
> fix(menu): labeled right menu icon size

- .github/workflows/ci.yml
prettier v2.8.3 was fixed officially excl. one last patch - see https://github.com/fomantic/prettier/releases/tag/2.8.3-patched
> feat(lint): upgrade prettier to 2.8.3-patched

- tasks/config/project/install.js
The config path was not detected anymore in 2.9.1 leading into always using the defaults and, for example, autoinstall via semantic.json was not working anymore
#2660
> fix(build): fix path creation to avoid always using default settings

- src/theme.less
The theme.less file imports variables from a 3 layer logic, meant to possibly override previous defined variables for custom theming.
In 2.9 we implemented conditional checks if an element has got a custom theme to avoid importing the files multiple times.
Unfortunately this activated scoping, which means variables from a theme did not override the default variables anymore or, even worse, a custom element cannot access the same custom site.variables.
This PR now removes the conditional checks again. It does not hurt even if the same variable files are imported multiple time, as everything which is not LESS variable inside those files is removed by the gulp pipeline after building.
#2666
> fix(theme): dont conditional import variables to avoid scoping

- src/definitions/modules/modal.js
- src/definitions/modules/transition.js
Also remove the `active` class when a modal is hidden. This makes sure the modal doesnt keep an in between added active class if `hide` was called when the `show` transition has not already ended. The class is already removed at the start of the hiding process and it is still needed there because of CSS settings which will otherwise disturb the hide animation.
This PR fixes such a specific use case 
#2528
> fix(modal): remove active class on hide

- tasks/install.js
The strict check for running gulp install inside node_modules was breaking the nightly build. The only necessary check was to look for the _site folder, so i adjusted that , so gulp install also works when FUI for example was just cloned from git wihtout being inside node_modules)
> fix(build): allow gulp install from direct checkout folder

- src/definitions/collections/menu.less
- src/definitions/modules/dropdown.less
Whenever a `compact selection dropdown` has got large menu items and a shorter menu item was selected, the whole dropdown menu was shrinked to the selected item width which in turn cropped all other items when the menu was opened again
This PR make sure by default the items text is not cropped and shown in one line.
In case somebody wants to wrap item text by whitespace one could add `multiline` to the menu node.
@BBX999 This closes your issue in the SUI repo where i am not allowed to post anymore 
https://jsfiddle.net/lubber/s56mgjc3/4/
https://github.com/Semantic-Org/Semantic-UI/issues/7107
> fix(dropdown): compact menu items were cut

- src/definitions/collections/menu.less
- src/themes/default/globals/variation.variables
- Added a `wrapping` variant for menu just like we already implemented for a button group
- Optional `wrapped` class adjusts border radius (just as in button group)
- enhanced `centered` to work together with  `fluid` to allow centered menu items which stay inside a full width fluid menu (works great with wrapping :)
https://jsfiddle.net/lubber/8r9czsux/59/
#2345 
#595
> feat(menu): wrapping variant

- src/definitions/collections/grid.less
- src/definitions/elements/segment.less
- src/themes/default/globals/variation.variables
This PR finally allows to have a `vertical tabular menu` flawlessly attached to a left or right segment inside a grid column.
To accomplish this the tabular menu has to stay inside a `left/right attached column` and a `left/right attached segment` has to stay in a `left/right attached column`
https://jsfiddle.net/lubber/L9go6tab/13/
https://github.com/Semantic-Org/Semantic-UI/issues/5874
> feat(segment,grid): left and right attached variant

- src/definitions/collections/grid.less
- src/definitions/elements/segment.less
- src/themes/default/globals/variation.variables
enhanced the new left/right attached segment (#2683) by having borders removed using a dedicated `seamless` class.
The previous approach removed the borders as well but "attached" does not remove them in vertical usage, so this is consistent now. In addition seamless also works for vertical segments
This PR also fixes the wrong terminology (a left attached has to remove the right border and vices versa to be consistent of having a top attached having the bottom border removed)
> feat(segment): seamless variant

- src/definitions/behaviors/form.js
Some form events were not detroyable because attached namespace was missing which leads into memory leaks
#2695
> fix(form): use namespace to be able to destroy events

- src/definitions/elements/segment.less
This PR adds an alias `wrapping` to the current `stackable horizontal segments` for consistency as we already use `wrapping` for button groups or menu items which actually wrap single elements instead of stacking _all_ of them at once which is meant by "stackable" in every other element.
The `horizontal stackable` variant gets deprecated and will be removed in 2.10
> feat(segment): wrapping in addition to stackable

- src/definitions/modules/dropdown.js
This PR fixes a possible XSS through an entity encoded select option text when converted into a FUI dropdown.
Even if `preserveHTML: false` would prevent this, a select tag cannot contain html at all and if it contains entity encoded HTML instead, it  should not be reconverted into html.
The PR also fixes recreating the dropdown menu twice when no values are selected in a multiple dropdown
Thanks to @brian-codes for reporting
- Select the obvious evil dropdown entry
The alert message appears upon selection
https://jsfiddle.net/lubber/f5to49ew/3/
All fine
https://jsfiddle.net/lubber/f5to49ew/5/
https://github.com/fomantic/Fomantic-UI/discussions/2692#discussioncomment-5009642
> fix(dropdown): possible XSS through select option text

- src/definitions/modules/toast.js
The `onRemove` callback was called after the this reference was destroyed
> fix(toast): destroy toast after onremove callback

- src/definitions/behaviors/form.js
This PR reverts #1950 as the cause of the original issue was related to the separate dirty events which were refactored before 2.8.8 was released.
I also added some checks for reset and set values as file inputs would otherwise return a js error as file input cannot be set any value other than an empty string.
Additionally this PR simplifies the input change event detection as we dont support older browsers than ie11 and avoid memory leaks when attachEvents behavior is used and the form gets detroyed.
https://jsfiddle.net/lubber/tc9ox8dj/
#2712
> fix(formvalidation): support file inputs for validation

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
Multiple, but non selection dropdowns had issues:
- When no values were selected, a possible long place holder was partly covered by the dropdown icon
- When no values are selected, the dropdown icon was completely misaligned
- When clearable was enabled both icons weere misaligned
- the search input was doubling its content while typing
https://jsfiddle.net/lubber/51haf39w/6/
#817
> fix(dropdown): adjust icon on multiple non selection non search

- src/definitions/behaviors/form.js
- src/definitions/collections/form.less
A required Inline fields label does not get an asterisk and does not get a state color
To fix the state color i had to make use of the `:has()` class selector. This [isnt supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility), so in those browsers this feature wont work. 
I also fixed positioning of fields when an empty label is used
https://jsfiddle.net/lubber/6po2btaw/23/
> fix(form): support inline fields group label for required attribute

- src/definitions/modules/slider.js
Always bind events even if the initial slider is disabled. This allows to keep the slider intact if the `disabled` class is removed manually
https://jsfiddle.net/Lm5tv2bh/3/
https://jsfiddle.net/lubber/n37q8bd6/
#2389
> fix(slider): also bind events on disabled variant

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
When multiple modals are used and one of them got the `scrolling` class, the other non scrolling modals are position shifted right before they get hidden/overlayed
- Open first modal
- Open second
https://jsfiddle.net/lubber/wenjov56/
#934
> fix(modal): scrolling multple modals positioning

- src/definitions/modules/flyout.js
- src/definitions/modules/modal.js
The observer should only retrigger autofocus if an input has changed, not for any kind of tabbable element.
Click into the editor and press enter
... it focuses the dropdown right after pressing enter inside the editor
https://jsfiddle.net/yk1evctn/
... focus stays inside the editor
https://jsfiddle.net/lubber/krghmwuv/
#2723
> fix(modal, flyout): ignore observed non inputs for autofocus

- src/definitions/modules/popup.less
- src/definitions/modules/slider.js
This PR adds new features to the slider module:
- minRange and maxRange settings to be able to restrict a range slider to a specific range by giving edge values 
- minRange: 5  makes sure that the two thumbs always need to have a difference of 5 
- maxRange: 10 makes sure that the two thumbs dont exceed a difference of 10
- restrictedLabels: an array of label values which restrict the displayed labels to only those which are defined
- showLabelTicks "always". This differs from "true" and comes in handy when used together with "restrictedLabels"
- 'always' will always show the ticks for _all_ labels (even if not shown)
- true will display the ticks only if the related label is also shown	
- showThumbTooltip option will display a tooltip containing the current value to the thumb(s) …
> feat(slider): restrictedLabels, min/maxRange, always ticks, tooltip

- src/definitions/modules/search.js
The `onResults` callback was not firedwhen the results came from the cache.
This is now implemented. The callback will retrieve an additional 2nd parameter which will indicate if the call was initiated from remote (false) or cache (true)
- Watch Console
- Enter "test"
- Enter something else
- Enter "test" again
onResult is not called when coming from cache
https://jsfiddle.net/lubber/Lphw05ek/5/
onResult is called from Cache aswell indicated by a second parameter
https://jsfiddle.net/lubber/Lphw05ek/7/
#909
> feat(search): onresults callback fromcache

- src/definitions/collections/menu.less
This PR unifies the `equal width` logic for menu as we already have in fields, grid and segment
I left the old approach ("x item menu") to avoid being a breaking change.
I will investigate if we can remove the old approach for 2.10.0 as , at the moment, i could not detect if there is a technical reason equal width menu items were done differently than in the other components
https://jsfiddle.net/lubber/ydwfnur0/2/
#2732
> feat(menu): simpler equal width

- src/definitions/elements/segment.less
- src/themes/default/elements/segment.variables
An empty loading segment does not cover the loading spinner
> Original Fix by @brendon in https://github.com/Semantic-Org/Semantic-UI/pull/6560
https://jsfiddle.net/lubber/uf3hgkes/
> feat(segment): loading segment should cover loading spinner

- src/themes/default/elements/flag.variables
#<issue id>, #<issue id>, #<issue id>
> feat(flags): add alias for czech

- tasks/admin/distributions/create.js
- tasks/config/project/install.js
- tasks/install.js
The new file `overrides.less` was missing at install/update. Without that any install would miss the overrides files which in turn breaks components which rely on them like transition
> fix(install): copy overrides.less file on install/update

- src/definitions/behaviors/form.js
- src/definitions/collections/form.less
- src/themes/default/globals/variation.variables
Form validation will trigger success even if native form validations are still invalid.
This PR respects any native form validation by the browser in addition to the FUI form validation rules
Native invalid fields (like required file inputs) are now only shown as error'ed after a form submit has taken place at least once
I also fixed a possible double submit when the submit button is not a native submit input.
https://jsfiddle.net/lubber/7L4qhzjg/2/
#2750
> fix(formvalidation): support native validation, after submit only

- tasks/config/tasks.js
As theme override inclusions are always optional, LESS wont trigger an error in case the theme folder is not found.
We also moved the related code into a new overrides.less file (which still includes the files as optional), so fetching the import on error is never reached so the code can be safely removed.
> fix(build): removed never reached error handling

- src/definitions/modules/search.less
- src/themes/default/globals/variation.variables
Added a `horizontal category search` variant, which moves the category headers to the top of each results instead of the left
https://jsfiddle.net/lubber/Lv2fhp98/26/
#1195 
https://github.com/Semantic-Org/Semantic-UI/issues/6901
> feat(search): horizontal category variant

- src/definitions/views/comment.less
- src/definitions/views/item.less
- src/themes/default/globals/variation.variables
Added a `disabled` variant to comment and item because such elements could contain interactive elements and it's quite a common use case to have all/single comment(s)/item(s) being disabled
> feat(item,comment): disabled variants

- src/definitions/collections/menu.less
When using the wrapping option for some menu variants (such as secondary, text, tabular or borderless)  a very right border to the last item is not wanted .
#2772
> fix(menu): dont show right wrapping border on secondary

- src/definitions/modules/checkbox.less
- src/themes/default/globals/variation.variables
- src/themes/default/modules/checkbox.variables
Added an `invisible` variant to checkbox which allows to use text- or image-only check/radioboxes which are styled by using any other component for the checkbox's label tag like button, message or segment
- icons, emojis or flag only need the `image` class for the label tag. A classic "ui image" works as well
- `compact invisible` keeps the width to the content 
```html
<div class="ui invisible radio checkbox">
<input type="checkbox" id="id1a" name="radiogroup">
<label for="id1a" class="ui pink button "><b>Believe me</b><br/>I am a radio  checkbox!</label>
</div>
<div class="ui invisible radio checkbox">
<input type="checkbox" id="id1b" name="radiogroup">
<label for="id1b" class="ui blue message"><b>Believe me</b><br/>I am a radio checkbox as well!</label>
</div>
<div class="ui invisible …
```
> feat(checkbox): invisible variant for text only

- README.md
openbase has been shut down in 2023, so this badge does not work anymore
> chore(docs): remove openbase badge

- types/fomantic-ui-api.d.ts
- types/fomantic-ui-dropdown.d.ts
- types/fomantic-ui-search.d.ts
- types/fomantic-ui-tab.d.ts
Following Fomantic's documentation, `apiSettings` can also accept a `JQueryAjaxSettings` object as parameter. So this PR enable correct type checking for modules that includes `apiSettings` as a parameter: `dropdown`, `search` and `tab`.
Before:
After:
#2840
> fix(types): allow JQueryAjaxSettings objects for modules using apiSettings

- package.json
- src/definitions/modules/popup.less
- src/themes/default/collections/table.variables
- src/themes/default/elements/button.variables
- src/themes/default/elements/label.variables
- src/themes/default/globals/site.variables
- src/themes/default/modules/popup.variables
- src/themes/default/modules/toast.variables
- src/themes/default/views/item.variables
- src/themes/flat/collections/form.variables
- src/themes/flat/globals/site.variables
- src/themes/material/globals/site.variables
- yarn.lock
This change allows to use CSS variables in custom themes for LESS variables which are basically used in color functions.
Although the themes changed variables are imported after the default theme, the LESS logic still tried to apply a css variable to a color function like "darken()" which of course does not work. It makes #737 complete now.
So this simple order results into "error evaluating darken()", although the variables are immediatly overridden:
```less
@linkColor           : #4183C4;
@linkHoverColor      : darken(saturate(@linkColor, 20), 15, relative);
@linkColor: var(--some-link-color);
@linkHoverColor: var(--some-link-hover-color);
.foo {
bar: @linkHoverColor;
}
```
By changing every existing color function call inside the default theme to check for a valid color value it is now …
> fix(theme): check real colors to support css variables

- src/definitions/modules/dropdown.less
A `disabled` or `read-only` dropdown used in combination with clearable or multiple labels still showed the remove/delete icon which could indicate to still being able to delete the related value
Remove CSS to issue
https://jsfiddle.net/lubber/18okh92g/5/
#2862
> fix(dropdown): remove clearable icon on disabeled or readonly

- src/definitions/modules/calendar.less
- src/themes/default/globals/variation.variables
This PR adds classic size variations for the calendar module. I've tested it and so far didn't found any issue, but i'm a little bit rusted.
[JSFiddle](https://jsfiddle.net/uokxnbc6/)
> feat(calendar): add size variations

- src/definitions/modules/slider.js
Sometimes a calculation of max value or number of labels went into JS floating point issues why dividing
Max value is determined as 0.92999999 instead of 0.94
https://jsfiddle.net/4robkn7u/1/
Max value is 0.94 as expected
https://jsfiddle.net/lubber/qbs3cn9e/1/
#2877
> fix(slider): max value had js floating point issues

- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
When `pointing` or `floating` was used
- background color overlayed the border corners of first and last item if menu was not scrolled/overflowed
- in combination with `selection` borders were missing
- inverted upward pointing had wrong arrow direction
I also added a new `unlimited` variant which does not make the selection menu scrollable but shows all items at once instead. This is especially needed in combination with `pointing`. Otherwise the arrow wont be displayed as the arrow is part of the (overflowing) dom node.
https://jsfiddle.net/lubber/jq3vmLde/7/
> fix(dropdown): support selection floating or pointing

- src/definitions/behaviors/api.js
This change fixes the false positive snyk warning about a possible Redos regex attack. Synk does not correctly detect the settings reference, because the related regexes themselves are safe (checked via https://devina.io/redos-checker)
#2891
> fix(api): create regexp alias to fix snyk redos false positive

- src/definitions/modules/flyout.js
- src/definitions/modules/sidebar.js
This PR removes leftover and unused/ineffective code to check for ios browsers. The whole codebase does not have any class reference to `.ios` anymore.
This was already removed in SUI 2.2.11 almost 6 years ago via https://github.com/Semantic-Org/Semantic-UI/commit/da0aff070a05ab2c12a603c9c5db01b9208e9400 , but it was forgotten to clean up the code entirely.
As `set.ios` as well as any `.ios` selector was removed, any additional codechecks don't have any impact, so it's safe to delete without tagging as breaking change
> fix(sidebar,flyout): remove unused ios checks

- src/definitions/elements/header.less
- src/themes/default/globals/variation.variables
The attached header doesn't support the seamless variant like the segment element which results in showing the border between the header and the attached element below.
This PR allows to have the attached header element with seamless variant that allows to remove the bottom border when it attaches with the another segment below.
**Before:** https://jsfiddle.net/jkszwbxe/
**After:** https://jsfiddle.net/ko2in/yoafg8mx/1/
**Before:**
**After:**
#2874
> feat(header): seamless attached variant

- src/definitions/collections/form.less
- src/definitions/elements/input.less
- src/themes/default/collections/form.variables
Supports textarea in the action input to display like the input field and the button stacked together.
**Before:** https://jsfiddle.net/vhfrb2qt/1/
**After:** https://jsfiddle.net/ko2in/5aco9q8m/
#2814
> feat(form, input): support textarea with action button

- types/fomantic-ui-api.d.ts
- types/fomantic-ui-calendar.d.ts
- types/fomantic-ui-checkbox.d.ts
- types/fomantic-ui-dropdown.d.ts
- types/fomantic-ui-flyout.d.ts
- types/fomantic-ui-form.d.ts
- types/fomantic-ui-modal.d.ts
- types/fomantic-ui-nag.d.ts
- types/fomantic-ui-popup.d.ts
- types/fomantic-ui-progress.d.ts
- types/fomantic-ui-search.d.ts
- types/fomantic-ui-tab.d.ts
- types/fomantic-ui-tests.ts
- types/fomantic-ui-toast.d.ts
- types/fomantic-ui-transition.d.ts
- types/fomantic-ui-visibility.d.ts
This is the first round of fixes/improvements for type declarations of Fomantic. Some properties and methods were missing, some were too restrictive.
I've enabled strict type checking on my work project (~500k lines of code and use almost every module of Fomantic). Before the fix I had around 2500 errors during transpilation, 0 after.
I just cannot fix one error, that I circumvent by adding the `//@ts-expect-error` on the line before:
For a `Form`, creating a new rule will raise an error in VSCode (that can be safely bypassed).
`$.fn.form.settings.rules` is typed and Intellisense is working, but adding a new rule to it will trigger an error. Anyway, this is not a blocking issue for merging, since this PR will make a lot more good than bad :)
#2906
> fix(types): better declaration files

- src/definitions/collections/grid.less
The stackable inverted grid item is not showing the divider in mobile screen due to the override by specificity of non-inverted grid.
- Open fiddle https://jsfiddle.net/ko2in/tqw0anjv/
- Resize the panel to become narrow as mobile screen size
- Open fiddle https://jsfiddle.net/ko2in/tqw0anjv/4/
- Resize the panel to become narrow as mobile screen size
#2922
> fix(grid): fix stackable inverted grid divider for mobile screen

- src/definitions/modules/dropdown.less
Dropdown sizes were ignored when used inside forms.
https://jsfiddle.net/lubber/jewyfngq/13/
#2947
> fix(dropdown): support individual sizing inside forms

- src/definitions/collections/form.less
Added the `.grouped.fields > label` selector for targeted styling, ensuring labels within grouped fields inherit the inverted color in inverted forms. Used `@invertedLabelColor` for color consistency. Tested in various configurations and browsers.
https://jsfiddle.net/Festiis/8t6fgkjo/
> style(form): ensure consistent inverted label color in grouped fields

- src/definitions/collections/table.less
Changed the CSS selectors to target the last row instead of the first row in the table footer.
Previously, the styles targeted the first row of the table footer. 
https://jsfiddle.net/Festiis/02m8dx13/7/
> Refactor: Apply border-radius styles to last row of table footer

- types/fomantic-ui-dropdown.d.ts
- types/fomantic-ui-search.d.ts
Type additions for new `highlightMatches` and `ignoreSearchCase` setting as of #2963
> fix(types): highlightmatches setting

- src/definitions/modules/dropdown.js
This PR allows to render custom data- attributes for each dropdown item by providing a `data` key object.
Every key inside the data object will be rendered as data attribute (only "text" and "value" will be ignored as those are already used by the dropdown module internally)
```javascript
values: [
{
name: 'Mother',
value: 'mom',
data: {
husband: 'george',
age: 73
}
}
]
})
;
```
which results in
```html
<div class="item" data-value="mom" data-husband="george" data-age="73">Mother</div>
```
#1236
> feat(dropdown): support custom data attributes for items

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
clearable icon ...
- was missing when used inside a search selection dropdown
- was misaligned when used inside an inline dropdown
The basic fixes where already implemented but only if the `clearable` class was set manually, which this PR now automatically adds when the clearable setting is used.
https://jsfiddle.net/lubber/nwjqr7Le/
> fix(dropdown): clearable icon was missing or misaligned

- src/definitions/collections/table.less
- src/definitions/globals/site.less
- src/definitions/modules/dimmer.less
- src/definitions/modules/dropdown.less
The `scrollbar-width` and `scrollbar-color` properties are also supported by Chromium based Browsers nowadays (Since 121).
However, the properties in chromium based browsers don't visually work the same (and old FUI) way as it does in firefox.
This PR makes sure those CSS properties are only applied in firefox  so chromium based browsers will still only use the old `::-webit-scrollbar-xxxx` approach.
#3002
> fix(core): use scrollbar-width and color on firefox only

- src/definitions/modules/dropdown.less
#2883 broke specificity when a (very) long/short variant was used for a `search selection` dropdown (a pure `selection` dropdown was not affected
Manipulate the specificity via console or remove the `search` class to see the fix
https://jsfiddle.net/unarist/dfcw0rbq/9/
#3035
> fix(dropdown): long/short variants were not working anymore

- src/definitions/elements/button.less
- src/themes/default/elements/button.variables
The new circular button group variant did not respect the spaced variant for right margin and did not respect the icon variant for width
https://jsfiddle.net/lubber/yh25feLd/21/
https://jsfiddle.net/lubber/yh25feLd/24/
#2946
> fix(button): circular spaced and circular icon group was not respected

- package.json
- yarn.lock
Turns out the latest version of ordered-read-streams, 2.0.0, does not always order the files as they were given.
Looks like the issue is inside the new used streamx lib. It seems the given order is modified internally by the end of the file read, so larger files are still merged at the end rather as the desired position.
For example the large emoji.css was always set to the end of the order although the order of that file was given much earlier in the stream array.
Reverting back to to v 1.0.1 fixes that (as it does not use streamx, but readable-stream instead of streamx)
> fix(deps): downgrade ordered-read-streams

- src/definitions/collections/form.less
- src/definitions/modules/dropdown.less
Whenever an empty (placeholder shown) multiple search dropdown got a form state (error/info/warning/success) the cursor was not shown anymore when clicking into the search field of the dropdown.
Click into the errored dropdown
Remove CSS to see issue (cursor wont show)
https://jsfiddle.net/lubber/omg7v1aj/41/
#3050
> fix(dropdown): hidden cursor on form states

- src/definitions/collections/message.less
In some situations when specific nested width limited elements are inside a `compact message`, the message could overflow the screen width
Open https://fomantic-ui.com/modules/accordion.html#right-icon on a mobile device or switch your browser to mobile view
This example wraps an accordion inside a compact message and overflows the screen.
|Before|After|
|-|-|
|![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/b7307c9f-ee69-4c0e-9f5d-591d40ccc4b8)|![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/5bd6c5a5-e531-4bac-aedb-9c99b9cea5c0)|
> fix(message): compact message should not exceed max width

- src/definitions/collections/form.less
Followup of #2711
Whenever an empty label was used for a required single field or non-grouped, non-inline fields group, the label was still receiving an extra space to create a default height and did not display the asterisk. The intention of the space character was for empty non required fields to match same height when used inside a fields row.
If one does not want a label at all and does not want to make this field required, you would not render the label at all and wont get additional space then
https://github.com/fomantic/Fomantic-UI/pull/2711#issuecomment-2176221081
> fix(form): dont add whitespace on empty required field labels

- src/themes/default/modules/progress.variables
When a progress is very short, the bar could contain a value > "10%" which then does not completely fit into the bar anymore.
By slightly increasing the min-width, this should cover almost every usecase.
https://jsfiddle.net/gq045pk7/3/
The second example is using the fix from this PR
The progess should show "11%"
#3068
> fix(progress): wider bar min width

- types/fomantic-ui-calendar.d.ts
- types/fomantic-ui-search.d.ts
There was a missing type declaration on module `search.fullTextSearch`. I added these changes based on the current document: https://fomantic-ui.com/modules/dropdown.html#additional-settings
N/A
N/A
N/A
> chore(types): fix missing types on some module

- types/fomantic-ui-dropdown.d.ts
- types/fomantic-ui-flyout.d.ts
- types/fomantic-ui-form.d.ts
- types/fomantic-ui-modal.d.ts
- types/fomantic-ui-search.d.ts
- types/fomantic-ui-slider.d.ts
- types/fomantic-ui-tab.d.ts
- types/fomantic-ui-transition.d.ts
Latest linting rule [no-unsafe-function-type](https://typescript-eslint.io/rules/no-unsafe-function-type/) breaks existing types which results in failed CI checks on every other PR.
> fix(types): satisfy lint rule no-unsafe-function-type

- types/fomantic-ui-transition.d.ts
fixing the transition looping enabling call signature. The passed behavior gets interpreted as a nonexistent animation otherwise.
> fix(types): correct transition behavior "set looping"

- types/fomantic-ui-dropdown.d.ts
- types/fomantic-ui-modal.d.ts
- types/fomantic-ui-popup.d.ts
- types/fomantic-ui-transition.d.ts
Some types fixes to reflect settings in modal, dropdown, popup and transition
#3081
> fix(types): missing/wrong types for modal. dropdown, popup, transition

- src/themes/default/elements/flag.variables
According to https://en.wikipedia.org/wiki/North_Macedonia , the related country flags name needs correction
To avoid a breaking change, i still left the previous name as a second alias. This will be removed again in 2.10.0
https://github.com/Semantic-Org/Semantic-UI/issues/7143
> fix(flag): update macedonia flag name

- src/definitions/elements/label.less
Tihs PR supports grouping of image labels and fixes bottom margin
https://jsfiddle.net/lubber/v0tqdh65/6
https://github.com/fomantic/Fomantic-UI/issues/2986#issuecomment-2245741558
> fix(label): grouping image labels margin

- .github/workflows/ci.yml
Latest node 23 ci check fails because of active development and dependencies would need an update or fix
However, even if this check is declared as not required, the github actions still fail, which is a false positive as long as it's not an LTS version (which node 23 isn't)
To get rid of the failures, this PR removes the latest node check and adds dedicated LTS version instead which makes the CI succeed again.
Will review this for latest node again when working on 2.10.x soon
> fix(ci): dont let job fail for latest node

- types/fomantic-ui-slider.d.ts
Missing and new types for slider matching the feature s of #3111
> feat(types): missing and new option for slider

- src/definitions/elements/step.less
Hotfix to increase color specificity when a single circular step has an independenat color but the whole step group also got a colors definition
> fix(step): color variant specificity

- .github/workflows/ci.yml
- yarn.lock
Switch Lint CI check for prettier to latest official stable version v3. Everything fixed via #2669 seems to be included in prettier@3 since quite a while now, so no need to stay at a fixed commit anymore.
@mvorisek Thanks again :)
> feat(ci): upgrade to prettier v3

- tasks/config/project/release.js
- tasks/config/tasks.js
Instead of releasing the files:
```
semantic.css
semantic.js
semantic.min.css
semantic.min.js
```
optionally release the files that include the version number and an optional revision string:
```
semantic-2.9.3-a.css
semantic-2.9.3-a.js
semantic-2.9.3-a.min.css
semantic-2.9.3-a.min.js
```
The advantage is to make clear which version is currently being used, and preventing the browser cache from running an obsolete version.
This pull-request is fully backward compatible as the default behaviour does not change at all.
The change is activated in semantic.json by adding the relevant fields:
```
{
// ...
"permission": false,
"autoInstall": false,
"rtl": false,
"includeVersionInFileName": true,          <== Here
"revision": "a",                                           <== Optionally this, …
```
> feat(build): optionally include version in released filename

- types/fomantic-ui-calendar.d.ts
Added types for the new optional format parameters for calendars get date functions as of #3141
> feat(types): format parameters for calendars get date functions

- semantic.json.example
- tasks/config/defaults.js
- tasks/config/tasks.js
Support a custom filename instead of hardcoded "semantic" (which is still default).
This also prepares for a later change for the default from "semantic" to "fomantic" and a quicker fallback
> feat(build): customizable output filename

- package.json
- yarn.lock
I published a new version of[ fomantic/rework-import](https://github.com/fomantic/rework-import) (through [gulp-concat-css](https://github.com/fomantic/gulp-concat-css)) which gets rid of re2 and url-regex(-safe) dependency.
The only need was to check a possible prototcol inside the import string. It does not matter if the whole URL is valid, as rework-import only needs to know if the import is a local file or not. This logic was already the case in 2.0 of the original rework-import, so basically there never was a need to switch to a separate package just for that check.
By doing all of this, fomantic does not need re2 dependency anymore which itself needs an installed python instance which especially on windows is not available by default.
#3167
> fix(deps): remove re2 and url-regex through rework-import

- src/definitions/modules/dropdown.less
This PR fixes the upper/lower border of submenus when used inside a `unlimited selection dropdown` 
The docs for `unlimited` should be enhanced to show that use case
#3158
> feat(dropdown): support submenus for selection dropdown

- src/definitions/elements/divider.less
- src/themes/default/elements/divider.variables
Final fix for vertical divider inside a stackable grid. However, the divider needs to be set at the desired location (between the columns where it should be shown)
Remove CSS to see issue while resizing the viewport to swtch between mobile view
https://jsfiddle.net/lubber/p8tfgbjq/12/
https://github.com/fomantic/Fomantic-UI/issues/531
https://github.com/Semantic-Org/Semantic-UI/issues/4342
https://github.com/Semantic-Org/Semantic-UI/issues/6637
> fix(divider): vertical in stackable mobile grid

- src/definitions/elements/step.less
The cursor was not changed on link steps inside `circular steps` when only the anchor tag was used
> fix(step): link cursor not working on a tags
