- src/definitions/collections/form.less
Fixes Semantic-Org/Semantic-UI#6363
> [Form] IE11 - CSS rule is incorrect for input placeholders.

- src/definitions/behaviors/form.js
Fixes Semantic-Org/Semantic-UI#6237.
> [Form Validation] Avoid trim of values before validation

- src/definitions/modules/dropdown.js
The option sortSelect was extended to accept true, 'natural' and a custom function(a, b){}
Was reported in Semantic-Org/Semantic-UI#4775, adapted from Semantic-Org/Semantic-UI#6412
> [Dropdown] Extend sortSelect with 'natural' and custom function

- src/definitions/modules/dropdown.js
Dividers are siblings of ".item" elements and mach the divider selector (.header, .divider)
This option takes following values:
- **false**   => Same behavior as before
- **true**    => hide all dividers
- **'empty'** => hide all dividers if they are not followed by a visible item (direct divider siblings are treated as a group)
Fixes Semantic-Org/Semantic-UI#6173
> [Dropdown] Add new hideDividers option

- src/definitions/modules/dropdown.less
When we have a `.fluid.dropdown` inside of `.inline.fields` the dropdown is set to `auto` because of the `.inline.fields`
A fluid dropdown should always be 100%
This is an example
The dropdown should take all the red space but it does not
https://jsfiddle.net/dq9urpzn/8/
> [Dropdown] A fluid dropdown should be fluid

- src/definitions/elements/label.less
Fixes odd background color variation in tag labels:
Closes Semantic-Org/Semantic-UI#5908
> [Label] :ActiveHover is not a valid selector error #5908

- src/definitions/elements/segment.less
Segments used in tabs should always have the same margin.
Closes issue Semantic-Org/Semantic-UI#6461
>  [Tab] Last tab should still have a bottom margin

- src/definitions/modules/modal.js
Pressing the mouse inside the modal and releasing it outside closed the modal in Chrome.
Additionally pressing the mouse outside the modal and releasing it inside closed it in both Chrome and Firefox.
Was reported in Semantic-Org/Semantic-UI#6430
> [Modal] In Chrome, Modals close on Mouse up outside the Modal

- src/definitions/modules/dimmer.js
The change causes a regression on all touchmove events. Removing until further investigation.
This reverts commit 75dcaa2
Reported in Semantic-Org/Semantic-UI#6449
> [Modal] Revert "Add solve for dimmer to prevent modal scrolling in bg"

- src/definitions/modules/dropdown.js
Closes issue Semantic-Org/Semantic-UI#6420.
Allow to add header items to dropdown during js initialization, using this syntax:
```js
values: [
{
name     : 'Filter by tag',
type     : 'header'
// Will be displayed as header
},
{
name     : 'Important',
value    : 'important',
type     : 'item'
// Will be displayed as item
},
{
name     : 'Announcement',
value    : 'announcement'
// Will be displayed as item
}
]
});
```
Works too with API requests.
> [Dropdown] Add possibility to add header items during js initialization

- src/definitions/modules/dropdown.js
The `module.is.selectMutation()` function was unused. I just rewrote the function where she should have be called (in `module.event.select.mutation()`).
> [Dropdown] Clean select mutation code

- src/definitions/modules/modal.less
This fixes the absolutely positioned close icon inside the modal
Closes Semantic-Org/Semantic-UI#6251
> [Modal] Fullscreen Modals since 2.3.0 regression in Safari

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
Add the ability to clear a single selection dropdown thanks to the `clearable` class.
Related SUI issue: Semantic-Org/Semantic-UI#3635.
> [Dropdown] Add clear icon in single selection mode

- src/themes/default/elements/button.variables
Fixes #60 
The tertiary buttons have the basic background color on active state, I changed it to none to match the other states.
> [Button] tertiary buttons have @basicDownBackground when :active

- tasks/docs/build.js
Fixes #54
Latest node version errors and exits script because fs doesn't contain a callback.
I added a blank function therefore it doesn't complain
> [Docs] build error on new node version

- src/definitions/modules/dropdown.less
A little background...
The PR Semantic-Org/Semantic-UI#4211 add a left class to the dropdown menu under some circumstances. That left class trigger some CSS items that broke the dropdown display... This PR cannot be reverted, so we must find another way to fix the issue... and here it is !
Fixes Semantic-Org/Semantic-UI#6491.
> Fix the dropdown pointer that still remains after dropdown menu is collapsed

- src/definitions/elements/header.less
This PR fix the incorrect top attached header top margin which was negative.
Before:
After:
**Bonus point**
It also add the ability to stack many top or bottom attached headers without broke everything !
```html
<div class="ui top attached header">Demo</div>
<div class="ui top attached header">Demo</div>
<div class="ui attached header">Demo</div>
<div class="ui bottom attached header">Demo</div>
<div class="ui bottom attached header">Demo</div>
```
Before:
After:
Semantic-Org/Semantic-UI#5436
Semantic-Org/Semantic-UI#5462
> Fix incorrect top attached header top margin

- src/definitions/collections/form.less
Added `@inputFont` to the textarea so it now uses the theme font family. Also removed duplicate `font-size`.
https://github.com/Semantic-Org/Semantic-UI/issues/5546
> Fixed textarea having wrong font family

- RELEASE-NOTES.md
- src/definitions/modules/rating.js
Rating couldn't be started read-only with the disabled class. This PR add the ability to do so.
> Disabled rating

- src/definitions/modules/search.js
- src/definitions/modules/search.less
Added ability to disable the link and turn it into a div when `actionURL` is equal to `false`.
https://github.com/Semantic-Org/Semantic-UI/issues/6490
> [Search] added ability to disable link action

- src/definitions/modules/search.js
Moved the result set value to run before the onSelect callback allowing the user to change the value without it being overridden.
https://github.com/Semantic-Org/Semantic-UI/issues/6454
> [Search] set value inside onSelect callback

- src/definitions/collections/menu.less
This PR allow tab menu to be centered. Also works with the secondary style. Closes Semantic-Org/Semantic-UI#5589.
Thanks @franckpopchef for the implementation idea !
>  [Tab] Allow centered tab menu 

- src/definitions/modules/checkbox.js
Previously it only worked if fireOnInit was set to true (default is false)
Behaviour of fireOnInit was not modified: the callbacks are only called on initial load when fireOnInit is true
Semantic-Org/Semantic-UI#2506
> [Checkbox] toggle don't have the "checked" class when initialized in a 'checked' state

- src/definitions/views/comment.less
This PR add the `inverted` variation for comments.
Preview:
[![14e30daf80a1bf5c10e790e5935d9ca9.png](https://tof.cx/images/2018/08/14/14e30daf80a1bf5c10e790e5935d9ca9.png)](https://tof.cx/image/eTFXZ)
> [Comment] Add `inverted` variation

- src/definitions/modules/accordion.less
Instead of setting the default display to 'none' and active display to 'block', we only set the the display to 'none' when it's `:not(.active)`
Fixes Semantic-Org/Semantic-UI#6351
> fix(accordion): Invert active condition

- src/definitions/collections/form.less
This pull request is to add a transparent textarea option on forms as shown below:
> [Form] Added a transparent textarea option

- src/definitions/elements/step.less
Before:
[![22b6e3e244f87729f3e1fbd4c8ced087.md.png](https://tof.cx/images/2018/08/16/22b6e3e244f87729f3e1fbd4c8ced087.md.png)](https://tof.cx/image/ehVO1)
After:
[![aec340832592ab9a5794b2ae5ab93aa2.md.png](https://tof.cx/images/2018/08/16/aec340832592ab9a5794b2ae5ab93aa2.md.png)](https://tof.cx/image/ehk9A)
Test case:
```html
<div class="ui ordered steps">
<div class="completed step">
<div class="content">
<div class="title">Shipping</div>
<div class="description">Choose your shipping options</div>
</div>
</div>
<div class="completed step">
<div class="content">
<div class="title">Billing</div>
<div class="description">Enter billing information</div>
</div>
</div>
<div class="active step">
<div class="content">
<div class="title">Confirm Order</div>
<div class="description">Verify order …
```
> [Step] Fix the bad step count in a segment

- src/definitions/modules/checkbox.less
- src/themes/default/modules/checkbox.variables
This PR add inverted style for standalone checkboxes (eg. not tied to form...). It's working but needs to be polished on events (focus, hover...), help is really appreciated !
Fixes Semantic-Org/Semantic-UI#6471.
My test case:
```html
<div class="ui inverted segment">
<div class="ui inverted checkbox">
<input type="checkbox" name="example">
<label>Make my profile visible</label>
</div>
</div>
<div class="ui segment">
<div class="ui checkbox">
<input type="checkbox" name="example">
<label>Make my profile visible</label>
</div>
</div>
<div class="ui inverted segment">
<div class="ui inverted slider checkbox">
<input type="checkbox" name="example">
<label>Make my profile visible</label>
</div>
</div>
<div class="ui segment">
<div class="ui slider checkbox">
<input type="checkbox" …
```
> [Checkbox] Implements inverted mode for standalone checkboxes

- src/definitions/collections/grid.less
- src/definitions/collections/menu.less
- src/definitions/modules/dropdown.less
- src/themes/default/collections/grid.variables
- src/themes/default/collections/menu.variables
- src/themes/default/collections/table.variables
- src/themes/default/elements/container.variables
- src/themes/default/elements/divider.variables
- src/themes/default/elements/label.variables
- src/themes/default/elements/rail.variables
- src/themes/default/elements/segment.variables
- src/themes/default/elements/step.variables
- src/themes/default/globals/site.variables
- src/themes/default/modules/dimmer.variables
- src/themes/default/modules/dropdown.variables
- src/themes/default/modules/popup.variables
- src/themes/default/modules/search.variables
- src/themes/default/views/card.variables
Replaces all tilde string escaping with explicit function calls.
This was tested with gulp-less@3.5.0 and gulp-less@4.0.1
Reported in Semantic-Org/Semantic-UI#6512
> [Dependency] Fix compatibility issue with less >= 3.5 due to math changes

- src/definitions/views/card.less
- src/themes/default/views/card.variables
Added horizontal card variation
https://github.com/Semantic-Org/Semantic-UI/issues/6534
> [Cards] add horizontal variation

- src/definitions/views/card.less
- src/themes/default/views/card.variables
This PR add the `inverted` variation for cards.
Preview:
[![27a972c2dc68c7740205e7f6d99f1615.png](https://tof.cx/images/2018/08/23/27a972c2dc68c7740205e7f6d99f1615.png)](https://tof.cx/image/ebmjC)
> [Card] Add `inverted` variation

- src/definitions/collections/grid.less
- src/themes/default/collections/grid.variables
This PR add the `compact` and `very compact` variations for grids.
Preview:
[![ae70063314e48eecf439b2206718eac7.png](https://tof.cx/images/2018/08/24/ae70063314e48eecf439b2206718eac7.png)](https://tof.cx/image/tq58f)
> [Grid] Add `compact` and `very compact` variations

- src/definitions/collections/form.less
- src/definitions/collections/menu.less
- src/definitions/elements/button.less
- src/definitions/modules/dropdown.less
This PR allow different sizes for dropdowns. It will need a lot of tests before merging it !
Semantic-Org/Semantic-UI#5154
> Implements dropdown different sizes (standalone and in forms)

- src/definitions/modules/accordion.less
The changed rule for "not active" content in accordion mistakenly hides content inside the header as well
Closes #102
> [Accordion][Header] Header with content has display:none when in an accordion element

- dist/components/calendar.css
- dist/components/calendar.js
- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
- An optional new setting "showWeekNumbers" in day-view adds a column to the left with the appropriate weeknumber 
```javascript
$('#date_calendar')
.calendar({
type: 'date',
showWeekNumbers: true
})
;
```
> [Calendar] Adds support for WeekNumbers in Day View

- src/definitions/modules/checkbox.js
> [Checkbox] since 2.5.0 'before[Un]Checked' fires already on init

- src/definitions/modules/modal.js
In case of nested modals, pressing the ESC key will only close the last opened modal.
Semantic-Org/Semantic-UI#5768
> [Modal] Pressing the ESC key won't close all open modals anymore

- src/definitions/modules/modal.js
This PR will prevent the ability to interact with modals that are not the focused one. It works by adding an inside dimmer to each modal that got the `allowMultiple: true` setting. If a modal is open, other will be dimmed so you cannot use them, until you close the last modal by pressing ESC (thanks to #118), or you close all of them by clicking on the dimmer.
[![f61277c28c2f61d1e9a5250ff5198635.gif](http://tof.cx/images/2018/09/14/f61277c28c2f61d1e9a5250ff5198635.gif)](http://tof.cx/image/zwi8V)
Semantic-Org/Semantic-UI#5770
> Lower modals are not accessible anymore in multiple modals

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
Would be nice if someone could check the usage of `.ui.fullscreen.scrolling.modal` I didn't find any use-cases.
Closes #130 / Semantic-Org/Semantic-UI#6587
> [Modal] Fullscreen modal stuck to left edge of page

- src/definitions/views/comment.less
- src/themes/chubby/views/comment.overrides
this allows "comments"-icon to be used in the actions section (or elsewhere)
Closes #131 / Semantic-Org/Semantic-UI#4404 / Semantic-Org/Semantic-UI#6595
> [Icon] Comments icon inside "comment" component is not well aligned

- src/definitions/modules/modal.less
Increased the importance of legacy modal class definition
fullscreen modal class overrules the top / left definition of the legacy modals, which results in off-screen rendering of modals in IE11
Closes #134 / Semantic-Org/Semantic-UI#6597
> [Modal] Fullscreen modals are not working in IE11

- dist/components/dropdown.css
- dist/components/dropdown.js
- src/definitions/modules/dropdown.js
- src/themes/default/modules/dropdown.variables
A multiple dropdown selection searchable box had
1. The close icon displayed over the search input field when many entries have been selected
2. Whenever an entry was selected via enter, it looses it's focus making quick keyboard selection impossible (you needed to click again into the search field
Before:
After:
> [Dropdown] Multiple search keyboard + icon fix

- src/definitions/modules/transition.less
Using a hidden transition on a placeholder does not set display:none, because placeholder style will still override it. 
The Fix should make sure it wont happen to any other element having .hidden.transition
https://jsfiddle.net/zqfrjso1/4/ (from original issue)
https://github.com/Semantic-Org/Semantic-UI/issues/6608
> force display:none on .placeholder.hidden.transition

- src/definitions/modules/dropdown.js
This PR fixes the compatibility with semantic's clearable dropdown implementation. Setting clearable to `true` now display correctly the clear icon when there is a selected value.
Also, this PR does not clear the selection when you click on the toggle icon, as you might want to change a value without setting it empty in between.
> [Dropdown] Fix the clearable setting that does'nt init a clearable dropdown

- src/definitions/collections/form.less
Support for transparent textarea in an inverted segment or form (only the color needed to be changed)
#158
> [Form] Support inverted transparent textarea

- src/definitions/collections/form.less
- src/themes/default/collections/form.variables
As  discussed in #107 , i implemented option b)
As the padding discussion is only relevant for the error background display, i decided to leave all inputs which are _not_ within a form untouched. Means, those inputs still don't have any padding.
#107
> [Form] Transparent Input/Textarea Error

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
Support for `ui inverted modal`
```javascript
$('.ui.modal').modal({
dimmerSettings: {
variation: 'inverted'
}
});
```
Buttons in actions Row need to be defined as inverted separately as usual as `ui inverted negative button`
#108
> [Modal] Inverted variant

- src/definitions/modules/toast.js
- src/definitions/modules/toast.less
Added the usual colors to default `ui toast` className. Also supports `inverted`
`class: 'red|orange|yellow|olive|green|teal|blue|violet|purple|pink|brown|grey|black'`
`class: 'inverted red|orange|yellow|olive|green|teal|blue|violet|purple|pink|brown|grey|black'`
> [Toast] Added SUI usual color palette with inverted support

- src/definitions/modules/progress.less
Instead of animating the "width" property, animate the transform (scale) property instead.
This improves the performance, because the property doesn't affect the layout.
https://jsfiddle.net/Korinu/sjpw54da/
Before
After
Possible closes Semantic-Org/Semantic-UI#2316
> [Progress] Improve performance for active progress bars

- src/definitions/modules/toast.less
On scrolling body content the `top center` or `bottom center` positioning was broken
> [Toast] fix position for top and bottom centered container

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
This PR add the abilty to set a min date and/or a max date for a calendar trough metadata at init and trough behaviors at any time.
```html
<div class="ui calendar" data-min-date="15/10/2018" data-max-date="17/10/2018 12:00:00">
<div class="ui input left icon">
<i class="calendar icon"></i>
<input placeholder="Date/Time" type="text">
</div>
</div>
```
User will be able to select any date between 15/10/2018 00:00:00 and 17/10/2018 12:00:00.
```js
$('.ui.calendar').calendar('set maxDate', '12/25/2018');
```
User will be able to select a date until Christmas this year.
Bonus feature: added some code format and component name (usefull for debug...).
> [Calendar] Add ability to set `minDate` and `maxDate` by behavior or metadata

- src/definitions/elements/header.less
Changed the attached header classes as following:
- All non-top attached headers have no border top
- All top attached headers have a border-radius top left / top right
- All bottom attached headers have a border-radius bottom left / bottom right
#180
> [Header] Top-attached headers missing top border

- .gitignore
This PR only add the vcode folder in the .gitignore file, allow preventing vscode users (and the dumbest one, a.k.a. myself) submitting unwanted files to the repo...
> chore: add vscode folder into .gitignore

- src/definitions/modules/dimmer.less
- src/themes/default/modules/dimmer.variables
The text color in an inverted dimmer had the same color (white) as in a normal dimmer making it unreadable
```html
<div class="ui medium image">
<div class="ui inverted medium dimmer">
<div class="content">
<h3>Look!</h3>
Can you still read me?
</div>
</div>
</div>
```
Before -> After (using `ui inverted medium dimmer`, but normal `ui inverted dimmer` would make it look even worse)
https://github.com/Semantic-Org/Semantic-UI/pull/4631
> [Dimmer] Fix content text color in inverted dimmer

- src/definitions/modules/dropdown.less
- Open the fiddle
- Select an item from the right dropdown field
- At least on Chrome the dropdown shifts a few pixels down
- To see the fix, uncomment the CSS part in the fiddle and run again
https://jsfiddle.net/n5gz8vx6/1/
Before
After
https://github.com/Semantic-Org/Semantic-UI/issues/5699
> [Dropdown] Prevent downshifting on multiselection

- src/definitions/modules/dropdown.js
Since implementing #143, whenever one selected an item on multiple search via enter, the DropDown-List was closing/opening immediatly making it look ugly.
This PR fixes that. It simply does not hide the List on multiple anymore.
Before:
After:
#143
> [Dropdown] Prevent close/open bubbling on keyselect via enter

- src/definitions/modules/dropdown.js
When clicking on a label of a select-dropdown it behaves like it would open the dropdown again after closing it. Indeed toggle() is called, but the previous event was hiding it before
https://jsfiddle.net/d0aosr6q/1 
- Click on the label above the dropdown. It opens the dropdown.
- Clicking again closes it, but opens it again.
https://github.com/Semantic-Org/Semantic-UI/issues/6638
> [Dropdown] Stop Events after clicking outside of module

- src/definitions/modules/dropdown.js
If a dropdown had `showOnFocus` set to false, the dropdown icon and the dropdown itself was not clickable anymore to open the whole list of options
https://jsfiddle.net/ibelar/eokn6yv8/
#191
> [Dropdown] showOnFocus:false prevented click to open dropdown

- src/definitions/modules/dropdown.js
If a submenu entry was selected from a dropdown, the Element got focus on IE11 and reopened the dropdown again. This was basically already fixed in case the dropdown had a searchmenu, but now it works anytime.
https://jsbin.com/yofawovahi/edit?html,js,output
https://github.com/Semantic-Org/Semantic-UI/issues/6565
> [Dropdown] Fix IE11 submenu selection triggered menu opening

- src/definitions/modules/progress.less
- src/themes/default/modules/progress.variables
Some progress text is unreadable on inverted progress bars, because their background color is too light.
This PR changes the text colors from white to black on `inverted yellow|olive|teal|grey progress`
> [Progress] Display dark text on light inverted backgrounds

- src/definitions/modules/calendar.js
This PR add the ability to disable some days of the week from selection. By setting `disabledDaysOfWeek` to array of numbers (0= Sunday, 1=Monday...), you can now disallow users from selecting these days.
`disabledDaysOfWeek: [0, 3, 6]`
[![e83d8246564d523526c4c6bc5a4b7f1b.png](http://tof.cx/images/2018/10/24/e83d8246564d523526c4c6bc5a4b7f1b.png)](http://tof.cx/image/NG7v7)
> [Calendar] Add ability to disable days of week

- src/definitions/modules/dimmer.less
This adds the possibility to use any dimmer only partially and limited only to the overall height of its content and not over the whole to be covered area. This can be used for example as a caption on any element of choice by simply using
`top dimmer`, `center dimmer` or `bottom dimmer`
Works also very well with transitions 'fade up' or 'fade down'
```html
<div class="ui medium image">
<div class="ui active top dimmer">
<div class="content">
<h3>Look!</h3>
ui top dimmer
</div>
</div>
</div>
```
```html
<div class="ui medium image">
<div class="ui center dimmer">
<div class="content">
<h3>Look!</h3>
ui center dimmer
</div>
</div>
</div>
```
```javascript
$('.center.dimmer').dimmer({
transition: 'fade down',
on: 'hover'
});
```
https://github.com/Semantic-Org/Semantic-UI/issues/3459 …
> [Dimmer] Added support for using dimmers only partially on top,center,bottom

- src/definitions/modules/dropdown.less
Items in a simple dropdown within an existing menu cannot be clicked, because the submenu vanishes right before clicking
Sidenote: this PR also fixes wrong comment block header in less file
http://jsfiddle.net/pjga38wv/
Uncomment the CSS Part to see the fix
The right dropdown is the important one.
https://github.com/Semantic-Org/Semantic-UI/issues/2444
https://github.com/Semantic-Org/Semantic-UI/issues/5322
> [Dropdown] Item of 'simple dropdown' in existing menus or 'simple floating' vanish preventing click

- src/definitions/modules/modal.less
Using images within `image content` as suggested in the docs, which are too large, they overlay the modal and the description does not wrap
Original Fix provided by @GammaGames
https://jsfiddle.net/j7qsb24n/
https://github.com/Semantic-Org/Semantic-UI/issues/6636
> [Modal] image content images can go out of content and description does not wrap

- src/definitions/elements/header.less
- src/themes/default/elements/header.variables
Fix [corner icon (SUI)](https://semantic-ui.com/elements/icon.html#corner-icon) does not look like corner in [icon header (SUI)](https://semantic-ui.com/elements/header.html#icon-headers)
https://codepen.io/anon/pen/ajaEaj
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/127635/47613651-a28ff500-dad6-11e8-8721-25ec36321867.png) | ![image](https://user-images.githubusercontent.com/127635/47613661-bf2c2d00-dad6-11e8-9245-664fb391af9c.png) |
https://github.com/Semantic-Org/Semantic-UI/issues/6525
> [Header] Fix corner icon size in icon header

- src/definitions/collections/menu.less
Dropdown item inside `.pointing.menu` or `.secondary.pointing.menu` should not reflect menu item styling.
https://jsfiddle.net/bjup1fd5/
https://github.com/Semantic-Org/Semantic-UI/issues/6463
> [menu] Dropdown inside menu should not reflect menu styling.

- src/definitions/elements/list.less
List style bullets given via `data-value` were ignored on`div` tags because the a) pseudo class was missing and b) nesting was not supported
https://jsfiddle.net/6ohwqmxe/2/
Uncomment the CSS part to see the fix
https://github.com/Semantic-Org/Semantic-UI/issues/5911
> [List] data-value on <div> list items is ignored

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
- Basic Fullscreen Modal had black close icon on black dimmer
- Basic Modal on inverted dimmer had grey borders on action and header
- Basic Modal on usual black dimmer had the borders aswell (although nearly invisible)
- inverted modal on inverted dimmer in small viewports had black close icon on black modal
Before:
After:
Before:
After:
Before:
After:
https://github.com/Semantic-Org/Semantic-UI/issues/5831
> [Modal] Basic Modal and inverted modal on inverted dimmer had wrong close icon color

- src/definitions/elements/icon.less
Remove uncessesary margin so 2 icon in [`.icons`](https://fomantic-ui.com/elements/icon.html#icons) looks center-aligned.
I suppose the margin-right is not much needed, from the commit histories. 
> b21a5669189999fc878f25d6708bfd66abc55b82 | Thu Apr 02 08:23:23 JST 2015 | jlukic | https://github.com/Semantic-Org/Semantic-UI/issues/2046 First pass of grouped icons
It seems just follows `i.icon` definition.
```css
i.icon {
display: inline-block;
opacity: @opacity;
margin: 0em @distanceFromText 0em 0em;
```
http://jsfiddle.net/z2yLmw67/5/
inner/corner icons are slightly right-aligned
https://github.com/Semantic-Org/Semantic-UI/issues/5861
> [Icon] Fix icons alignment

- src/definitions/elements/list.less
- src/definitions/views/item.less
- src/themes/default/elements/list.variables
- src/themes/default/views/item.variables
Inverted variant of Item.
#109
> [Item] Inverted Variant

- src/definitions/views/statistic.less
- src/themes/default/views/statistic.variables
This PR add a `stackable` variation for the `statistics` group, allowing a single statistic per line display on mobile devices.
[![01b9908e0617b839c5bb579c7df21c0d.png](http://tof.cx/images/2018/11/05/01b9908e0617b839c5bb579c7df21c0d.png)](http://tof.cx/image/SMyQN)
#152
> feat(statistic): add stackable variation

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
Add an option `disabledDates` to the Calendar module.
This option should hold an array of `Date` or structured <del>`{date: Date, title: string, message: string}`</del>`{date: Date, message: string}`.
This option allows users to disable the specific date(s) such as national holiday or something like that.
Oct 15, 16 and 27 are disabled.
Oct 27 has CSS-only tooltip to explain why it is disabled.
#200
> [Calendar] Add ability to disable specific date(s)

- src/definitions/collections/form.less
Override `min-width` of `dropdown` inside `field` of `form`, so the dropdown can fit to width of the field.
https://jsfiddle.net/31d6y7mn/117/
#228
> [Form] Dropdown width in form

- src/definitions/elements/button.less
- src/themes/default/globals/site.variables
This PR adds brand colors for WhatsApp and Telegram, and update colors of Twitter, LinkedIn and VK.
Before I update the Instagram colors, we need to discuss if we should use the gradient color scheme or the b/w one, as recommended by Instagram (please see original PR Semantic-Org/Semantic-UI#6153).
#217
> [Theme] Add brand colors and update some

- src/definitions/elements/placeholder.less
- src/definitions/modules/transition.less
The  old generic fix to completely hide a hidden placeholder was disturbing popup position calculations, because offsets for popups now always resulted in top:0,left:0.
This PR reverts #148 and fixes it again directly in placeholder definition
As a side effect the popup position calculations are working as before 2.6.3 again
https://jsfiddle.net/zqfrjso1/7/
#148
#240
https://github.com/Semantic-Org/Semantic-UI/issues/6608
> [Popup/Transition/Placeholder] Old Fix was disturbing Popup position calculations

- src/definitions/modules/dropdown.js
After merging the IE11 focus fix #189 ,the previous merge #190 for Dropdown Menu bubbling was not working anymore, because blurring was taking place all the time now. This is now fixed for both PRs working together. The blurring only takes place when the activeElement is not the search input itself
#189 #190
> [Dropdown] Fix to make PR #189 and #190 work together (Menu list bubbling)

- src/definitions/modules/dropdown.js
When a searchable dropdown allows for user additions and clearable icon, the dropdown trigger was not working after clearing. That's because the general clear-method did not remove the `.filtered` class of all items in that case.
https://jsfiddle.net/gjwLaqem/
https://github.com/Semantic-Org/Semantic-UI/issues/6665
> [Dropdown] Clearing user additions prevented Dropdown List

- src/definitions/modules/dropdown.less
This PR prevents user selection of whole dropdown (as it is done in mostly all other components aswell)
I especially tested this, because i had doubts it might block the search or filter input fields. And they still work fine. :+1: 
Infact, for every `button dropdown` this was already implemented, because `button` sets `user-select:none` by default since ages :slightly_smiling_face: 
Original PR by @chaaya
https://fomantic-ui.com/modules/dropdown.html
- Search Dropdown & Search In-Menu Dropdown already have this applied (cannot mark by mouse, because they are `button`)
- 2nd Search In-Menu is not a button, so you can currently mark everything of it by the mouse
https://github.com/Semantic-Org/Semantic-UI/pull/6629
> [Dropdown] Prevent user selection

- src/definitions/elements/placeholder.less
An image icon withing a placeholder was handled as a normal `image` gaining the wrong height.
https://jsfiddle.net/70q5er49/1/
Change `image` to for example `pdf`to see the current behavior
https://github.com/Semantic-Org/Semantic-UI/issues/6671
> [Placeholder] Respect a possible 'image icon' not occupying the same space

- src/definitions/collections/table.less
__This one needs a bit of explanation:__
The main cause of this bug was introduced in 2014 by https://github.com/Semantic-Org/Semantic-UI/commit/400949ce41a382807e284aec0e3f98601f0421b8
It was related to issue https://github.com/Semantic-Org/Semantic-UI/issues/1510, where it seemed to be fixed but the main cause was the `collapsing` class set to the cell column, which causes the width to be reduced to 1px to force the browser to reduce its width until the main occupied content got the minimum width.
So, this PR actually reverts the fix for https://github.com/Semantic-Org/Semantic-UI/issues/1510 and fixes the main cause correctly now.
Once done, the bug mentioned in https://github.com/fomantic/Fomantic-UI/issues/227 does not appear anymore, because basically max-width:100% is set by …
> [Table] images in tables did not display properly

- src/definitions/elements/placeholder.less
Call `.loadUIOverrides();` in placeholder.less
#255 Semantic-Org/Semantic-UI#6679
> [Placeholder] Placeholder.less doesn't include placeholder.overrides

- src/definitions/modules/search.js
When the api on a search request returns an array it always returned "no results", because it was expecting a json object with a given result-parameter.
This is now easily covered by wrapping the result into an object when the result is an array.
No need to change the `fields.results` parameter (infact, it needs to hold a string, so just omit it while calling the api, so it`s using the default value, but do not set it to false (as suggested by @hammy2899 ))
This way, all of the original search-code remains untouched :smiley: 
The same jsfiddle from @hammy2899 but injecting the fixed search.js directly from the PR-Branch on github :grin: 
https://jsfiddle.net/wka6xsdp/1/
#263
> [Search] Wrap result into object when original result is received as array

- package-lock.json
Change the `event-stream` version in the `package-lock` file since we don't have control over `prompt-sui`.
Refs:
https://github.com/dominictarr/event-stream/issues/116
https://github.com/dominictarr/event-stream/issues/115
#268
> fix(security): changed event-stream version

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
A clearable Dropdown initiated via an existing `select` tag always showed the clearable icon.
Thats because it's unfortunately not possible to either check an empty value via css on a `select` tag and there also is no clear/easy indication for CSS from the generated DOM if any value was selected.
So i added a class `noselection`  which is set to the hidden input/select html element on runtime if nothing is/was selected to be able to easily fetch empty values via css and finally fix the issue :wink: 
In addition i also fixed the cursor for the clearable icon which, on multiple search dropdowns, was set to text, and the indication to click on it was missing.
Same as @prudho but injects the fixed dropdown.js from the github branch :slightly_smiling_face: 
https://jsfiddle.net/zw349kst/1/ …
> [Dropdown] Clearable dropdown initialized with a select always showed remove icon

- src/definitions/modules/modal.js
This PR fixes lots of issues if touchscroll is not working in modals on mobile devices anymore.
All components within modals which are supposed to be scrollable (for example dropdowns) by touchmove were not working because the touch events were cancelled. This behaviour was invented because of background scrolling issues when a modal was opened. I now simply check if the touch event occurs within the modal (were it is wanted) and only cancel the event, when it is outside.
This PR also fixes lost background scrolling if a modal with focussed input was closed having an open mobile keyboard.
To test this, i have prepared a little mobile test suite. Just follow the short mentioned steps there
**Open the following links in a real mobile browser to reproduce the issues and fixes** …
> [Modal] Touch Scrolling (dropdown, content, focussed input) fixed

- src/definitions/elements/input.less
- src/themes/default/elements/input.variables
This PR supports `corner label` and `icon` for `textarea` when using the `input` class
All possible features can be seen here
- left/right corner label
- left/right icon
- both in combination
http://jsfiddle.net/0pske8u1/1/
#276
> [Input, Textarea] Support for corner label and icon in textarea

- src/definitions/collections/message.less
`compact icon message` still had 100% width. Fixed by adding `auto`
http://jsfiddle.net/95kzk6mr/2/
https://github.com/Semantic-Org/Semantic-UI/issues/4759
https://github.com/Semantic-Org/Semantic-UI-React/issues/2280
> [Message] fixed compact icon message width

- src/definitions/modules/dropdown.js
When the remoteApi was used in a dropdown to retrieve the items according to some searchterm, the list of items was always renewed, but already selected items from the previous list where not filtered again, so they appeared again.
- Click the dropdown and select anything you want 
- close the drop down, reopen it by clicking into it again
-  The same values incuding the previously selected ones are listed again
https://jsfiddle.net/e1onupd6/8/
- Each new list does not contain the already selected ones anymore
https://jsfiddle.net/e1onupd6/9/
https://github.com/Semantic-Org/Semantic-UI/issues/6388
> [Dropdown] Filter already selected items when using remote api as datastore

- src/definitions/behaviors/form.js
- src/definitions/modules/dropdown.js
This is due to the use of jquery's `.filter` or `.find` dom selector mechanism
FUI already implemented an escaping function to mask special characters, but some of them were missing.
I also slightly optimized the `get.field` function to not quering the dom twice. Might be just a few milliseconds, but every performance optimation counts :laughing: 
https://jsfiddle.net/h6sxdr1f/
https://jsfiddle.net/h6sxdr1f/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6701
> [Form, Dropdown] Formvalidation broke when id has colon in it

- src/definitions/modules/dropdown.js
If a menu with submenus was too narrow to the bottom of the screen, the submenu positioning was broken making the dropdown unusable
Thanks to @sillicon for the original PR
http://jsfiddle.net/47wtpcy8
http://jsfiddle.net/47wtpcy8/2/
#194 
https://github.com/Semantic-Org/Semantic-UI/issues/6007
https://github.com/Semantic-Org/Semantic-UI/issues/3505
https://github.com/Semantic-Org/Semantic-UI/issues/6700
> [Dropdown] Fixed Submenu positioning

- src/definitions/modules/dropdown.js
When a datastore has a different name for the `value` field, all probably preselected values will not be assigned initially to the dropdown. That's because it was always expecting its name being called `value` instead of respecting a probably changed name in `settings.field.value`.
Thanks @patilkiranm for the original PR
https://jsfiddle.net/pf2ae8cn/
https://jsfiddle.net/pf2ae8cn/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6682
> [Dropdown] Preselected values are ignored when data has individual value-name

- src/definitions/modules/modal.js
Trying to close a modal by clicking in the dimmer area but having `return false` at the `onHide`-Method did still close the modal if `allowMultiple` was set to true
https://jsfiddle.net/ibelar/h8a3se4o/
https://jsfiddle.net/bagwd05n/
#284
> [Modal] Dimmer-Click closed Modal when allowMultiple=true even if onHide()=false 

- src/definitions/behaviors/api.js
- src/definitions/behaviors/form.js
- src/definitions/behaviors/state.js
- src/definitions/behaviors/visibility.js
- src/definitions/globals/site.js
- src/definitions/modules/accordion.js
- src/definitions/modules/calendar.js
- src/definitions/modules/checkbox.js
- src/definitions/modules/dimmer.js
- src/definitions/modules/dropdown.js
- src/definitions/modules/embed.js
- src/definitions/modules/modal.js
- src/definitions/modules/nag.js
- src/definitions/modules/popup.js
- src/definitions/modules/progress.js
- src/definitions/modules/rating.js
- src/definitions/modules/search.js
- src/definitions/modules/shape.js
- src/definitions/modules/sidebar.js
- src/definitions/modules/sticky.js
- src/definitions/modules/tab.js
- src/definitions/modules/toast.js
- src/definitions/modules/transition.js
jquery deprecated lots of methods. 3 of them are used widely in FUI. This PR prepares to work with a future jquery Version where those functions were removed.
You can also see this PR as a little step towards independency of jquery :slightly_smiling_face: 
- `$.isArray` is replaced by native `Array.isArray`
- `$.isFunction` and `$.isWindow` statements are adopted from jquery (the same wrapper as before, but put in FUI if not found in jquery)
> [Global]: Remove deprecated jquery functions 

- src/definitions/behaviors/visibility.js
Rename the placeholder class to constraint to stop the conflict with the placeholder component
Broken: https://jsfiddle.net/djpw7ket/
Fixed: https://jsfiddle.net/yge5fm2c/
Broken:
Fixed:
#296
> [Visibility] rename placeholder class

- src/definitions/modules/dropdown.js
- src/definitions/modules/search.js
This PR sanitizes the probably fetched and vulnerable HTML Data for dropdown user additions aswell as for search response values.
For `search` an additional option `preserveHTML` (default `true`) (adopted from dropdown where this is already available). When this is set to `false` every result value from the response stream will be sanitized in the default templates.
unfixed dropdown 
https://jsfiddle.net/9x8tqdam/
fixed dropdown
https://jsfiddle.net/9x8tqdam/1/
To test search you need to setup something locally to fake evil remote api data:
```html
<div class="ui search">
<div class="ui left icon input">
<input class="prompt" type="text" placeholder="Search GitHub">
<i class="github icon"></i>
</div>
</div>
```
Initialize the search specifying a url which points to some evil prepared …
> [Search,Dropdown,XSS] prevent JS execution from manual entries or untrusted remote data

- src/definitions/modules/checkbox.js
Changing Radio-Button Selections via Cursor Key-Navigation was not triggering the onChange Event
- Click an option of the Radio Button Group
- User cursor keys to switch between the options
- Message is not updated, because onChange event is not fired
https://jsfiddle.net/n9sLf81w/
- Message gets updated just as you would have clicked on another option
https://jsfiddle.net/ujkdreqs/
https://github.com/Semantic-Org/Semantic-UI/issues/6676
> [Checkbox] Support onChange for cursor keynav

- src/definitions/modules/dropdown.js
The PR #287 to filter remote dropdown values with already preselected values was broken when the dropdown was initiated out of a div-tag and resulted in console error, because those dropdowns use input-fields, thus strings for storing selections. Select-fields, which was used in the PR, stored value are retrieved as arrays where it was working before.
This PR now takes care of that and always generates an array, making the functionality work for all types of dropdowns now. 
#287
> [DropDown] Filter Preselected entries from #287 was not working for div-dropdowns

- src/definitions/modules/modal.less
When a modal had `allowMultiple:true` set, the top border radius was not set anymore.
This regression happens since an additional dimmer was introduced in #119 to prevent the ability to interact with modals that are not the focused one.
This PR now takes care of a possible existing extra dimmer and shows top border radius correctly again
Comment out the CSS Code to see the issue
http://jsfiddle.net/co3gaj8q/
#308
> [Modal] Fix top border radius when allowMultiple is true

- src/definitions/modules/dropdown.js
When a remoteApi returns no results according to the search query, the dropdown was still showing the previous filtered list when `filterRemoteData` was false (which is default)
Also fixed the behavior in combination that "no results" prevented possible allowed useradditions. So if `allowAdditions` is true, then "No results" will not be shown (this is how it already behaves when remote Api data was not used)
> **Hint**:  If you try to test the `allowAdditions:true` feature in the following fiddles and it does not work, then jsdelivr still caches an old commit. If in doubt, tell me, i'll put the whole JS in the fiddle then)
- Follow the 2 steps in the fiddles
https://jsfiddle.net/c092thvs/
https://jsfiddle.net/c092thvs/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6603
> [Dropdown] Show "no results" when filterRemoteData is false and response is empty

- src/definitions/elements/loader.less
- Elastic Loader in dropdown/input misses correct color setting in :before tag.
- Also changed the static `@grey` or `@white` variables to the loader specific variables `@loaderLineColor`and `@invertedLoaderLineColor` instead. Infact the color is the same on the default theme, but using the loader specific variables is now more safe regarding the new central color mixin usage from #261 
https://fomantic-ui.com/modules/dropdown.html#loading
https://fomantic-ui.com/elements/input.html#loading
Comment out the css part to see the issue again
http://jsfiddle.net/015dbk4t/1/
2.7.0
> [Dropdown, Input, Loader] Elastic Animation Style had wrong color

- src/definitions/elements/button.less
Buttons in menu items had its own font-size assigned via @buttonSize . If somebody now wants to have smaller or higher buttons  somewhere by adding any of the button size classes (like `mini`), it does not work.
https://jsfiddle.net/bfojrmqs/
Remove the CSS Part to see the isse (both buttons are the same size then and `mini` is ignored)
https://github.com/Semantic-Org/Semantic-UI/issues/5374
> [Button] Increased size specificity to work with menu item buttons

- src/definitions/elements/list.less
When adding  the `loading` class to an icon in a list item, the entire icon rotates around a wrong point rather than rotating about it's own center.
http://jsfiddle.net/pn75L2tj/
- first list item shows the issue
- second item is fixed
- third one is normal item without loading class (to show alignment)
https://github.com/Semantic-Org/Semantic-UI/issues/6717
> [List,Icon] List Item Icon Rotates Around Wrong Point when using Loading class

- src/definitions/elements/input.less
In addtion to the enhancement from @prudho , this PR also adds support for input action buttons being surrounded by the error border
https://jsfiddle.net/o0c6mk6u/2/
https://github.com/fomantic/Fomantic-UI/pull/270
https://github.com/Semantic-Org/Semantic-UI/issues/5670
> [Input] Support error class on input action buttons

- src/definitions/collections/menu.less
- src/definitions/elements/label.less
Menu Item Labels have a different default color (darker grey) than normal labels. To not interfere with the new dynamic colors, which do not use `!important` anymore, i originally (in #230) had to add  `:not({color})` statements for each color to the menu item label.
Now, having implemented the dynamic color system #261, this, still hardcoded, part of `:not()` had to be removed from menu item labels to fully support individual color maps. Thus an increase of specificity for the labels was needed.
http://jsfiddle.net/7hp8m5og/
> [Label] Remove hardcoded color exception "not()" for menu item labels

- src/definitions/collections/form.less
- src/definitions/elements/segment.less
- src/themes/default/collections/form.variables
- src/themes/default/elements/segment.variables
When a form or segment is inverted, the `loading` class is still styled as for normal variants (white dimmer).
This PR now shows a black dimmer for inverted forms/segments with white loader color.
It also removes a bug where any textual segment content was completely invisble.
http://jsfiddle.net/zvs0fmh3/
Remove CSS to see previous behavior
https://github.com/Semantic-Org/Semantic-UI/issues/5656
> [Form,Segment] Inverted variants should get inverted loader properly

- src/definitions/collections/menu.less
- src/definitions/modules/dropdown.less
A simple dropdown in a vertical menu had wrong positioning, thus nearly unusable.
Also a submenu had second submenu dropdown icon misplaced
http://jsfiddle.net/Lnba5udj/1/
The fix cannot be applied directly in the fiddle CSS here, because you need to remove the !important flags from the original library manually in the debugger console (which i did for testing and below screenshot)
I added the JS-Dropdown Menus in the fiddle to test and make sure the changes do not affect non-simple dropdowns.
https://github.com/Semantic-Org/Semantic-UI/issues/5454
https://github.com/Semantic-Org/Semantic-UI/issues/5657
> [Dropdown] Fix simple dropdown positioning in vertical menus

- src/definitions/collections/menu.less
Wrong specificity and missing `pointer-events:none` for disabled items in inverted menus. 
https://jsfiddle.net/216r43ep/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6581
> [Menu] Corrected support for disabled items in inverted menus

- src/definitions/collections/menu.less
`icon menu` should always have its width getting auto calculated by the size of their icons and/or labels. This is basically already the case unless somebody adds any size like `mini` to the icon menu. The menu would get a fixed width then which does not really look right.
http://jsfiddle.net/joe2ks5w/2/
Remove the CSS Part to see current behavior
https://github.com/Semantic-Org/Semantic-UI/issues/5607
> [Menu] Keep auto width for icon menu sizes

- src/definitions/elements/icon.less
- `disabled` and `link` icon(s) at the same time ignored the `disabled` setting
- icon**s** (grouped) did also not work everywhere with those settings
- some CSS pseudoclass settings were wrong (for example `.hover` instead iof `:hover`)
- unnecessary `!important` values removed (which also partially caused the issue)
https://jsfiddle.net/vnmgt6y9/3/
from original SUI Issue
https://jsfiddle.net/akym370t/
Because of the `!important` removements in the PR i prepared a similiar testcase having the same CSS settings given
https://github.com/Semantic-Org/Semantic-UI/issues/5694
> [Icon] Make "link" and "disabled" work together correctly

- src/definitions/modules/search.js
When a type: "category" search box contains a category without results, incorrect items are passed to onSelect.
This was caused by wrongly increasing the categoryIndex on `module.inject.id` when no result was given for a category.
- enter 2 characters in the searchbox to trigger the search
- select the last entry  "fourth"
- The unfixed version shows "second", while the fixed one correctly shows "fourth" in the input field below the searchbox
http://jsfiddle.net/3n85jcpp/1/
http://jsfiddle.net/3n85jcpp/9/
https://github.com/Semantic-Org/Semantic-UI/issues/5508
> [Search] Results with empty categories caused onSelect to return incorrect item

- src/definitions/elements/icon.less
- src/definitions/elements/step.less
Add size variation of icon in steps Module.
Default (medium for icon) is not changed.
I initially tried adding `.ui.steps .step > .icon.medium { icon-size: @medium; }` but it displays the icon for Medium. Therefore, icon cannot be medium (1em).
https://jsfiddle.net/nc0up8oz/
https://jsfiddle.net/djm15ybh/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6441
> [Steps] feat(steps): Icon size variation

- src/themes/default/elements/header.variables
This PR sets the default background color for `inverted attached header` to the same as it already is for `inverted attached segment` or `inverted attached menu`
http://jsfiddle.net/9hhkqwf8/2/
Remove CSS to see previous behavior.
https://github.com/Semantic-Org/Semantic-UI/issues/5435
> [Header] Attached inverted variant should have same background color as other inverted components

- src/themes/default/modules/popup.variables
Tooltip popups had wrong z-index making checkbox slider shine through.
https://jsfiddle.net/gcp8od1s/1/
https://github.com/Semantic-Org/Semantic-UI/issues/5069
> [Popup] A Popup should have a higher z-index than a checkbox’s pin

- src/definitions/elements/list.less
- src/themes/default/elements/list.variables
Ordered list has conventionally dot or something after the end of counter like
> 1. 2019
> 2. 2018
> 3. 500px
But SUI/FUI's ordered list does not follow the convention and omit dot.
This may lower readability specially when list item starts with number (below example).
> 1&ensp;2019
> 2&ensp;2018
> 3&ensp;500px
So This PR 
* Add `.suffixed.ordered.list` variation that add the dots.
* Add LESS variables that allows developers to change separator and suffix like '1-2.' or '1.3)'.
https://jsfiddle.net/Lsawqmj6/
https://jsfiddle.net/fso94dmx/1/
https://github.com/Semantic-Org/Semantic-UI/issues/4738
> [List] Add suffixed ordered list variation

- src/definitions/elements/loader.less
- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
When a modal also had loaders used, these got the wrong default color (white if dimmer of modal was black, so white color on white modal background was...uhm..white :rofl: )
I fixed this now for every combination of dimmer and modal
Also fixed unnessary css settings and missing color in inverted modal action (came across this while testing the original SUI issue)
http://jsfiddle.net/o92qen2j/10/
In every Modal there is a inline loader in the actions section which is not visible if the fix is not applied
Remove CSS to see the original issue again
https://github.com/Semantic-Org/Semantic-UI/issues/4014
> [Loader,Modal] Default Loader color settings in Dimmers had impact on loaders in modals

- src/definitions/modules/dropdown.js
In case a dropdown should be initiated out of a `select` -tag, the html was created via a template. This template however did not use classname settings from the `settings.className` property list, but had them hardcoded instead.
Given a very (very! :rofl:  ) simple example
Two dropdowns, one from  select, one from div:
```html
<select class="ui dropdown"></select>
<div class="ui dropdown"></div>
```
Both initiated by
```javascript
className : {
menu: 'custom-hint-box menu',
selection: 'custom-select'
}
});
```
In the DOM Inspector you will recognize the difference: The className setting is not applied to the dropdown made out of the select-tag
https://github.com/Semantic-Org/Semantic-UI/issues/3603
> [Dropdown]: Template for select-dropdown did not use classname-property from settings

- src/definitions/collections/menu.less
- src/definitions/elements/label.less
- src/themes/default/collections/menu.variables
Images in `image label` had wrong height when they were used within a menu item.
http://jsfiddle.net/n75faL4y/8/
https://github.com/Semantic-Org/Semantic-UI/issues/5247
> [Label] Adjust image height of image labels in menu items

- src/definitions/collections/table.less
Table fixes:
- on `striped` tables any additional color like `error` on rows were ignored
- `definition` tables still had their column color set when stacked
- rows on `selectable`, `basic`, `striped` tables did not work everytime
- some single color cells on those tables had their background lost
That is now fixed by proper specificity.
> Btw, all of above issues are still the case in SUI 2.4.1, they are not related to the dynamic color PR, nor the `!important` removements we implemented in FUI 2.7.x
http://jsfiddle.net/nv6q8d5e/
https://github.com/Semantic-Org/Semantic-UI/issues/5318
> [Table] Make colors work on striped, basic, selectable, stacked, definition

- src/definitions/modules/sidebar.js
The `closable` setting is ignored in sidebar when the setting was changed after initialization.
- Keep the red sidebar open
- Click on "Fix sidebar"
- Click on "Toggle sidebar"
-> Sidebar should not close
https://jsfiddle.net/r7fws0nn
https://jsfiddle.net/r7fws0nn/23/
https://github.com/Semantic-Org/Semantic-UI/issues/5329
> [Sidebar] Respect a change of closable setting

- src/definitions/elements/button.less
- src/definitions/elements/icon.less
- src/themes/default/elements/button.variables
A `loading icon` within a button was rotated around a wrong anchor position (similiar to the Fix in #336 )
- The positioning is corrected
- It is now also supported in `labeled icon button` (a loading spinner was rotating the background sqare before if you tried it)
Due to the fixes you are now finally able to correctly use loading icons in buttons together with text by either using `labeled icon button`or just `icon button`.
After fixing it, the used `notched circle icon` used in the fiddle still looked slightly misaligned. It turned out this is due to the icon in FontAwesome itself not being centered accurately.
To proove this, i added an example in the fiddle below where you can obviously see it. The 100% circle background stays fixed while the spinning icon does not precisely although …
> [Button, Icon] Loading icon Position in Button was not rotating around center

- src/definitions/elements/loader.less
Firefox does not support `inherit` in animation keyframes for `border-color` (it should inherit from color, which is indeed working in firefox but **not inside keyframes** 😭 )
All other browsers do support this also in keyframes (but those do not support `currentColor` in keyframes for `border-color` instead 🙄 ).
As there is no vendor specific `-???-border-left-color`, i had to double the animation sequence for `-moz-animation` only. Most clean solution (and prepared in case any other browser might change their behavior also (which i doubt 😉 )
http://jsfiddle.net/a5gt6nc9/2/
Fiddle works everywhere, also in Firefox now. Remove the CSS to see the issue in Firefox
2.7.1
> [Loader] Elastic Loader was not working in Firefox

- src/definitions/collections/menu.less
- src/definitions/elements/segment.less
`secondary` is part of the new  central dynamic color map from #316.
Unfortunately there already was `secondary segment` and `secondary menu` available, but not meant as color variant resulting in different visual behavior as before.
To stay backward compatible, i simply removed `secondary` from the color creation loop in `segment` aswell as `menu`. For all other colorizable elements `secondary` is still available (as it is a new feature since 2.7.0)
I also removed `primary` for color creation in `segment` because it was also separately supported previously (even if not documented)
I kept `primary` for color creation in `menu` because it had no separate support before.
Tell me, if i should remove this for menu aswell
#364 
2.7.1
> [Segment, Menu] "secondary segment" or "secondary menu" have a different meaning

- src/definitions/modules/dropdown.js
Because of the XSS sanitizing in 2.7.0, all values used in the template were expected to be strings. 
This is now fixed by casting the value into a String before. 
https://jsfiddle.net/ibelar/qf1b5yn8/
https://jsfiddle.net/s0qat1vh/
#379
> [Dropdown] Cast to String before rendering if value is an integer

- src/definitions/collections/menu.less
An `inverted secondary pointing menu` had a border set around the whole menu instead of only at the bottom as in the non-inverted variant. This was definately wrong (copy/paste) behavior, because the border-color class was doubled and had the non-inverted variable `@secondaryPointingBorderColor` instead of `@secondaryPointingInvertedBorderColor` set (which is again done one class definition later)
I guess in those (probably rarely used) cases where this combination was used, it was used with a black background, where the border was very hard to recognize. In a whole: It simply looked wrong and inconsistent to the non-inverted variant.
Additionally I also fixed the missing `inverted` color loop to omit the `secondary` value just like in #366 because `secondary` is used with a different …
> [Menu] Wrong Border for inverted pointing menu removed and fix for secondary as color

- src/definitions/collections/menu.less
- src/themes/default/collections/menu.variables
Putting an inline label for some, but not all menu items in a `secondary pointing menu` breaks the vertical alignment.
I labeled this as a bug rather than an enhancement as it was in the original SUI issue.
http://jsfiddle.net/mgy37rw5/
https://github.com/Semantic-Org/Semantic-UI/issues/5959
> [Menu] Labels in secondary pointing menu items were misaligned

- src/definitions/behaviors/form.js
- If the first option of a radio group was disabled the whole validation of that group was skipped
- Additional fix: `is empty` always returned `false` for empty radio button groups
- I also removed unnecessary sets of `fieldValid=true`..because it is initially `true` in all cases anyway
Follow the short info in the fiddles (TL;DR: press both buttons :smile: )
https://jsfiddle.net/u2abzw3r/1/
https://jsfiddle.net/u2abzw3r/2/
https://github.com/Semantic-Org/Semantic-UI/issues/6511
> [Formvalidation] Radio buttons do not validate if the first is disabled

- src/themes/default/modules/dimmer.variables
Thanks to @mayfield for the Fix (me being a lazy dude kindly copied parts of his issue text :smile: here)
>For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
>The use of a filter CSS property will impose z-index stacking rules for an element. As such, when using a blurring modal dimmer there are side effects left over from having a filter property on the non-dimmed content. 
>This leads to unexpected stacking behavior for elements that would otherwise not have z-index stacking rules applied to them. One example being the use of menus with dropdowns following the open/close of a blurred modal.
http://jsfiddle.net/ncoa89yf/2/
- Remove the CSS and open the top dropdown to see the issue
- use the button to proove the …
> [Dimmer] blurring dimmable leaves z-index stacking side effects

- src/definitions/modules/dropdown.js
When dropdown list has an entry with given value "0", is is not selectable via `set selected` method
In the code, there already was a triple equal check, but this made a real 0 invalid resulting in always comparing String to Number (which of course is false)
http://jsfiddle.net/budiadiono/fcsbashq/1/
http://jsfiddle.net/g0f7y9pq/
https://github.com/Semantic-Org/Semantic-UI/issues/5354
https://github.com/Semantic-Org/Semantic-UI/issues/5638
> [Dropdown] Allow a real zero to be a selectable value in 'set selected'

- src/definitions/elements/label.less
`link` icons which are contained within a `corner label` do not have the desired effect of setting `cursor:pointer`. 
This is a regression since 2015 by https://github.com/Semantic-Org/Semantic-UI/commit/958848847cd39e1efc8e69bcd06db067d3e277d5
The original intention to set `cursor:default`  was to prevent mouse selection (according to the commit message). However i was not able to reproduce this behavior :thinking: , maybe it was a  special browser fix.
To be save with this intention and still support the `pointer` if the label was created using an `a` tag, i changed the value to `inherit` instead. 
https://fomantic-ui.com/elements/label.html#corner
https://github.com/Semantic-Org/Semantic-UI/issues/4238
https://github.com/Semantic-Org/Semantic-UI/issues/5299 …
> [Label] Link icon cursors in corner labels did not work

- src/definitions/elements/step.less
A huge amount of steps were overflowing the viewport if the amount of steps was not explicit given as classname. It was already intended to wrap (a single step already got `flex-wrap:wrap`), but it was missing for grouping by using `steps`.
This is ignored when `unstackable steps` is used because a possible overflow is wanted behavior.
If a step amount is given to the group (`six steps`), the behavior stays as before: Each step will reduce itself to stay inline. (Also part of the testcase below)
http://jsfiddle.net/v8yrgs6t/
https://github.com/Semantic-Org/Semantic-UI/issues/4880
https://github.com/Semantic-Org/Semantic-UI-React/issues/1114
> [Step] make steps wrap by default as intended for single step

- src/definitions/elements/label.less
This PR is based on https://github.com/Semantic-Org/Semantic-UI/pull/6210 by @w96k.
* Add `icon label` variation that allows to put an icon without text.
* Add `right icon label` variation that allows to put an icon in the right side of label with correct margin. 
* Add `left icon label` variation to let `delete icon` and `close icon` be placed in left with correct margin for backward-compatibility
* ~Add `hoverable` class that makes icon to be used for action, as same style as current `close`/`delete` icon have.~
https://jsfiddle.net/oLc3pqeu/
https://jsfiddle.net/y4L7cadb/
#222 
https://github.com/Semantic-Org/Semantic-UI/pull/6210
https://github.com/Semantic-Org/Semantic-UI/issues/5328
https://github.com/Semantic-Org/Semantic-UI/issues/5446 …
> [Label] Right icon should have correct margin when placed after text

- src/definitions/elements/input.less
In a `form`, every `inverted transparent input` had a black color making it useless on inverted backgrounds. A simple increase of specificity fixed it :laughing: 
In Addition `textarea` is now also supported the same way
http://jsfiddle.net/dopLac92/3/
https://github.com/Semantic-Org/Semantic-UI/issues/3597
> [Input] Make inverted transparent input in forms appear white

- src/themes/default/modules/popup.variables
Changed the tooltip `z-index` to be the same as standard popup which forces it to appear on top of other components such as sticky elements.
https://jsfiddle.net/95f1wmL8/
#394
> [Popup] correct tooltip z-index value

- src/definitions/collections/menu.less
using a `secondary pointing menu` together with a color was still showing the default colors of a `secondary menu` because of too low specificity
https://jsfiddle.net/uvg6e4af/
The fiddle cointains the inverted variant aswell which also includes the fixes from #380
#406
> [Menu] Increased color specificity to override secondary menu default colors

- src/definitions/modules/dropdown.js
While discovering #383 it turns out, the `delete` icon is hardcoded in the template for labels.
Although you are able to change the selector for this via settings, you cannot for the icon class itself, but would have to provide the whole template for labels instead, just to be able to use another iconname
This PR changes the label-template to fetch the classname for the delete icon from the settings instead
#383
> [Dropdown] Use delete icon classname from settings instead of having it hardcoded

- src/definitions/elements/label.less
If a `floating label` had whitespace inside, especially when including icons, it did not stay inline. This happens for every whitespace.
To make it still look consistent even if the label content is a bit larger, i also made the label centered to the top right corner of the parent element, 
http://jsfiddle.net/k1qp7dgv/3/
https://github.com/Semantic-Org/Semantic-UI/issues/4217
https://github.com/Semantic-Org/Semantic-UI/issues/4155
> [Label] Content in floating labels should not wrap whitespace

- src/definitions/elements/text.less
- src/themes/default/elements/text.variables
Added support for `text` sizes. The same as for `icon` to have the same flow
https://jsfiddle.net/dehuotga/
#413
> [Text] Added sizes identically to icon

- src/definitions/behaviors/form.js
If a form uses array inputs by appending brackets to their names ( `name="myfield[]"`) the validation on those fields was always done for the whole field group. Means, if the first field was valid, it validated for the whole group which is wrong.
This behavior is now fixed, so even if multiple input fields have the same name to act as array inputs, the validation is done on each field separately and also the error class is set/removed to each field individually.
@prudho was already providing a [PR for that in SUI](https://github.com/Semantic-Org/Semantic-UI/pull/6370) some time ago, but the individual error display handling was missing there.
> Hint: If you ask yourself while reviewing, why i added an `internal` parameter to the `add.prompt()`and `validate.rule()` functions: This is to …
> [Formvalidation] Input array validations should respect each single field on its own

- src/definitions/modules/accordion.js
- src/definitions/modules/transition.js
Transition did always detect "block" as display value and did not respect or remembered an initial given inline block style which was probably wanted by the user. For example `inline` or even `none`, if an element within a transition should definately not be shown. 
Not only because of this, but it was also displaying `script` or other unwanted tags :roll_eyes: 
`script`, `link` or `style` tags are now skipped all the time.
Especially for accordion it turns out to be usefull that transition should be skipped if the item has initially been set to be hidden. This is true in most cases for the to be animated element itself, but in an accordion there could be some elements within the container where those elements should be kept hidden.
Therefore i added a new setting
```javascript …
```
> [Transition] Remember inline style display and dont show hidden objects like <script>

- src/definitions/modules/progress.js
- src/definitions/modules/progress.less
- src/themes/default/modules/progress.variables
When using `progress` 
Trying to display "0%" was not recognized when given as a `data-percent` or `data-value` attribute. 0 was recognized as "false", thus it was not displayed at all.
Even when 0% was displayed (using JS), the progressbar already has increased to 2em, because this is set as min-width. Reason because of this is obviously to force the percentage display any time, as the text is inside the bar and would vanish if the bar itself would had a width of 0%. 
To still show "0%" but also have the bar disappear to definately show zero progress, the background color is now simply transparent when the value is 0%. Percentages >0% will show the progressbar as before.
If the progress was `inverted indicating` the label below the bar was set to black. Simply because there wasn't a …
> [Progress] Fix 0% display and  "inverted indicating" label color 

- src/definitions/behaviors/form.js
Using a custom rule for a radio button to validate against a given value of each radio was not working because the value was always taken from the first radio button of the group.
This is now fixed to supply the individual value from the actually checked radio button.
https://jsfiddle.net/3568sfau/
https://jsfiddle.net/3568sfau/1/
Taken from the fiddles above: After Validating the received value is displayed underneath the button.
Always receives "yes", regardless which radio button was checked:
Correctly receives "yes" if the first radio button is checked and receives "no" when the second radio button is checked:
https://github.com/Semantic-Org/Semantic-UI/issues/6194
> [Validation] Supply checked radio value to custom rule

- src/definitions/modules/progress.less
Progressbars which have not been initialized by javascript or don't have the `data-percent` attribute set (which will be set on initialization) still showed the min-width progressbar background.
https://jsfiddle.net/ba51wkjm/
#424
> [Progress] Don't show min-width progress bar when module was not initialized

- src/definitions/modules/modal.js
The `onDeny` and `onApprove` events were only called once and never again, in case `onHide` returned false preventing the modal to be closed.
I decided against calling the given callback function (which would have fixed it in that case also), but the callback is basically unknown in general and `hide` could also be called as a behavior from outside where probably given callbacks are not supposed to be called also in case the modal was denied to be closed.
- Click on the 'No' Button of  the modal, An alert message appears
- Click again. It does not work anymore
https://jsfiddle.net/0sqk6yhx/
- Click again. It does work all the time
https://jsfiddle.net/7gs90uqc/
https://github.com/Semantic-Org/Semantic-UI/issues/5558
> [Modal] Reactivate approve/deny event handling if onHide returned false

- src/definitions/elements/segment.less
Added `stackable` variant to `horizontal segments` to make those segments wrap if needed
http://jsfiddle.net/tmxLgno1/2/
Remove CSS to see usual behavior without stackable support
> [Segment] Introducing stackable horizontal segments

- src/definitions/modules/checkbox.js
The keypoint here is, that this PR basically fixes a very old behavior in SUI:
According to the docs the behaviors `set checked|unchecked|enabled|disabled|determinate|indeterminate` are not supposed to run callbacks. But they actually always did (!) They ever since triggered the `change event`, but it never had any impact, just because the module itself did not have any `onChange` event until #295
That said, in conclusion the onchange event was now called twice: In the `set` methods aswell as in the `module` methods. :disappointed:  The onChange event has to be kept, otherwise the keynav will not notify any change to the event system, so i removed the (wrong) event triggering in the above mentioned behavior functions and put them outside instead.
In addition i also hotfixed #295, because …
> [Checkbox] Call onChange only once and dont at all on "set checked" (and others)

- src/definitions/elements/icon.less
This PR increases color specificity, so icons in links of a `list item` won't be overridden by the default grey
http://jsfiddle.net/qy3ptbka/1/
#436
> [Icon] Increase color specificity

- src/definitions/modules/modal.js
As mentioned in https://github.com/fomantic/Fomantic-UI/pull/431#issuecomment-458141837 by @ko2in, a modal gets closed when a webkit-custom scrollbar of the dimmer has been dragged
It seems to be only happening on webkit because of the custom scrollbar. The event system still recognizes the dimmer as target.
The new option `scrollbarWidth` by default has the same value as the `@customScrollbarWidth` value from `site.less`. I initially wanted to calculate the scrollbar-Width at runtime via javascript, but it turns out this is not possible, because webkit does not return a width difference if a custom scrollbar is used. (that probably also the reason why the event still receognized the dimmer when clicking on the scrollbar)
I think, using the same value as the webkit scrollbar width is the …
> [Modal] Prevent closing the modal when webkit scrollbar has been dragged

- src/definitions/views/card.less
Whenever a bottom attached button was used in cards and the card itself had a color, there was always a small 1px blurry grey box-shadow background left, which made it look a bit disturbing. See screenshots
https://jsfiddle.net/gome0xvc/1/
#454
> [Card] Bottom attached colored buttons left blurry grey bottom line

- src/definitions/modules/progress.less
The background fix from #412 only works when the progressbar does not have a fixed color class assigned :cry: 
https://jsfiddle.net/x6fyp5he/
```html
<div class="ui red progress" data-percent="0">
<div class="bar"></div>
</div>
```
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/52270014-fd3fb500-293f-11e9-8548-ee71d288fc52.png)|![image](https://user-images.githubusercontent.com/18379884/52269984-e600c780-293f-11e9-8878-2daf3db6a05a.png)|
> [Progress] Fix 0 percent bars on colored progress

- tasks/docs/build.js
When building docs the metadata.json was not written to disk anymore.
fomantic/Fomantic-UI-Docs#94
> fix(build): write metadata.json for docs

- src/definitions/modules/transition.js
This PR fixes a regression since #357. All transitions made out of elements being invisible by an inline style `display:none` were not working correctly anymore. 
The subheader of the title should animate by the `drop` transition
http://jsfiddle.net/q2u0hjy1
http://jsfiddle.net/bc5hgv9j/1/
> [Transition] Transitions made of hidden inline style elements were not animated correctly anymore

- src/definitions/modules/shape.less
Shape Transition was not working when another element within the current shape side also had some other transition set (like  a `loading button` or simply a `icon button` (because icon buttons have opacity transition set!))
Remove CSS to see issues
http://jsfiddle.net/0yf8hvm1/ (loading button)
https://jsfiddle.net/b8gpmjtx/ (icon button)
https://github.com/Semantic-Org/Semantic-UI/issues/2860
https://github.com/Semantic-Org/Semantic-UI/issues/4782
> [Shape] Transition did not work when child element also had a transition set

- src/definitions/views/card.less
An inverted card did not support any color. It was always overridden by the default inverted gray.
https://jsfiddle.net/3sjmfoew/
#454
> [Card] Support inverted colors

- src/definitions/modules/sidebar.js
This PR fixes a misunderstood meaning of `closable` implemented in #335 
The `closable` setting should only have effect on clickAway events, but a sidebar should be closable all the time when triggered via any behavior call as stated in the docs.
- Click "Open" to open the sidebar
- Click "Close" (top left in the sidebar..hard to see, because its black...sorry)
- ...
... it does not close
http://jsfiddle.net/xqtb1pw0
.. it does (but does not when clicking in the pusher area as expected)
http://jsfiddle.net/pw2xfs3v/
#467
> [Sidebar] Make closable only work in clickaway event as stated in the docs

- src/definitions/elements/segment.less
`inverted`, `secondary` or `tertiary` segment was not working inside of `horizontal segments` group
Because the reason for this is an unnecessary background-color property (obviously copy/pasted when it was introduced in 2015 by https://github.com/Semantic-Org/Semantic-UI/commit/6258196a97a485db5800c4000a8015c535d942b1 ) , it cannot be simply removed in a fiddle by another css class, so you have to manually remove the property in chrome developer tools to see the fix (See screenshot below for better explanation proof) I could not find any reason why the segment itself inside a horizontal segment group should have an explicit transparent background set. It only makes sense for the segment group.
http://jsfiddle.net/hoqmxbka/
https://github.com/Semantic-Org/Semantic-UI/issues/3587 …
> [Segment] Fix  support for inverted, secondary or tertiary in horizontal segments

- src/definitions/elements/segment.less
The `clearing` segment used the usual clearfix-method with a :after pseudo element.
However `piled` and `stacked` segment used the :after element aswell to display their effects.
The clearing class has now been adjusted so it works together now
http://jsfiddle.net/c8nk90jv/3/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/52676640-18f02000-2f2b-11e9-9119-083320f766d7.png)|![image](https://user-images.githubusercontent.com/18379884/52676650-24434b80-2f2b-11e9-8bfc-445d602bcec4.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/4865
https://github.com/Semantic-Org/Semantic-UI/issues/4611
> [Segment] Make Clearing segment work with stacked or piled segments

- src/definitions/elements/button.less
`buttons` in `basic buttons` group should never show a box shadow if either the group or the buttons inside are basic or inverted. Otherwise the box-shadow of colored basic buttons were overridden
https://fomantic-ui.com/views/card.html#cards
#495
> [Button] Basic colored buttons were overridden by basic button group box shadow

- src/definitions/elements/segment.less
`header` is directly supported to change its color to white in `inverted segment` without the need to be specified as `inverted header`.
Unfortunately this is not the case for `sub header`, which this PR now fixes
https://jsfiddle.net/njvdhk2e/
#486
> [Segment,Header] Color sub header in inverted segment just like normal header

- src/definitions/collections/menu.less
A `disabled item` in a `tabular menu` got the same color as a normal item. For normal or secondary menus is appears as expected.
https://jsfiddle.net/o6mpnjL1/2/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/52801257-c6734880-307d-11e9-863f-d8df1360a468.png)|![image](https://user-images.githubusercontent.com/18379884/52801226-b491a580-307d-11e9-8f7a-f0e18196852b.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/3178
https://github.com/Semantic-Org/Semantic-UI/issues/3578
> [Menu] Disabled items in tabular menus had same color as normal items

- src/definitions/modules/checkbox.less
- src/themes/default/modules/checkbox.variables
It's already possible to set the `indeterminate` state to a checkbox via javascript behavior
```javascript
$('.ui.toggle').checkbox('set indeterminate');
```
But that's actually **regardless** if it's a toggle checkbox or a normal checkbox!
So the only missing is a visual indication for a toggle checkbox to completely support `indeterminate` there aswell.
Thanks for the original proposal code to @lauri-elevant
https://jsfiddle.net/cbyp1ego/
https://github.com/Semantic-Org/Semantic-UI/issues/3216
https://github.com/Semantic-Org/Semantic-UI/issues/5133
> [Checkbox] Visual support for indeterminate toggle

- src/definitions/elements/input.less
The `input` element was missing the `tiny` size variant, thus such inputs were diplayed in medium / default size.
https://jsfiddle.net/xeungdv8/1/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/52844822-c9198080-3105-11e9-84ea-47507e06c8dd.png)|![image](https://user-images.githubusercontent.com/18379884/52844794-b56e1a00-3105-11e9-8072-15dd02aa9244.png)|
https://github.com/Semantic-Org/Semantic-UI-React/issues/3439
> [Input] Tiny size variant was missing

- src/definitions/behaviors/api.js
The current API behavior raises an console error on failure, even when the status code was 2xx.
It only omits it when the status code is exactly 200
https://jsfiddle.net/q5osrg7k/2/
https://jsfiddle.net/q5osrg7k/3/
https://github.com/Semantic-Org/Semantic-UI/issues/4908
> [API] Do not raise console error on all 2xx status codes on failure

- src/definitions/modules/popup.js
The `onHide` event in the popup module was called twice.
- First at the hide behavior (where it is correct)
- Second right after the first call again in the module.animate.hide call and this is only called from the hide method mentioned before
Obviously an old copy/paste bug. In comparison to `onShow` this has now the same flow logic after applying the fix.
- Click on the little button to show the Popup
- Click again to hide it and watch the console:
onHide is shown twice
http://jsfiddle.net/bm1gzosv
onHide is shown once
http://jsfiddle.net/bm1gzosv/1/
https://github.com/Semantic-Org/Semantic-UI/issues/4722
https://github.com/Semantic-Org/Semantic-UI/issues/4752
> [Popup] onHide was called twice

- src/themes/default/elements/label.variables
When a `ribbon label` was used for `table` cells there were slightly mispositioned making it overlap the border
https://jsfiddle.net/g3t0zea4/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/52622865-282f8900-2eab-11e9-938b-e836da16f9f5.png)|![image](https://user-images.githubusercontent.com/18379884/52622813-00402580-2eab-11e9-92ff-d334b43e1e4c.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/5203
> [Label] Table ribbon labels had wrong calculated position

- src/definitions/modules/progress.less
Because of too low specificity the states `success`,`warning` and `error` for `inverted progress` had only the default gray color set overriding their respective colors
https://jsfiddle.net/rhvqno2z/
> [Progress] Inverted success/warning/error progress bars had no color

- src/definitions/collections/menu.less
Having right items in a menu inside a container misses a final right border just like there is a left border for the very left item.
Result-view has to be at least a width of 768px to see the outer borders
Remove CSS to see the difference
http://jsfiddle.net/s693qbct/
https://github.com/Semantic-Org/Semantic-UI/issues/3332
> [Menu] Last right item in a menu inside a container misses right border

- src/definitions/elements/segment.less
If a compact segment is used within a `horizontal segment` group, the segment was expanded, thus ignoring the `compact` flex-setting. The PR now only sets the specific flex setting for horizontal segments if it is not for compact segment children.
Remove CSS to see the issue 
https://jsfiddle.net/eL4usw6n/
#477
> [Segment] compact segment in horizontal segment group should stay compact

- src/definitions/modules/dropdown.js
If a dropdown button has a label inside, the click/touch event to show/toggle the dropdown menu was ignoring any click on the label itself.
- Click on the big grey button to trigger the dropdown. It works.
- Click on the white label inside the grey dropdown button....
... it does not work.
https://jsfiddle.net/fej70wv2/
... it works.
https://jsfiddle.net/fej70wv2/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6165
> [Dropdown] Allow a label to be clickable inside a dropdown button

- tasks/build/assets.js
- tasks/build/css.js
- tasks/build/javascript.js
- tasks/config/project/config.js
gulp-chmod needs the octal representation of the file permissions (f.e. `0o755`), but in the config it was saved as a string. As a result, gulp-chmod crashed.
Additionally permissions on js files were not set correctly.
#502
> [Build] Fix incorrect format of file permission

- src/definitions/modules/dropdown.js
Whenever a `minCharacter` setting > 0 was set, it was not possible to open the whole dropdown list anymore by clicking on the dropdown icon. (as it was in SUI)
https://jsfiddle.net/1fvrphsa/2/
https://jsfiddle.net/nkhg3cs8/
#496
> [Dropdown] Always show list when clicked on icon, regardless of minCharacter setting

- src/definitions/modules/modal.js
If a modal opens another modal using `onDeny` callback, the `onDeny` method of that modal works only one time and it never works again which means the modal cannot be closed.
* Click the button to open Modal 1.
* Inside Modal 1, click the button to open Modal 2.
* Close Modal 2, which will re-open Modal 1 again.
* Click again the button in Modal 1 to open Modal 2 again.
* Try to close Modal 2 again now and ...
...  it cannot be closed.
https://jsfiddle.net/1qo9nkre/
... it closes again as expected 
https://jsfiddle.net/0m1pukaw/
#511 
https://github.com/Semantic-Org/Semantic-UI/issues/6069
> [Modal] A modal couldnt be closed a second time it was opened by another modal

- src/definitions/modules/calendar.js
If an entered date had a 2-digit year notation (like 88 which actually meant 1988) and the year was set between 60 and 99, the day was always internally wrong calculated and displayed to the last day of the month
https://jsfiddle.net/to7c056b/1/
https://jsfiddle.net/mar7xzvu/
|Before|After|
|-|-|
|![calendar88_bad](https://user-images.githubusercontent.com/18379884/53275725-7be87080-36fc-11e9-8d75-eb6114e4dba6.gif)|![calendar88_good](https://user-images.githubusercontent.com/18379884/53275736-8440ab80-36fc-11e9-883b-12d9c91eeb82.gif)|
#507
> [Calendar] Day was calculated to last day of month if year had 2-digit notation between 60 and 99

- src/definitions/modules/dropdown.js
In case the initial value of a dropdown is `null` (for example an empty `select` tag returns this),
the fetch of preselected values after a remote api call is broken
Just click into the search dropdown to trigger the remoteAPI call and watch the console returning JS errors immediatly
https://jsfiddle.net/y18p4thg/1/
https://jsfiddle.net/y18p4thg/2/
#505
> [Dropdown] Catch a possible null value for preselected values

- src/definitions/modules/checkbox.js
Unable to check/uncheck the checkbox. Tick mark flicks on hitting Space button.
This occurs only when JS is assigned over that checkbox DIV.
and only on Edge and Internet Explorer Browsers.
Click on the checkbox or its label once and right after check try to check/uncheck via spacebar again
Does not work in IE11 or Edge
https://jsfiddle.net/jph1r2se/2/
Works now :)
https://jsfiddle.net/06kde5fg/
|Edge||IE||
|-|-|-|-|
|Before|After|Before|After|
|![edgespace_bad](https://user-images.githubusercontent.com/18379884/53183537-d3eb7e00-35fb-11e9-839c-79ffdb1c98a9.gif)|![edgespace_good](https://user-images.githubusercontent.com/18379884/53183544-d8b03200-35fb-11e9-868f-19e366f05103.gif)|![ie11space_bad](https://user-images.githubusercontent.com/18379884/53183555-dc43b900-35fb-11e9-8d64-08c661fca0 …
> [Checkbox] Support check/uncheck by hitting space key in IE11 and Edge

- src/definitions/modules/tab.js
'tabPath' was not escaped before sent over to jquery engine resulting in JS console errors when used with the history hash option 
Click on any link at the bottom and watch the console spitting JS errors
https://jsfiddle.net/zm0p591d/
All fine
https://jsfiddle.net/rLewdf9t/
https://github.com/Semantic-Org/Semantic-UI/issues/6750
> [Tab] should escape meta characters before sending to jquery

- src/definitions/modules/dimmer.js
- src/definitions/modules/dimmer.less
- src/definitions/modules/modal.js
- src/definitions/modules/sidebar.less
When a modal is shown, a possible scrollbar gets hidden because of `overflow:hidden` to the body. This is correct to prevent scrolling of the background.
However, the overflow actually removes the scrollbar providing additional space (width of the scrollbar) to the body content. This again results in a recognizable width change of all background content and will be visible again when the modal closes.
Also, because of this behavior, the modal gets immediatly moved to the left by the width of the scrollbar when it gets hidden, because the dimmer resets the overflow setting **before** the dimmer is actually completely hidden.
This PR solves everything now:
- Still remove the scrollbar by overflow hidden (no change)
- **but** give a temporary right margin to the body having the same width as …
> [Modal] Don't move content and modal on dimmer when scrollbar hides

- src/definitions/elements/label.less
- src/themes/default/elements/label.variables
By making the icon inside a `corner label` position absolute, its positioning is not modified anymore, if the `corner label` was used inside a `<button>` tag
The `ui corner label` is used in a `<button>` tag instead of an `a`
```html
<button class="ui left corner label">
<i class="heart icon"></i>
</button>
``` 
https://jsfiddle.net/moshfeu/h4582kbc/3/
https://jsfiddle.net/Lfha3wnb/1/
#518 
https://github.com/Semantic-Org/Semantic-UI-React/issues/3462
> [Label] Make corner icon position absolute to support other tags for label like <button>

- src/definitions/modules/calendar.js
3rd iteration... (the last one or I eat my shoes !)
This PR allow to enable only some dates by passing an array called `enabledDates` when initializing the calendar.
[![0fca86fa65ee213dd6e0a5bd2b738a93.md.png](http://tof.cx/images/2019/02/25/0fca86fa65ee213dd6e0a5bd2b738a93.md.png)](http://tof.cx/image/I8npR)
#484
> [Calendar] Disable all dates but some

- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
The current `fullscreen` modal was (according to the docs) supposed to "use the entire size of the screen". This was not really true, because there still was lots of margin left, so you could see the dimmer, and also modals with little content were not even close to fullscreen.
This PR makes it possible now and adds a new variant to the modal module:
`overlay fullscreen modal`
When used, it is now **really** using and overlaying the entire viewport, regardless of the content. 🙂 
https://jsfiddle.net/sbru45e1/
#522
> [Modal] Introducing "overlay fullscreen modal"

- src/definitions/modules/calendar.js
This PR adds the ability to adjust the calculation of entered shortyears to the belonging century by adding two new options
```javascript
// default values to stay backward compatible to current behavior
currentCentury: 2000,
centuryBreak: 60,
```
https://jsfiddle.net/7mhLw321/
#514
> [Calendar] Adjustable shortyear to century calculation

- src/definitions/modules/shape.js
When a shape had a focussed input inside, any animation was broken.
Previously, you had to click outside of the shape to blur the input to make the animation work again.
Although in the example below, the checkbox indeed gets blurred right before the button to animate the shape is clicked, it seems the browser engine still gets confused and does not recognize the change early enough.
This PR now delays the animation for a short time in case of input being part of the the shape, so the blurred checkout is also recognized by the browser engine at animation time
Check/uncheck the checkbox. Then **quickly** (means don't hold the mousebutton for too long) click the Button to trigger the animation
https://jsfiddle.net/o5tqeuha/
https://jsfiddle.net/xr2jvnof/
|Broken|Fixed|
|-|-| …
> [Shape] Focussed Checkbox inside shape breaks animation

- src/definitions/modules/modal.js
- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
When a modal opened another modal, the positioning given by `centered:false` was broken. The first modal did not stay at it's supposed position.
Reason for this was, that modal positioning was done by applying `top aligned` to the page dimmer instead of the modal itself.
This PR now takes care of the positioning for each opened modal and keeps its position until it's closed.
In addition it also invents `top aligned modal` and `bottom aligned modal`
> Hint: Unfortunately the current code already used the word `top` internally to mark the most active modal in the front and removed it again when the modal closes. No CSS Class for `top` was existing and it is not even documented. I therefore decided to rename the internal `top`to `front`instead, because i didn't want to name this `upper …
> [Modal] Allow different modal positions on multi-modals. Added top and bottom aligned modal

- src/definitions/modules/dropdown.js
Because the global event object is not available in firefox but is supplied as property to the event method and the focus event was missing this property, firefox raises a JS error at the console.
This has now been catched by correctly adding the event property to the focus event function.
-  Use Firefox
- Open the modal by clicking the button
- Watch the console
https://jsfiddle.net/dutrieux/7gwko0L6/14/
https://jsfiddle.net/zhgwbLjd/
#533
> [Dropdown] Missing event property in focus event raises JS error in firefox

- src/definitions/elements/button.less
Thanks to @dylmye for the hint
The consequences loop for basic buttons always used "primary" when setting the margin instead of the supplied consequences name .
https://github.com/Semantic-Org/Semantic-UI/pull/6766
> [Button] Basic button loop always used "primary" for margin

- src/definitions/behaviors/form.js
Checkbox groups where the checkboxes share the same name property were only "checked" validated if every single checkbox within the group was checked. This is wrong, it should behave the same as the radio group "checked" validation (SUI does it)
> Hint: The example uses the same name attribute for each checkbox also with a bracket suffix "[]"
The form validator already supports using this selector by putting it into quotes .
> Hint 2: selector.checkbox covers checkbox and radiobutton aswell..in case you wonder if the old behavior with radio still works 
```javascript
fields: {
"sizes[]": 'checked'
},
```
Every toggle checkbox has to be checked to pass the validation
https://jsfiddle.net/ogz73ks5/
Only one checkbox has to be checked to pass validation
https://jsfiddle.net/ogz73ks5/2/ …
> [Formvalidation] Support checkbox groups for "checked" rule like radio groups

- src/definitions/modules/checkbox.js
The fix in #509 (which fixes a IE only behavior) did not fetch a possible call by firefox, which in turn does not provide the global "event" object.
The original fix was done in a method that is not necessarily called by an event, so a proper check for an existing `event` variable was missing, as it is only needed for IE.
This is the original fiddle adjusted by the fix from this PR. Open this on firefox and it will raise a console error when trying to hover or change the checkbox  😢 
https://jsfiddle.net/06kde5fg/
https://jsfiddle.net/q48rLgap/
#543
> [Checkbox] Proper check for non existent event object in Firefox

- src/definitions/modules/calendar.js
This PR fixes the no displayed date despite user has set `initialDate`. It also fixes an error when a non standard date was given trough metadata.
#549
> [Calendar] initialDate now update input

- src/definitions/collections/form.less
Because of an unclear CSS definition for `:empty` and `:not(:empty)`, Safari was never displaying any error message on form validation
https://jsfiddle.net/43kLfupd/5/
- Open in Safari
- Click on "Login" -> Error Message below the form appears as expected
- Remove the CSS Block
- Re-Run the jsfiddle
- Click on "Login" -> Error Message is not shown
#557 
https://github.com/Semantic-Org/Semantic-UI/issues/6668
> [Formvalidation] Safari was not showing error message

- src/definitions/modules/slider.less
The `slider` component conflicts with the existing `slider checkbox` especially in terms of padding
|Single example|Table example|
|-|-|
|![slider_checkbox_bad](https://user-images.githubusercontent.com/18379884/54063339-f4c2ee80-420b-11e9-8c0d-224be4b5c7b4.gif)|![slider_checkbox_bad2](https://user-images.githubusercontent.com/18379884/54063348-f987a280-420b-11e9-96e9-8a2cdc862e1e.gif)|
#547
> [Slider] Don't conflict with checkbox

- dist/components/form.js
- src/definitions/behaviors/form.js
When executing `form("remove fields", field) check if `validation[field] !== undefined` before accessing any of it's properties
> [Form validation] Check if `validation[field] !== undefined` before accessing any of it's properties

- src/definitions/globals/site.less
- src/themes/default/globals/site.variables
- src/themes/flat/globals/site.variables
The unknown CSS property `font-smoothing` was found during introducing stylelint (linter for CSS and alt-CSSs like LESS) to FUI by the [`property-no-unknown` rule](https://stylelint.io/user-guide/rules/property-no-unknown/).
According to git history, the line had been added by jlukic in 2014 but not sure why.
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth), there is no such property `font-smoothing` but `font-smooth`, `-webkit-font-smoothing` and `-moz-osx-font-smoothing`.
I think it is better to remove the invalid property.
Reasons
* It seems not working even on macOS because wrong name (just my guess, I don't have macOS), so removing it may not be a breaking change.
* Supported features are incompatible even between `-webkit-` and `-moz-`.
* Other …
> [Site] Remove unknown CSS property: font-smoothing

- src/themes/default/globals/site.variables
Using higher Screen-DPI Settings (on Windows) than 100% leads to some possible "floating value pixels" for width like "767.2px" 
The current breakpoints for every component are always set in full 1px difference. This creates a uncovered gap between 767 and 767.99 now where no media query covers a different visibility setting making every usually hidden element appear.
For simplicity the jsfiddle only covers the grid-element. But the PR just changes the breakpoints so every other element using media queries will get fixed at compile time aswell
https://jsfiddle.net/o04hrpfL/1/show
- Use Windows
- Set your screen DPI Setting to 125%
- Use Chrome
- Resize the screen to 767.2 Pixel (yes, that's possible... just be patient when resizing the window 🙂 )
https://jsfiddle.net/o04hrpfL/show
#385
> [Site] Support dpi > 100% for media queries

- src/definitions/modules/dimmer.less
According to the [docs](https://fomantic-ui.com/modules/dimmer.html#simple-dimmer), a `simple dimmer` should completely hide all of its content when the parent element is not `dimmed`
Unfortunately a possible loader inside the dimmer was still shown and got especially visible when used in a `simple inverted dimmer`
https://jsfiddle.net/2Lgukfc0/
https://github.com/Semantic-Org/Semantic-UI/issues/6257
> [Dimmer] Loader inside simple inverted dimmer was still visible even when parent was not dimmed

- src/definitions/modules/calendar.js
- src/definitions/modules/calendar.less
- src/themes/default/modules/calendar.variables
The calendar can show dates from adjacent months. These adjacent month dates can also be made selectable.
Option: selectOtherMonths boolean defaults to false
> Enhancements: [Dropdown] Possibility to select adjacent month dates.

- src/definitions/modules/dropdown.less
This PR adds columnar variation to dropdown module like `two column dropdown` in the same manner as `two column grid`, so that more items can be glanced at once.
This is helpful if dropdown have tons of items (e.g. Countries, States/Providences, Divisions, something like that).
Numbers of columns can vary between 2 (`50%` for each item) and 5 (`20%` for each).
Related to #545 (taller dropdown) but different approach and different use-case .
> [Dropdown] Columnar dropdown variation

- src/definitions/elements/button.less
A `fluid left/right labeled icon button` always had a fixed equal padding on both sides without respecting the width of the label icon.
Infact this is basically already covered by the framework, because it's correctly adjusted for the non-fluid variant, but for some unknown and un-reproducable reason the padding was additionally overridden to the same value on both sides for the `fluid` variant, which is not neccessary and most important wrong.
https://jsfiddle.net/7bo0zyck/1/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/54884981-62f7ea00-4e77-11e9-82e4-cfdd04fd6cd0.png)|![image](https://user-images.githubusercontent.com/18379884/54884971-4d82c000-4e77-11e9-8025-bf20170798d8.png)| …
> [Button] Fixed padding for fluid right/left labeled icon buttons

- src/definitions/elements/step.less
Thanks to @Alamantus for the [original SUI-PR](https://github.com/Semantic-Org/Semantic-UI/pull/5929)
> Fix step borders by moving it below steps instead of bunching them all up to the right.
> This provides a consistent look for the steps when stacked and also remains separate from the "vertical" styled steps.
I also added an additional fix to still hide the pointer in the last active item in the forced vertical variant
- Size your screen to mobile size to force stacking of the steps. The arrow in active step will also appear now and the border is consistent now
https://jsfiddle.net/ochbq14w/
Notice the following changes on mobile:
- Step on Desktop always have a vertical 1px border divider which are missing on mobile
- On mobile the right border was doubled, thus bolder, if not the last …
> [Step] Show step pointer and border also on stacked mobile for consistent look

- bower.json
Increasing the jquery dependency for bower installations to the same version as for the usual npm package (^3.2.1) "fixes" an issue with animations used for example in accordion in case one is still using jquery 1.8
More info in the related SUI issue
https://github.com/Semantic-Org/Semantic-UI/issues/5731
> [Chore] Update jquery dependency for bower to the same version as for npm

- src/definitions/collections/table.less
- src/themes/default/collections/table.variables
A few fixes for `inverted table`
- `sortable table` header still had black text color
- `disabled` rows or cells on (also) colored rows/cells had unreadable text color
- `celled` cells still had the same, thus too dark, left cell border from the non-inverted variant
https://jsfiddle.net/63g1y07j/5/
Remove CSS to see issues
https://github.com/Semantic-Org/Semantic-UI/issues/6778
> [Table] Inverted Table fixes for sortable header and disabled colored rows/cells

- src/definitions/modules/progress.js
- src/definitions/modules/progress.less
Allow `progress` modue to have multiple bars.
* `data-percent` and `data-value` are extended to have multiple values like `data-pecent="30,0,70"`
* Bar of 0 width are hidden for readability.
* `{bar}` placeholder are added to indicate name of bars so that end-users can ditinguish bars.
https://github.com/Semantic-Org/Semantic-UI/issues/6160
> [Progress] Allow multiple bars

- src/definitions/modules/dropdown.less
This PR adds height variation to dropdown module so that more items can be glanced at once.
This is helpful if dropdown have tons of items (e.g. Countries, States/Providences, Divisions, something like that).
This is usable if every items can be shown at once within the height of window without scroll bar.
If there are so many items that requires scroll bar, user can consider columnar variation proposed in #586.
Closes #545
> [Dropdown] Height variation

- package-lock.json
- package.json
In 2.7.3 we moved the dependencies so all the dev dependencies were in
devDependencies but the npm install script doesn't instal
devDependencies so the package installation would fail. I have moved
them all into dependencies so they should now be installed.
```
$ npm init
$ npm install --save fomantic-ui
```
#607
> build(deps): fix install issue caused by dev deps

- src/definitions/modules/modal.js
When a modal opens another modal just when itself closes and both modals have `allowMultiple` set, the dimmer is hidden too early  making the second modal also close immediatly.
https://jsfiddle.net/wrzjh1gy/1/
https://jsfiddle.net/wrzjh1gy
https://github.com/Semantic-Org/Semantic-UI/issues/6741
https://github.com/Semantic-Org/Semantic-UI/issues/6786
> [Modal] Don't close dimmer when another modal is still animating

- src/definitions/modules/calendar.js
Since #559 the value of `initialDate` setting is displayed in the input field of the calendar.
Unfortunately the parse.date function did not support raw Date Objects, but always expects text string, resulting in a wrong displayed date around Year 100 🙂 , e.g. when a Date Object is given as initialDate)
https://jsfiddle.net/sruafp7k/
https://jsfiddle.net/sruafp7k/1/
Also reproducable on the current 2.7.4 docs page
https://fomantic-ui.com/modules/calendar.html#enable-only-specific-dates
#614
> [Calendar] Support Date-Object given for parser.date, initialDate setting is wrongly displayed otherwise

- src/definitions/modules/dropdown.js
When a single selection dropdown allowed additions which are not available in the dropdown itself by configuring the dropdown using `allowAdditions:true` and such non-existing value was entered, it was not possible to click anywhere else in the document anymore, because the click-event was swallowed.
Reason for this was that the dropdownmenu was not active but still visible. The empty dropdown was not animated to be hidden anymore and the unbinding of the click event  (which prevented any other click event)  did not take place, keeping all following clicks for the whole document in a trap. 
- Enter anything in the dropdown which does not exist, for example `foobar`.
- Try to click on the `clickaway` link which should open google in a  new blank browser window
- Nothing happens, the click …
> [Dropdown] click-event was locked when single selection had allowAdditions enabled

- src/definitions/modules/dropdown.less
Simple dropdowns had a vanishing submenu if one item was hovered and this item overlapped another submenu.
As the fix is done by removing an unneccessary !important statement, i cannot provide a immediatly working fiddle.  You have to remove the `!important` from `top:0 !important;` of the `.ui.dropdown .menu .menu` selector via devtools. See screenshot.
https://jsfiddle.net/L7eabtcj/3/show
#590
> [Dropdown] prevent submenu vanishing for simple dropdowns

- src/definitions/modules/modal.less
`image content` was wrongly fixed by #209. It set a forced flex wrapper although `image content` is supposed to stay in a row by using `flex-direction :row`.
This PR partly reverts #209 for this reason. Anyhow the issue in the mentioned SUI issue only occurs when the related images were very large. To still fix this i provided 3 workarounds, see testcases.
Text is set next to the image (in a row) as expected and as it was until 2.6.4. It is not force-wrapping anymore
https://jsfiddle.net/kdvum7ho/2/
Remove CSS (or watch the scrolling modal example at http://localhost:99/modules/modal.html#scrolling-modal ) to see the issue
Wrapping the image into a `ui image` div
https://jsfiddle.net/kdvum7ho/
Force wrapping by using `content` instead of `image content` 
https://jsfiddle.net/kdvum7ho/1/ …
> [Modal] Don't wrap image content direct images

- src/definitions/elements/button.less
The icon padding had to be adjusted for `compact labeled icon button`, because the positioning of the icon was optimized to support loading icons in #361 
http://jsfiddle.net/0vp6kz2g/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/55268160-9bd4fc00-5287-11e9-9aa7-90b8fe6152db.png)|![image](https://user-images.githubusercontent.com/18379884/55268145-84960e80-5287-11e9-9a01-481360ee776c.png)|
#598
> [Button] Fix padding for compact labeled icon button icon

- src/definitions/collections/table.less
A `definition table` footer had a box-shadow set to the left. It should look like the header.
Thanks to @Banandrew for the finding and original fix (2 years ago... 🙄 )
http://jsfiddle.net/cLraoj6x/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/55280093-09813680-5321-11e9-827d-de34d0a8a32c.png)|![image](https://user-images.githubusercontent.com/18379884/55280086-ef475880-5320-11e9-9c16-9cfa79324d9f.png)|
> [Table] Definition table footer had wrong box-shadow to the left

- src/definitions/collections/table.less
This PR enables support for nesting tables which use either different variants or components inside which themselves also use tables (like `calendar` which is used as the base for the testcase)
As you will see, all table definitions are now defined as direct sibling selectors to accomplish this.
In case the last selector had an additional specific table class set (e.g. `.table td.active`), the direct sibling change was not necessary, because the class clearly defines its usage, so don't get confused when reviewing.
This PR is based on a SUI PR by @Banandrew (again, 2 years ago... 🙄 ). I just had to fix some declarations and adjusted it to the current FUI codebase.
https://jsfiddle.net/vd1b2ksf/
https://jsfiddle.net/vd1b2ksf/1/
Example of a calendar inside a `definition table`
- Content is …
> [Table] Don't break style when nested tables like calendar are used (or having different variants)

- src/definitions/collections/table.less
A selectable cell in a table already had a pointing cursor, but just because of the full sized a-tag within (browser default). For a `selectable table` instead the cursor still remains as arrow although each row is supposed to be selectable (unless disabled)
This PR now adds the pointing cursor for those rows/cell aswell.
Thanks to @zediogoviana for the basic idea. I simplified the implementation and defined the selectors so they work nicely together with #604 in nested tables
https://jsfiddle.net/zgdjnvb5/1/
Hover over the rows in the first table.
Remove CSS to see the difference
https://github.com/Semantic-Org/Semantic-UI/pull/6784
> [Table] selectable rows/cells should have pointing cursor

- src/definitions/behaviors/api.js
According to [the docs](https://fomantic-ui.com/behaviors/api.html#/settings), `beforeSend` should have the "initialized element" as context, not the element matching `stateContext`!
https://jsfiddle.net/7oz0bncp/
https://jsfiddle.net/7oz0bncp/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6207
> [API] Set context in beforesend to $module instead of possible stateContext to match docs

- src/definitions/modules/dimmer.less
If content within a dimmer, most likely a modal, uses a popup and the dimmer is blurred, then the popup itself also gets blurred, because the popup is rendered as a direct sibling to body.
There indeed exists a setting `inline` which will also prevent this behavior, but `inline:true` will also keep all popup markup in the DOM once created, which might unnecessarily bloat the domtree and might not be the desired side effect.
As a popup is never supposed to stay open, but will always vanish before a modal is shown it's save to not blur any popup as a direct sibling of body (no popup outside of the modal will be triggered). (And in case the popup option `closable:false` is used, one definately wants to control all the popups on his own anyway)
- Hover over the button …
> [Dimmer] Don't blur a popup , might be used inside the dimmer like modal

- src/definitions/collections/menu.less
This style was already added to the left menu
Fixes the issue where a right sub-menu dropdown of a menu would open up horizontally instead of vertically. This style was already added for the left menu, but was not for the right menu.
https://jsfiddle.net/986c0o5L/1/
#382
> [Menu]: Fixes right dropdown sub-menu not being vertical

- src/definitions/collections/form.less
The ::before `.loader` pseudo-element did not have segment rounded corners on a `.segments.form`. Added those.
https://jsfiddle.net/douglasg14b/e7cs93zd/4/
#628
> [Form] Adds segment corner rounding to form segments loader

- src/definitions/modules/popup.js
iOS does not trigger the `click` event when clicked inside whitespace, but only `touchstart`.
Because of this an open popup with setting `on: 'click'` was not closable again by clicking somewhere else
I adopted the same logic as for dimmer to fix this by binding either the `click` or the `touchstart` event depending on existance of `ontouchstart` 
http://jsfiddle.net/byre2q7d
http://jsfiddle.net/byre2q7d/1/
https://github.com/Semantic-Org/Semantic-UI/issues/5356
> [Popup] support iOS to recognize popup close on touch

- src/definitions/modules/dropdown.less
An `image icon` aswell as a `remove icon` used as item icons in dropdown menus conflicted with other css settings which basically took care of "real" images or the clearing icon.
As a clearing icon is always rendered as a direct sibling of dropdown it is save to change the selector to direct sibling which fixes the issue for the remove icon
For image is was the usual problem of having font awesome icons which names conflict with FUI classnames so the fix as always is to remove the .icon class from the selector
http://jsfiddle.net/se7hm0wf/
A bit difficult to reset the current setting to make a proper fiddle, so watch the screenshot 😄 
#620
> [Dropdown]: image and remove icons used as item icons are misaligned

- tasks/build/css.js
If changes are detected in the site.variables file, all css files should be rebuilt.
#631
> [build] Task `watch` do not update files that depends on site.variable

- src/definitions/elements/divider.less
Add text alignment modifiers for dividers: `left aligned` and `right aligned`
`center aligned` is the default divider alignment
https://jsfiddle.net/9umo0ac8/
> [Divider] Horizontal alignment for divider content

- src/definitions/collections/form.less
The property `-webkit-appearance: none` causes the select element unstable on focus and unfocus
events. Removing native appearance from select on focus reduces the space between the border
and it's content which causes unexpected bouncing.
This property doesn't give any extra effect to all fields for focus event, but making select
element inconsistency alone. So, better to remove this property to make the select element stable
along with the other fields when it's focused or unfocused.
Before | After
--------- | ---------
#576
> fix(form): Remove unnecessary property '-webkit-appearance: none' with :focus from error field

- src/definitions/behaviors/form.js
First, a great kudo to @simontaite for inspiring me this. I'm using his [plugin](https://github.com/simontaite/jquery.dirty) on a lot of projects and it works well with FUI.
This PR add the ability to define a state for the form: `clean` or `dirty`. Default state is `clean` and is changed to `dirty` when the user change at least one field. Reseting a form also change state to `clean`. Theses events are now triggered:
- `onDirty()`
- `onClean()`
Dirty fields can be showed by using the `get dirty fields` behavior.
State can also be changed programmaticaly by using behaviors `set as clean` and `set as dirty`. Its now also possible to prevent a user form leaving the page if the form is in `dirty` state, using `preventLeaving: true`, which can be useful when you don't want to loose data.
Bonus …
> [Form] Add dirty and clean states, and ability to cancel submit

- src/definitions/views/card.less
As reported in #159, the meta data, actions and extra content are forced to display in one row in horizontal cards. It's because of `flex-direction: row` setting `flex-wrap: wrap`, and the flex item for meta data has no initial size. So, it forces the other flex items to wrap in available spaces next to it which leads them displaying in the same row.
Since, the extra content and buttons are always supposed to appear on the next line and should take 100% width of the card. The meta data should have initial size with minimum value which will make sure the meta data to wrap in the available space on the current row and the extra content and buttons to appear in the next row respectively.
**Before:** https://jsfiddle.net/kv2sj3hq/
**After:** https://jsfiddle.net/axc9hmqy/
Before | After …
> [Card] Force horizontal cards meta, extra content and actions to align properly

- src/definitions/modules/dropdown.js
In case a dropdown is recreated and a menu was open, the re-instantiated dropdown still had this menu open, although the initial state of a dropdown is a hidden menu. The dropdown is not active, thus click events outside of the dropdown did not close the menu.
Also takes care, that any running animations are stopped
https://jsfiddle.net/gad2791y/  
https://jsfiddle.net/c62bagsn/
#653
#654
> [Dropdown] Hide a possible open menu on destroy for correct reset state

- src/definitions/modules/modal.js
In 2.7.3 we fixed the behavior of a modal when opening on large page with a scrollbar to not slide the body to the right for the width of the scrollbar.
Unfortunately a possible existing `fixed menu`, `right sidebar` or `right toast-container` still move 😢 
This PR fixes them as well 🙂 
https://jsfiddle.net/snudrg69
https://jsfiddle.net/snudrg69/1/
|Bad|Good|
|-|-|
|![modal_fixed_move_bad](https://user-images.githubusercontent.com/18379884/55726799-f2250600-5a10-11e9-8145-fa9032dc8f84.gif)|![modal_fixed_move_good](https://user-images.githubusercontent.com/18379884/55726818-f94c1400-5a10-11e9-95d7-ad4aafdca1da.gif)|
#634
> [Modal] Support fixed menu, toast and sidebar to also not move when a modal is shown

- src/definitions/elements/button.less
Group of **disabled basic** button not properly display
Before
After 
#643
> [Button] Group of disabled basic button should have box-shadow

- src/definitions/behaviors/form.js
When there are multiple forms on a page and the form fields also have identical names, the `match` and `difference` rule functions possibly select the wrong field from a different form.
This PR makes sure the field selection takes place within the form
- Enter something in the "Username" field of the **second** form
- Enter the same value in the "Retype username" field of the **first** form
- See that...
- ... the rule validates
https://jsfiddle.net/v0hm1r8f
- ... the rule does not validate
https://jsfiddle.net/v0hm1r8f/1
https://github.com/Semantic-Org/Semantic-UI/issues/5190
> [Formvalidation] Make sure match/difference rules are selecting within the same form

- src/definitions/modules/dropdown.less
When the position of floating menu of dropdown is upward, the margin is missing
**Before**
**after**
> fix(dropdown): margin missing when the position of floating menu of dropdown is upward

- src/definitions/collections/menu.less
The additional specificity for `secondary inverted menu` was necessary (when 2.7.0 was released) to override a background color setting when `secondary` was still supported as a background color for menus. We removed this in #366 , so the additional specificity is not needed anymore
https://fomantic-ui.com/
- The top menu bar was the reason for the previous added `.menu` specificity. Removing it does not disturb it anymore,
#672
> [Menu] Additional specificity for secondary inverted menu not necessary anymore

- src/definitions/modules/modal.less
The `.content` selector for `.overlay.fullscreen.modal` is too generic. If a accordion or something else using a `.content` class is available within the modal dom tree, it will get stretched in height. 
https://jsfiddle.net/9648kvab/
- Remove CSS to see issue(the first accordion item stretches in height over the whole screen and you won't see the other items anymore)
#682
> [Modal] Use direct sibling for content selector in overlay fullscreen modals

- src/definitions/modules/dropdown.js
- src/definitions/modules/transition.js
To fix the issue 542
https://jsfiddle.net/dutrieux/ajwfetgh/76/
#542
> fix(modal): open animation broken on first open

- src/definitions/behaviors/form.js
- src/definitions/modules/calendar.js
This PR add calendar as a form field, plus it implement its validation and allow to grab underlying value while validating in three different formats.
To do so, a new parameter has been added to the settings: `dateHandling`. It can contain one of these three string:
- `date` (default): field value will be the selected date as a string.
- `input`: field value will be the underlying input value of the calendar.
- `formatter` will let you customize the format of the selected date (or datetime, time, month and year).
Default formatter settings is:
```js
formatter: {
date: function(date) {
var date = new Date(date);
return Intl.DateTimeFormat('en-GB', {
year: "numeric",
month: "2-digit",
day: "2-digit"
}).format(date);
},
datetime: function(date) {
return Intl.DateTimeFormat('en-GB', {
year: …
```
> feat(form): add calendar input field

- src/themes/default/globals/site.variables
Especially recognized in `table` or `grid` elements a breakpoint wasn't correctly fetched by the browsers, because the floating max value covers a 0.99 of the "before pixel" (was implemented by #567)
While mathematically correct, it was not working on the browser to correctly recognize the next full pixel again. (768 pixel were still recognized as something below)
I found out that it was working again when we'll use 0.98 of the breakpoint pixel (instead of 0.99.
This way the dpi fix of #567 still works but also fixes #681 now.
While i was testing with different dpi settings and windows resizings, i never came across a value of xxxx.99, so xxxx.98 as a breakpoint should fix both issues now.
https://fomantic-ui.com/collections/table.html
See gif-video:
- Open the mentioned website in chrome …
> fix(*): breakpoints ignoring next breakpoint in some cases

- src/definitions/modules/calendar.js
In case the startCalendar/endCalendar settings were given as string (which basically was supported) the current code assumes the selector would have the same parent as the opposite calendar, which is not even true in the docs-example (where each calendar is inside a form div)
This PR now corrects this, so it is using the given string selector as expected searching in the whole document
- Select an end-Date in the right calendar
- Open the left calendar to select a start Date
- The calendar should recognize the range given the end date from the other calendar value
https://jsfiddle.net/ue9hy7vL/
https://jsfiddle.net/c83kypx1/
#685
> fix(calendar): string selectors for start/endCalendar did not work

- src/definitions/modules/calendar.js
This PR adds support for `eventDates` and a new event handler `onSelect` to provide individual functionality whenever a cell-item was clicked.
This works similar as `disabledDates` by providing the option to set a tooltip given a message to a date cell.In addition a given `class` can be added to the cell. Otherwise a default `eventClass` (default `blue`) will be added to every event-cell.
```javascript
$('.ui.calendar').calendar({
eventDates: [
{
date: new Date(2019,3,21),
message: 'Show me in light purple',
class: 'inverted purple'
},{
date: new Date(2019,3,22),
message: 'Show me in green',
class: 'green'
}
]
});
```
```javascript
$('.ui.calendar').calendar({
eventClass: 'inverted red',
eventDates: [
new Date(2019,3,20), //no message tooltip
{
date: new Date(2019,3,21),
message: 'I got …
```
> feat(calendar): add eventDates support and onSelect handler

- src/definitions/collections/menu.less
For Semantic-Org/Semantic-UI#4248 a horizontal margin of -1px is introduced, this is not needed for tabular menus.
#671
> fix(tab): position issue with fixed item size

- src/definitions/elements/segment.less
This PR adds the variants `fitted`, `horizontally fitted` and `vertically fitted` to the segment element, as is it already availble for `menu`
https://jsfiddle.net/g7ha28wk/4/
https://github.com/Semantic-Org/Semantic-UI/issues/6117
#701 (when the mentioned workaround is used)
> feat(segment): add fitted variant

- src/definitions/modules/modal.js
If the first input (or its field) (in a modal) has the disabled class, autofocus will still give it focus, which makes it fully editable until it loses focus.
This PR now additionally filters all possible input fields accordingly.
Open the modal. It has a textarea inside and its `field` has the `disabled` class
https://jsfiddle.net/tb4qwhdr
-  The textarea is focused although disabled. You can type anything inside until blurring
https://jsfiddle.net/tb4qwhdr/1/
- Textarea is not focused as expected
https://github.com/Semantic-Org/Semantic-UI/issues/5794
> fix(modal): `autofocus` shouldn’t focus disabled inputs

- src/definitions/behaviors/form.js
When a form has an api attached (for form submissions via ajax) and that form is validated manually by behavior `validate form` a console error
`Uncaught TypeError: Cannot read property 'stopImmediatePropagation' of undefined` 
raises, because the event is not given
https://jsfiddle.net/x40jsLhr/
https://jsfiddle.net/x40jsLhr/1/
https://github.com/Semantic-Org/Semantic-UI/issues/5537
> fix(form validation): error when calling "validate form" with API attached

- src/definitions/elements/list.less
Define min-width for icon in lists, so text is aligned.
Closes #597
https://jsfiddle.net/vk2enzd5/
> fix(list): align text in lists with icons

- src/definitions/elements/label.less
- src/themes/default/elements/label.variables
"ui basic ribbon" has a 1px border, but "ui ribbon" does not, so "ui basic ribbon" is 1 pixel wider than "ui ribbon" in all directions:
- subtract 1px from padding on all sides of "ui ribbon basic", so it is same size as "ui ribbon"
- adjust position of "ui.basic.ribbon.label:after"
"ui ribbon"
"ui basic ribbon" before:
"ui basic ribbon" after:
Closes #708
https://jsfiddle.net/eruc460w/
left:
right:
> fix(label): adjust basic ribbon label size and position

- src/definitions/collections/breadcrumb.less
- src/themes/default/collections/breadcrumb.variables
When browser screen is narrowed and the breadcrumb gets in two lines there is no enough vertical space between them.
https://jsfiddle.net/1s9xgcvh/2/
https://github.com/Semantic-Org/Semantic-UI/issues/4671
> fix(breadcrumb): increase line height for readability on wrapped content

- src/definitions/collections/breadcrumb.less
- src/themes/default/collections/breadcrumb.variables
This PR adds `ui inverted breadcrumb`
https://jsfiddle.net/1s9xgcvh/
https://github.com/Semantic-Org/Semantic-UI/issues/3543
> feat(breadcrumb): add inverted variant

- src/definitions/modules/dropdown.less
This PR adds support for `scrolling` to `simple dropdown`
https://jsfiddle.net/mu7e1xsk/
https://github.com/Semantic-Org/Semantic-UI/issues/4219
> feat(dropdown): add scrolling support for simple variant

- src/definitions/views/card.less
Whenever a card has a long string inside, it overflows the card container.
Although @hammy2899 mentioned [here](https://github.com/Semantic-Org/Semantic-UI/issues/6186#issuecomment-367317097) that this is a rare case to fix, i thought about links in cards, which probably are not so much rarely used.
... so i adopted the fix by @w96k.
https://jsfiddle.net/9wz01hek/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/56897369-ace37980-6a8e-11e9-8029-c7d847b32b60.png)|![image](https://user-images.githubusercontent.com/18379884/56897356-9fc68a80-6a8e-11e9-9e28-1473dca164d9.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/6186
https://github.com/Semantic-Org/Semantic-UI/issues/5608
> fix(card): word-wrap overflowing with long strings

- src/definitions/modules/progress.js
https://jsfiddle.net/syvph8jg/
https://jsfiddle.net/9axt3n0b/
#707
> fix(progess): all percents are shown while animation

- src/definitions/modules/search.js
This PR fixes a typo, because `settings.content` does not exist and is never specified or documented or used.
That value is always replaced by `setting.source` within the function `module.search.object` instead, so codewise it works identical without the fix, but it's "cleaner" this way.
https://github.com/Semantic-Org/Semantic-UI/issues/5313
> fix(search): undefined internal variable

- src/definitions/collections/menu.less
Labels in `secondary pointing menu` were adjusted, but did not respect `floating` labels, which have a different positioning. Thus those were misaligned.
https://jsfiddle.net/gv2br0zu/
#668
> [Menu] Leave floating labels in secondary pointing menus as they are

- src/definitions/collections/menu.less
The Fix of #632 was correctly implemented by the given jsfiddle. However in the PR itself the change was done differently (similiar to `left menu`...but this was also wrong already).
Unfortunately the change now leads to break normal existing `right menu` elements
This PR reverts the change by #632 but adds the fix out of the jsfiddle which was given by #632 ,so it' still @douglasg14b who found a fix for the main problem 😄 
https://jsfiddle.net/zobwu0q2/
#632 
#382
> fix(menu): correct submenu fix which broke right menus

- bower.json
- package-lock.json
- package.json
Update jQuery to v3.4.0 to fix security issues surrounding nvd.nist.gov/vuln/detail/CVE-2019-11358
> jQuery before 3.4.0, as used in Drupal, Backdrop CMS, and other products, mishandles jQuery.extend(true, {}, ...) because of Object.prototype pollution. If an unsanitized source object contained an enumerable proto property, it could extend the native Object.prototype.
> build(deps): update jquery

- src/definitions/modules/transition.js
This PR fixes a regression of #698 where it was not covered that the `complete`method could have been called outside of an event, thus the event object was not available and accessing it lead into a TypeError 
- Click on the "One" Button
- Dimmer is shown ... and ...
- ... breaks resulting into console TypeError
https://jsfiddle.net/allwe/kucxvf79/4/
- ... dimmer gets hidden as expected, no error
https://jsfiddle.net/Luzdq681/
#747
> fix(transition): not checking for event object lead to TypeError

- src/definitions/modules/calendar.js
This PR supports JSON-Dates like `2019-05-14T21:00:00.000Z`  or `2019-05-14T21:00:00.00` given as 
- initialdate
- eventDates
- disabledDates
- enabledDates
https://jsfiddle.net/s0wdh57y/1/
#741
> fix(calendar): support JSON dates

- src/definitions/modules/slider.js
If a max value is not reachable as a multiplier counting from (min + steps * i) it should be adjusted.
For example if min=1, max=10 but step=2 then the 10 is never reachable. But this is not fetched and instead a higher value (next reachable step) is rendered instead. Even worse: That wrong value (11 in the example) is selectable although it shouldn't because the max value is still 10.
This PR now adjusts a given max value to the last reachable value before the given max value is reached.
Given the above example, it now calculates 9 instead of 10.
That also corrects the step points of the slider (was misaligned in those cases)
While testing i figured out the labels are rendered wrongly when working with float values (the usual JS rounding issue).This is also fixed now. …
> fix(slider): non reachable max value and rounding issues

- src/definitions/elements/icon.less
- src/theme.less
Don't automatically import the default theme overrides file for icons.
#763
> fix(icon): don't import default theme overrides

- src/definitions/collections/table.less
On mobile Screens the table header was inheriting a wrong margin, width and border setting since 2.7.5
This has been corrected now
https://jsfiddle.net/4gozw610/
#787
> fix(table): table header on mobile

- src/definitions/modules/dropdown.js
When a search dropdown is initialized out of a `select` tag with given option values and one of those is set as `allowAddition:true` is set, it will trigger a observer at initialization time, but the observer is not yet initialized. This leads into a TypeError.
This PR adds a check for existing observer object before trying to access it (as it is implemented everywhere else in the code)
https://jsfiddle.net/6t70ce54/
https://jsfiddle.net/7rsge546/
#784
> fix(dropdown): check for existing observer before accessing it

- composer.json
- tasks/config/admin/templates/composer.json
This PR corrects the composer.json files for correct schema usage and fomantic-domain as well as a typo 
https://github.com/Semantic-Org/Semantic-UI/pull/6815
> build(composer): fix typo, add web property & changed domain to FUI

- src/definitions/behaviors/form.js
The behavior `remove rule` is self modifying the rules array of a field. Thus, a previous deleted rule reduces the length of the rule array which the current loop is still running on. 
When the loop now reaches the last array index which does not link to an object anymore because of deletion, this was not fetched leading into a typerror.
- Open console to watch ...
... typeerror
https://jsfiddle.net/eL0jh56x/
... no error. The rule `notExactly[1]` is successfully removed and you can enter 1 character in the for field and the form gets validated
https://jsfiddle.net/eL0jh56x/1/
https://github.com/Semantic-Org/Semantic-UI/issues/6270
> fix(form): remove rule function lead to TypeError

- src/definitions/elements/button.less
While `fluid button` has centered text, `fluid vertical buttons` group do not, because of the flex display setting difference.
This PR corrects it now, so the text is also centered in those button groups.
Thanks to @tcmal for the [original SUI PR](https://github.com/Semantic-Org/Semantic-UI/pull/6335). I just left out the `width` setting change, because it's not necessary.
https://jsfiddle.net/0x3jntob/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/58367585-4f9de500-7ee1-11e9-8b86-e764763565b4.png)|![image](https://user-images.githubusercontent.com/18379884/58367590-60e6f180-7ee1-11e9-8f20-c54ca866936b.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/6065
> [Button] Center button text in fluid & vertically aligned button group

- src/definitions/collections/form.less
- src/definitions/elements/input.less
- src/themes/default/elements/input.variables
A lot of padding and support of textarea were misaligned, wrong or not supported at all:
- icons in `transparent input` were misaligned when inside a form
- `textarea` had no style at all when outside of a form
- `field error` on a `transparent input` still had a border
- `field error` on `transparent input icon` for `textarea` had no error background
https://jsfiddle.net/bq9kv4a8/
https://jsfiddle.net/bq9kv4a8/1
As i removed many `!important` the fixed fiddle contains a whole adjusted dist css file
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/59143385-e3d07780-89ca-11e9-8f36-2a8de36180b3.png)|![image](https://user-images.githubusercontent.com/18379884/59143389-f2b72a00-89ca-11e9-8a1a-41aa38754810.png)| …
> fix(form): transparent input padding and texarea support

- tasks/config/tasks.js
The tasks already fetches an error in `theme.less`. But it differed between a missing element or missing theme. To figure it out it relied on line numbers.
As theme.less had changed a lot over time since 2015 the line numbers were not correct anymore, leading into never informing the user what probably went wrong.
This PR adjusts the line numbers to their respective new positions of the relevant codelines.
> build(theme.less): adjust line numbers for error messages

- src/definitions/behaviors/form.js
The `isDirty` method was immediatly stopping any other bubbling events, preventing other events to the same object to not work anymore.
But the method was also not preventing the default browser action, resulting in opening for example a file dialogue twice when manually triggered.
Try to select a file by clicking either into the FUI Input field or on the button of the lower native file input
- The FUI Field does not open the file dialogue at all.
- The native field opens twice
https://jsfiddle.net/y0dsjotp/1/
- Both ways will show the upload dialogue once as expected.
https://jsfiddle.net/y0dsjotp/2/
#746
#770
#786
https://github.com/atk4/ui/issues/718
> fix(form): stop propagation only when dirty event was triggered and prevent default action

- src/definitions/behaviors/api.js
- src/definitions/modules/calendar.js
- src/definitions/modules/embed.js
- src/definitions/modules/embed.less
- src/definitions/modules/popup.js
Some cosmetics to deprecated stuff
- `event.keyCode` -> `event.which`
- removed unnecessary var
- replaced `iframe frameborder=0` and `scrolling=0` by `border:none` and `overflow:hidden`
- added missing semicolons
> refactor(*): clean up deprecated symbols

- src/definitions/modules/progress.js
1. Validation on sum of percents now is performed before rounding, as proposed by @ryamaguchi0220  in #759.
2.  Add `module.helper.derivePrecision` that calculates small-enough precision for multiple progress.
This is handy for users since they do not need to take care about precision for most cases.
If `precision` option is explicitly specified, it is used.
https://jsfiddle.net/x1ptzvs7/
Multiple progress bars are shown for the data in #757
#757
> [Progress] Fix wrong error on validating sum total on multiple progress 

- src/definitions/modules/calendar.js
This PR adds the possibility to append the calendar popup to the parent dom instead of prepending it.
In some cases (especially when used in `inline fields` of forms) prepending the calendar lead into CSS issue where `:first-child` did not work anymore.
I haven't found a way for a CSS only solution. It is not 100% sure, that inline fields will always have a `label` as its first child, so a
```less
.ui.form .inline.fields .field > label:first-of-type,
```
could have been a solution. If anybody else has a better idea to solve this otherwise, i am happy to close this PR without merging.
https://jsfiddle.net/2e59gpw7/
https://jsfiddle.net/vmethgkq/
#699
> fix(calendar): support dynamic way to append popup instead of prepending to the parent

- src/definitions/modules/progress.less
- src/themes/default/modules/progress.variables
This PR adds a proposed solution for an `indeterminate` state to the progress module.
It does not even need javascript and works with any existing FUI progress html code by just applying an additional class 😄 
To visually comply with the current FUI style relied on the `active` state animation style.
Every state is fully compatible to any size or color.
In addtion this PR adds an optional `centered` class to the inner progress text, to provide a functionality to show the percentage as static centered text regardless of the bar width.
I added the following `indeterminate` states :
`pulsating` (currently default, thus not explicitely defined as a class)
`filling`
`sliding`
`swinging`
I would be happy to hear feedback 🙂 
https://jsfiddle.net/nekc8v7m/8/ …
> feat(progress): add indeterminate states

- src/definitions/collections/menu.less
- src/themes/default/collections/menu.variables
This PR corrects some color settings for `inverted/secondary/pointing` menus:
- `secondary pointing menu`: A colored active item went to black on hover
- `inverted secondary pointing menu`: non-active items went to black on hover
- Colored `inverted pointing menu` had black or half transparent pointer
- Active item on `inverted secondary pointing menu` had a background color
https://jsfiddle.net/b6z45ru3
https://jsfiddle.net/tqn4yub6/1/ (all colors example)
https://jsfiddle.net/b6z45ru3/1/
https://jsfiddle.net/tqn4yub6/2/ (all colors example using a precompiled dist-css)
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/59159482-7a379280-8aca-11e9-9344-8ffe9f907269.png)|![image](https://user-images.githubusercontent.com/18379884/59159490-950a0700-8aca-11e9-8 …
> fix(menu): hover & active state colors on inverted secondary pointing

- tasks/config/tasks.js
- Removes warning from the latest version of Autoprefixer
- The warning which gets removed looks like the following:
> Replace Autoprefixer browsers option to Browserslist config.
>   Use browserslist key in package.json or .browserslistrc file.
> 
>   Using browsers option cause some error. Browserslist config 
>   can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> 
>   If you really need to use option, rename it to overrideBrowserslist.
> 
>   Learn more at:
>   https://github.com/browserslist/browserslist#readme
>   https://twitter.com/browserslist
See: [browserslist](https://www.npmjs.com/package/browserslist) for more information 
N/A
N/A
N/A
> build(autoprefixer): change 'browsers' setting to 'overrideBrowserslist'

- src/definitions/modules/checkbox.js
The usual behavior of a standard (non FUI / html default) checkbox is to also get toggled by the SPACE key, but not by the ENTER key, when the checkbox is focused. 
But if a checkbox is initialized via the checkbox module of FUI it also allows to be toggled via the ENTER key by default.
This could lead into unwanted form submissions.
This PR adds a new setting `enableEnterKey` (default `true` to stay backward compatible), so one can make the FUI behavior match to the html default behavior of a checkbox
https://jsfiddle.net/6o8pvfe4/
#819
> feat(checkbox): add toggle on ENTER-key option

- src/definitions/elements/step.less
This PR reverts a small change from #216 (commit https://github.com/fomantic/Fomantic-UI/pull/216/commits/32c932b607d990f68fa51b58b3172d56a867f031), which was (by accident) also removing the pointer step on (horizontal and non active) steps .
https://jsfiddle.net/f10pvax3/
#830
> fix(step): step visualization also on non active

- src/definitions/modules/dropdown.less
This PR fixes the bad icon alignment in sized form's dropdowns. Icon `font-size` was overwritten by a rule in form.less, so I just increased the `.icon` weight in `dropdown.less` (hope this sentence is understandable...).
[![85b12e6759daf68101a38f093dcc80d7.md.png](http://tof.cx/images/2019/06/28/85b12e6759daf68101a38f093dcc80d7.md.png)](http://tof.cx/image/Yw4j9)
[![779d8d11540e33ad377f6c3fc1326eca.md.png](http://tof.cx/images/2019/06/28/779d8d11540e33ad377f6c3fc1326eca.md.png)](http://tof.cx/image/YwpSv)
#837
> fix(dropdown): correct clear icon alignment

- src/definitions/collections/form.less
Labels of `inline` fields within a form kept their black label color even when the field is marked as `error`
I also tested against other used labels like `checkbox` or `corner` but those specificity is not affected
https://jsfiddle.net/q2bowsne/1/
#818
> fix(form): inline field label doesn't respect error styles

- src/themes/default/elements/flag.overrides
RTLCSS which creates the Right-To-Left language support versions (semantic.rtl.css) incorrectly converts background-position: 0 ... to background-position: 100% .... Which breaks the flags.
This is expected behaviour in RTLCSS, see:
MohammadYounes/rtlcss#109
And the correct solution is to tell RTLCSS to ignore that section.
Adds in rtl:ignore directives see: https://rtlcss.com/learn/usage-guide/control-directives/
https://jsfiddle.net/1f4qbLa7/
#859
> Tell RTLCSS to ignore flag icon background-positions. Fix #859

- src/definitions/collections/form.less
- src/themes/default/collections/form.variables
Make the top margin for checkboxes smaller when there's a label
https://jsfiddle.net/1kobehda/
#823
> label + .ui.checkbox

- src/definitions/elements/image.less
A `hidden image` inside a `ui images` group hasn't got enough specificity to be hidden when not also used together with a `transition`.
You should not see any image
https://jsfiddle.net/2fy3gLaw/1/
Remove the CSS and one image , which is inside the group, will be shown
https://github.com/Semantic-Org/Semantic-UI/issues/6827
> [Image] Hidden images were still visible when used in image groups

- src/definitions/behaviors/form.js
The form template function used to create error labels was using a string literal instead of the `className.label` setting.
Before: https://jsfiddle.net/snkr9d4p/
After: https://jsfiddle.net/cyxb2v3z/
Before:
After:
> fix(form): prompt template function

- src/definitions/modules/modal.js
I don't know if the project coding style guide recommends to remove trailing white spaces, but I get the feeling it does considering the other empty lines in `modal.js`
So just a little PR to avoid my editor editing this line when I hack Fomantic ;-)
> Removing traling white spaces

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
This PR adds support for image or icon properties to be used in json values for item data (either by `values` or most important by any API response)
This is done if the following optional key-properties for an item value are given
|Property|Content|
|-|-|
|image|url to the image to be displayed. If omitted, image code rendering is skipped|
|imageClass|individual className for the image (for example `ui avatar image`). Default is `image`|
|icon|name of the icon/flag to be displayed. If omitted, icon code rendering is skipped|
|iconClass|could be changed to `flag` here. Default is `icon`|
```json
{
"name": "Avatar",
"value": "jenny",
"image": "https://fomantic-ui.com/images/avatar/small/jenny.jpg",
"imageClass": "ui avatar image"
},
{
"name": "Image",
"value": "elliot",
"image": …
```
> [Dropdown] Support icon and or image settings as json properties

- src/definitions/modules/dropdown.js
`set selected` toggles rather than adds values on multiple value dropdown that has `useLabels: false` setting.
Click on the blue button to trigger a `set selected` 
- The values toggle between selected and unselected
https://jsfiddle.net/a5j7u231/
- values are selected / kept being selected all the time
https://jsfiddle.net/k8oqpjgx/1/
#670
> [Dropdown] Don't toggle on "set selected" when no labels are used

- src/definitions/modules/search.js
When defining custom searchFields the $('.ui.search').search('get result', value)  do not use the user defined values, it uses the default ones.
This is because the default array is passed and the user setting are not used in line 616
``            searchFields = (searchFields !== undefined)
? searchFields
: settings.searchFields
;
``
https://jsfiddle.net/venturaEesc/q3p1b52t/13/
https://jsfiddle.net/2db9gf7u/
https://jsfiddle.net/venturaEesc/q3p1b52t/4/
https://jsfiddle.net/2jx6bhd8/
#897 
https://github.com/Semantic-Org/Semantic-UI/pull/6023
> [Search] Behavior 'get result:' Support numerical fields and make use of user defined searchFields

- src/definitions/modules/popup.js
This PR adds a new optional setting `forcePosition` (default `false` to stay backward compatible) to the popup module.
Before this PR the popup module always tries to recalculate a given `position` setting, in case the popup wouldn't be completely visible. if now `forcePosition: true` is used, the `position` setting will definately be used, regardless if it's completely shown or cropped. This could help in situations for the calendar module because the (non-inline) calendar is a popup itself and disturbs wanted UI behavior.
Reduce output viewport, so calendar would fit to the right, but not to the bottom (see screenshots)
https://jsfiddle.net/0cxn2gy3/
Given:  `position: 'bottom left' `
- Position is ignored, because the calendar does not fit to viewport on bottom left
- Displayed at …
> [Popup] Optional setting "forcePosition" to disable calculation, even if popup will not fit

- src/definitions/collections/table.less
- src/themes/default/collections/table.variables
A colored `definition table` was still showing the table color border on the top left cell (which is not used on definition tables by design)
I first thought it was enough to change the background, but IE/Edge still showed the border on zooming, thats why i still had to use and adjust the box-shadow
https://jsfiddle.net/gc15zfku/
#883 
https://github.com/Semantic-Org/Semantic-UI-React/issues/3710
> [Table] Colored definition table shows overlapping border in top left cell

- src/definitions/modules/checkbox.less
- src/themes/default/globals/site.variables
- src/themes/default/modules/checkbox.variables
Checkbox was the only form/input element left which did not support sizes or inheritance of form sizes
https://jsfiddle.net/wtrxjupk/
- Remove CSS to see issue
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/61568422-7e6cad80-aa83-11e9-8b72-d9d4a4dd6327.png)|![image](https://user-images.githubusercontent.com/18379884/61568456-a22ff380-aa83-11e9-9b0b-aa675533bbef.png)|
|![image](https://user-images.githubusercontent.com/18379884/61568382-51b89600-aa83-11e9-92a7-a82eeb8be231.png)|![image](https://user-images.githubusercontent.com/18379884/61568325-174ef900-aa83-11e9-999e-4cbd8c655ab9.png)|
#666 
https://github.com/Semantic-Org/Semantic-UI/issues/3941
> [Checkbox] Support sizes and form size inheritance

- src/definitions/modules/dropdown.js
When a dropdown was setup out of a `select` tag and had empty <option> values set but used something different than `placeholder: 'auto'`, the initial clearable icon was shown, although the initial value was "" (= no selection)
https://jsfiddle.net/dfp09hLz/
https://jsfiddle.net/pn12f3Lr/2/
#839
> [Dropdown] Corrected initial clearable icon when <select> was used for conversion

- src/definitions/modules/dropdown.js
This PR adjusts the fix implemented by #188 
The implemented `preventDefault` avoided a dropdown by reopening when clicking on the associated label instead of the dropdown itself.
Unfortunately this also stops other events in some situations which do not belong to the dropdown itself.
This PR now only prevents the event when the special case of the associated label was the target.
This example is taken from the related issue #861 
- Choose something from the dropdown
- It is going to replace the whole dropdown adding an additional form (which is not related DOM-wise to the dropdown)
- Clicking on the form submit button ...
... does not trigger the event (see console, it should read "event")
https://jsfiddle.net/fpr4joez/4/
.. triggers the event as expected
https://jsfiddle.net/m51q6oje/ …
> [Dropdown] Only preventdefault on hide for associating labels

- src/definitions/modules/accordion.js
A `loading transition` moves into invisible area, which is correct behavior.
However when some content, like a form or segment, got the `transition` class after getting animated and you try to add the `loading` class onto it (for example to show a loading form or segment), the loader and whole content vanishes, because the transition class is still set and prevents the loading display.
Exactly that happens in the accordion module when child elements are getting animated. They keep the `transition` class.
This PR now removes the `transition` class after show-animation finishes (only there! hidden transition must be kept!) to prepare the element for usage of a `loading` class again. This is a safe action, because any additional animation (opening/closing accordion) will always re-add the …
> [Accordion] Remove transition class after animation to make conten loader work again

- src/definitions/elements/container.less
A `fluid container` is supposed to always have 100% width without any margin.
This is so far working until the screen gets < 768px, then a margin appears.
This PR makes sure a `fluid` is always respected.
While we are at it, this PR also removed the `!important` from the container settings and used  class-specificity levels instead where necessary.
Scale your browser window until it gets the size of <768px (or switch to mobile view in dev-tools)
> It also shows all other container combinations to proove the specificity after removing the !important statements, is still working correctly (But please test yourself)
... fluid container gets a margin
https://jsfiddle.net/pmbL25r4/5/
https://jsfiddle.net/pmbL25r4/5/show
... fluid container keeps zero margin
https://jsfiddle.net/pmbL25r4/4/ …
> [Container] Respect fluid container on mobile screen and remove !important

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
Whenever a dropdown was created out of a `select` tag, any possible existing `optgroup` groups were ignored.
This PR now supports
- option groups of select tags being converted into dropdown group headers
- manual values and API response settings by new optional item attributes `divider`, `class`, `header`, `icon`
- optional usage of `ui horizontal divider` instead of the usual (since then hardcoded) `header`
- optional display a divider line underneath a usual header
- display of a group header icon either by central setting `groupIcon` or individually as item value
- usage of colors or sizes of when `ui header` is used (needs CSS recompilation, that's why the testcase does not show it)
- display of a possible group header at first position when nothing is selected and menu gets opened
- …
> feat(dropdown): add select optgroup and horizontal divider support

- src/definitions/modules/dropdown.js
This PR fixes to enter something in input fields within dropdowns when it's not the search input
- Open the dropdown and try to click into any of the three entries
- First two entries open the calendar but loose focus immediatly so entering dates manually is not possible
- Third entry is just a simple input field which is also not clickable because it looses focus
https://jsfiddle.net/g19fdp7s/2/
- All entries changable as expected
https://jsfiddle.net/g19fdp7s/1/
#937
> [Dropdown] Keep input field focus if it's an menu item 

- src/definitions/modules/progress.js
I propose to store unrounded percents in the `data-percent` attribute instead of rounded percents.
Here is what causes the wrong error.
① Store rounded percents in the `data-percent` attribute [here](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/progress.js#L483)
② Get the rounded percents [here](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/progress.js#L165)
③ Validate sum of the rounded percents  [here](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/progress.js#L513).
As [this comment](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/progress.js#L514) indicates, it is not expected to pass rounded percents to the `percent()`.
https://jsfiddle.net/yxLr6mut/
#953
> fix(progress): wrong error on validating sum of rounded percents

- src/definitions/modules/tab.js
This PR activate automatically the first tab if no active tab is specified trough the `active` class.
Before: [JSFiddle](https://jsfiddle.net/t6we9gv8/)
After: [JSFiddle](https://jsfiddle.net/kLzqex81/1/)
#914
> feat(tab): auto activate first tab if no active specified

- src/definitions/modules/slider.js
- src/definitions/modules/slider.less
This PR adds dynamically adjusted labels to sliders, which will avoid unreadable labels when there's too many on screen.
It works by calculating the labels which respect a minimal distance between them (adjustable trough the new setting `labelDistance`; default `100`). All intermediate labels still exists, but they don't display a value, and their tick height is half sized.
This new feature can be disabled by setting `autoAdjustLabels` to `false`.
Oh, and the labels are also adjusted on window resizing too.
Before: [JSFiddle](https://jsfiddle.net/Lopwyghd/)
After: [JSFiddle](https://jsfiddle.net/xj827hfw/)
#913
> feat(slider): add auto adjusted label display

- src/definitions/behaviors/form.js
When a `calendar` was used within a `form` and the forms `set values` behavior was used, the calendar got only the textual representation of the given date without actually using the date itself. Therefore the calendar internally still had the old value.
https://jsfiddle.net/dbLr687e/
https://jsfiddle.net/dbLr687e/1/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/64007592-bb14d580-cb14-11e9-85b4-28a15af49869.png)|![image](https://user-images.githubusercontent.com/18379884/64007887-455d3980-cb15-11e9-99d7-0ad1229d7a41.png)|
#980
> fix(form): 'set values' behavior had no proper calendar support

- src/definitions/modules/dropdown.js
If you have a dropdown with a search term and `forceSelection:false` and a given search value not matching any dropdown entry, setting the value of the dropdown with "set selected"/"set exactly" afterwards, did not remove the search term making the selected value overlay the search term.
Enter random text into the dropdown (don't select an item from the list)
Click the button "Click Me"
https://jsfiddle.net/twe78h0n/
A value is selected (Graphic Design), but the search term does not get removed.
https://jsfiddle.net/twe78h0n/1/
A value gets selected (Graphic Design), and the search term gets removed.
|Broken|Fixed|
|-|-|
|![dd_remove_term_bad](https://user-images.githubusercontent.com/18379884/64185877-28569c80-ce6e-11e9-8b39-a99759c6cabf.gif)|![dd_remove_term_good](https://user-images.git …
> fix(dropdown): setting value of dropdown did not remove search

- src/definitions/modules/calendar.js
This PR aim to fix (or at least drastically reduce) the broken date format when it's typed through keyboard. It's a bit hacky, since it only reverse supposed days and month when the setting `monthFirst` is defined to `true`, but I think this little piece of code will cover 98% of cases.
Before: [JSFiddle](https://jsfiddle.net/musjvb63/)
After: [JSFiddle](https://jsfiddle.net/z6ghfcv9/)
#829 
#986
> [Calendar] Fix broken dates when keyboard typed

- src/themes/default/elements/list.variables
> List component bullets appear as â€¢ instead of bullets utf-8 \2022.
> Problem was showing up in Android and iOS after using Cordova to create the app.
> Traced the issue and not a Cordova problem but a CSS issue.
> 
In usual browsers there is no visual difference, but using hex notation is a more clean implementation anyway
https://github.com/Semantic-Org/Semantic-UI/issues/6867
https://github.com/Semantic-Org/Semantic-UI-React/issues/2325
> [List] use hex notation for unicode character

- src/definitions/modules/calendar.js
This PR makes #995 crossbrowser compatible. The usage of dot was handled differently in javascript engines <> chrome/webkit based.
The replace itself was ok. But the following Date Object creation was handled differently.
To satisfy any browser i now replaced any given `/` or `-` or `.` by an /  so the `Date()` Object creation does never see anything else than a / and works identically everywhere now
https://jsfiddle.net/9caf67pv/
#829 
#986 
#995
> fix(calendar): cross browser support for dateparsing using dots

- src/definitions/modules/modal.js
First, i'm not sure this is the best solution, but it seems to fix the problem.
Second, this needs to be heavily tested, so don't approve it until you've tested many cases, please.
When modal is not detachable, it use the legacy display system, not flex based. So it calculates the position of the modal based on his window position, then apply a margin to center it. It works, when you don't have scrolled...
For me, the margin trick is not the best solution, so i tried to center the modal by calculating the top property instead (hope what I write is understandable), but with including the scroll position.
This is not a breaking change, but regarding the nature of the bug I think that we need to be careful with this PR.
Et voilà !
Before: [JSFiddle](http://jsfiddle.net/7j38xdbw/1/)
After: …
> fix(modal): vertical alignment on detachable modal was incorrect

- src/definitions/modules/tab.js
My previous PR #977 introduced auto activation for no specified tab. Except that each time you call the `.tab()` method for one of thoses tabs, it checks again and change the active one...
This fix just consist of checking if tabs were initializes before, so it doesn't have to recheck again...
[JSFiddle](https://jsfiddle.net/spj408zw/)
[JSFiddle (Fixed)](https://jsfiddle.net/bw89drqL/)
#1014
> fix(tab): do not auto activate tabs more than once

- src/definitions/collections/grid.less
removes important from stackable grid so that correct style compact grid is used
Broken:
https://jsfiddle.net/2tnp7vrb/2/
Fixed:
https://jsfiddle.net/8ftyua2g/1/
Broken:
Fixed:
#652
> fix(grid): fix padding on stackable compact grid on mob devices

- src/definitions/collections/table.less
- src/themes/default/collections/table.variables
This PR adds optional `left marked` or `right marked` to  table row `tr`.
This way a colored table row can be displayed with a small border bar instead of the whole row background
https://jsfiddle.net/j0x1cfqo/8/
#1030
> feat(table): add colored left & right row border

- src/definitions/modules/modal.js
When body direction was set to rtl, clicking on the scrollbar closed the modal.
This was fixed in #437 , but missed to support rtl environments.
http://jsfiddle.net/vz92gfLo/
http://jsfiddle.net/e59rqp8n/
#1087
> [Modal] Don't close modal when scrollbar is clicked in rtl enviroment

- src/definitions/modules/calendar.js
As reported in #901 that today button is also affected when select the end date because it's toggle when that's in range or not.
So I created helper `isTodayButton`, that check text inside the cell if that same with `settings.text.today`. If return true then don't toggle the range class.
https://jsfiddle.net/t7f50Lk8/
https://jsfiddle.net/t7f50Lk8/1/
#901
> fix(calendar): prevent toggle range class at today button

- src/definitions/modules/modal.less
The bottom margin of scrolling modals was only working in Chrome. Turned out that IE, Edge and Firefox were ignoring it, because the modal DOM node is moved by the modal module  to become the last node of the body. 
Fixed it by adding a pseudo element with a height (not margin, because margin was still not working there!) Also, firefox was still ignoring it unless the content value had at least one character (but space was also ignored!), so i used a non-printable, thus invisible character instead to also convince Firefox  😄 
The additional pseudo element however is swallowed by chrome (because chrome respects the given margin), so it looks the same everywhere now 🙂 
https://jsfiddle.net/zt0cfo6d/1/
#1075
> fix(modal): make bottom margin scrolling modals work in firefox & edge

- src/definitions/modules/modal.js
- src/definitions/modules/modal.less
- src/themes/default/modules/modal.variables
This PR enhances the fix by @prudho and corrects positioning calculation when `detachable: false` was used together with large modals.
This now works in any possible combination: detachable true/false, useFlex: true/false, top aligned, bottom aligned
http://jsfiddle.net/5er1f3va/2/
#1079 
https://github.com/Semantic-Org/Semantic-UI/issues/4676
> fix(modal): correct undetached positioning when large modal is used

- src/definitions/modules/dropdown.js
`ignoreCase` was only used for affecting the label creation. ~This MR makes the filtering respect that setting, for both searches, on text and value.~
Instead or reusing the same variable, as that would introduce a breaking change where none of the current users will have case insensitive search, this MR adds a new setting that allows setting the case sensitivity for the item filtering
before: https://jsfiddle.net/3we8nb7j/
after: https://jsfiddle.net/ye1hg6c4/
#932
> feat(dropdown): add case sensitivity setting for search

- src/definitions/modules/dropdown.js
Closes https://github.com/fomantic/Fomantic-UI/issues/997
The blur event for dropdowns that allowed additions wasn't calling the regular event handler, and it was bypassing some of the preprocessing, checks and side effects, like sanitization or flushing the values.
broken: https://jsfiddle.net/Lxv71m8k/
fixed: https://jsfiddle.net/cyL5r09k/
#997
> fix(dropdown): use regular event handler for allowAdditions input blur

- src/definitions/modules/dropdown.js
- Create a dropdown with an API search and minCharacters set to something >1
- Enter something into the dropdown, so API search get triggered
- After a response from the server, deleting some characters from the searchfield, so they get less as defined in the `minCharacters` setting
- Menu hides but field gets blurred
http://jsfiddle.net/4tacdvLq/1/
http://jsfiddle.net/4tacdvLq/2/
#1089
> fix(dropdown): prevent blur when hiding dropdown directly after search

- src/definitions/behaviors/form.js
When using the behavior `set value` or `set values`, checkbox elements were only supporting a real boolean `true` to check any checkbox.
This PR additionally supports the integer value `1` to have a checkbox checked now.
https://jsfiddle.net/6eL31k90
https://jsfiddle.net/6eL31k90/1/
#987
> feat(form): accept 1 in addition to true as checked value for checkboxes

- src/definitions/behaviors/form.js
- src/definitions/modules/dropdown.js
When a form is cleared or reset any existing dropdown field triggerd revalidation (all other type of fields don't, as expected)
- Create a form which has a dropdown
- Define the form to trigger validation on change event by using `on: 'change'`
- Define  the 'empty' rule to the dropdown
- Select something from the dropdown
- Clear or reset the form
-> Dropdownfield was cleared, but validation appears because the change of an empty value in dropdown always triggers the change event, which in turn calls an existing form validation
https://jsfiddle.net/6voLqgm0
https://jsfiddle.net/6voLqgm0/2/
#778
> fix(form): dont trigger change for dropdown when form is cleared

- src/definitions/modules/progress.js
When using any of the following behaviors, the progress bar is always set to 100%.
- `set error`
- `set warning`
- `set success`
In some cases it might be a desired feature to keep the state instead
This PR adds support for another parameter `keepState` to those behavior calls to make this possible. If the parameter is omitted (as in all existing applications) the progressbar is still working as before for backward compatibility.
```javascript
//as before: will set to 100%
$(.ui.progess).progress('set error');
$(.ui.progess).progress('set error','oups');
//stay at the current percentage state
$(.ui.progess).progress('set error','oups',true);
$(.ui.progess).progress('set error',null,true); //null, if label should not be changed
```
https://jsfiddle.net/d3wc8p5m/
> feat(progress): made setting to 100% optional when set error/warning

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Help_wanted.md
Added `labels` property to GitHub issue template, so new issues are labeled automatically.
This may reduce triaging effort from maintainers.
<del>For "Bug Report" template, no label are automatially added.
Because I think an existing label ":bug: Confirmed Bug" should be manually added.
(Maybe we change our workflow to automate "bug" labeling?)</del>
TIPS) It also allow attaching multiple labels in a form of comma-separated `labels: "labelA, labelB"`.
You may try new template from:
* https://github.com/fomantic/Fomantic-UI/issues/new?template=Feature_request.md&labels=:zap:%20enhancement
* https://github.com/fomantic/Fomantic-UI/issues/new?template=Help_wanted.md&labels=:thought_balloon:%20usage%20question
* https://github.com/fomantic/Fomantic-UI/issues/new?template=Bug_report.md&labels=: …
> chore(templates): add labels to new issue to reduce triage effort

- src/definitions/behaviors/form.js
Wow, that one was quite hard to find out... 
This PR fixes a behavior when non JS initialized components were used in forms. Especially checkboxes were affected.
The dirty-events were triggered on appropriate `change click keyup keydown blur` events.
By using jQuery's `.trigger()` method it was not only triggering the wanted `.dirty` events, but also any existing behavior having the same name. Unfortunately it exists jquery's `.click` method, which was now also called whenever a raw (non JS initialized) component like checkbox was clicked. 
This resulted in un-clicking the checkbox immediatly when it was clicked. Thus clicking on it had no effect.
Whenever a form component already was initialized by JS before, this was not happening, because there the click-event was explicitely handled …
> fix(form): trigger correct dirty handlers to fix function of checkboxes

- src/definitions/elements/input.less
When icon inputs where used inside of menus their padding was not correct anymore because of too low specificity
https://jsfiddle.net/uyqwskfj/1/
https://jsfiddle.net/uyqwskfj
> fix(input): icon inputs have wrong padding when inside menus

- src/definitions/modules/dropdown.less
Since 2.7.7 the dropdown icon adjustments got increased specificity by #838 
Unfortunately this also had impact if the dropdown was used in combination with a `labeled button`
I had to revert the specificity increase, but the additional `:not(labeled)` fixes the previous issues as well (and keeping the additional `.icon` would have messed up general dropdowns in combination `:not(.labeled)` then.
So this PR should fix all three issues now (tested by using the fiddles from the original issues and modding via developer console tools)
https://jsfiddle.net/ytsm9xc5/
https://jsfiddle.net/ytsm9xc5/2/
#1058 
#837 
#458
> fix(dropdown): dont adjustment dropdown icon when inside a label button

- src/definitions/modules/slider.js
Slider was triggering events when initialized, which is not the wanted behavior by default. So I just added a `fireOnInit` parameter (default `false`), to implement it properly.
Before: [JSFiddle](https://jsfiddle.net/jgwkd75c/)
After: [JSFiddle](https://jsfiddle.net/vut1bocm/)
#1000
> fix(slider): add fireOnInit parameter to prevent events being triggered

- src/definitions/modules/slider.js
Adds a new setting called `preventCrossover` which prevents the lower thumb to crossover the upper thumb.
This is set to `true` by default, making this a breaking change.
Does not prevent calling `$("#slider").slider("set rangeValue", 50, 25);`
https://jsfiddle.net/nb4x7ukm/2/
#1021
> [Slider] preventCrossover setting for range sliders

- src/definitions/modules/dropdown.js
When in multiple selection dropdowns a value is selected, the amount of parameters provided to the `set value` method is not matching. It provides 4 values instead of 3 expected, therefore inconsistent, and because of this also in wrong order. Four parameters are never used anywhere else and not even documented:
Providing the additional single value is not necessary because there also exists the `onAdd` event fetching that value and in multiple dropdowns its only the  value itself that counts.
https://jsfiddle.net/onp7vtwz
https://jsfiddle.net/onp7vtwz/1/
> fix(dropdown): parameter count resulted in wrong data for onchange

- src/definitions/modules/dropdown.js
Whenever a `search dropdown` having `forceSelection:false` gets a value which does not match one of the dropdown menu items, the search term stays visible when blurring the search input field.
I think, this is fine only when such value is supposed to be added and thus used as current value when `allowAddition:true` is set.
To avoid confusion and also because the behavior `get value` won't return the unmatching searchterm anyway when `allowAdditions:false` (which is default), i removed the searchterm in case the search field is blurred then.
Enter anything into the dropdown field which does not match the menu items
http://jsfiddle.net/15py2t7a/
```javascript
// Should keep the searchtearm visible (it's used as current value)
forceSelection : false, …
```
> fix(dropdown): remove searchterm if nothing matches & opts are disabled

- src/definitions/modules/dropdown.js
This PR adds the possibility to provide a second parameter `preventFocus` to the `show` behavior method.
That second parameter controls if a search dropdown should be _prevented_ to be focussed on open 
(default false/undefined to stay backward compatible)
This might be useful to prevent 
As the `show`  method already got an optional `callback` parameter, you have to provide at least `null` (if no real callback is necessary) as a first parameter, before providing `true` as the second parameter for the focus prevention.
```javascript
$('.ui.dropdown').dropdown('show',null,true);
```
Click the second button, it will open the bottom right dropdown and...
... scrolls to it because search field is getting focused
https://jsfiddle.net/ad1h8u03/
... does not scroll
https://jsfiddle.net/ragfLzky/ …
> feat(dropdown): optional skip focus when calling 'show' behavior

- src/definitions/modules/calendar.js
This PR actually provide two things:
- a new callback, called `onBeforeChange`, which allow to cancel a change before it's applied to calendar logic. The old `onChange` callback is now moved further.
- a fix to the `onChange` callback. His position was bad, since the date wasn't really changed internally when it was called, so any call the one of the behaviors or using the input resulted in a bad value.
⚠️ This is a breaking change ! The new `onChange` callback, doesn't allow to cancel change anymore, so we might warn users when we'll publish this update.
Before: [JSFiddle](https://jsfiddle.net/a28ruv0x/1/)
After: [JSFiddle](https://jsfiddle.net/rL6ukpz1/)
#417 
https://github.com/mdehoog/Semantic-UI-Calendar/issues/124
> feat(calendar): add onBeforeChange callback and fix a date value issue

- src/definitions/modules/popup.js
When a popup was defined to get its content out of an existing DOM-Node it was in some situations wrongly reused on another, totally different popup because the popup-creation  code was searching for existing nodes _before__checking for a specific domnode. That way a previously detached domnode from another  popup was used by accident.
This PR switched priorities to always check for a specific defined DOM node in `settings.popup` before looking for an existing dom node next to the popup.
https://jsfiddle.net/61L98vxt
https://jsfiddle.net/61L98vxt/1/
|Wrong|Fixed|
|-|-|
|![6331_bad](https://user-images.githubusercontent.com/18379884/67151925-d3f86680-f2cd-11e9-9d3f-1b40a0692db7.gif)|![6331_good](https://user-images.githubusercontent.com/18379884/67151926-d955b100-f2cd-11e9-8dde-dcda0b254ebe …
> fix(popup): avoid detection of wrong existing popup

- tasks/config/defaults.js
The permission value in the install task was set as integer, whereas gulp chmod expects an octal value.
@ColinFrick already implemented a conversion in case the value was given as string, so i just put the value in quotes 😄 
#1153
> [Task] Make sure permission value is tranformed into correct octal value for gulp chmod

- src/definitions/modules/slider.js
When jquery 2 is used together with FUI the `changedTouches` or `touches` property was not attached to the event object, but still exists at the `event.originalEvent` Object.
Slider was always expecting it at the event object which results in a JS error when trying to move the slider using touch devices.
This is especially the case when trying to simulate touch devices using chrome developer tools.
I also removed the completely unused second originalEvent parameter in all event handlers , just because it is never provided by any jquery version and always undefined. instead `originalEvent` is always provided as a child of `event` itself.
Why support jquery 2? Because this might be bundled with other packages like wordpress.
- Open any of the below testcases in chrome
- open developer tools …
> [Slider] Fix touch events handling when jquery 2 is used 

- src/definitions/views/card.less
The border radius of an image in horizontal cards always assumes that the image is positioned to the left. If its placed to the right, the border radius was wrong.
https://jsfiddle.net/esk27L1m/
> [Card] Right images in horizontal cards had wrong border radius

- src/themes/default/views/card.variables
Horizontal cards had a too strong minimum width, so they got cut on small mobile screens
https://jsfiddle.net/84ga57xd/show
- Open the fiddle on mobile device or switch to mobile view in developer  tools
- Remove CSS to see the issue
#828
> [Card] Horizontal cards on mobile got cut

- src/definitions/modules/slider.js
A `labeled slider` which is hidden , for example inside an accordion, and  autoadjusts its labels (default) will freeze the browser, because the calculation gets stuck in an endless loop.
Reason: the calculation uses the current tracklength, which is 0 when the slider is hidden, not letting the while loop end and get stuck forever.
Beware: This will just freeze the browser and loads forever. (Use a separate browser window, which you can kill safely)
https://jsfiddle.net/dqn2sb1L/1/
https://jsfiddle.net/dqn2sb1L/
#1140
> [Slider] Hidden sliders render in an endless while loop freezing the browser

- src/themes/default/elements/emoji.variables
Change the emoji path to use svg instead of png to stop pixelation when using larger sizes.
Before:
After:
> fix(emoji): change emoji path to use svg

- scripts/nightly-version.js
The nightly build is using the wrong beta version. It's increasing the
build version continuing from the past beta release instead of starting
from 0 for a new version.
#1171
> build(actions): correct nightly build version

- src/definitions/elements/emoji.less
- src/themes/default/elements/emoji.overrides
- src/themes/default/elements/emoji.variables
- src/themes/default/globals/variation.variables
- src/themes/joypixels/elements/emoji.overrides
- src/themes/joypixels/elements/emoji.variables
- src/themes/twitter/elements/emoji.overrides
- src/themes/twitter/elements/emoji.variables
Emojis did not respect the font size of their element they were in.
That's because they are not a font.
This PR 
- makes it possible to adjust the emojis according to the font-size of the element they are integrated
- also respects paddings in buttons/labels now when they contain emojis
- makes the usage of colon (`data-emoji=':smile:'`) and no-colon (`data-emoji='smile'`) based usage optional to be able to reduce the generated CSS even more
https://jsfiddle.net/987rwnLq/
https://jsfiddle.net/hqgr29dj/
> fix(emoji): make emoji inherit font-size so they don't get cropped

- src/definitions/elements/input.less
Cause: `color` was wrongly used instead of `borderColor`.
#1181
> fix(input): action input border color in state fields

- src/definitions/collections/table.less
A sortable table always showed a background in its sortable headers .
`(very) basic` tables instead are supposed to not have any background in their table header rows at all
https://jsfiddle.net/tsynqk3L
https://jsfiddle.net/tsynqk3L/1/
#1194
> fix(table): dont show background on sortable headers if table is basic

- src/definitions/collections/form.less
When there is a fields class in another fields class, an extra margin-bottom is added.
Thanks to @dutrieux , who already provided the fix in the related issue 😄 
https://jsfiddle.net/ya4b9prt/
Remove The CSS to see the issue
#1202
> fix(form): avoid additional margin with nested fields

- src/definitions/collections/form.less
`.ui.input` in `.ui.form` has border-radius at all corners.
https://github.com/fomantic/Fomantic-UI/blob/2f3312f0f075e3a570dc96725be17e965b3b0964/src/definitions/collections/form.less#L411
Unfortunately, this override brings border-radius to `.ui.action.input`.
This PR removes border-radius from `.ui.action.input` in `.ui.form` where radius not needed.
https://jsfiddle.net/qdp6gxLy/1/
#1184
#1185
> fix(form): action input had wrong border radius in some cases

- src/definitions/modules/dropdown.js
On mobile devices a clearable icon was not  working. The mobile browsers do not seem to fetch/interpret the existing "click" event as a "touchstart" event.
I centralized the eventbinding and whenever a touchdevice is recognized it (in most cases) used `touchstart` instead of `click` not, which makes the clearable icon work now :)
I had to leave one `click` event as it is to prevent a item selection on mobile when you try to scroll the menu list
- Open in a mobile device, especially iOS
Clearable icon does not work
https://jsfiddle.net/tnk79L1q/show
Clearable works now
https://jsfiddle.net/tnk79L1q/1/show
#647
> fix(dropdown): clearable icon is not clickable on mobile

- src/definitions/behaviors/form.js
While investigating on adding some autoset rules on required fields, I found that adding a rule trought the `add rule` behavior was overwritting existing rules.
This PR fixes this bad behavior and add some checks in the related function (checks if args are defined, check is a rule already exists...).
Before: [JSFiddle](https://jsfiddle.net/ohvu2q84/)
After: [JSFiddle](https://jsfiddle.net/jsmvop9h/)
> [Form] `add rule` was overwriting existing rules

- src/themes/default/globals/variation.variables
Just removed a duplicate variable declaration. The same variable is declared one line before already.
> fix(chore): duplicate variable declaration

- src/definitions/modules/popup.less
- src/themes/default/globals/variation.variables
When a popup is used directly from any html source, it inherits its default width by its parent container. width.
This leads into situations where popups appear too small and text wraps looking ugly
The only solution without changing existing html code is to give such popups a fixed width.
Therefore i added a new optional `fixed` variant.
This PR also supports css-only tooltips , so if `data-variation="fixed"` is used on `data-tooltip` the behavior is the same as for popups
https://jsfiddle.net/baukrwxq/
https://jsfiddle.net/pfdLt8aq/
#1213
https://github.com/Semantic-Org/Semantic-UI/issues/6434
> feat(popup): add variant to ensure width if parent container is to small

- src/definitions/modules/modal.less
- src/themes/default/globals/variation.variables
On larger screens an existing close icon of a modal is always displayed outside of the modal itself.
Only when using `fullscreen` it is put directly into the header by default.
To make this behavior possible for small modals on large screens as well i invented an optional class `inside` which can be added to the `close icon`
https://jsfiddle.net/m59p0wq1/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/70624645-031dbb00-1c21-11ea-8948-334cec249f4b.png)|![image](https://user-images.githubusercontent.com/18379884/70624676-14ff5e00-1c21-11ea-8a18-82401553dadd.png)|
https://github.com/Semantic-Org/Semantic-UI/issues/2873
> feat(modal): allow close icon to be inside header for small modals

- src/definitions/modules/popup.less
Safari up to 12.1 has a bug to sometimes not work when `transition: all` is used .
This leads into tooltips not working 
https://jsfiddle.net/n8jed76x/1
https://github.com/Semantic-Org/Semantic-UI/issues/6702
> fix(popup): tooltips don't work on safari <= 12.1

- src/definitions/modules/slider.js
Fixes a regression introduces in  4b1d54894c640896e6554358140e4578159a9bf4
The preventCrossover setting affected single sliders as well, which prevented them to slider correctly.
Before: https://jsfiddle.net/kj2m03f6/
After: https://jsfiddle.net/e5yt26bg/
#1231
> fix(slider): preventCrossover should only affect range sliders

- .github/workflows/nightly.yml
Add an `if` condition for the publish job so the nightly build only runs on the upstream repository.
> build(actions): stop nightly error on forks

- src/definitions/modules/dimmer.less
The change in #1027 changed the specificity. This lead into the border correction for partial dimmers in segments to not work anymore.
This PR increases their specificity so they are adjusted again.
I also removed the unnecessary `!important` settings for the `segment > dimmer` border settings
https://jsfiddle.net/q1Lfgpk2
https://jsfiddle.net/hq8tcs6w/
> fix(dimmer): borders on partial segment dimmers are incorrect

- src/definitions/modules/dropdown.js
This PR preserve the `data-text` attribute when creating the dropdown from a select, so the displayed text can be different than the in-dropdown text.
Before: [JSFiddle](https://jsfiddle.net/6hdtzybr/)
After: [JSFiddle](https://jsfiddle.net/1x4caqfm/2/)
#1103
> fix(dropdown): handle text metadata on select build dropdowns

- src/definitions/modules/dropdown.js
- src/definitions/modules/popup.js
- src/definitions/modules/search.js
- src/definitions/modules/toast.js
Dropdown values which are supposed to be encoded into htmlentities like `&lt;` were wrongly encoded whenever the values changed. Especially when working with mulitple selection dropdowns.
Reason for this was the overseen fact that an ampersand `&` was also encoded into `&amp;`. As htmlentities are in general encoded by starting with an ampersand aswell this was totally messing up the value string.
As the escape routine was also implemented in other modules, this PR fixes the logic there as well
https://jsfiddle.net/4cqtnf0d/
https://jsfiddle.net/yfgwph04/
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/70354235-5b466d00-186f-11ea-8406-f81b37e314ec.png)|![image](https://user-images.githubusercontent.com/18379884/70354164-3e119e80-186f-11ea-8332-f8fc820d234a …
> fix(dropdown): values are incorrect if they contain some special chars

- src/definitions/modules/dropdown.js
- src/definitions/modules/dropdown.less
- src/themes/default/modules/dropdown.variables
In #1112 a missing name of an selection option was fetched and replaced by the value instead when converting select tags into dropdowns.
But this is not the same behavior as for a usual html select where a missing name is rendered as an empty select entry (which of course still has its individual value)
The first  entry has a value but an empty name. Standard html select would keep the empty name, while...
... FUI replaces it with the value by default
https://jsfiddle.net/mons57e2/
... keeps an empty/non-existing name
https://jsfiddle.net/4oxpwhv2/
#1191
> fix(dropdown): do not use value as name when name is empty

- src/definitions/modules/checkbox.less
When any checkbox variant was disabled, it was still showing visual changes on hover which would indicate a possibility to change the checkbox (although greyed out and not possible)
Thanks to @tenKinetic , I adopted the PR idea from https://github.com/Semantic-Org/Semantic-UI/pull/6896 
https://jsfiddle.net/rn86ysde/
- Remove the CSS to see the difference
|Before|After|
|-|-|
|![checkbox_pointer_events_bad](https://user-images.githubusercontent.com/18379884/71528806-f9af7680-28e1-11ea-9e79-fbe76cbf61c0.gif)|![checkbox_pointer_events_good](https://user-images.githubusercontent.com/18379884/71528810-ff0cc100-28e1-11ea-847a-01665ddcc9b4.gif)|
> [Checkbox] dont show visual changes on disabled checkboxes

- src/definitions/elements/segment.less
Sub headers in inverted segments were not changed to white when inside content div of header
https://jsfiddle.net/ub3m5vsL/1/
https://jsfiddle.net/ub3m5vsL/2/
#1261
> fix(segment): sub headers in inverted segments were not changed to white when inside content div of header

- src/definitions/modules/modal.less
A Modal header has a bottom border. A `basic modal` instead should not ( the border for actions in basic modals is already removed,  and it just looks misplaced, especially when there is noticable background)
Using the default dimmer settings the dimmer color is identical to the bottom border, thus invisible.
However, when the dimmer has a different shade or is inverted, the border gets visible.
https://jsfiddle.net/z086mn1s/
> [Modal] Basic Modal header should not have a border

- src/definitions/modules/modal.less
The inner dimmer which covers a parent modal in case `allowMultiple: true` is used, didn't have a border radius. This results in visually removing the border from the modal itself.
Reomve the CSS to see the issue
https://jsfiddle.net/10dbpftg/
Look at the top left corner 
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/72664240-bd13fe00-39fb-11ea-9698-0043a1e6c01b.png)|![image](https://user-images.githubusercontent.com/18379884/72664234-a372b680-39fb-11ea-9de8-a368bf73cfdb.png)|
#1274
> [Modal] Border radius for inner dimmer should inherit from the modal

- tasks/config/tasks.js
Currently `gulp-autoprefixer` has forced settings via `overrideBrowserslist`, however it's not [recommended](https://github.com/postcss/autoprefixer/#options) and breaks best practices as it silently overrides user's settings. As user's settings in `package.json` for example are not respected there will be useless CSS properties for modern browsers, for example [existing config](https://browserl.ist/?q=last+2+versions%2C+++%3E+1%25%2C+++opera+12.1%2C+++bb+10%2C+android+4) includes even IE 10 😨
```bash
gzip-size button.css
12.6 kB
```
```css
-webkit-box-shadow: 0 0 0 1px transparent inset, 0 0 0 0 rgba(34, 36, 38, 0.15) inset;
box-shadow: 0 0 0 1px transparent inset, 0 0 0 0 rgba(34, 36, 38, 0.15) inset;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: …
```
> build(config): respect browserslist config

- src/definitions/modules/toast.js
In situations where a toast is going to be closed via Javascript while the hide animation is still in progress, access to the element is not possible anymore leading to a console.error
```console
semantic.js:23153 Uncaught TypeError: Cannot read property 'css' of undefined
at HTMLDivElement.onBeforeHide (semantic.js:23153)
at Object.hide (semantic.js:24414)
```
Click very fast on the second button and watch the console.
> Note: The transition message `Element is no longer attached to DOM. ` in some cases is still standard of fomantic and fetched so that does not matter here
Shows `Cannot read property 'css' of undefined` in some cases
http://jsfiddle.net/hgs9fzdx/8
It doesnt
https://jsfiddle.net/jas1896m/
> [Toast ]Make sure element does still exist before transition ends

- src/definitions/behaviors/form.js
This PR adds the ability to add automatically an 'empty' rule for fields that got the `required` class (or `checked` for checkboxes). It's disabled by default since I don't want it to be a breaking change, but can be enabled at initialization with `autoCheckRequired: true` or any time with the `.form('set auto check')` behavior.
It can handle all fields types, grouped fields as well, and is able to detect disabled fields or groups. Rule is added to others if there's already some defined, and isn't duplicated if already set.
[JSFiddle](https://jsfiddle.net/m2xaLgsz/)
#1094
> [Form] Auto add empty rule validation for required fields

- src/definitions/modules/shape.less
When doing CSS 3D transforms there is an old chrome bug which does not handle translateZ properly in some cases.
This had the side effect of not seeing some shape faces when transitions took place right after each other and seemed to be vanished
- Click the animation arrows quickly, so animation is stacked
- Remove the CSS to see the issue 
https://jsfiddle.net/gbem84ry/
|Before|After|
|-|-|
|![shape_bad](https://user-images.githubusercontent.com/18379884/73087190-6eba9f80-3ed2-11ea-9f21-435109926792.gif)|![shape_good](https://user-images.githubusercontent.com/18379884/73087203-737f5380-3ed2-11ea-9568-3b46cda625ce.gif)|
#1283
> [Shape] make sure chrome renders the z-translated faces properly

- src/definitions/modules/dropdown.less
If a search dropdown has an error class, the, the cursor is not properly visible when the field has focus
https://jsfiddle.net/84gdzxyh/
Watch the blinking Text cursor inside the dropdownfield
|Before|After|
|-|-|
|![errorcursor_bad](https://user-images.githubusercontent.com/18379884/73666019-66b4e980-46a2-11ea-989c-35247bcde5e7.gif)|![errorcursor_good](https://user-images.githubusercontent.com/18379884/73666028-6c123400-46a2-11ea-9512-64bd30c1d359.gif)|
#1235
> [Dropdown] Cursor in search field was barely visible when field has error class

- src/definitions/collections/menu.less
Colored active items in colored menus were not displayed colored because of too low specificity
https://jsfiddle.net/Ley9pt6v/2/
The active item is actually an  `orange active item`
#1321
> [Menu] Colored active items were not displayed colored

- src/definitions/modules/modal.js
This PR gives full control over the `useFlex` setting again.
Some combinations are not working for correct positioning, which was basically  fixed by #1079 and #1096
However, the fixes ignored a possible explicit given `useFlex:true` and always assumes `auto` instead (which makes sure the positioning will work all the time)
As it turned out [here](https://github.com/fomantic/Fomantic-UI/pull/1013#issuecomment-567530502) there are some usecases, where people need the explicit setting of `useFlex:true`, i reverted the logic for the `can.useFlex` method but added some debug warnings instead when unsupported combinations occur, because the positioning for `useFlex:true` will not work when:
- IE11 is used
- `detachable:false` is used
As the default of `useFlex` is `auto`,  existing code should …
> [Modal] Return control over useflex again, but provide unsupported debug warning

- src/definitions/collections/form.less
- src/themes/default/collections/form.variables
When a `ui calendar` is used within a `inline field`, its display was broken (shrunk and not inline)
I had to use a proper direct em setting to fix this, as the input field is inside the calendar component making the usual `width: auto` not work as for the other standard input form fields.
- remove the CSS to see the issue
https://jsfiddle.net/3payxo5h/1/
#1296
> [Form, Calendar] Calendar inline fields did not display properly

- src/definitions/behaviors/form.js
A form gets radio values wrong, if one of them has a value of `0`, but returns `false` instead
https://jsfiddle.net/designosis/hrj97xao/
https://jsfiddle.net/ab786gwe/
#1327
> fix(form): make a difference between value 0 and false for radio buttons

- src/definitions/elements/emoji.less
A `disabled link` emoji should not have a pointer cursor
https://jsfiddle.net/1fxmwk27/
https://jsfiddle.net/0vwx5hn8/
#1341
> fix(emoji): disabled link emoji should not have pointer cursor

- src/definitions/collections/table.less
The styling is sometimes broken in the `table`  element, when `rowspan` used. This confused later table rows which then usually have less columns.
As there is no way to look backward via CSS to find out if a previous column in a row was rowspanned and the table component is not a JS module, i invented a little helper class to solve this issue via pure html/css.
One just has to create a `<td>` node , where it is usually not necessary, and give it the new `rowspanned`  class. This will just hide it from the screen but all existing table classes are working again, because the amount of td remains the same just like if there was no rowspan used at all.
So, instead of
```html
<table class="ui definition table">
<tr>
<td rowspan="2">Category</td>
<td>Value 1</td>
</tr>
<tr>
<td>Message for …
```
> [Table] Invented a helper class to solve the styling logic when rowspan is used in tables

- src/definitions/elements/icon.less
Normal size of icon has not the same vertical-align and line-height of each other size
`vertical-align` and `line-height` always had the same value regardless of size....however the default size was missing those
#1371
> [Icon] medium/default font was missing general css properties

- src/definitions/collections/form.less
- src/definitions/elements/input.less
When `ui right action left icon input` is used, the current CSS selector is unclear and gets confused when also a `left icon` is used: The left corners are not rounded.
https://jsfiddle.net/allwe/5a3f06ps/1/
https://jsfiddle.net/jvhq9cLx/
|Broken|Fixed|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/77259710-c469b900-6c83-11ea-8b11-d6d89abfdf0e.png)|![image](https://user-images.githubusercontent.com/18379884/77259699-ac923500-6c83-11ea-9494-a2e445e54c64.png)|
#1377
> [Input] Better differ between left/right icon/action

- src/definitions/modules/modal.less
Modal module adds padding to ".description" block when window size less 769px.
Search blocks can contain ".description" inside. When search block is inside modal, then ".description" inside search breaks down on screen less 769px.
[Example](https://jsfiddle.net/xrgs3eyu/) (reduce the size of the browser window)
> fix(search) Fix padding it description when search inside modal

- src/definitions/behaviors/form.js
Currently, the code to detect a field is `disabled` cannot handle fields under `fieldset[disabled]`
Properly detect `disabled` with jQuery `:disabled` selector
https://codepen.io/jamesjav/pen/ZEGOMWO
Click "Validate" button, "baz" field should not have error since it won't be in form data.
> edited: added a test case from @lubber-de for radio buttons with first one disabled
#1345
> [Form Validation] fix "disabled" detection

- tasks/build/css.js
- tasks/build/javascript.js
- tasks/config/project/config.js
Individual components will have their .css/.js file generated under /dist/components, but are not included in semantic.css and semantic.js.
This is useful for including these components in your project only if you need them, while keeping the file size of the main .css/.js file as small as possible.
To make it work, create a new array in your semantic.json:
```
{
"components": [
...
],
"individuals": [
form,
modal,
step
]
}
```
Don't forget to remove these items from the regular "components" array.
This change should be fully backwards compatible. It only changes the src variable if an "individuals" array has been defined in the config.
> [Build] Allow individual components to be defined in config

- src/definitions/modules/modal.less
In case a `fluid` action button is used within a modal, it was not centered correctly because of the left margin. As fluid buttons occupy the whole width this PR removes the left margin in those cases
https://jsfiddle.net/kt85yapn/
#1405
> [Modal] Center fluid action buttons correctly

- src/definitions/modules/dropdown.js
When  `showOnFocus` was set to false but the dropdown was opened by clicking on the down arrow icon, then a focus of the input field afterwards was opening the whole menu once, which isn't allowed.
The `iconClicked` value needs to be reset whenever the dropdown list gets hidden which this PR is 
fixing.
- Click into the dropdown input field. It should **not** open because `showOnFocus=false` ✔️ 
- Click on the dropdowns down arrow. It should open the whole menu ✔️
- Close the menu by either clicking somewhere outside the menu or by the down arrow again ✔️ 
- Click into the dropdown input field again. It now opens the whole menu again (at least once) ❌  
https://jsfiddle.net/dutrieux/wqfnb7rj/
- Click into the dropdown input field again. It will **not** open the menu anymore as it should✔️ …
> [Dropdown] Prevent showing the whole list if showOnFocus is false

- src/definitions/behaviors/form.js
- src/definitions/modules/dropdown.js
This PR replaces the used jquery `trim` methods by its native vanilla javascript variant. As of jquery 3.5.0 the trim method gets [deprecated](https://github.com/jquery/jquery/pull/4461)
> fix(chore): replace jquery trim method with vanilla javascript (deprecated as of jq 3.5)

- tasks/build/css.js
- tasks/build/javascript.js
When defining individuals inside semantic.json, these components are added to the list of regular components inside the build function.
The problem is that this build function is also used by the 'watch' task to refresh individual files. So when running gulp watch with individuals defined, the src variable containing the path to the watched file is overwritten by the full list of components. The result is that each change triggers a full rebuild.
Not what we want, so I added an extra condition to the if statement that's changing the src variable. It seems the src variable is always passed as object when using watch.. So by checking if src is a string, it is only altered during regular build tasks.
> Prevent gulp watch task from refreshing all components

- tasks/config/npm/gulpfile.js
This PR imports the tasks under `tasks/collections/various` in the `gulpfile.js` that is installed, which then imports the `clean` and `version` tasks.
My team is looking to switch from Semantic UI to Fomantic UI because Fomantic is still actively maintained, but when we made the switch from Semantic UI to Fomantic UI I found that `gulp clean` wasn't working because the task isn't in scope.
I was thinking importing it in `gulpfile.js` should suffice, unless there is a reason it was left out.
> fix(build): Import 'various' gulp tasks

- src/definitions/elements/button.less
When icon is in button with animated, the margin-right & vertical-align & opacity is not the same when icon is in button without animated
__Icon without animated__ :
__icon with animated__ :
note: I use the last nightly build (08/04/2020) :
https://jsfiddle.net/dutrieux/a8mnz2yc/
fix issue #1409
> [Button Animated] Adjust vertical-align for icons & support ui.animated.icon.button

- src/definitions/modules/modal.less
- src/definitions/modules/progress.less
[Progress bar] indicating `background-color` is incorrect when `data-percent` have decimal number.
This problem only occur when the data-number have decimal and under 10.
https://jsfiddle.net/dutrieux/xoz2L4sw/
> [Progress bar] indicating background color is incorrect when data-percent have decimal number

- src/definitions/elements/step.less
- src/themes/default/elements/step.variables
As suggested by @ko2in , this PR adds support to display vertical step arrows to the left side by inventing a new `.ui.right.vertical.steps` variant
https://jsfiddle.net/3grpteq8/
Left steps: Usual steps as before
Right steps: new `right.vertical.steps`  variant
#1418
> [Step] Right vertical steps variant having the arrow to te left side

- src/definitions/modules/calendar.js
This PR allow to fire `onChange` only when a date selection if complete. For a datetime for example, onChange is called when a date is selected, then when a hour is selected, and again when minutes are selected... which is IMHO is a complete nonsense. If I apply a method when a date is changed, i'd prefer trigger this change only when i have finished to select my date...
Note 1: This may be labelled as a breaking change.
Note 2: This PR also include a small "refactor" of variables declarations I planned to publish later. As you know my git skills are legendary so revert this is really a PITA for me. As it's only minimal style change, do you mind if we let this PR as it ?
Select a date, then a time and then a hour.
Before: [JSFiddle](https://jsfiddle.net/cxb4ogzn/)
After: …
> [Calendar] Fire onchange only when date selection is complete

- src/definitions/modules/calendar.js
This PR fixes an issue where the popup would be called to be shown twice because the two modules are listening to the events to show the popup when only one should be. I've thus removed the calendar's listeners since the popup ones that should be expected.
This PR also fixes the end calendars' popup which were also getting called to be shown twice when using the default settings for input calendars. The calendar module was focusing the input which is triggering the focus event that is also listened by the popup module. With this PR, the popup's show method is called only if the listener is not on focus, so that the input can still be focused.
This can be a big performance issue on heavy DOM trees as the popup position calculation is very heavy.
https://jsfiddle.net/8qyenza2/8/
None
> [Calendar] Fix the popup show function getting called twice
