fomantic/Fomantic-UI

package.json, src/definitions/behaviors/state.js, src/definitions/views/card.less, tasks/install.js
7d76dae: See Semantic-Org/Semantic-UI#6414.
62c4c1e: Fixes Semantic-Org/Semantic-UI#6386
392854e: Fixes Semantic-Org/Semantic-UI#6323
651ad1d: Fixes Semantic-Org/Semantic-UI#6354, Semantic-Org/Semantic-UI#5801, Semantic-Org/Semantic-UI#5838, Semantic-Org/Semantic-UI#5985 and Semantic-Org/Semantic-UI#5667
=> Some fixes

src/themes/default/elements/flag.overrides
Fixes Semantic-Org/Semantic-UI#5145 and Semantic-Org/Semantic-UI#6400
=> [Flags] Fix wrong flag position for Myanmar / Burma

src/definitions/modules/dropdown.js
Fixes Semantic-Org/Semantic-UI#6404
=> [Dropdown] Adjust behavior of dropdown icon when search field is present

src/definitions/views/card.less
Fixes Semantic-Org/Semantic-UI#6320.
=> [Card] Icon containing class "card" misbehaves

src/definitions/modules/dropdown.js
Fixes Semantic-Org/Semantic-UI#6285
=> [Dropdown] Only update text if action is activate or combo

src/definitions/modules/dropdown.js
Fixes Semantic-Org/Semantic-UI#5817
=> [Dropdown] Only check option value to determine if option is selected

src/definitions/elements/segment.less
Fixes Semantic-Org/Semantic-UI#5408.
=> Fix last tab inside container which does not have correct bottom margin

src/definitions/collections/table.less
Fixes Semantic-Org/Semantic-UI#6311. Thanks @Apache02 !
=> [Table] Fix priority for td .disabled class

src/definitions/modules/dropdown.js
Performance regression because of the hideDividers option
Fixes #34
=> [Dropdown] Only select dividers if hideDividers option is true

src/definitions/elements/list.less
Was reported in Semantic-Org/Semantic-UI#6436
Thanks @Neketch
=> [List] Typo in selection list item:hover selector

CONTRIBUTING.md, README.md
Changed the `next` branch into `beta`
=> Next to beta

src/definitions/elements/icon.less
Additionally adds the halfway rotated variation
Closes issue Semantic-Org/Semantic-UI#6460
=> [Icon] Allow both rotated and flipped icons

src/definitions/modules/search.js
Fix #6442. Thanks **@ColinFrick** !
=> [Search] Add setting for error header in search results (Fix #6442)

src/definitions/modules/dropdown.js
Fix searchable dropdown that doesn't get focus on show
=> [Dropdown] Fix searchable dropdown that doesn't get focus on show

src/definitions/elements/loader.less, src/themes/default/globals/site.variables
This pull request is to implement various loader speeds to Fomantic-UI as requested at https://github.com/Semantic-Org/Semantic-UI/issues/6138
=> [Loader] Added loader speed variants

src/definitions/elements/label.less, src/themes/default/elements/label.variables
Fixed some ribbon labels having an incorrect background color and added primary & secondary colors.
https://github.com/Semantic-Org/Semantic-UI/issues/6497
=> [Label] fixed incorrect label background color

src/themes/default/elements/flag.overrides
Added `.uk` as an alias for the United Kingdom flag.
=> [Flag] added uk as gb flag alias

tasks/config/project/release.js
fix(build): fixed incorrect repo name
Changed the repo from SUI to FUI
Closes #84
=> [Build Tools] changed from SUI repo to FUI

src/definitions/views/feed.less
This PR add the `inverted` variation for feed.
Preview:
[![d674e61ba48a3de5982c2a618b9df95c.png](https://tof.cx/images/2018/08/14/d674e61ba48a3de5982c2a618b9df95c.png)](https://tof.cx/image/eTHY9)
=> [Feed] Add `inverted` variation

src/definitions/elements/step.less, src/themes/default/elements/step.variables
This PR add the inverted variation for step.
Preview:
[![fdf19380304b8957d84388b2289d003e.png](https://tof.cx/images/2018/08/16/fdf19380304b8957d84388b2289d003e.png)](https://tof.cx/image/ehR9a)
=> [Step] Add `inverted` variation

src/definitions/modules/dropdown.js, src/definitions/modules/dropdown.less
This PR simply allow multiple selection dropdowns to be cleared with a single click.
[![7da17d8e61f216fb9f1463bf7769263c.gif](https://tof.cx/images/2018/08/17/7da17d8e61f216fb9f1463bf7769263c.gif)](https://tof.cx/image/et9U4)
#66
=> [Dropdown] Add ability to clear multiple selection dropdowns

CONTRIBUTING.md
Fixed some typos in the CONTRIBUTING guide
=> Fixed some typos in the CONTRIBUTING guide

src/definitions/collections/message.less, src/themes/default/collections/message.variables
Closes #123 / Semantic-Org/Semantic-UI#6590
=> [Message] Add floating variation to colored messages

src/definitions/modules/toast.js, src/definitions/modules/toast.less
Just some small fixes prior to the Toast release:
- setting a high z-index for display the toast
- adding missing variables
=> [Toast] Small fixes

RELEASE-NOTES.md
Added changes missing in the release notes.
=> Add missing changes in release notes

src/definitions/modules/dropdown.js
Single selection Dropdown gained focus again after selection via keyboard ENTER
#153
=> [Dropdown] Single Selection via keyboard gained focus again Fixes #153

src/definitions/modules/progress.js
=> [Progress] Remove unused code

src/definitions/modules/dimmer.less, src/themes/default/modules/dimmer.variables
For those who think the dimmer default darkness/lightness is too heavy, here are some additional states `medium`, `light` and `very light`.
Works also in addition with `inverted` or `simple` and also for any Javascript 'variation'-property configuration where dimmer is used.
```html
<div class="medium dimmer"></div>
```
```javascript
$('.ui.modal').modal({
dimmerSettings: {
variation: 'very light inverted'
}
});
$('#mydiv').dimmer({
variation: 'medium inverted'
});
```
`dimmer` (as before)
`medium dimmer`
`light dimmer`
`very light dimmer`
`inverted dimmer` (as before)
`medium inverted dimmer`
`light inverted dimmer`
`very light inverted dimmer`
`inverted dimmer` (as before)
`medium inverted dimmer`
`light inverted dimmer`
`very light inverted dimmer`
=> [Dimmer] Additional intensity states very light, light, medium

src/definitions/elements/icon.less
Before :
[![c0738744c365befeb43cb160f058d65c.png](http://tof.cx/images/2018/10/17/c0738744c365befeb43cb160f058d65c.png)](http://tof.cx/image/NLJeZ)
After:
[![27b2d65bad48b312b17d3820f6ae06b3.png](http://tof.cx/images/2018/10/17/27b2d65bad48b312b17d3820f6ae06b3.png)](http://tof.cx/image/NLDl0)
#182
=> [Icon] Fix group icon corner positions

src/definitions/modules/calendar.js
Reverts fomantic/Fomantic-UI#198
=> Revert "[Calendar] Add timegap setting to expand time selector"

src/definitions/elements/segment.less
Increase specificity of raised modifier
#205
=> [Segment] Coloured inverted segments cannot be raised

src/definitions/collections/table.less, src/definitions/elements/button.less, src/definitions/elements/container.less, src/definitions/elements/divider.less, src/definitions/elements/header.less, src/definitions/elements/list.less, src/definitions/elements/segment.less, src/definitions/elements/step.less, src/definitions/modules/calendar.less, src/definitions/modules/checkbox.less, src/definitions/modules/dropdown.less, src/definitions/modules/embed.less, src/definitions/modules/modal.less, src/definitions/modules/progress.less, src/definitions/modules/shape.less, src/definitions/modules/sidebar.less, src/definitions/modules/toast.less, src/definitions/views/card.less, src/definitions/views/feed.less
This PR fixes several small CSS issues raised by my local linter ([stylelint](https://stylelint.io)). Most of them are duplicate properties or CSS selectors, and I just fixed the most obvious.
=> [Multi] Fixes some CSS lint issues

src/definitions/modules/popup.less
This PR adds two features for the no javascript version of popup, a.k.a. tooltip:
- Size variation
[![331634b51b3efebec7c382ed72f12867.gif](http://tof.cx/images/2018/10/24/331634b51b3efebec7c382ed72f12867.gif)](http://tof.cx/image/NMmER)
- Basic variation
[![78bc68a29ad34dc69b19dcff138be3d5.gif](http://tof.cx/images/2018/10/24/78bc68a29ad34dc69b19dcff138be3d5.gif)](http://tof.cx/image/NMuS9)
Bonus point ! These features can be used together:
```html
<button class="ui primary icon button" data-variation="tiny basic" data-inverted="" data-tooltip="I am a tiny inverted basic tooltip !">
<i class="plus icon"></i>
</button>
```
Will display:
[![235ab06ba737fff6ed8c24cad2a8b15a.png](http://tof.cx/images/2018/10/24/235ab06ba737fff6ed8c24cad2a8b15a.png)](http://tof.cx/image/NMWON)
=> [Popup] Add no javascript popup some new features

README.md
Added npm package quality badge fro and jsdelivr rounded style (to match other badges)
=> [README] Added package quality badge and jsdelivr rounded style (to match other badges)

src/definitions/collections/menu.less, src/definitions/elements/loader.less
Hotfix for 2.7.0
- Fixes elastic loader not working on basic buttons
- Fixes submenu transparent specificity (fomantic docs index page showed the issue)
=> 2.7 hotfixes

RELEASE-NOTES.md
=> Gulp 4 upgrade notes.

CODE_OF_CONDUCT.md
Created a Code of Conduct file following the info from https://opensource.guide/code-of-conduct/ and adapted from https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
=> [docs] code of conduct

README.md
Add travis build badge and change the last commit badge to develop branch since thats where most of the work happens.
=> [docs] add travis badge & change last commit branch

src/definitions/modules/search.js
Jusr removed wrong markup and added some missing semicolons...
=> [Search] Removed wrong markup and added missing semicolons

src/themes/default/globals/reset.overrides
The docs say Fomantic-UI includes the latest normalize.css, so we should update to the latest 8.0.1.
FUI currently includes 7.0 and we are not supporting IE <11 anymore.
=> [Reset] Updated normalize.css to 8.0.1

ROADMAP.md
Add a roadmap so users can see what the plans for v3 are.
=> docs(roadmap): add roadmap

README.md
Add message about v3 to readme so new users don't get mislead by the old message
=> docs(readme): add v3 development message

.travis.yml, package-lock.json, package.json
Refactor dependencies so they are in the correct place and so they all have specific versions instead of `*` and remove the unless peerDeps. Also update a few dependencies.
#386
=> [Build] Refactor dependencies

src/definitions/behaviors/form.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/globals/site.js, src/definitions/modules/accordion.js, src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/nag.js, src/definitions/modules/rating.js, src/definitions/modules/search.js, src/definitions/modules/shape.js, src/definitions/modules/sticky.js, src/definitions/modules/transition.js
Removed unused local variables so that it can
* increase runtime performance slightly 
* decrease annoying alarm by linting tools while development
* lower maintenance cost (less code)
To detect unused local variables, I used the code analyzer of JetBrains's IDE first, then confirm those are actually unused by manual text search.
N/A
N/A
=> [Refactoring] Remove unused local variables

src/definitions/modules/calendar.js
Possibility to set different week cell class
This PR exposes weekCell class setting within className setting.
- The week cell class setting defaults to disabled
- The week header cell must be identical to other header cell
=> Enhancements: [Dropdown] expose week cell class setting.

src/definitions/behaviors/form.js
The issue was found during introducing eslint in PR #555.
N/A
=> [Form] behavior "remove rules" fail if field is Array

RELEASE-NOTES.md, package-lock.json, package.json
**Build**
- **Dependencies** - Fixed an issue causing the npm install to fail **Thanks [@hammy2899](https://github.com/hammy2899)** [#608](https://github.com/fomantic/Fomantic-UI/pull/608)
=> chore(release): 2.7.4

src/definitions/behaviors/api.js
Reverts fomantic/Fomantic-UI#498
=> Revert "[API] Set context in beforesend to $module instead of possible stateContext to match docs"

src/definitions/modules/progress.js
=> [Progress] Display 0-width bar when value is 0

README.md
=> docs(readme): add jetbrains logo

.github/auto_assign.yml
Added setting to add all the reviewers and added @exoego to the reviewers list
=> chore(probot): add all reviewers and add exoego as reviewer

src/definitions/modules/progress.js
https://jsfiddle.net/52wqjnxf/
#705
#719
=> [Progess] Fix timing issue of updating value/percent

src/definitions/behaviors/api.js
Fixes typo but also preserves it to avoid breaking change.
N/A
Taking over https://github.com/Semantic-Org/Semantic-UI/pull/6716 by @andrewgorpenko
=> fix(api): module callback function typo

README.md
=> fixed submitting

ROADMAP.md
Added more detail to the roadmap. If anyone thinks something is missing leave a comment and I will add it.
=> docs(roadmap): update with more detail

src/definitions/elements/icon.less, src/theme.less
Improves the previous fix
Thanks @lubber-de 
#763
=> fix(icon): improve default theme overrides import

src/definitions/modules/modal.js
Ported changes from https://github.com/Semantic-Org/Semantic-UI/issues/6832
=> feat(modal): destroy should tear down mutation observer

.travis.yml
Run `build` on every pull requests, so that we can verify that PRs does not break build before merge.
#876
=> [CI] Verify build on pull requests

.github/workflows/ci.yml, tasks/config/tasks.js
Fix the CI building twice and also throw the build errors so the script exists with an error instead of success
=> Fix CI and build errors

.github/workflows/ci.yml, tasks/config/tasks.js
Throwing the no theme.less error causing build to fail when it shouldn't
=> build(ci): fix ci process

src/themes/default/globals/site.variables
Add a new variable to add font-display to google fonts
#262
=> feat(site): add font-display variable

src/definitions/collections/table.less
This PR add the support of `td` tags in table `tfoot`.
I've tested a lot of case and it I hope everything is okay...
Before: [JSFiddle](https://jsfiddle.net/czr5w0of/)
After: [JSFiddle](https://jsfiddle.net/hLqkrpde/)
#840
=> fix(table): add td support in tfoot tag

src/definitions/elements/input.less
Fixes issue #1072 + refactors CSS keeping same logic but less misguiding.
https://jsfiddle.net/qrv7xw2k/
https://jsfiddle.net/7gf135dc/
#1072
=> fix(dropdown): action button has incorrect border radius with dropdown

src/definitions/modules/slider.less, src/themes/default/modules/slider.variables
Fixed reversed vertical slider's thumb, it used to be offset.
https://jsfiddle.net/rt4zqeak/
#1142
=> fix(slider): offset for reversed vertical slider

.github/FUNDING.yml
As offered by @hammy2899 i added myself to the funding file. Thanks ❤️
=> feat(docs): Add lubber-de github account to funding info 😄 

src/definitions/modules/checkbox.js
This fixes a null pointer exception on IE11.
=> [Checkbox] Fix npe on IE11

README.md
Add snyk badge to show our vulnerabilities
=> docs(readme): add snyk badge

src/definitions/modules/dropdown.js
Let some items of a dropdown be resilient to filtered text searchs.
https://jsfiddle.net/arkanovicz/s6k9mqd1/35/
https://jsfiddle.net/0fo1bas3/
=> feat(dropdown): add unfilterable item class for search input

src/definitions/modules/calendar.js
This PR add the ability to disable entire month(s) and year(s) by using the `disabledDates` object.
Example:
```js
disabledDates: [
{
date: new Date("03/05/2020"),
message: "One disabled date"
},
{
date: [new Date("02/11/2020"), new Date("02/12/2020"), new Date("02/13/2020")],
message: "Array of disabled dates"
},
{
month: 3,
message: "All April month are disabled"
},
{
month: [4, 5, 6],
message: "May, June and July are disabled"
},
{
month: new Date("2020-03-01"),
message: "Disabled month thank to a Date object"
},
{
year: 2021,
message: "One disabled year"
},
{
year: [2018, 2019],
message: "Array of disabled years"
}
]
```
[JSFiddle](https://jsfiddle.net/4woxupka/)
#1086
=> [Calendar] Add ability to disable months and years

tasks/build/css.js
Wait for the uncompressed build to complete before gathering .css files
for the packed .min.css file.
Rebuild the css multiple times, eventually the race condition is hit.
```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
```
```
$ node -v
v12.16.1
```
```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
1354660
1354660
1354660
1321153
^C
```
```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
^C
```
Closes #1356
cc @silverwind
=> [build] fix the minified css build

src/definitions/elements/divider.less, src/themes/default/elements/divider.variables
This was hardcoded as 'solid', but deserves to be a variable design decision.
=> Add variable for divider border style

README.md
Add sponsor logo/content for DigitalOcean 😍
=> chore(readme): add do sponsor content

.github/auto_assign.yml
This will add @ko2in as a reviewer for the autoassign bot
=> feat(chore): autoassign ko2in for pr reviews

src/themes/default/globals/variation.variables, src/themes/default/modules/transition.overrides
This PR follows the principle of the dynamic LESS compilation and implements this now also for all transition effects so its possible for the user to reduce even more unneeded CSS within the existing `variation.variables` file. 
#769 
#1510
=> [Transition/Chore] Make effects optional for CSS compilation

ROADMAP.md
Changed "pollyfill" to "polyfill"
Changed "Visability" to "visibility"
#<issue id>, #<issue id>, #<issue id>
=> Fixed 2 instances of spelling issues

src/definitions/modules/slider.js
Same PR #1547 
Diferent folder.
I'll be more careful next time, sorry.
=> [Slider] operation sometimes returns not rounded value #1547

src/definitions/elements/button.less, src/themes/default/elements/button.variables
This PR uses dedicated variables for `toggle button` and `circular button` variants to allow for consistent theming.
`Circular` button had hardcoded values and `toggle` had fixed global variable names set, which made it nearly impossible to theme individually.
#1583
=> [Button] Dedicated variables for toggle and circular variants

README.md
This PR adds a rating badge for https://openbase.io/js/fomantic-ui
Thanks to @prudho for supplying the info 🙂 
openbase provides a nice dashboard with package statistics
=> feat(docs): added openbase.io badge

ROADMAP.md
Add Web Components to `ROADMAP.md` under Library Implementations.
#1650
=> [Docs] add web components to library implementations

README.md
=> fix(docs): grammar error

src/themes/default/globals/colors.less
Added semicolons after variable declarations
fomantic#1832
=> fix(colors): compile error of php less port

README.md
Use the offical discord api shield
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/108034787-5619ac00-7036-11eb-8a5d-7e22e59f122e.png)|![widget](https://user-images.githubusercontent.com/18379884/108034809-5ca82380-7036-11eb-9431-b4b13bb185ca.png)|
=> fix(readme): use the official discord shield

src/definitions/modules/dimmer.js
Fixed typo.
occured -> occurred
=> feat(dimmer): fix typo in dimmer.js

.github/workflows/ci.yml
Increases node version up to 14 LTS
=> feat(build): check node 13 and 14 for github actions

src/definitions/collections/form.less, src/definitions/collections/grid.less, src/definitions/collections/menu.less, src/definitions/collections/message.less, src/definitions/collections/table.less, src/definitions/elements/button.less, src/definitions/elements/container.less, src/definitions/elements/emoji.less, src/definitions/elements/header.less, src/definitions/elements/list.less, src/definitions/elements/segment.less, src/definitions/elements/step.less, src/definitions/modules/dropdown.less, src/definitions/modules/search.less, src/definitions/modules/sidebar.less, src/definitions/views/card.less, src/definitions/views/comment.less, src/definitions/views/feed.less, src/definitions/views/item.less, src/definitions/views/statistic.less, src/themes/default/globals/variation.variables
This PR adds lots of additional options for the `variation.variables` customization for switching CSS Variations to be able to shorten a custom build even more.
For an easier review, turn off whitespace changes in the review tab
https://github.com/fomantic/Fomantic-UI/pull/2106/files?w=1
=> feat(chore): more variation options

tasks/install.js
A callback call was missing to satisfy gulp
#2236
=> fix(tasks): provide callback to satisfy gulp

.github/workflows/nightly.yml, package-lock.json, package.json, scripts/nightly-version.js
Made changes to the nightly script and workflow so we can exit with code 0 so the action doesn't "fail" and alert us yet we can still prevent the publish steps from executing.
=> build(scripts): fix nightly exit codes

.github/workflows/nightly.yml
I've corrected the syntax of the workflow, outputs on the job was wrong.
=> build(workflows): fix nightly build syntax

.github/workflows/nightly.yml, scripts/nightly-version.js
Add a conditional check to the shouldPublish if expressions
=> build(actions): add condition for shouldPublish

src/definitions/collections/menu.less
When you are using a pointing menu and it stacks, due to small screen size, the pointer should disappear. 
Unfortunately I have no experience with CSS preprocessors (yet), so I'll likely need some help for any changes.
https://jsfiddle.net/gLhb4um3/
=> Fix vertical pointing menu

src/definitions/views/card.less, src/themes/default/globals/variation.variables, src/themes/default/views/card.variables
New `basic` variant which does not have a border and also allows support for full color background
https://jsfiddle.net/lubber/gvzq0fk2/9/
=> feat(card): basic variant

src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/modal.js, src/definitions/modules/rating.js
In some edge cases a class or iconname, given via settings, might get such values out of uncontrolled input.
For such cases we need to dequote the values.
https://github.com/fomantic/Fomantic-UI/security/code-scanning/56
https://github.com/fomantic/Fomantic-UI/security/code-scanning/57
=> fix(chore): prevent possible xss

src/definitions/behaviors/visibility.js, src/definitions/modules/dropdown.js, src/definitions/modules/popup.js, src/definitions/modules/sticky.js
Some slight performance adjustments by using native array access instead of .get(0) and reusage of cached variables
=> fix(chore): reuse variables and quicker element access

src/definitions/behaviors/api.js, src/definitions/modules/dropdown.js, src/definitions/modules/modal.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js, src/definitions/modules/search.js, src/definitions/modules/toast.js
Fixes codeql regex findings and fix non fetched multiple htmlentities for ampersand replacements in various modules
- https://github.com/fomantic/Fomantic-UI/security/code-scanning/58
- https://github.com/fomantic/Fomantic-UI/security/code-scanning/59
- https://github.com/fomantic/Fomantic-UI/security/code-scanning/60
=> fix(chore): fix codeql findings

src/definitions/behaviors/api.js, src/definitions/behaviors/form.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/globals/site.js, src/definitions/modules/accordion.js, src/definitions/modules/calendar.js, src/definitions/modules/checkbox.js, src/definitions/modules/dimmer.js, src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/modal.js, src/definitions/modules/nag.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js, src/definitions/modules/rating.js, src/definitions/modules/search.js, src/definitions/modules/shape.js, src/definitions/modules/sidebar.js, src/definitions/modules/slider.js, src/definitions/modules/sticky.js, src/definitions/modules/tab.js, src/definitions/modules/toast.js, src/definitions/modules/transition.js
Many variable usages were wrong/unused/buggy which this PR fixes or optimizes
=> fix(chore): variable declaration and usage fixes and optimization

examples/components/sticky-context.html, src/definitions/modules/sticky.js, tasks/config/admin/templates/css-package.js
SUI 2.5.0 was just released.
Most of the fixes and changes are already done since some time in FUI 🙂 
However, some sticky changes (and a small (in FUI unused) build fix) were not, so this PR adopts them to stay on par with the SUI code.
=> fix(sticky): adopt SUI 2.5.0 fixes

src/definitions/modules/rating.less
Unfortunately the last fix for partial rating #2023 hasn't got enough specificity to work properly, which this PR fixes
https://fomantic-ui.com/modules/rating.html#partial-ratings
https://jsfiddle.net/lubber/2crgwju9/1/ (remove CSS to see issue)
#2295
=> fix(rating): partial rating specificity

.github/workflows/ci.yml
=> feat(ci): check node 18 as well

src/definitions/elements/button.less, src/themes/default/globals/variation.variables
positive and negative button colors were not optional and always generated.
This PR makes them optional via new `@variationButtonConsequences` variable
https://github.com/fomantic/Fomantic-UI/issues/2530#issuecomment-1298470371
=> feat(button): make consequences optional

src/definitions/modules/popup.less
Color variant for popup/tooltip. The `@variationPopupColors` variable already exists, i just forgot to prepare that for 2.9.0
https://jsfiddle.net/lubber/rvqsfhom/11/
=> feat(popup): color variants

src/definitions/behaviors/api.js, src/definitions/behaviors/form.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/globals/site.js, src/definitions/modules/accordion.js, src/definitions/modules/calendar.js, src/definitions/modules/checkbox.js, src/definitions/modules/dimmer.js, src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/flyout.js, src/definitions/modules/modal.js, src/definitions/modules/nag.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js, src/definitions/modules/rating.js, src/definitions/modules/search.js, src/definitions/modules/shape.js, src/definitions/modules/sidebar.js, src/definitions/modules/slider.js, src/definitions/modules/sticky.js, src/definitions/modules/tab.js, src/definitions/modules/toast.js, src/definitions/modules/transition.js
Fixed deprecated jquery logics as been told by https://github.com/jquery/jquery-migrate/blob/main/warnings.md
#2569
=> fix(chore): replace jquery deprecated methods

.stylelintrc.js, src/definitions/collections/breadcrumb.less, src/definitions/collections/grid.less, src/definitions/collections/menu.less, src/definitions/collections/table.less, src/definitions/elements/button.less, src/definitions/elements/divider.less, src/definitions/elements/header.less, src/definitions/elements/image.less, src/definitions/elements/label.less, src/definitions/elements/step.less, src/definitions/modules/dropdown.less, src/definitions/views/card.less, src/definitions/views/statistic.less, src/themes/amazon/elements/button.overrides, src/themes/default/collections/menu.variables, src/themes/default/elements/button.variables, src/themes/default/elements/segment.variables, src/themes/default/globals/reset.overrides, src/themes/default/modules/dropdown.variables, src/themes/default/modules/flyout.variables, src/themes/default/modules/modal.variables, src/themes/default/views/card.variables, src/themes/default/views/item.variables, src/themes/material/elements/button.variables, src/themes/material/elements/icon.overrides, src/themes/resetcss/globals/reset.overrides
Fix several stylelint `stylelint-config-standard` config advisories.
=> feat(lint): modernize/unify CSS but maintain IE11 compatibility

src/theme.less
The colors.less file was not respecting the 3 layer logic (default->theme->site).
=> fix(chore): also use 3 layer logic for colors.less

tasks/collections/build.js, tasks/collections/docs.js, tasks/collections/install.js, tasks/collections/rtl.js, tasks/collections/various.js, tasks/rtl/build.js
Some multiline const statement blocks didnt have a nice indent anymore.
=> fix(chore): same indent level for multiline const

src/themes/default/elements/emoji.variables, src/themes/default/elements/flag.variables, src/themes/twitter/elements/emoji.variables
Changing CDN path from maxcdn to jsdelivr
#2626
=> fix(emoji,flag): changing from maxcdn to jsdelivr cdn path

src/definitions/behaviors/form.js, src/definitions/modules/tab.js, src/themes/default/modules/checkbox.overrides
This PR removes SUI v1.x legacy code which is not even documented since years anymore.
=> fix(chore): remove old sui v1 unsupported and undocumented code

src/definitions/modules/checkbox.less
Removing some !important statements and replaced by higher specificity where needed.
#2225
=> feat(checkbox): remove !important

src/definitions/collections/form.less, src/definitions/elements/input.less, src/definitions/globals/site.less, src/definitions/modules/dropdown.less
Again removed some not needed vendor prefixes
=> feat(chore): remove unneeded vendor prefixes

src/definitions/behaviors/form.js
Added new `size` rule to check for a character length. It's a shortcut to avoid having 2 separate rules (minLength+maxLength)
https://jsfiddle.net/lubber/o71muv3p/7/
#1279
=> feat(formvalidation): size rule to test string length range

src/definitions/elements/emoji.less, src/definitions/elements/placeholder.less, src/definitions/elements/text.less, src/definitions/modules/embed.less, src/definitions/modules/progress.less, src/definitions/modules/slider.less
Some file headers were different/missing/copyPasted which this PR unifies. Otherwise the build process fails to inject the version number into the header as the regex inside the build script does not find the header
=> fix(chore): unified template headers

src/definitions/elements/segment.less, src/definitions/modules/dropdown.less
=> fix(segment, dropdown): specificity and wrong selector

src/definitions/behaviors/api.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/modules/dropdown.js, src/definitions/modules/flyout.js, src/definitions/modules/modal.js, src/definitions/modules/nag.js, src/definitions/modules/popup.js, src/definitions/modules/sidebar.js, src/definitions/modules/sticky.js, src/definitions/modules/tab.js, src/definitions/modules/toast.js
This PR supports context in parent window objects
https://jsfiddle.net/lubber/1z48xugd/3/
#2701
=> fix(chore): check if context exists in parent windows

src/definitions/behaviors/api.js, src/definitions/behaviors/form.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/modules/accordion.js, src/definitions/modules/calendar.js, src/definitions/modules/checkbox.js, src/definitions/modules/dimmer.js, src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/flyout.js, src/definitions/modules/modal.js, src/definitions/modules/nag.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js, src/definitions/modules/rating.js, src/definitions/modules/search.js, src/definitions/modules/shape.js, src/definitions/modules/sidebar.js, src/definitions/modules/slider.js, src/definitions/modules/sticky.js, src/definitions/modules/tab.js, src/definitions/modules/toast.js, src/definitions/modules/transition.js
Removed the selectror api usage, because it is always undefined as jquery 3 removed it and was depreacted since jquery 1.7
=> fix(chore): removed selector api as removed in jquery 3

src/definitions/modules/calendar.less
A multimonth calendar had a little margin
https://jsfiddle.net/lubber/qoph2w3t/9/
=> fix(calendar): multimonth had margin

src/definitions/elements/label.less, src/themes/default/elements/label.variables
Added `center` and `bottom` ribbon label
https://jsfiddle.net/lubber/z1vnq427/7/
#2728
=> feat(label): center and bottom ribbon

src/definitions/collections/table.less, src/definitions/elements/container.less, src/definitions/elements/segment.less, src/definitions/modules/dropdown.less, src/definitions/modules/flyout.less, src/definitions/modules/modal.less, src/definitions/modules/search.less, src/themes/default/collections/table.variables, src/themes/default/elements/container.variables, src/themes/default/elements/segment.variables, src/themes/default/globals/variation.variables, src/themes/default/modules/dropdown.variables, src/themes/default/modules/modal.variables, src/themes/default/modules/search.variables
New `resizable` variant which enables native resize for scrolling variants like table, segment, container, search, dropdown just like a textarea
https://jsfiddle.net/lubber/u5yxzd62/5/
=> feat(table,segment,container,dropdown,search): resizable scrolling

README.md
Added some badges for CI+Nightly Build as well as OSSF Badge
=> feat(readme): added ci+ossf badges

SECURITY.md
=> chore(docs): added v2.9.x to security support

scripts/nightly-version.js, tasks/admin/components/create.js, tasks/admin/components/init.js, tasks/admin/components/update.js, tasks/admin/distributions/create.js, tasks/admin/distributions/init.js, tasks/admin/distributions/update.js, tasks/config/user.js, tasks/docs/build.js, tasks/docs/metadata.js, tasks/install.js
Recent changes to linting defaults require import order changes
#2858
=> fix(lint): satisfy linting for import order

.eslintrc.js, src/definitions/behaviors/api.js, src/definitions/behaviors/form.js, src/definitions/behaviors/state.js, src/definitions/behaviors/visibility.js, src/definitions/globals/site.js, src/definitions/modules/accordion.js, src/definitions/modules/calendar.js, src/definitions/modules/checkbox.js, src/definitions/modules/dimmer.js, src/definitions/modules/dropdown.js, src/definitions/modules/embed.js, src/definitions/modules/flyout.js, src/definitions/modules/modal.js, src/definitions/modules/nag.js, src/definitions/modules/popup.js, src/definitions/modules/progress.js, src/definitions/modules/rating.js, src/definitions/modules/search.js, src/definitions/modules/shape.js, src/definitions/modules/sidebar.js, src/definitions/modules/slider.js, src/definitions/modules/sticky.js, src/definitions/modules/tab.js, src/definitions/modules/toast.js, src/definitions/modules/transition.js
the new config is eslint default, only AirBnB CS changed it in https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v19.0.4/packages/eslint-config-airbnb-base/rules/style.js#L21
=> feat(lint): enforce NL before opening curly braces

README.md
Update sponsors and remove something (:
=> chore: update sponsors

types/fomantic-ui-dropdown.d.ts, types/fomantic-ui-embed.d.ts, types/fomantic-ui-search.d.ts, types/fomantic-ui-toast.d.ts
addtional types for the latest features
#3004 
#3011 
#2809
=> feat(types): alt + data support and search fields

types/fomantic-ui-search.d.ts
Complies with respective JSDoc and it works like that
=> fix(types): clear cache parameter in search module is optional

src/themes/default/elements/flag.variables, src/themes/twitter/elements/emoji.variables
I belive this was missed in #3086.
=> fix(flag): use jdecked twemoji fork
